.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80107A30_1BE380_HoneycombTreasureHunt, 0x18

glabel D_80107A30_1BE380_HoneycombTreasureHunt
    /* 80107A30 */ .space 0x18

nonmatching D_80107A48_1BE398_HoneycombTreasureHunt, 0x3C

dlabel D_80107A48_1BE398_HoneycombTreasureHunt
    /* 80107A48 */ .space 0x3C

nonmatching D_80107A84_1BE3D4_HoneycombTreasureHunt, 0x4

dlabel D_80107A84_1BE3D4_HoneycombTreasureHunt
    /* 80107A84 */ .space 0x04

nonmatching D_80107A88_1BE3D8_HoneycombTreasureHunt, 0x4

dlabel D_80107A88_1BE3D8_HoneycombTreasureHunt
    /* 80107A88 */ .space 0x04

nonmatching D_80107A8C_1BE3DC_HoneycombTreasureHunt, 0x4

dlabel D_80107A8C_1BE3DC_HoneycombTreasureHunt
    /* 80107A8C */ .space 0x04

nonmatching D_80107A90_1BE3E0_HoneycombTreasureHunt, 0x4

dlabel D_80107A90_1BE3E0_HoneycombTreasureHunt
    /* 80107A90 */ .space 0x04

nonmatching D_80107A94_1BE3E4_HoneycombTreasureHunt, 0x4

dlabel D_80107A94_1BE3E4_HoneycombTreasureHunt
    /* 80107A94 */ .space 0x04

nonmatching D_80107A98_1BE3E8_HoneycombTreasureHunt, 0x4

dlabel D_80107A98_1BE3E8_HoneycombTreasureHunt
    /* 80107A98 */ .space 0x04

nonmatching D_80107A9C_1BE3EC_HoneycombTreasureHunt, 0x4

dlabel D_80107A9C_1BE3EC_HoneycombTreasureHunt
    /* 80107A9C */ .space 0x04

nonmatching D_80107AA0_1BE3F0_HoneycombTreasureHunt, 0x34

dlabel D_80107AA0_1BE3F0_HoneycombTreasureHunt
    /* 80107AA0 */ .space 0x34

nonmatching D_80107AD4_1BE424_HoneycombTreasureHunt, 0x40

dlabel D_80107AD4_1BE424_HoneycombTreasureHunt
    /* 80107AD4 */ .space 0x40

nonmatching D_80107B14_1BE464_HoneycombTreasureHunt, 0x8

dlabel D_80107B14_1BE464_HoneycombTreasureHunt
    /* 80107B14 */ .space 0x08

nonmatching D_80107B1C_1BE46C_HoneycombTreasureHunt, 0x4

dlabel D_80107B1C_1BE46C_HoneycombTreasureHunt
    /* 80107B1C */ .space 0x04

nonmatching D_80107B20_1BE470_HoneycombTreasureHunt, 0x4

dlabel D_80107B20_1BE470_HoneycombTreasureHunt
    /* 80107B20 */ .space 0x04

nonmatching D_80107B24_1BE474_HoneycombTreasureHunt, 0x18

dlabel D_80107B24_1BE474_HoneycombTreasureHunt
    /* 80107B24 */ .space 0x18

nonmatching D_80107B3C_1BE48C_HoneycombTreasureHunt, 0x8

dlabel D_80107B3C_1BE48C_HoneycombTreasureHunt
    /* 80107B3C */ .space 0x08

nonmatching D_80107B44_1BE494_HoneycombTreasureHunt, 0x4

dlabel D_80107B44_1BE494_HoneycombTreasureHunt
    /* 80107B44 */ .space 0x04

nonmatching D_80107B48_1BE498_HoneycombTreasureHunt, 0x4

dlabel D_80107B48_1BE498_HoneycombTreasureHunt
    /* 80107B48 */ .space 0x04

nonmatching D_80107B4C_1BE49C_HoneycombTreasureHunt, 0x4

dlabel D_80107B4C_1BE49C_HoneycombTreasureHunt
    /* 80107B4C */ .space 0x04

nonmatching D_80107B50_1BE4A0_HoneycombTreasureHunt, 0x8

dlabel D_80107B50_1BE4A0_HoneycombTreasureHunt
    /* 80107B50 */ .space 0x08

nonmatching D_80107B58_1BE4A8_HoneycombTreasureHunt, 0x2

dlabel D_80107B58_1BE4A8_HoneycombTreasureHunt
    /* 80107B58 */ .space 0x02

nonmatching D_80107B5A_1BE4AA_HoneycombTreasureHunt, 0x4A

dlabel D_80107B5A_1BE4AA_HoneycombTreasureHunt
    /* 80107B5A */ .space 0x4A

nonmatching D_80107BA4_1BE4F4_HoneycombTreasureHunt, 0x10

dlabel D_80107BA4_1BE4F4_HoneycombTreasureHunt
    /* 80107BA4 */ .space 0x10

nonmatching D_80107BB4_1BE504_HoneycombTreasureHunt, 0xA

dlabel D_80107BB4_1BE504_HoneycombTreasureHunt
    /* 80107BB4 */ .space 0x0A

nonmatching D_80107BBE_1BE50E_HoneycombTreasureHunt, 0x8

dlabel D_80107BBE_1BE50E_HoneycombTreasureHunt
    /* 80107BBE */ .space 0x08

nonmatching D_80107BC6_1BE516_HoneycombTreasureHunt, 0x4

dlabel D_80107BC6_1BE516_HoneycombTreasureHunt
    /* 80107BC6 */ .space 0x04

nonmatching D_80107BCA_1BE51A_HoneycombTreasureHunt, 0x4

dlabel D_80107BCA_1BE51A_HoneycombTreasureHunt
    /* 80107BCA */ .space 0x04

nonmatching D_80107BCE_1BE51E_HoneycombTreasureHunt, 0x8

dlabel D_80107BCE_1BE51E_HoneycombTreasureHunt
    /* 80107BCE */ .space 0x08

nonmatching D_80107BD6_1BE526_HoneycombTreasureHunt, 0x6

dlabel D_80107BD6_1BE526_HoneycombTreasureHunt
    /* 80107BD6 */ .space 0x06

nonmatching D_80107BDC_1BE52C_HoneycombTreasureHunt, 0x1C

dlabel D_80107BDC_1BE52C_HoneycombTreasureHunt
    /* 80107BDC */ .space 0x1C

nonmatching D_80107BF8_1BE548_HoneycombTreasureHunt, 0x4

dlabel D_80107BF8_1BE548_HoneycombTreasureHunt
    /* 80107BF8 */ .space 0x04

nonmatching D_80107BFC_1BE54C_HoneycombTreasureHunt, 0x4

dlabel D_80107BFC_1BE54C_HoneycombTreasureHunt
    /* 80107BFC */ .space 0x04

nonmatching D_80107C00_1BE550_HoneycombTreasureHunt, 0x10

dlabel D_80107C00_1BE550_HoneycombTreasureHunt
    /* 80107C00 */ .space 0x10

nonmatching D_80107C10_1BE560_HoneycombTreasureHunt, 0x8

dlabel D_80107C10_1BE560_HoneycombTreasureHunt
    /* 80107C10 */ .space 0x08

nonmatching D_80107C18_1BE568_HoneycombTreasureHunt, 0x10

dlabel D_80107C18_1BE568_HoneycombTreasureHunt
    /* 80107C18 */ .space 0x10

nonmatching D_80107C28_1BE578_HoneycombTreasureHunt, 0x4

dlabel D_80107C28_1BE578_HoneycombTreasureHunt
    /* 80107C28 */ .space 0x04

nonmatching D_80107C2C_1BE57C_HoneycombTreasureHunt, 0x10

dlabel D_80107C2C_1BE57C_HoneycombTreasureHunt
    /* 80107C2C */ .space 0x10

nonmatching D_80107C3C_1BE58C_HoneycombTreasureHunt, 0xC

dlabel D_80107C3C_1BE58C_HoneycombTreasureHunt
    /* 80107C3C */ .space 0x0C

nonmatching jtbl_80107C48_1BE598_HoneycombTreasureHunt, 0x28

dlabel jtbl_80107C48_1BE598_HoneycombTreasureHunt
    /* 80107C48 */ .space 0x28

nonmatching D_80107C70_1BE5C0_HoneycombTreasureHunt, 0x18

dlabel D_80107C70_1BE5C0_HoneycombTreasureHunt
    /* 80107C70 */ .space 0x18

nonmatching D_80107C88_1BE5D8_HoneycombTreasureHunt, 0x1C

dlabel D_80107C88_1BE5D8_HoneycombTreasureHunt
    /* 80107C88 */ .space 0x1C

nonmatching D_80107CA4_1BE5F4_HoneycombTreasureHunt, 0x18

dlabel D_80107CA4_1BE5F4_HoneycombTreasureHunt
    /* 80107CA4 */ .space 0x18

nonmatching D_80107CBC_1BE60C_HoneycombTreasureHunt, 0x1C

dlabel D_80107CBC_1BE60C_HoneycombTreasureHunt
    /* 80107CBC */ .space 0x1C

nonmatching jtbl_80107CD8_1BE628_HoneycombTreasureHunt, 0x1C

dlabel jtbl_80107CD8_1BE628_HoneycombTreasureHunt
    /* 80107CD8 */ .space 0x1C

nonmatching D_80107CF4_1BE644_HoneycombTreasureHunt, 0x10

dlabel D_80107CF4_1BE644_HoneycombTreasureHunt
    /* 80107CF4 */ .space 0x10

nonmatching D_80107D04_1BE654_HoneycombTreasureHunt, 0x10

dlabel D_80107D04_1BE654_HoneycombTreasureHunt
    /* 80107D04 */ .space 0x10

nonmatching D_80107D14_1BE664_HoneycombTreasureHunt, 0x10

dlabel D_80107D14_1BE664_HoneycombTreasureHunt
    /* 80107D14 */ .space 0x10

nonmatching D_80107D24_1BE674_HoneycombTreasureHunt, 0x4

dlabel D_80107D24_1BE674_HoneycombTreasureHunt
    /* 80107D24 */ .space 0x04

nonmatching D_80107D28_1BE678_HoneycombTreasureHunt, 0x18

dlabel D_80107D28_1BE678_HoneycombTreasureHunt
    /* 80107D28 */ .space 0x18

nonmatching jtbl_80107D40_1BE690_HoneycombTreasureHunt, 0x38

dlabel jtbl_80107D40_1BE690_HoneycombTreasureHunt
    /* 80107D40 */ .space 0x38

nonmatching jtbl_80107D78_1BE6C8_HoneycombTreasureHunt, 0x18

dlabel jtbl_80107D78_1BE6C8_HoneycombTreasureHunt
    /* 80107D78 */ .space 0x18

nonmatching D_80107D90_1BE6E0_HoneycombTreasureHunt, 0x2

dlabel D_80107D90_1BE6E0_HoneycombTreasureHunt
    /* 80107D90 */ .space 0x02

nonmatching D_80107D92_1BE6E2_HoneycombTreasureHunt, 0xE

dlabel D_80107D92_1BE6E2_HoneycombTreasureHunt
    /* 80107D92 */ .space 0x0E

nonmatching D_80107DA0_1BE6F0_HoneycombTreasureHunt, 0x10

dlabel D_80107DA0_1BE6F0_HoneycombTreasureHunt
    /* 80107DA0 */ .space 0x10

nonmatching D_80107DB0_1BE700_HoneycombTreasureHunt, 0x1

dlabel D_80107DB0_1BE700_HoneycombTreasureHunt
    /* 80107DB0 */ .space 0x01

nonmatching D_80107DB1_1BE701_HoneycombTreasureHunt, 0x1

dlabel D_80107DB1_1BE701_HoneycombTreasureHunt
    /* 80107DB1 */ .space 0x01

nonmatching D_80107DB2_1BE702_HoneycombTreasureHunt, 0x1

dlabel D_80107DB2_1BE702_HoneycombTreasureHunt
    /* 80107DB2 */ .space 0x01

nonmatching D_80107DB3_1BE703_HoneycombTreasureHunt, 0x1

dlabel D_80107DB3_1BE703_HoneycombTreasureHunt
    /* 80107DB3 */ .space 0x01

nonmatching D_80107DB4_1BE704_HoneycombTreasureHunt, 0x8

dlabel D_80107DB4_1BE704_HoneycombTreasureHunt
    /* 80107DB4 */ .space 0x08

nonmatching D_80107DBC_1BE70C_HoneycombTreasureHunt, 0x2

dlabel D_80107DBC_1BE70C_HoneycombTreasureHunt
    /* 80107DBC */ .space 0x02

nonmatching D_80107DBE_1BE70E_HoneycombTreasureHunt, 0x2

dlabel D_80107DBE_1BE70E_HoneycombTreasureHunt
    /* 80107DBE */ .space 0x02

nonmatching D_80107DC0_1BE710_HoneycombTreasureHunt, 0x4

dlabel D_80107DC0_1BE710_HoneycombTreasureHunt
    /* 80107DC0 */ .space 0x04

nonmatching D_80107DC4_1BE714_HoneycombTreasureHunt, 0x4

dlabel D_80107DC4_1BE714_HoneycombTreasureHunt
    /* 80107DC4 */ .space 0x04

nonmatching D_80107DC8_1BE718_HoneycombTreasureHunt, 0x2

dlabel D_80107DC8_1BE718_HoneycombTreasureHunt
    /* 80107DC8 */ .space 0x02

nonmatching D_80107DCA_1BE71A_HoneycombTreasureHunt, 0x2

dlabel D_80107DCA_1BE71A_HoneycombTreasureHunt
    /* 80107DCA */ .space 0x02

nonmatching D_80107DCC_1BE71C_HoneycombTreasureHunt, 0x8

dlabel D_80107DCC_1BE71C_HoneycombTreasureHunt
    /* 80107DCC */ .space 0x08

nonmatching D_80107DD4_1BE724_HoneycombTreasureHunt, 0x2

dlabel D_80107DD4_1BE724_HoneycombTreasureHunt
    /* 80107DD4 */ .space 0x02

nonmatching D_80107DD6_1BE726_HoneycombTreasureHunt, 0x2

dlabel D_80107DD6_1BE726_HoneycombTreasureHunt
    /* 80107DD6 */ .space 0x02

nonmatching D_80107DD8_1BE728_HoneycombTreasureHunt, 0x2

dlabel D_80107DD8_1BE728_HoneycombTreasureHunt
    /* 80107DD8 */ .space 0x02

nonmatching D_80107DDA_1BE72A_HoneycombTreasureHunt, 0x2

dlabel D_80107DDA_1BE72A_HoneycombTreasureHunt
    /* 80107DDA */ .space 0x02

nonmatching D_80107DDC_1BE72C_HoneycombTreasureHunt, 0x2

dlabel D_80107DDC_1BE72C_HoneycombTreasureHunt
    /* 80107DDC */ .space 0x02

nonmatching D_80107DDE_1BE72E_HoneycombTreasureHunt, 0x2

dlabel D_80107DDE_1BE72E_HoneycombTreasureHunt
    /* 80107DDE */ .space 0x02

nonmatching D_80107DE0_1BE730_HoneycombTreasureHunt, 0x2

dlabel D_80107DE0_1BE730_HoneycombTreasureHunt
    /* 80107DE0 */ .space 0x02

nonmatching D_80107DE2_1BE732_HoneycombTreasureHunt, 0x2

dlabel D_80107DE2_1BE732_HoneycombTreasureHunt
    /* 80107DE2 */ .space 0x02

nonmatching D_80107DE4_1BE734_HoneycombTreasureHunt, 0x2

dlabel D_80107DE4_1BE734_HoneycombTreasureHunt
    /* 80107DE4 */ .space 0x02

nonmatching D_80107DE6_1BE736_HoneycombTreasureHunt, 0xA

dlabel D_80107DE6_1BE736_HoneycombTreasureHunt
    /* 80107DE6 */ .space 0x0A

nonmatching D_80107DF0_1BE740_HoneycombTreasureHunt, 0x20

dlabel D_80107DF0_1BE740_HoneycombTreasureHunt
    /* 80107DF0 */ .space 0x20

nonmatching D_80107E10_1BE760_HoneycombTreasureHunt, 0x4

dlabel D_80107E10_1BE760_HoneycombTreasureHunt
    /* 80107E10 */ .space 0x04

nonmatching D_80107E14_1BE764_HoneycombTreasureHunt, 0x4

dlabel D_80107E14_1BE764_HoneycombTreasureHunt
    /* 80107E14 */ .space 0x04

nonmatching D_80107E18_1BE768_HoneycombTreasureHunt, 0xC

dlabel D_80107E18_1BE768_HoneycombTreasureHunt
    /* 80107E18 */ .space 0x0C

nonmatching D_80107E24_1BE774_HoneycombTreasureHunt, 0xC

dlabel D_80107E24_1BE774_HoneycombTreasureHunt
    /* 80107E24 */ .space 0x0C

nonmatching D_80107E30_1BE780_HoneycombTreasureHunt, 0x4

dlabel D_80107E30_1BE780_HoneycombTreasureHunt
    /* 80107E30 */ .space 0x04

nonmatching D_80107E34_1BE784_HoneycombTreasureHunt, 0x4

dlabel D_80107E34_1BE784_HoneycombTreasureHunt
    /* 80107E34 */ .space 0x04

nonmatching D_80107E38_1BE788_HoneycombTreasureHunt, 0x4

dlabel D_80107E38_1BE788_HoneycombTreasureHunt
    /* 80107E38 */ .space 0x04

nonmatching D_80107E3C_1BE78C_HoneycombTreasureHunt, 0x4

dlabel D_80107E3C_1BE78C_HoneycombTreasureHunt
    /* 80107E3C */ .space 0x04

nonmatching D_80107E40_1BE790_HoneycombTreasureHunt, 0x1E

dlabel D_80107E40_1BE790_HoneycombTreasureHunt
    /* 80107E40 */ .space 0x1E

nonmatching D_80107E5E_1BE7AE_HoneycombTreasureHunt, 0x6

dlabel D_80107E5E_1BE7AE_HoneycombTreasureHunt
    /* 80107E5E */ .space 0x06

nonmatching D_80107E64_1BE7B4_HoneycombTreasureHunt, 0x8

dlabel D_80107E64_1BE7B4_HoneycombTreasureHunt
    /* 80107E64 */ .space 0x08

nonmatching D_80107E6C_1BE7BC_HoneycombTreasureHunt, 0x4

dlabel D_80107E6C_1BE7BC_HoneycombTreasureHunt
    /* 80107E6C */ .space 0x04

nonmatching D_80107E70_1BE7C0_HoneycombTreasureHunt, 0x4

dlabel D_80107E70_1BE7C0_HoneycombTreasureHunt
    /* 80107E70 */ .space 0x04

nonmatching D_80107E74_1BE7C4_HoneycombTreasureHunt, 0x1

dlabel D_80107E74_1BE7C4_HoneycombTreasureHunt
    /* 80107E74 */ .space 0x01

nonmatching D_80107E75_1BE7C5_HoneycombTreasureHunt, 0x1

dlabel D_80107E75_1BE7C5_HoneycombTreasureHunt
    /* 80107E75 */ .space 0x01

nonmatching D_80107E76_1BE7C6_HoneycombTreasureHunt, 0x7A

dlabel D_80107E76_1BE7C6_HoneycombTreasureHunt
    /* 80107E76 */ .space 0x7A

nonmatching D_80107EF0_1BE840_HoneycombTreasureHunt, 0x60

dlabel D_80107EF0_1BE840_HoneycombTreasureHunt
    /* 80107EF0 */ .space 0x60

nonmatching D_80107F50_1BE8A0_HoneycombTreasureHunt, 0x1

dlabel D_80107F50_1BE8A0_HoneycombTreasureHunt
    /* 80107F50 */ .space 0x01

nonmatching D_80107F51_1BE8A1_HoneycombTreasureHunt, 0x1

dlabel D_80107F51_1BE8A1_HoneycombTreasureHunt
    /* 80107F51 */ .space 0x01

nonmatching D_80107F52_1BE8A2_HoneycombTreasureHunt, 0x4

dlabel D_80107F52_1BE8A2_HoneycombTreasureHunt
    /* 80107F52 */ .space 0x04

nonmatching D_80107F56_1BE8A6_HoneycombTreasureHunt, 0xA

dlabel D_80107F56_1BE8A6_HoneycombTreasureHunt
    /* 80107F56 */ .space 0x0A

nonmatching D_80107F60_1BE8B0_HoneycombTreasureHunt, 0x18

dlabel D_80107F60_1BE8B0_HoneycombTreasureHunt
    /* 80107F60 */ .space 0x18

nonmatching D_80107F78_1BE8C8_HoneycombTreasureHunt, 0x10

dlabel D_80107F78_1BE8C8_HoneycombTreasureHunt
    /* 80107F78 */ .space 0x10

nonmatching D_80107F88_1BE8D8_HoneycombTreasureHunt, 0x4

dlabel D_80107F88_1BE8D8_HoneycombTreasureHunt
    /* 80107F88 */ .space 0x04

nonmatching D_80107F8C_1BE8DC_HoneycombTreasureHunt, 0xC

dlabel D_80107F8C_1BE8DC_HoneycombTreasureHunt
    /* 80107F8C */ .space 0x0C

nonmatching D_80107F98_1BE8E8_HoneycombTreasureHunt, 0x10

dlabel D_80107F98_1BE8E8_HoneycombTreasureHunt
    /* 80107F98 */ .space 0x10

nonmatching D_80107FA8_1BE8F8_HoneycombTreasureHunt, 0x8

dlabel D_80107FA8_1BE8F8_HoneycombTreasureHunt
    /* 80107FA8 */ .space 0x08

nonmatching D_80107FB0_1BE900_HoneycombTreasureHunt, 0x10

dlabel D_80107FB0_1BE900_HoneycombTreasureHunt
    /* 80107FB0 */ .space 0x10

nonmatching D_80107FC0_1BE910_HoneycombTreasureHunt, 0x14

dlabel D_80107FC0_1BE910_HoneycombTreasureHunt
    /* 80107FC0 */ .space 0x14

nonmatching D_80107FD4_1BE924_HoneycombTreasureHunt, 0x4C

dlabel D_80107FD4_1BE924_HoneycombTreasureHunt
    /* 80107FD4 */ .space 0x4C

nonmatching D_80108020_1BE970_HoneycombTreasureHunt, 0x10

dlabel D_80108020_1BE970_HoneycombTreasureHunt
    /* 80108020 */ .space 0x10

nonmatching D_80108030_1BE980_HoneycombTreasureHunt, 0x8

dlabel D_80108030_1BE980_HoneycombTreasureHunt
    /* 80108030 */ .space 0x08

nonmatching D_80108038_1BE988_HoneycombTreasureHunt, 0x4

dlabel D_80108038_1BE988_HoneycombTreasureHunt
    /* 80108038 */ .space 0x04

nonmatching D_8010803C_1BE98C_HoneycombTreasureHunt, 0x4

dlabel D_8010803C_1BE98C_HoneycombTreasureHunt
    /* 8010803C */ .space 0x04

nonmatching D_80108040_1BE990_HoneycombTreasureHunt, 0x10

dlabel D_80108040_1BE990_HoneycombTreasureHunt
    /* 80108040 */ .space 0x10

nonmatching D_80108050_1BE9A0_HoneycombTreasureHunt, 0x4

dlabel D_80108050_1BE9A0_HoneycombTreasureHunt
    /* 80108050 */ .space 0x04

nonmatching D_80108054_1BE9A4_HoneycombTreasureHunt, 0x4

dlabel D_80108054_1BE9A4_HoneycombTreasureHunt
    /* 80108054 */ .space 0x04

nonmatching D_80108058_1BE9A8_HoneycombTreasureHunt, 0x4F68

dlabel D_80108058_1BE9A8_HoneycombTreasureHunt
    /* 80108058 */ .space 0x4F68
