.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80108E60_1D6EE0_RollCall, 0x4

glabel D_80108E60_1D6EE0_RollCall
    /* 80108E60 */ .space 0x04

nonmatching D_80108E64_1D6EE4_RollCall, 0x98C

dlabel D_80108E64_1D6EE4_RollCall
    /* 80108E64 */ .space 0x98C

nonmatching D_801097F0_1D7870_RollCall, 0x2C

dlabel D_801097F0_1D7870_RollCall
    /* 801097F0 */ .space 0x2C

nonmatching D_8010981C_1D789C_RollCall, 0x4

dlabel D_8010981C_1D789C_RollCall
    /* 8010981C */ .space 0x04

nonmatching D_80109820_1D78A0_RollCall, 0x110

dlabel D_80109820_1D78A0_RollCall
    /* 80109820 */ .space 0x110

nonmatching D_80109930_1D79B0_RollCall, 0x4

dlabel D_80109930_1D79B0_RollCall
    /* 80109930 */ .space 0x04

nonmatching D_80109934_1D79B4_RollCall, 0x3C

dlabel D_80109934_1D79B4_RollCall
    /* 80109934 */ .space 0x3C

nonmatching D_80109970_1D79F0_RollCall, 0x3C

dlabel D_80109970_1D79F0_RollCall
    /* 80109970 */ .space 0x3C

nonmatching D_801099AC_1D7A2C_RollCall, 0x50

dlabel D_801099AC_1D7A2C_RollCall
    /* 801099AC */ .space 0x50

nonmatching D_801099FC_1D7A7C_RollCall, 0x2

dlabel D_801099FC_1D7A7C_RollCall
    /* 801099FC */ .space 0x02

nonmatching D_801099FE_1D7A7E_RollCall, 0xE

dlabel D_801099FE_1D7A7E_RollCall
    /* 801099FE */ .space 0x0E

nonmatching D_80109A0C_1D7A8C_RollCall, 0x18

dlabel D_80109A0C_1D7A8C_RollCall
    /* 80109A0C */ .space 0x18

nonmatching D_80109A24_1D7AA4_RollCall, 0x18

dlabel D_80109A24_1D7AA4_RollCall
    /* 80109A24 */ .space 0x18

nonmatching D_80109A3C_1D7ABC_RollCall, 0x10

dlabel D_80109A3C_1D7ABC_RollCall
    /* 80109A3C */ .space 0x10

nonmatching D_80109A4C_1D7ACC_RollCall, 0x2

dlabel D_80109A4C_1D7ACC_RollCall
    /* 80109A4C */ .space 0x02

nonmatching D_80109A4E_1D7ACE_RollCall, 0xE

dlabel D_80109A4E_1D7ACE_RollCall
    /* 80109A4E */ .space 0x0E

nonmatching D_80109A5C_1D7ADC_RollCall, 0xC

dlabel D_80109A5C_1D7ADC_RollCall
    /* 80109A5C */ .space 0x0C

nonmatching D_80109A68_1D7AE8_RollCall, 0x48

dlabel D_80109A68_1D7AE8_RollCall
    /* 80109A68 */ .space 0x48

nonmatching D_80109AB0_1D7B30_RollCall, 0x40

dlabel D_80109AB0_1D7B30_RollCall
    /* 80109AB0 */ .space 0x40

nonmatching D_80109AF0_1D7B70_RollCall, 0x1

dlabel D_80109AF0_1D7B70_RollCall
    /* 80109AF0 */ .space 0x01

nonmatching D_80109AF1_1D7B71_RollCall, 0x1

dlabel D_80109AF1_1D7B71_RollCall
    /* 80109AF1 */ .space 0x01

nonmatching D_80109AF2_1D7B72_RollCall, 0x62

dlabel D_80109AF2_1D7B72_RollCall
    /* 80109AF2 */ .space 0x62

nonmatching D_80109B54_1D7BD4_RollCall, 0xC

dlabel D_80109B54_1D7BD4_RollCall
    /* 80109B54 */ .space 0x0C

nonmatching D_80109B60_1D7BE0_RollCall, 0x8

dlabel D_80109B60_1D7BE0_RollCall
    /* 80109B60 */ .space 0x08

nonmatching D_80109B68_1D7BE8_RollCall, 0x18

dlabel D_80109B68_1D7BE8_RollCall
    /* 80109B68 */ .space 0x18

nonmatching D_80109B80_1D7C00_RollCall, 0x2

dlabel D_80109B80_1D7C00_RollCall
    /* 80109B80 */ .space 0x02

nonmatching D_80109B82_1D7C02_RollCall, 0x2

dlabel D_80109B82_1D7C02_RollCall
    /* 80109B82 */ .space 0x02

nonmatching D_80109B84_1D7C04_RollCall, 0x2

dlabel D_80109B84_1D7C04_RollCall
    /* 80109B84 */ .space 0x02

nonmatching D_80109B86_1D7C06_RollCall, 0x1

dlabel D_80109B86_1D7C06_RollCall
    /* 80109B86 */ .space 0x01

nonmatching D_80109B87_1D7C07_RollCall, 0x1

dlabel D_80109B87_1D7C07_RollCall
    /* 80109B87 */ .space 0x01

nonmatching D_80109B88_1D7C08_RollCall, 0x4

dlabel D_80109B88_1D7C08_RollCall
    /* 80109B88 */ .space 0x04

nonmatching D_80109B8C_1D7C0C_RollCall, 0x4

dlabel D_80109B8C_1D7C0C_RollCall
    /* 80109B8C */ .space 0x04

nonmatching D_80109B90_1D7C10_RollCall, 0x1C

dlabel D_80109B90_1D7C10_RollCall
    /* 80109B90 */ .space 0x1C

nonmatching D_80109BAC_1D7C2C_RollCall, 0x24

dlabel D_80109BAC_1D7C2C_RollCall
    /* 80109BAC */ .space 0x24

nonmatching D_80109BD0_1D7C50_RollCall, 0x2

dlabel D_80109BD0_1D7C50_RollCall
    /* 80109BD0 */ .space 0x02

nonmatching D_80109BD2_1D7C52_RollCall, 0xE

dlabel D_80109BD2_1D7C52_RollCall
    /* 80109BD2 */ .space 0x0E

nonmatching D_80109BE0_1D7C60_RollCall, 0x10

dlabel D_80109BE0_1D7C60_RollCall
    /* 80109BE0 */ .space 0x10

nonmatching D_80109BF0_1D7C70_RollCall, 0x4

dlabel D_80109BF0_1D7C70_RollCall
    /* 80109BF0 */ .space 0x04

nonmatching D_80109BF4_1D7C74_RollCall, 0x4

dlabel D_80109BF4_1D7C74_RollCall
    /* 80109BF4 */ .space 0x04

nonmatching D_80109BF8_1D7C78_RollCall, 0x2

dlabel D_80109BF8_1D7C78_RollCall
    /* 80109BF8 */ .space 0x02

nonmatching D_80109BFA_1D7C7A_RollCall, 0x8

dlabel D_80109BFA_1D7C7A_RollCall
    /* 80109BFA */ .space 0x08

nonmatching D_80109C02_1D7C82_RollCall, 0x8

dlabel D_80109C02_1D7C82_RollCall
    /* 80109C02 */ .space 0x08

nonmatching D_80109C0A_1D7C8A_RollCall, 0x2

dlabel D_80109C0A_1D7C8A_RollCall
    /* 80109C0A */ .space 0x02

nonmatching D_80109C0C_1D7C8C_RollCall, 0x8

dlabel D_80109C0C_1D7C8C_RollCall
    /* 80109C0C */ .space 0x08

nonmatching D_80109C14_1D7C94_RollCall, 0x4

dlabel D_80109C14_1D7C94_RollCall
    /* 80109C14 */ .space 0x04

nonmatching D_80109C18_1D7C98_RollCall, 0x4

dlabel D_80109C18_1D7C98_RollCall
    /* 80109C18 */ .space 0x04

nonmatching D_80109C1C_1D7C9C_RollCall, 0x4

dlabel D_80109C1C_1D7C9C_RollCall
    /* 80109C1C */ .space 0x04

nonmatching D_80109C20_1D7CA0_RollCall, 0x8

dlabel D_80109C20_1D7CA0_RollCall
    /* 80109C20 */ .space 0x08

nonmatching D_80109C28_1D7CA8_RollCall, 0x2

dlabel D_80109C28_1D7CA8_RollCall
    /* 80109C28 */ .space 0x02

nonmatching D_80109C2A_1D7CAA_RollCall, 0x36

dlabel D_80109C2A_1D7CAA_RollCall
    /* 80109C2A */ .space 0x36

nonmatching D_80109C60_1D7CE0_RollCall, 0x10

dlabel D_80109C60_1D7CE0_RollCall
    /* 80109C60 */ .space 0x10

nonmatching D_80109C70_1D7CF0_RollCall, 0x4

dlabel D_80109C70_1D7CF0_RollCall
    /* 80109C70 */ .space 0x04

nonmatching D_80109C74_1D7CF4_RollCall, 0x2

dlabel D_80109C74_1D7CF4_RollCall
    /* 80109C74 */ .space 0x02

nonmatching D_80109C76_1D7CF6_RollCall, 0x8

dlabel D_80109C76_1D7CF6_RollCall
    /* 80109C76 */ .space 0x08

nonmatching D_80109C7E_1D7CFE_RollCall, 0x2

dlabel D_80109C7E_1D7CFE_RollCall
    /* 80109C7E */ .space 0x02

nonmatching D_80109C80_1D7D00_RollCall, 0x10

dlabel D_80109C80_1D7D00_RollCall
    /* 80109C80 */ .space 0x10

nonmatching D_80109C90_1D7D10_RollCall, 0x4

dlabel D_80109C90_1D7D10_RollCall
    /* 80109C90 */ .space 0x04

nonmatching D_80109C94_1D7D14_RollCall, 0x4

dlabel D_80109C94_1D7D14_RollCall
    /* 80109C94 */ .space 0x04

nonmatching D_80109C98_1D7D18_RollCall, 0x28

dlabel D_80109C98_1D7D18_RollCall
    /* 80109C98 */ .space 0x28

nonmatching D_80109CC0_1D7D40_RollCall, 0xC

dlabel D_80109CC0_1D7D40_RollCall
    /* 80109CC0 */ .space 0x0C

nonmatching D_80109CCC_1D7D4C_RollCall, 0xC

dlabel D_80109CCC_1D7D4C_RollCall
    /* 80109CCC */ .space 0x0C

nonmatching D_80109CD8_1D7D58_RollCall, 0x18

dlabel D_80109CD8_1D7D58_RollCall
    /* 80109CD8 */ .space 0x18

nonmatching D_80109CF0_1D7D70_RollCall, 0x4

dlabel D_80109CF0_1D7D70_RollCall
    /* 80109CF0 */ .space 0x04

nonmatching D_80109CF4_1D7D74_RollCall, 0x4

dlabel D_80109CF4_1D7D74_RollCall
    /* 80109CF4 */ .space 0x04

nonmatching D_80109CF8_1D7D78_RollCall, 0x40

dlabel D_80109CF8_1D7D78_RollCall
    /* 80109CF8 */ .space 0x40

nonmatching D_80109D38_1D7DB8_RollCall, 0x10

dlabel D_80109D38_1D7DB8_RollCall
    /* 80109D38 */ .space 0x10

nonmatching D_80109D48_1D7DC8_RollCall, 0x6498

dlabel D_80109D48_1D7DC8_RollCall
    /* 80109D48 */ .space 0x6498
