.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_8010BFF0_19B590_BobsledRun, 0x4

dlabel D_8010BFF0_19B590_BobsledRun
    /* 8010BFF0 */ .space 0x04

nonmatching D_8010BFF4_19B594_BobsledRun, 0x1

dlabel D_8010BFF4_19B594_BobsledRun
    /* 8010BFF4 */ .space 0x01

nonmatching D_8010BFF5_19B595_BobsledRun, 0x3

dlabel D_8010BFF5_19B595_BobsledRun
    /* 8010BFF5 */ .space 0x03

nonmatching D_8010BFF8_19B598_BobsledRun, 0x4

dlabel D_8010BFF8_19B598_BobsledRun
    /* 8010BFF8 */ .space 0x04

nonmatching D_8010BFFC_19B59C_BobsledRun, 0x4

dlabel D_8010BFFC_19B59C_BobsledRun
    /* 8010BFFC */ .space 0x04

nonmatching D_8010C000_19B5A0_BobsledRun, 0xC

dlabel D_8010C000_19B5A0_BobsledRun
    /* 8010C000 */ .space 0x0C

nonmatching D_8010C00C_19B5AC_BobsledRun, 0xC

dlabel D_8010C00C_19B5AC_BobsledRun
    /* 8010C00C */ .space 0x0C

nonmatching D_8010C018_19B5B8_BobsledRun, 0x4

dlabel D_8010C018_19B5B8_BobsledRun
    /* 8010C018 */ .space 0x04

nonmatching D_8010C01C_19B5BC_BobsledRun, 0x4

dlabel D_8010C01C_19B5BC_BobsledRun
    /* 8010C01C */ .space 0x04

nonmatching D_8010C020_19B5C0_BobsledRun, 0x1C

dlabel D_8010C020_19B5C0_BobsledRun
    /* 8010C020 */ .space 0x1C

nonmatching D_8010C03C_19B5DC_BobsledRun, 0x4

dlabel D_8010C03C_19B5DC_BobsledRun
    /* 8010C03C */ .space 0x04

nonmatching D_8010C040_19B5E0_BobsledRun, 0x8

dlabel D_8010C040_19B5E0_BobsledRun
    /* 8010C040 */ .space 0x08

nonmatching D_8010C048_19B5E8_BobsledRun, 0x8

dlabel D_8010C048_19B5E8_BobsledRun
    /* 8010C048 */ .space 0x08

nonmatching D_8010C050_19B5F0_BobsledRun, 0x10

dlabel D_8010C050_19B5F0_BobsledRun
    /* 8010C050 */ .space 0x10

nonmatching D_8010C060_19B600_BobsledRun, 0x4

dlabel D_8010C060_19B600_BobsledRun
    /* 8010C060 */ .space 0x04

nonmatching D_8010C064_19B604_BobsledRun, 0x2

dlabel D_8010C064_19B604_BobsledRun
    /* 8010C064 */ .space 0x02

nonmatching D_8010C066_19B606_BobsledRun, 0x6

dlabel D_8010C066_19B606_BobsledRun
    /* 8010C066 */ .space 0x06

nonmatching D_8010C06C_19B60C_BobsledRun, 0x2

dlabel D_8010C06C_19B60C_BobsledRun
    /* 8010C06C */ .space 0x02

nonmatching D_8010C06E_19B60E_BobsledRun, 0xA

dlabel D_8010C06E_19B60E_BobsledRun
    /* 8010C06E */ .space 0x0A

nonmatching D_8010C078_19B618_BobsledRun, 0x2

dlabel D_8010C078_19B618_BobsledRun
    /* 8010C078 */ .space 0x02

nonmatching D_8010C07A_19B61A_BobsledRun, 0x1

dlabel D_8010C07A_19B61A_BobsledRun
    /* 8010C07A */ .space 0x01

nonmatching D_8010C07B_19B61B_BobsledRun, 0x1

dlabel D_8010C07B_19B61B_BobsledRun
    /* 8010C07B */ .space 0x01

nonmatching D_8010C07C_19B61C_BobsledRun, 0x1

dlabel D_8010C07C_19B61C_BobsledRun
    /* 8010C07C */ .space 0x01

nonmatching D_8010C07D_19B61D_BobsledRun, 0x1

dlabel D_8010C07D_19B61D_BobsledRun
    /* 8010C07D */ .space 0x01

nonmatching D_8010C07E_19B61E_BobsledRun, 0x1

dlabel D_8010C07E_19B61E_BobsledRun
    /* 8010C07E */ .space 0x01

nonmatching D_8010C07F_19B61F_BobsledRun, 0x1

dlabel D_8010C07F_19B61F_BobsledRun
    /* 8010C07F */ .space 0x01

nonmatching D_8010C080_19B620_BobsledRun, 0x1

dlabel D_8010C080_19B620_BobsledRun
    /* 8010C080 */ .space 0x01

nonmatching D_8010C081_19B621_BobsledRun, 0x1

dlabel D_8010C081_19B621_BobsledRun
    /* 8010C081 */ .space 0x01

nonmatching D_8010C082_19B622_BobsledRun, 0x1

dlabel D_8010C082_19B622_BobsledRun
    /* 8010C082 */ .space 0x01

nonmatching D_8010C083_19B623_BobsledRun, 0x1

dlabel D_8010C083_19B623_BobsledRun
    /* 8010C083 */ .space 0x01

nonmatching D_8010C084_19B624_BobsledRun, 0x3

dlabel D_8010C084_19B624_BobsledRun
    /* 8010C084 */ .space 0x03

nonmatching D_8010C087_19B627_BobsledRun, 0x1

dlabel D_8010C087_19B627_BobsledRun
    /* 8010C087 */ .space 0x01

nonmatching D_8010C088_19B628_BobsledRun, 0x1

dlabel D_8010C088_19B628_BobsledRun
    /* 8010C088 */ .space 0x01

nonmatching D_8010C089_19B629_BobsledRun, 0x33

dlabel D_8010C089_19B629_BobsledRun
    /* 8010C089 */ .space 0x33

nonmatching D_8010C0BC_19B65C_BobsledRun, 0x4

dlabel D_8010C0BC_19B65C_BobsledRun
    /* 8010C0BC */ .space 0x04

nonmatching D_8010C0C0_19B660_BobsledRun, 0x1

dlabel D_8010C0C0_19B660_BobsledRun
    /* 8010C0C0 */ .space 0x01

nonmatching D_8010C0C1_19B661_BobsledRun, 0x1

dlabel D_8010C0C1_19B661_BobsledRun
    /* 8010C0C1 */ .space 0x01

nonmatching D_8010C0C2_19B662_BobsledRun, 0xE

dlabel D_8010C0C2_19B662_BobsledRun
    /* 8010C0C2 */ .space 0x0E

nonmatching D_8010C0D0_19B670_BobsledRun, 0x4

dlabel D_8010C0D0_19B670_BobsledRun
    /* 8010C0D0 */ .space 0x04

nonmatching D_8010C0D4_19B674_BobsledRun, 0x4

dlabel D_8010C0D4_19B674_BobsledRun
    /* 8010C0D4 */ .space 0x04

nonmatching D_8010C0D8_19B678_BobsledRun, 0x4

dlabel D_8010C0D8_19B678_BobsledRun
    /* 8010C0D8 */ .space 0x04

nonmatching D_8010C0DC_19B67C_BobsledRun, 0x4

dlabel D_8010C0DC_19B67C_BobsledRun
    /* 8010C0DC */ .space 0x04

nonmatching D_8010C0E0_19B680_BobsledRun, 0x2

dlabel D_8010C0E0_19B680_BobsledRun
    /* 8010C0E0 */ .space 0x02

nonmatching D_8010C0E2_19B682_BobsledRun, 0x2

dlabel D_8010C0E2_19B682_BobsledRun
    /* 8010C0E2 */ .space 0x02

nonmatching D_8010C0E4_19B684_BobsledRun, 0x2

dlabel D_8010C0E4_19B684_BobsledRun
    /* 8010C0E4 */ .space 0x02

nonmatching D_8010C0E6_19B686_BobsledRun, 0x2

dlabel D_8010C0E6_19B686_BobsledRun
    /* 8010C0E6 */ .space 0x02

nonmatching D_8010C0E8_19B688_BobsledRun, 0x18

dlabel D_8010C0E8_19B688_BobsledRun
    /* 8010C0E8 */ .space 0x18

nonmatching D_8010C100_19B6A0_BobsledRun, 0x18

dlabel D_8010C100_19B6A0_BobsledRun
    /* 8010C100 */ .space 0x18

nonmatching D_8010C118_19B6B8_BobsledRun, 0x4

dlabel D_8010C118_19B6B8_BobsledRun
    /* 8010C118 */ .space 0x04

nonmatching D_8010C11C_19B6BC_BobsledRun, 0x4

dlabel D_8010C11C_19B6BC_BobsledRun
    /* 8010C11C */ .space 0x04

nonmatching D_8010C120_19B6C0_BobsledRun, 0x4

dlabel D_8010C120_19B6C0_BobsledRun
    /* 8010C120 */ .space 0x04

nonmatching D_8010C124_19B6C4_BobsledRun, 0x4

dlabel D_8010C124_19B6C4_BobsledRun
    /* 8010C124 */ .space 0x04

nonmatching D_8010C128_19B6C8_BobsledRun, 0x4

dlabel D_8010C128_19B6C8_BobsledRun
    /* 8010C128 */ .space 0x04

nonmatching D_8010C12C_19B6CC_BobsledRun, 0x4

dlabel D_8010C12C_19B6CC_BobsledRun
    /* 8010C12C */ .space 0x04

nonmatching D_8010C130_19B6D0_BobsledRun, 0x4

dlabel D_8010C130_19B6D0_BobsledRun
    /* 8010C130 */ .space 0x04

nonmatching D_8010C134_19B6D4_BobsledRun, 0xC

dlabel D_8010C134_19B6D4_BobsledRun
    /* 8010C134 */ .space 0x0C

nonmatching D_8010C140_19B6E0_BobsledRun, 0x4

dlabel D_8010C140_19B6E0_BobsledRun
    /* 8010C140 */ .space 0x04

nonmatching D_8010C144_19B6E4_BobsledRun, 0x1A

dlabel D_8010C144_19B6E4_BobsledRun
    /* 8010C144 */ .space 0x1A

nonmatching D_8010C15E_19B6FE_BobsledRun, 0xA

dlabel D_8010C15E_19B6FE_BobsledRun
    /* 8010C15E */ .space 0x0A

nonmatching D_8010C168_19B708_BobsledRun, 0x4

dlabel D_8010C168_19B708_BobsledRun
    /* 8010C168 */ .space 0x04

nonmatching D_8010C16C_19B70C_BobsledRun, 0x4

dlabel D_8010C16C_19B70C_BobsledRun
    /* 8010C16C */ .space 0x04

nonmatching D_8010C170_19B710_BobsledRun, 0x4C

dlabel D_8010C170_19B710_BobsledRun
    /* 8010C170 */ .space 0x4C

nonmatching D_8010C1BC_19B75C_BobsledRun, 0x4

dlabel D_8010C1BC_19B75C_BobsledRun
    /* 8010C1BC */ .space 0x04

nonmatching D_8010C1C0_19B760_BobsledRun, 0x4

dlabel D_8010C1C0_19B760_BobsledRun
    /* 8010C1C0 */ .space 0x04

nonmatching D_8010C1C4_19B764_BobsledRun, 0x334

dlabel D_8010C1C4_19B764_BobsledRun
    /* 8010C1C4 */ .space 0x334

nonmatching D_8010C4F8_19BA98_BobsledRun, 0x4

dlabel D_8010C4F8_19BA98_BobsledRun
    /* 8010C4F8 */ .space 0x04

nonmatching D_8010C4FC_19BA9C_BobsledRun, 0x4

dlabel D_8010C4FC_19BA9C_BobsledRun
    /* 8010C4FC */ .space 0x04

nonmatching D_8010C500_19BAA0_BobsledRun, 0x3C4

dlabel D_8010C500_19BAA0_BobsledRun
    /* 8010C500 */ .space 0x3C4

nonmatching D_8010C8C4_19BE64_BobsledRun, 0x4

dlabel D_8010C8C4_19BE64_BobsledRun
    /* 8010C8C4 */ .space 0x04

nonmatching D_8010C8C8_19BE68_BobsledRun, 0x4

dlabel D_8010C8C8_19BE68_BobsledRun
    /* 8010C8C8 */ .space 0x04

nonmatching D_8010C8CC_19BE6C_BobsledRun, 0x40

dlabel D_8010C8CC_19BE6C_BobsledRun
    /* 8010C8CC */ .space 0x40

nonmatching D_8010C90C_19BEAC_BobsledRun, 0x4

dlabel D_8010C90C_19BEAC_BobsledRun
    /* 8010C90C */ .space 0x04

nonmatching D_8010C910_19BEB0_BobsledRun, 0x4

dlabel D_8010C910_19BEB0_BobsledRun
    /* 8010C910 */ .space 0x04

nonmatching D_8010C914_19BEB4_BobsledRun, 0x4C

dlabel D_8010C914_19BEB4_BobsledRun
    /* 8010C914 */ .space 0x4C

nonmatching D_8010C960_19BF00_BobsledRun, 0x18

dlabel D_8010C960_19BF00_BobsledRun
    /* 8010C960 */ .space 0x18

nonmatching jtbl_8010C978_19BF18_BobsledRun, 0x18

dlabel jtbl_8010C978_19BF18_BobsledRun
    /* 8010C978 */ .space 0x18

nonmatching jtbl_8010C990_19BF30_BobsledRun, 0x18

dlabel jtbl_8010C990_19BF30_BobsledRun
    /* 8010C990 */ .space 0x18

nonmatching D_8010C9A8_19BF48_BobsledRun, 0x8

dlabel D_8010C9A8_19BF48_BobsledRun
    /* 8010C9A8 */ .space 0x08

nonmatching D_8010C9B0_19BF50_BobsledRun, 0x8

dlabel D_8010C9B0_19BF50_BobsledRun
    /* 8010C9B0 */ .space 0x08

nonmatching D_8010C9B8_19BF58_BobsledRun, 0x8

dlabel D_8010C9B8_19BF58_BobsledRun
    /* 8010C9B8 */ .space 0x08

nonmatching D_8010C9C0_19BF60_BobsledRun, 0x8

dlabel D_8010C9C0_19BF60_BobsledRun
    /* 8010C9C0 */ .space 0x08

nonmatching jtbl_8010C9C8_19BF68_BobsledRun, 0x28

dlabel jtbl_8010C9C8_19BF68_BobsledRun
    /* 8010C9C8 */ .space 0x28

nonmatching D_8010C9F0_19BF90_BobsledRun, 0x4

dlabel D_8010C9F0_19BF90_BobsledRun
    /* 8010C9F0 */ .space 0x04

nonmatching D_8010C9F4_19BF94_BobsledRun, 0x2

dlabel D_8010C9F4_19BF94_BobsledRun
    /* 8010C9F4 */ .space 0x02

nonmatching D_8010C9F6_19BF96_BobsledRun, 0x2

dlabel D_8010C9F6_19BF96_BobsledRun
    /* 8010C9F6 */ .space 0x02

nonmatching D_8010C9F8_19BF98_BobsledRun, 0x2

dlabel D_8010C9F8_19BF98_BobsledRun
    /* 8010C9F8 */ .space 0x02

nonmatching D_8010C9FA_19BF9A_BobsledRun, 0x2

dlabel D_8010C9FA_19BF9A_BobsledRun
    /* 8010C9FA */ .space 0x02

nonmatching D_8010C9FC_19BF9C_BobsledRun, 0x4

dlabel D_8010C9FC_19BF9C_BobsledRun
    /* 8010C9FC */ .space 0x04

nonmatching D_8010CA00_19BFA0_BobsledRun, 0x4

dlabel D_8010CA00_19BFA0_BobsledRun
    /* 8010CA00 */ .space 0x04

nonmatching D_8010CA04_19BFA4_BobsledRun, 0x4

dlabel D_8010CA04_19BFA4_BobsledRun
    /* 8010CA04 */ .space 0x04

nonmatching D_8010CA08_19BFA8_BobsledRun, 0x4

dlabel D_8010CA08_19BFA8_BobsledRun
    /* 8010CA08 */ .space 0x04

nonmatching D_8010CA0C_19BFAC_BobsledRun, 0x2

dlabel D_8010CA0C_19BFAC_BobsledRun
    /* 8010CA0C */ .space 0x02

nonmatching D_8010CA0E_19BFAE_BobsledRun, 0x2

dlabel D_8010CA0E_19BFAE_BobsledRun
    /* 8010CA0E */ .space 0x02

nonmatching D_8010CA10_19BFB0_BobsledRun, 0x10

dlabel D_8010CA10_19BFB0_BobsledRun
    /* 8010CA10 */ .space 0x10

nonmatching D_8010CA20_19BFC0_BobsledRun, 0x4

dlabel D_8010CA20_19BFC0_BobsledRun
    /* 8010CA20 */ .space 0x04

nonmatching D_8010CA24_19BFC4_BobsledRun, 0x4

dlabel D_8010CA24_19BFC4_BobsledRun
    /* 8010CA24 */ .space 0x04

nonmatching D_8010CA28_19BFC8_BobsledRun, 0x10

dlabel D_8010CA28_19BFC8_BobsledRun
    /* 8010CA28 */ .space 0x10

nonmatching D_8010CA38_19BFD8_BobsledRun, 0xA4

dlabel D_8010CA38_19BFD8_BobsledRun
    /* 8010CA38 */ .space 0xA4

nonmatching D_8010CADC_19C07C_BobsledRun, 0x54

dlabel D_8010CADC_19C07C_BobsledRun
    /* 8010CADC */ .space 0x54

nonmatching D_8010CB30_19C0D0_BobsledRun, 0x10

dlabel D_8010CB30_19C0D0_BobsledRun
    /* 8010CB30 */ .space 0x10

nonmatching D_8010CB40_19C0E0_BobsledRun, 0x2

dlabel D_8010CB40_19C0E0_BobsledRun
    /* 8010CB40 */ .space 0x02

nonmatching D_8010CB42_19C0E2_BobsledRun, 0x6

dlabel D_8010CB42_19C0E2_BobsledRun
    /* 8010CB42 */ .space 0x06

nonmatching D_8010CB48_19C0E8_BobsledRun, 0xA4

dlabel D_8010CB48_19C0E8_BobsledRun
    /* 8010CB48 */ .space 0xA4

nonmatching D_8010CBEC_19C18C_BobsledRun, 0x50

dlabel D_8010CBEC_19C18C_BobsledRun
    /* 8010CBEC */ .space 0x50

nonmatching D_8010CC3C_19C1DC_BobsledRun, 0x2

dlabel D_8010CC3C_19C1DC_BobsledRun
    /* 8010CC3C */ .space 0x02

nonmatching D_8010CC3E_19C1DE_BobsledRun, 0x95A2

dlabel D_8010CC3E_19C1DE_BobsledRun
    /* 8010CC3E */ .space 0x95A2
