.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80109040_20C750_ShuffleAdventure, 0x4

dlabel D_80109040_20C750_ShuffleAdventure
    /* 80109040 */ .space 0x04

nonmatching D_80109044_20C754_ShuffleAdventure, 0x1

dlabel D_80109044_20C754_ShuffleAdventure
    /* 80109044 */ .space 0x01

nonmatching D_80109045_20C755_ShuffleAdventure, 0x3

dlabel D_80109045_20C755_ShuffleAdventure
    /* 80109045 */ .space 0x03

nonmatching D_80109048_20C758_ShuffleAdventure, 0x1

dlabel D_80109048_20C758_ShuffleAdventure
    /* 80109048 */ .space 0x01

nonmatching D_80109049_20C759_ShuffleAdventure, 0xC

dlabel D_80109049_20C759_ShuffleAdventure
    /* 80109049 */ .space 0x0C

nonmatching D_80109055_20C765_ShuffleAdventure, 0x1

dlabel D_80109055_20C765_ShuffleAdventure
    /* 80109055 */ .space 0x01

nonmatching D_80109056_20C766_ShuffleAdventure, 0xC

dlabel D_80109056_20C766_ShuffleAdventure
    /* 80109056 */ .space 0x0C

nonmatching D_80109062_20C772_ShuffleAdventure, 0x1

dlabel D_80109062_20C772_ShuffleAdventure
    /* 80109062 */ .space 0x01

nonmatching D_80109063_20C773_ShuffleAdventure, 0xC

dlabel D_80109063_20C773_ShuffleAdventure
    /* 80109063 */ .space 0x0C

nonmatching D_8010906F_20C77F_ShuffleAdventure, 0x1

dlabel D_8010906F_20C77F_ShuffleAdventure
    /* 8010906F */ .space 0x01

nonmatching D_80109070_20C780_ShuffleAdventure, 0xC

dlabel D_80109070_20C780_ShuffleAdventure
    /* 80109070 */ .space 0x0C

nonmatching D_8010907C_20C78C_ShuffleAdventure, 0x1

dlabel D_8010907C_20C78C_ShuffleAdventure
    /* 8010907C */ .space 0x01

nonmatching D_8010907D_20C78D_ShuffleAdventure, 0xC

dlabel D_8010907D_20C78D_ShuffleAdventure
    /* 8010907D */ .space 0x0C

nonmatching D_80109089_20C799_ShuffleAdventure, 0x1

dlabel D_80109089_20C799_ShuffleAdventure
    /* 80109089 */ .space 0x01

nonmatching D_8010908A_20C79A_ShuffleAdventure, 0xC

dlabel D_8010908A_20C79A_ShuffleAdventure
    /* 8010908A */ .space 0x0C

nonmatching D_80109096_20C7A6_ShuffleAdventure, 0x1

dlabel D_80109096_20C7A6_ShuffleAdventure
    /* 80109096 */ .space 0x01

nonmatching D_80109097_20C7A7_ShuffleAdventure, 0xC

dlabel D_80109097_20C7A7_ShuffleAdventure
    /* 80109097 */ .space 0x0C

nonmatching D_801090A3_20C7B3_ShuffleAdventure, 0x1

dlabel D_801090A3_20C7B3_ShuffleAdventure
    /* 801090A3 */ .space 0x01

nonmatching D_801090A4_20C7B4_ShuffleAdventure, 0xC

dlabel D_801090A4_20C7B4_ShuffleAdventure
    /* 801090A4 */ .space 0x0C

nonmatching D_801090B0_20C7C0_ShuffleAdventure, 0x1

dlabel D_801090B0_20C7C0_ShuffleAdventure
    /* 801090B0 */ .space 0x01

nonmatching D_801090B1_20C7C1_ShuffleAdventure, 0x1

dlabel D_801090B1_20C7C1_ShuffleAdventure
    /* 801090B1 */ .space 0x01

nonmatching D_801090B2_20C7C2_ShuffleAdventure, 0x1A

dlabel D_801090B2_20C7C2_ShuffleAdventure
    /* 801090B2 */ .space 0x1A

nonmatching D_801090CC_20C7DC_ShuffleAdventure, 0xC

dlabel D_801090CC_20C7DC_ShuffleAdventure
    /* 801090CC */ .space 0x0C

nonmatching D_801090D8_20C7E8_ShuffleAdventure, 0x5

dlabel D_801090D8_20C7E8_ShuffleAdventure
    /* 801090D8 */ .space 0x05

nonmatching D_801090DD_20C7ED_ShuffleAdventure, 0xB

dlabel D_801090DD_20C7ED_ShuffleAdventure
    /* 801090DD */ .space 0x0B

nonmatching D_801090E8_20C7F8_ShuffleAdventure, 0x5

dlabel D_801090E8_20C7F8_ShuffleAdventure
    /* 801090E8 */ .space 0x05

nonmatching D_801090ED_20C7FD_ShuffleAdventure, 0xB

dlabel D_801090ED_20C7FD_ShuffleAdventure
    /* 801090ED */ .space 0x0B

nonmatching D_801090F8_20C808_ShuffleAdventure, 0x14

dlabel D_801090F8_20C808_ShuffleAdventure
    /* 801090F8 */ .space 0x14

nonmatching D_8010910C_20C81C_ShuffleAdventure, 0x14

dlabel D_8010910C_20C81C_ShuffleAdventure
    /* 8010910C */ .space 0x14

nonmatching D_80109120_20C830_ShuffleAdventure, 0x1

dlabel D_80109120_20C830_ShuffleAdventure
    /* 80109120 */ .space 0x01

nonmatching D_80109121_20C831_ShuffleAdventure, 0x1

dlabel D_80109121_20C831_ShuffleAdventure
    /* 80109121 */ .space 0x01

nonmatching D_80109122_20C832_ShuffleAdventure, 0x1

dlabel D_80109122_20C832_ShuffleAdventure
    /* 80109122 */ .space 0x01

nonmatching D_80109123_20C833_ShuffleAdventure, 0x1

dlabel D_80109123_20C833_ShuffleAdventure
    /* 80109123 */ .space 0x01

nonmatching D_80109124_20C834_ShuffleAdventure, 0x2

dlabel D_80109124_20C834_ShuffleAdventure
    /* 80109124 */ .space 0x02

nonmatching D_80109126_20C836_ShuffleAdventure, 0x2

dlabel D_80109126_20C836_ShuffleAdventure
    /* 80109126 */ .space 0x02

nonmatching D_80109128_20C838_ShuffleAdventure, 0x2

dlabel D_80109128_20C838_ShuffleAdventure
    /* 80109128 */ .space 0x02

nonmatching D_8010912A_20C83A_ShuffleAdventure, 0x2

dlabel D_8010912A_20C83A_ShuffleAdventure
    /* 8010912A */ .space 0x02

nonmatching D_8010912C_20C83C_ShuffleAdventure, 0x4

dlabel D_8010912C_20C83C_ShuffleAdventure
    /* 8010912C */ .space 0x04

nonmatching D_80109130_20C840_ShuffleAdventure, 0x4

dlabel D_80109130_20C840_ShuffleAdventure
    /* 80109130 */ .space 0x04

nonmatching D_80109134_20C844_ShuffleAdventure, 0x4

dlabel D_80109134_20C844_ShuffleAdventure
    /* 80109134 */ .space 0x04

nonmatching D_80109138_20C848_ShuffleAdventure, 0x4

dlabel D_80109138_20C848_ShuffleAdventure
    /* 80109138 */ .space 0x04

nonmatching D_8010913C_20C84C_ShuffleAdventure, 0x4

dlabel D_8010913C_20C84C_ShuffleAdventure
    /* 8010913C */ .space 0x04

nonmatching D_80109140_20C850_ShuffleAdventure, 0x2

dlabel D_80109140_20C850_ShuffleAdventure
    /* 80109140 */ .space 0x02

nonmatching D_80109142_20C852_ShuffleAdventure, 0x2

dlabel D_80109142_20C852_ShuffleAdventure
    /* 80109142 */ .space 0x02

nonmatching D_80109144_20C854_ShuffleAdventure, 0x1

dlabel D_80109144_20C854_ShuffleAdventure
    /* 80109144 */ .space 0x01

nonmatching D_80109145_20C855_ShuffleAdventure, 0x3

dlabel D_80109145_20C855_ShuffleAdventure
    /* 80109145 */ .space 0x03

nonmatching D_80109148_20C858_ShuffleAdventure, 0x80

dlabel D_80109148_20C858_ShuffleAdventure
    /* 80109148 */ .space 0x80

nonmatching D_801091C8_20C8D8_ShuffleAdventure, 0x4

dlabel D_801091C8_20C8D8_ShuffleAdventure
    /* 801091C8 */ .space 0x04

nonmatching D_801091CC_20C8DC_ShuffleAdventure, 0x4

dlabel D_801091CC_20C8DC_ShuffleAdventure
    /* 801091CC */ .space 0x04

nonmatching D_801091D0_20C8E0_ShuffleAdventure, 0x4

dlabel D_801091D0_20C8E0_ShuffleAdventure
    /* 801091D0 */ .space 0x04

nonmatching D_801091D4_20C8E4_ShuffleAdventure, 0xC

dlabel D_801091D4_20C8E4_ShuffleAdventure
    /* 801091D4 */ .space 0x0C

nonmatching D_801091E0_20C8F0_ShuffleAdventure, 0x14

dlabel D_801091E0_20C8F0_ShuffleAdventure
    /* 801091E0 */ .space 0x14

nonmatching D_801091F4_20C904_ShuffleAdventure, 0x14

dlabel D_801091F4_20C904_ShuffleAdventure
    /* 801091F4 */ .space 0x14

nonmatching D_80109208_20C918_ShuffleAdventure, 0x14

dlabel D_80109208_20C918_ShuffleAdventure
    /* 80109208 */ .space 0x14

nonmatching D_8010921C_20C92C_ShuffleAdventure, 0x14

dlabel D_8010921C_20C92C_ShuffleAdventure
    /* 8010921C */ .space 0x14

nonmatching D_80109230_20C940_ShuffleAdventure, 0x14

dlabel D_80109230_20C940_ShuffleAdventure
    /* 80109230 */ .space 0x14

nonmatching D_80109244_20C954_ShuffleAdventure, 0x14

dlabel D_80109244_20C954_ShuffleAdventure
    /* 80109244 */ .space 0x14

nonmatching D_80109258_20C968_ShuffleAdventure, 0xC

dlabel D_80109258_20C968_ShuffleAdventure
    /* 80109258 */ .space 0x0C

nonmatching D_80109264_20C974_ShuffleAdventure, 0xC

dlabel D_80109264_20C974_ShuffleAdventure
    /* 80109264 */ .space 0x0C

nonmatching D_80109270_20C980_ShuffleAdventure, 0x14

dlabel D_80109270_20C980_ShuffleAdventure
    /* 80109270 */ .space 0x14

nonmatching D_80109284_20C994_ShuffleAdventure, 0x14

dlabel D_80109284_20C994_ShuffleAdventure
    /* 80109284 */ .space 0x14

nonmatching jtbl_80109298_20C9A8_ShuffleAdventure, 0x20

dlabel jtbl_80109298_20C9A8_ShuffleAdventure
    /* 80109298 */ .space 0x20

nonmatching D_801092B8_20C9C8_ShuffleAdventure, 0x8

dlabel D_801092B8_20C9C8_ShuffleAdventure
    /* 801092B8 */ .space 0x08

nonmatching D_801092C0_20C9D0_ShuffleAdventure, 0x8

dlabel D_801092C0_20C9D0_ShuffleAdventure
    /* 801092C0 */ .space 0x08

nonmatching D_801092C8_20C9D8_ShuffleAdventure, 0x8

dlabel D_801092C8_20C9D8_ShuffleAdventure
    /* 801092C8 */ .space 0x08

nonmatching D_801092D0_20C9E0_ShuffleAdventure, 0x18

dlabel D_801092D0_20C9E0_ShuffleAdventure
    /* 801092D0 */ .space 0x18

nonmatching D_801092E8_20C9F8_ShuffleAdventure, 0x8

dlabel D_801092E8_20C9F8_ShuffleAdventure
    /* 801092E8 */ .space 0x08

nonmatching D_801092F0_20CA00_ShuffleAdventure, 0x8

dlabel D_801092F0_20CA00_ShuffleAdventure
    /* 801092F0 */ .space 0x08

nonmatching D_801092F8_20CA08_ShuffleAdventure, 0x8

dlabel D_801092F8_20CA08_ShuffleAdventure
    /* 801092F8 */ .space 0x08

nonmatching D_80109300_20CA10_ShuffleAdventure, 0x8

dlabel D_80109300_20CA10_ShuffleAdventure
    /* 80109300 */ .space 0x08

nonmatching D_80109308_20CA18_ShuffleAdventure, 0x8

dlabel D_80109308_20CA18_ShuffleAdventure
    /* 80109308 */ .space 0x08

nonmatching D_80109310_20CA20_ShuffleAdventure, 0x8

dlabel D_80109310_20CA20_ShuffleAdventure
    /* 80109310 */ .space 0x08

nonmatching D_80109318_20CA28_ShuffleAdventure, 0x10

dlabel D_80109318_20CA28_ShuffleAdventure
    /* 80109318 */ .space 0x10

nonmatching jtbl_80109328_20CA38_ShuffleAdventure, 0x28

dlabel jtbl_80109328_20CA38_ShuffleAdventure
    /* 80109328 */ .space 0x28

nonmatching D_80109350_20CA60_ShuffleAdventure, 0x8

dlabel D_80109350_20CA60_ShuffleAdventure
    /* 80109350 */ .space 0x08

nonmatching D_80109358_20CA68_ShuffleAdventure, 0x8

dlabel D_80109358_20CA68_ShuffleAdventure
    /* 80109358 */ .space 0x08

nonmatching D_80109360_20CA70_ShuffleAdventure, 0x8

dlabel D_80109360_20CA70_ShuffleAdventure
    /* 80109360 */ .space 0x08

nonmatching D_80109368_20CA78_ShuffleAdventure, 0x8

dlabel D_80109368_20CA78_ShuffleAdventure
    /* 80109368 */ .space 0x08

nonmatching D_80109370_20CA80_ShuffleAdventure, 0x8

dlabel D_80109370_20CA80_ShuffleAdventure
    /* 80109370 */ .space 0x08

nonmatching D_80109378_20CA88_ShuffleAdventure, 0xC

dlabel D_80109378_20CA88_ShuffleAdventure
    /* 80109378 */ .space 0x0C

nonmatching D_80109384_20CA94_ShuffleAdventure, 0x10

dlabel D_80109384_20CA94_ShuffleAdventure
    /* 80109384 */ .space 0x10

nonmatching D_80109394_20CAA4_ShuffleAdventure, 0xC

dlabel D_80109394_20CAA4_ShuffleAdventure
    /* 80109394 */ .space 0x0C

nonmatching D_801093A0_20CAB0_ShuffleAdventure, 0x10

dlabel D_801093A0_20CAB0_ShuffleAdventure
    /* 801093A0 */ .space 0x10

nonmatching D_801093B0_20CAC0_ShuffleAdventure, 0x2

dlabel D_801093B0_20CAC0_ShuffleAdventure
    /* 801093B0 */ .space 0x02

nonmatching D_801093B2_20CAC2_ShuffleAdventure, 0x2

dlabel D_801093B2_20CAC2_ShuffleAdventure
    /* 801093B2 */ .space 0x02

nonmatching D_801093B4_20CAC4_ShuffleAdventure, 0x4

dlabel D_801093B4_20CAC4_ShuffleAdventure
    /* 801093B4 */ .space 0x04

nonmatching D_801093B8_20CAC8_ShuffleAdventure, 0x4

dlabel D_801093B8_20CAC8_ShuffleAdventure
    /* 801093B8 */ .space 0x04

nonmatching D_801093BC_20CACC_ShuffleAdventure, 0x4

dlabel D_801093BC_20CACC_ShuffleAdventure
    /* 801093BC */ .space 0x04

nonmatching D_801093C0_20CAD0_ShuffleAdventure, 0x10

dlabel D_801093C0_20CAD0_ShuffleAdventure
    /* 801093C0 */ .space 0x10

nonmatching D_801093D0_20CAE0_ShuffleAdventure, 0x8

dlabel D_801093D0_20CAE0_ShuffleAdventure
    /* 801093D0 */ .space 0x08

nonmatching D_801093D8_20CAE8_ShuffleAdventure, 0x18

dlabel D_801093D8_20CAE8_ShuffleAdventure
    /* 801093D8 */ .space 0x18

nonmatching D_801093F0_20CB00_ShuffleAdventure, 0x1

dlabel D_801093F0_20CB00_ShuffleAdventure
    /* 801093F0 */ .space 0x01

nonmatching D_801093F1_20CB01_ShuffleAdventure, 0x1

dlabel D_801093F1_20CB01_ShuffleAdventure
    /* 801093F1 */ .space 0x01

nonmatching D_801093F2_20CB02_ShuffleAdventure, 0x1

dlabel D_801093F2_20CB02_ShuffleAdventure
    /* 801093F2 */ .space 0x01

nonmatching D_801093F3_20CB03_ShuffleAdventure, 0x1

dlabel D_801093F3_20CB03_ShuffleAdventure
    /* 801093F3 */ .space 0x01

nonmatching D_801093F4_20CB04_ShuffleAdventure, 0x4

dlabel D_801093F4_20CB04_ShuffleAdventure
    /* 801093F4 */ .space 0x04

nonmatching D_801093F8_20CB08_ShuffleAdventure, 0x4

dlabel D_801093F8_20CB08_ShuffleAdventure
    /* 801093F8 */ .space 0x04

nonmatching D_801093FC_20CB0C_ShuffleAdventure, 0x3

dlabel D_801093FC_20CB0C_ShuffleAdventure
    /* 801093FC */ .space 0x03

nonmatching D_801093FF_20CB0F_ShuffleAdventure, 0x151

dlabel D_801093FF_20CB0F_ShuffleAdventure
    /* 801093FF */ .space 0x151

nonmatching D_80109550_20CC60_ShuffleAdventure, 0x4

dlabel D_80109550_20CC60_ShuffleAdventure
    /* 80109550 */ .space 0x04

nonmatching D_80109554_20CC64_ShuffleAdventure, 0x4

dlabel D_80109554_20CC64_ShuffleAdventure
    /* 80109554 */ .space 0x04

nonmatching D_80109558_20CC68_ShuffleAdventure, 0x4

dlabel D_80109558_20CC68_ShuffleAdventure
    /* 80109558 */ .space 0x04

nonmatching D_8010955C_20CC6C_ShuffleAdventure, 0x6694

dlabel D_8010955C_20CC6C_ShuffleAdventure
    /* 8010955C */ .space 0x6694
