.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_801098A0_2C7CF0_HotBobOmb2P, 0x2

dlabel D_801098A0_2C7CF0_HotBobOmb2P
    /* 801098A0 */ .space 0x02

nonmatching D_801098A2_2C7CF2_HotBobOmb2P, 0x2

dlabel D_801098A2_2C7CF2_HotBobOmb2P
    /* 801098A2 */ .space 0x02

nonmatching D_801098A4_2C7CF4_HotBobOmb2P, 0x2

dlabel D_801098A4_2C7CF4_HotBobOmb2P
    /* 801098A4 */ .space 0x02

nonmatching D_801098A6_2C7CF6_HotBobOmb2P, 0x1C

dlabel D_801098A6_2C7CF6_HotBobOmb2P
    /* 801098A6 */ .space 0x1C

nonmatching D_801098C2_2C7D12_HotBobOmb2P, 0x236

dlabel D_801098C2_2C7D12_HotBobOmb2P
    /* 801098C2 */ .space 0x236

nonmatching D_80109AF8_2C7F48_HotBobOmb2P, 0x18

dlabel D_80109AF8_2C7F48_HotBobOmb2P
    /* 80109AF8 */ .space 0x18

nonmatching D_80109B10_2C7F60_HotBobOmb2P, 0x4

dlabel D_80109B10_2C7F60_HotBobOmb2P
    /* 80109B10 */ .space 0x04

nonmatching D_80109B14_2C7F64_HotBobOmb2P, 0xC

dlabel D_80109B14_2C7F64_HotBobOmb2P
    /* 80109B14 */ .space 0x0C

nonmatching D_80109B20_2C7F70_HotBobOmb2P, 0xC

dlabel D_80109B20_2C7F70_HotBobOmb2P
    /* 80109B20 */ .space 0x0C

nonmatching D_80109B2C_2C7F7C_HotBobOmb2P, 0x24

dlabel D_80109B2C_2C7F7C_HotBobOmb2P
    /* 80109B2C */ .space 0x24

nonmatching D_80109B50_2C7FA0_HotBobOmb2P, 0xC

dlabel D_80109B50_2C7FA0_HotBobOmb2P
    /* 80109B50 */ .space 0x0C

nonmatching D_80109B5C_2C7FAC_HotBobOmb2P, 0x24

dlabel D_80109B5C_2C7FAC_HotBobOmb2P
    /* 80109B5C */ .space 0x24

nonmatching D_80109B80_2C7FD0_HotBobOmb2P, 0x18

dlabel D_80109B80_2C7FD0_HotBobOmb2P
    /* 80109B80 */ .space 0x18

nonmatching D_80109B98_2C7FE8_HotBobOmb2P, 0xC

dlabel D_80109B98_2C7FE8_HotBobOmb2P
    /* 80109B98 */ .space 0x0C

nonmatching D_80109BA4_2C7FF4_HotBobOmb2P, 0x4

dlabel D_80109BA4_2C7FF4_HotBobOmb2P
    /* 80109BA4 */ .space 0x04

nonmatching D_80109BA8_2C7FF8_HotBobOmb2P, 0x4

dlabel D_80109BA8_2C7FF8_HotBobOmb2P
    /* 80109BA8 */ .space 0x04

nonmatching D_80109BAC_2C7FFC_HotBobOmb2P, 0x4

dlabel D_80109BAC_2C7FFC_HotBobOmb2P
    /* 80109BAC */ .space 0x04

nonmatching D_80109BB0_2C8000_HotBobOmb2P, 0x10

dlabel D_80109BB0_2C8000_HotBobOmb2P
    /* 80109BB0 */ .space 0x10

nonmatching D_80109BC0_2C8010_HotBobOmb2P, 0xC

dlabel D_80109BC0_2C8010_HotBobOmb2P
    /* 80109BC0 */ .space 0x0C

nonmatching D_80109BCC_2C801C_HotBobOmb2P, 0xC

dlabel D_80109BCC_2C801C_HotBobOmb2P
    /* 80109BCC */ .space 0x0C

nonmatching D_80109BD8_2C8028_HotBobOmb2P, 0x18

dlabel D_80109BD8_2C8028_HotBobOmb2P
    /* 80109BD8 */ .space 0x18

nonmatching D_80109BF0_2C8040_HotBobOmb2P, 0xC

dlabel D_80109BF0_2C8040_HotBobOmb2P
    /* 80109BF0 */ .space 0x0C

nonmatching D_80109BFC_2C804C_HotBobOmb2P, 0x4

dlabel D_80109BFC_2C804C_HotBobOmb2P
    /* 80109BFC */ .space 0x04

nonmatching D_80109C00_2C8050_HotBobOmb2P, 0x8

dlabel D_80109C00_2C8050_HotBobOmb2P
    /* 80109C00 */ .space 0x08

nonmatching D_80109C08_2C8058_HotBobOmb2P, 0xC

dlabel D_80109C08_2C8058_HotBobOmb2P
    /* 80109C08 */ .space 0x0C

nonmatching D_80109C14_2C8064_HotBobOmb2P, 0x18

dlabel D_80109C14_2C8064_HotBobOmb2P
    /* 80109C14 */ .space 0x18

nonmatching D_80109C2C_2C807C_HotBobOmb2P, 0x10

dlabel D_80109C2C_2C807C_HotBobOmb2P
    /* 80109C2C */ .space 0x10

nonmatching D_80109C3C_2C808C_HotBobOmb2P, 0x4

dlabel D_80109C3C_2C808C_HotBobOmb2P
    /* 80109C3C */ .space 0x04

nonmatching D_80109C40_2C8090_HotBobOmb2P, 0xC

dlabel D_80109C40_2C8090_HotBobOmb2P
    /* 80109C40 */ .space 0x0C

nonmatching D_80109C4C_2C809C_HotBobOmb2P, 0xC

dlabel D_80109C4C_2C809C_HotBobOmb2P
    /* 80109C4C */ .space 0x0C

nonmatching D_80109C58_2C80A8_HotBobOmb2P, 0x10

dlabel D_80109C58_2C80A8_HotBobOmb2P
    /* 80109C58 */ .space 0x10

nonmatching D_80109C68_2C80B8_HotBobOmb2P, 0x80

dlabel D_80109C68_2C80B8_HotBobOmb2P
    /* 80109C68 */ .space 0x80

nonmatching D_80109CE8_2C8138_HotBobOmb2P, 0x10

dlabel D_80109CE8_2C8138_HotBobOmb2P
    /* 80109CE8 */ .space 0x10

nonmatching D_80109CF8_2C8148_HotBobOmb2P, 0x10

dlabel D_80109CF8_2C8148_HotBobOmb2P
    /* 80109CF8 */ .space 0x10

nonmatching D_80109D08_2C8158_HotBobOmb2P, 0x18

dlabel D_80109D08_2C8158_HotBobOmb2P
    /* 80109D08 */ .space 0x18

nonmatching D_80109D20_2C8170_HotBobOmb2P, 0x18

dlabel D_80109D20_2C8170_HotBobOmb2P
    /* 80109D20 */ .space 0x18

nonmatching D_80109D38_2C8188_HotBobOmb2P, 0x18

dlabel D_80109D38_2C8188_HotBobOmb2P
    /* 80109D38 */ .space 0x18

nonmatching D_80109D50_2C81A0_HotBobOmb2P, 0x18

dlabel D_80109D50_2C81A0_HotBobOmb2P
    /* 80109D50 */ .space 0x18

nonmatching D_80109D68_2C81B8_HotBobOmb2P, 0x8

dlabel D_80109D68_2C81B8_HotBobOmb2P
    /* 80109D68 */ .space 0x08

nonmatching D_80109D70_2C81C0_HotBobOmb2P, 0x4

dlabel D_80109D70_2C81C0_HotBobOmb2P
    /* 80109D70 */ .space 0x04

nonmatching D_80109D74_2C81C4_HotBobOmb2P, 0x4

dlabel D_80109D74_2C81C4_HotBobOmb2P
    /* 80109D74 */ .space 0x04

nonmatching D_80109D78_2C81C8_HotBobOmb2P, 0x2

dlabel D_80109D78_2C81C8_HotBobOmb2P
    /* 80109D78 */ .space 0x02

nonmatching D_80109D7A_2C81CA_HotBobOmb2P, 0x2

dlabel D_80109D7A_2C81CA_HotBobOmb2P
    /* 80109D7A */ .space 0x02

nonmatching D_80109D7C_2C81CC_HotBobOmb2P, 0x2

dlabel D_80109D7C_2C81CC_HotBobOmb2P
    /* 80109D7C */ .space 0x02

nonmatching D_80109D7E_2C81CE_HotBobOmb2P, 0x2

dlabel D_80109D7E_2C81CE_HotBobOmb2P
    /* 80109D7E */ .space 0x02

nonmatching D_80109D80_2C81D0_HotBobOmb2P, 0x4

dlabel D_80109D80_2C81D0_HotBobOmb2P
    /* 80109D80 */ .space 0x04

nonmatching D_80109D84_2C81D4_HotBobOmb2P, 0x4

dlabel D_80109D84_2C81D4_HotBobOmb2P
    /* 80109D84 */ .space 0x04

nonmatching D_80109D88_2C81D8_HotBobOmb2P, 0x4

dlabel D_80109D88_2C81D8_HotBobOmb2P
    /* 80109D88 */ .space 0x04

nonmatching D_80109D8C_2C81DC_HotBobOmb2P, 0x4

dlabel D_80109D8C_2C81DC_HotBobOmb2P
    /* 80109D8C */ .space 0x04

nonmatching D_80109D90_2C81E0_HotBobOmb2P, 0x4

dlabel D_80109D90_2C81E0_HotBobOmb2P
    /* 80109D90 */ .space 0x04

nonmatching D_80109D94_2C81E4_HotBobOmb2P, 0x4

dlabel D_80109D94_2C81E4_HotBobOmb2P
    /* 80109D94 */ .space 0x04

nonmatching D_80109D98_2C81E8_HotBobOmb2P, 0x10

dlabel D_80109D98_2C81E8_HotBobOmb2P
    /* 80109D98 */ .space 0x10

nonmatching D_80109DA8_2C81F8_HotBobOmb2P, 0x8

dlabel D_80109DA8_2C81F8_HotBobOmb2P
    /* 80109DA8 */ .space 0x08

nonmatching D_80109DB0_2C8200_HotBobOmb2P, 0x10

dlabel D_80109DB0_2C8200_HotBobOmb2P
    /* 80109DB0 */ .space 0x10

nonmatching D_80109DC0_2C8210_HotBobOmb2P, 0x4

dlabel D_80109DC0_2C8210_HotBobOmb2P
    /* 80109DC0 */ .space 0x04

nonmatching D_80109DC4_2C8214_HotBobOmb2P, 0x4

dlabel D_80109DC4_2C8214_HotBobOmb2P
    /* 80109DC4 */ .space 0x04

nonmatching D_80109DC8_2C8218_HotBobOmb2P, 0x4

dlabel D_80109DC8_2C8218_HotBobOmb2P
    /* 80109DC8 */ .space 0x04

nonmatching D_80109DCC_2C821C_HotBobOmb2P, 0x4

dlabel D_80109DCC_2C821C_HotBobOmb2P
    /* 80109DCC */ .space 0x04

nonmatching D_80109DD0_2C8220_HotBobOmb2P, 0x10

dlabel D_80109DD0_2C8220_HotBobOmb2P
    /* 80109DD0 */ .space 0x10

nonmatching D_80109DE0_2C8230_HotBobOmb2P, 0x4

dlabel D_80109DE0_2C8230_HotBobOmb2P
    /* 80109DE0 */ .space 0x04

nonmatching D_80109DE4_2C8234_HotBobOmb2P, 0x4

dlabel D_80109DE4_2C8234_HotBobOmb2P
    /* 80109DE4 */ .space 0x04

nonmatching D_80109DE8_2C8238_HotBobOmb2P, 0x4

dlabel D_80109DE8_2C8238_HotBobOmb2P
    /* 80109DE8 */ .space 0x04

nonmatching D_80109DEC_2C823C_HotBobOmb2P, 0x4

dlabel D_80109DEC_2C823C_HotBobOmb2P
    /* 80109DEC */ .space 0x04

nonmatching D_80109DF0_2C8240_HotBobOmb2P, 0x4

dlabel D_80109DF0_2C8240_HotBobOmb2P
    /* 80109DF0 */ .space 0x04

nonmatching D_80109DF4_2C8244_HotBobOmb2P, 0x8

dlabel D_80109DF4_2C8244_HotBobOmb2P
    /* 80109DF4 */ .space 0x08

nonmatching D_80109DFC_2C824C_HotBobOmb2P, 0xC

dlabel D_80109DFC_2C824C_HotBobOmb2P
    /* 80109DFC */ .space 0x0C

nonmatching D_80109E08_2C8258_HotBobOmb2P, 0x12C

dlabel D_80109E08_2C8258_HotBobOmb2P
    /* 80109E08 */ .space 0x12C

nonmatching D_80109F34_2C8384_HotBobOmb2P, 0x12C

dlabel D_80109F34_2C8384_HotBobOmb2P
    /* 80109F34 */ .space 0x12C

nonmatching D_8010A060_2C84B0_HotBobOmb2P, 0x4

dlabel D_8010A060_2C84B0_HotBobOmb2P
    /* 8010A060 */ .space 0x04

nonmatching D_8010A064_2C84B4_HotBobOmb2P, 0xC

dlabel D_8010A064_2C84B4_HotBobOmb2P
    /* 8010A064 */ .space 0x0C

nonmatching D_8010A070_2C84C0_HotBobOmb2P, 0xA

dlabel D_8010A070_2C84C0_HotBobOmb2P
    /* 8010A070 */ .space 0x0A

nonmatching D_8010A07A_2C84CA_HotBobOmb2P, 0xA

dlabel D_8010A07A_2C84CA_HotBobOmb2P
    /* 8010A07A */ .space 0x0A

nonmatching D_8010A084_2C84D4_HotBobOmb2P, 0x2

dlabel D_8010A084_2C84D4_HotBobOmb2P
    /* 8010A084 */ .space 0x02

nonmatching D_8010A086_2C84D6_HotBobOmb2P, 0x2

dlabel D_8010A086_2C84D6_HotBobOmb2P
    /* 8010A086 */ .space 0x02

nonmatching D_8010A088_2C84D8_HotBobOmb2P, 0x4

dlabel D_8010A088_2C84D8_HotBobOmb2P
    /* 8010A088 */ .space 0x04

nonmatching D_8010A08C_2C84DC_HotBobOmb2P, 0x4

dlabel D_8010A08C_2C84DC_HotBobOmb2P
    /* 8010A08C */ .space 0x04

nonmatching D_8010A090_2C84E0_HotBobOmb2P, 0x4

dlabel D_8010A090_2C84E0_HotBobOmb2P
    /* 8010A090 */ .space 0x04

nonmatching D_8010A094_2C84E4_HotBobOmb2P, 0x4

dlabel D_8010A094_2C84E4_HotBobOmb2P
    /* 8010A094 */ .space 0x04

nonmatching D_8010A098_2C84E8_HotBobOmb2P, 0x4

dlabel D_8010A098_2C84E8_HotBobOmb2P
    /* 8010A098 */ .space 0x04

nonmatching D_8010A09C_2C84EC_HotBobOmb2P, 0x4

dlabel D_8010A09C_2C84EC_HotBobOmb2P
    /* 8010A09C */ .space 0x04

nonmatching D_8010A0A0_2C84F0_HotBobOmb2P, 0x4

dlabel D_8010A0A0_2C84F0_HotBobOmb2P
    /* 8010A0A0 */ .space 0x04

nonmatching D_8010A0A4_2C84F4_HotBobOmb2P, 0x4

dlabel D_8010A0A4_2C84F4_HotBobOmb2P
    /* 8010A0A4 */ .space 0x04

nonmatching D_8010A0A8_2C84F8_HotBobOmb2P, 0xC

dlabel D_8010A0A8_2C84F8_HotBobOmb2P
    /* 8010A0A8 */ .space 0x0C

nonmatching D_8010A0B4_2C8504_HotBobOmb2P, 0x4

dlabel D_8010A0B4_2C8504_HotBobOmb2P
    /* 8010A0B4 */ .space 0x04

nonmatching D_8010A0B8_2C8508_HotBobOmb2P, 0x8

dlabel D_8010A0B8_2C8508_HotBobOmb2P
    /* 8010A0B8 */ .space 0x08

nonmatching D_8010A0C0_2C8510_HotBobOmb2P, 0x20

dlabel D_8010A0C0_2C8510_HotBobOmb2P
    /* 8010A0C0 */ .space 0x20

nonmatching D_8010A0E0_2C8530_HotBobOmb2P, 0x20

dlabel D_8010A0E0_2C8530_HotBobOmb2P
    /* 8010A0E0 */ .space 0x20

nonmatching D_8010A100_2C8550_HotBobOmb2P, 0x6D10

dlabel D_8010A100_2C8550_HotBobOmb2P
    /* 8010A100 */ .space 0x6D10
