.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80106560_406640_MinigameSelect, 0x4

glabel D_80106560_406640_MinigameSelect
    /* 80106560 */ .space 0x04

nonmatching D_80106564_406644_MinigameSelect, 0x2C

dlabel D_80106564_406644_MinigameSelect
    /* 80106564 */ .space 0x2C

nonmatching D_80106590_406670_MinigameSelect, 0x4

dlabel D_80106590_406670_MinigameSelect
    /* 80106590 */ .space 0x04

nonmatching D_80106594_406674_MinigameSelect, 0x18

dlabel D_80106594_406674_MinigameSelect
    /* 80106594 */ .space 0x18

nonmatching D_801065AC_40668C_MinigameSelect, 0x18

dlabel D_801065AC_40668C_MinigameSelect
    /* 801065AC */ .space 0x18

nonmatching D_801065C4_4066A4_MinigameSelect, 0xC

dlabel D_801065C4_4066A4_MinigameSelect
    /* 801065C4 */ .space 0x0C

nonmatching D_801065D0_4066B0_MinigameSelect, 0xC

dlabel D_801065D0_4066B0_MinigameSelect
    /* 801065D0 */ .space 0x0C

nonmatching D_801065DC_4066BC_MinigameSelect, 0x2

dlabel D_801065DC_4066BC_MinigameSelect
    /* 801065DC */ .space 0x02

nonmatching D_801065DE_4066BE_MinigameSelect, 0xE

dlabel D_801065DE_4066BE_MinigameSelect
    /* 801065DE */ .space 0x0E

nonmatching D_801065EC_4066CC_MinigameSelect, 0x2

dlabel D_801065EC_4066CC_MinigameSelect
    /* 801065EC */ .space 0x02

nonmatching D_801065EE_4066CE_MinigameSelect, 0x2

dlabel D_801065EE_4066CE_MinigameSelect
    /* 801065EE */ .space 0x02

nonmatching D_801065F0_4066D0_MinigameSelect, 0x2

dlabel D_801065F0_4066D0_MinigameSelect
    /* 801065F0 */ .space 0x02

nonmatching D_801065F2_4066D2_MinigameSelect, 0x2

dlabel D_801065F2_4066D2_MinigameSelect
    /* 801065F2 */ .space 0x02

nonmatching D_801065F4_4066D4_MinigameSelect, 0x4

dlabel D_801065F4_4066D4_MinigameSelect
    /* 801065F4 */ .space 0x04

nonmatching D_801065F8_4066D8_MinigameSelect, 0x18

dlabel D_801065F8_4066D8_MinigameSelect
    /* 801065F8 */ .space 0x18

nonmatching D_80106610_4066F0_MinigameSelect, 0x24

dlabel D_80106610_4066F0_MinigameSelect
    /* 80106610 */ .space 0x24

nonmatching D_80106634_406714_MinigameSelect, 0x28

dlabel D_80106634_406714_MinigameSelect
    /* 80106634 */ .space 0x28

nonmatching D_8010665C_40673C_MinigameSelect, 0x10

dlabel D_8010665C_40673C_MinigameSelect
    /* 8010665C */ .space 0x10

nonmatching D_8010666C_40674C_MinigameSelect, 0x8

dlabel D_8010666C_40674C_MinigameSelect
    /* 8010666C */ .space 0x08

nonmatching D_80106674_406754_MinigameSelect, 0x1

dlabel D_80106674_406754_MinigameSelect
    /* 80106674 */ .space 0x01

nonmatching D_80106675_406755_MinigameSelect, 0x1

dlabel D_80106675_406755_MinigameSelect
    /* 80106675 */ .space 0x01

nonmatching D_80106676_406756_MinigameSelect, 0x1

dlabel D_80106676_406756_MinigameSelect
    /* 80106676 */ .space 0x01

nonmatching D_80106677_406757_MinigameSelect, 0x1

dlabel D_80106677_406757_MinigameSelect
    /* 80106677 */ .space 0x01

nonmatching D_80106678_406758_MinigameSelect, 0x2

dlabel D_80106678_406758_MinigameSelect
    /* 80106678 */ .space 0x02

nonmatching D_8010667A_40675A_MinigameSelect, 0x1

dlabel D_8010667A_40675A_MinigameSelect
    /* 8010667A */ .space 0x01

nonmatching D_8010667B_40675B_MinigameSelect, 0x1

dlabel D_8010667B_40675B_MinigameSelect
    /* 8010667B */ .space 0x01

nonmatching D_8010667C_40675C_MinigameSelect, 0x2

dlabel D_8010667C_40675C_MinigameSelect
    /* 8010667C */ .space 0x02

nonmatching D_8010667E_40675E_MinigameSelect, 0x6

dlabel D_8010667E_40675E_MinigameSelect
    /* 8010667E */ .space 0x06

nonmatching D_80106684_406764_MinigameSelect, 0x20

dlabel D_80106684_406764_MinigameSelect
    /* 80106684 */ .space 0x20

nonmatching D_801066A4_406784_MinigameSelect, 0x8

dlabel D_801066A4_406784_MinigameSelect
    /* 801066A4 */ .space 0x08

nonmatching D_801066AC_40678C_MinigameSelect, 0x18

dlabel D_801066AC_40678C_MinigameSelect
    /* 801066AC */ .space 0x18

nonmatching D_801066C4_4067A4_MinigameSelect, 0x20

dlabel D_801066C4_4067A4_MinigameSelect
    /* 801066C4 */ .space 0x20

nonmatching D_801066E4_4067C4_MinigameSelect, 0x3

dlabel D_801066E4_4067C4_MinigameSelect
    /* 801066E4 */ .space 0x03

nonmatching D_801066E7_4067C7_MinigameSelect, 0x3

dlabel D_801066E7_4067C7_MinigameSelect
    /* 801066E7 */ .space 0x03

nonmatching D_801066EA_4067CA_MinigameSelect, 0x6

dlabel D_801066EA_4067CA_MinigameSelect
    /* 801066EA */ .space 0x06

nonmatching D_801066F0_4067D0_MinigameSelect, 0x4

dlabel D_801066F0_4067D0_MinigameSelect
    /* 801066F0 */ .space 0x04

nonmatching D_801066F4_4067D4_MinigameSelect, 0x4

dlabel D_801066F4_4067D4_MinigameSelect
    /* 801066F4 */ .space 0x04

nonmatching D_801066F8_4067D8_MinigameSelect, 0x8

dlabel D_801066F8_4067D8_MinigameSelect
    /* 801066F8 */ .space 0x08

nonmatching D_80106700_4067E0_MinigameSelect, 0x8

dlabel D_80106700_4067E0_MinigameSelect
    /* 80106700 */ .space 0x08

nonmatching D_80106708_4067E8_MinigameSelect, 0x8

dlabel D_80106708_4067E8_MinigameSelect
    /* 80106708 */ .space 0x08

nonmatching D_80106710_4067F0_MinigameSelect, 0x8

dlabel D_80106710_4067F0_MinigameSelect
    /* 80106710 */ .space 0x08

nonmatching D_80106718_4067F8_MinigameSelect, 0x8

dlabel D_80106718_4067F8_MinigameSelect
    /* 80106718 */ .space 0x08

nonmatching D_80106720_406800_MinigameSelect, 0x8

dlabel D_80106720_406800_MinigameSelect
    /* 80106720 */ .space 0x08

nonmatching D_80106728_406808_MinigameSelect, 0x8

dlabel D_80106728_406808_MinigameSelect
    /* 80106728 */ .space 0x08

nonmatching D_80106730_406810_MinigameSelect, 0x10

dlabel D_80106730_406810_MinigameSelect
    /* 80106730 */ .space 0x10

nonmatching D_80106740_406820_MinigameSelect, 0x2

dlabel D_80106740_406820_MinigameSelect
    /* 80106740 */ .space 0x02

nonmatching D_80106742_406822_MinigameSelect, 0x2

dlabel D_80106742_406822_MinigameSelect
    /* 80106742 */ .space 0x02

nonmatching D_80106744_406824_MinigameSelect, 0x1

dlabel D_80106744_406824_MinigameSelect
    /* 80106744 */ .space 0x01

nonmatching D_80106745_406825_MinigameSelect, 0x13

dlabel D_80106745_406825_MinigameSelect
    /* 80106745 */ .space 0x13

nonmatching D_80106758_406838_MinigameSelect, 0x18

dlabel D_80106758_406838_MinigameSelect
    /* 80106758 */ .space 0x18

nonmatching D_80106770_406850_MinigameSelect, 0x4

dlabel D_80106770_406850_MinigameSelect
    /* 80106770 */ .space 0x04

nonmatching D_80106774_406854_MinigameSelect, 0x4

dlabel D_80106774_406854_MinigameSelect
    /* 80106774 */ .space 0x04

nonmatching D_80106778_406858_MinigameSelect, 0x8

dlabel D_80106778_406858_MinigameSelect
    /* 80106778 */ .space 0x08

nonmatching D_80106780_406860_MinigameSelect, 0x8

dlabel D_80106780_406860_MinigameSelect
    /* 80106780 */ .space 0x08

nonmatching D_80106788_406868_MinigameSelect, 0x8

dlabel D_80106788_406868_MinigameSelect
    /* 80106788 */ .space 0x08

nonmatching D_80106790_406870_MinigameSelect, 0x4

dlabel D_80106790_406870_MinigameSelect
    /* 80106790 */ .space 0x04

nonmatching D_80106794_406874_MinigameSelect, 0x4

dlabel D_80106794_406874_MinigameSelect
    /* 80106794 */ .space 0x04

nonmatching D_80106798_406878_MinigameSelect, 0x2

dlabel D_80106798_406878_MinigameSelect
    /* 80106798 */ .space 0x02

nonmatching D_8010679A_40687A_MinigameSelect, 0x2

dlabel D_8010679A_40687A_MinigameSelect
    /* 8010679A */ .space 0x02

nonmatching D_8010679C_40687C_MinigameSelect, 0x2

dlabel D_8010679C_40687C_MinigameSelect
    /* 8010679C */ .space 0x02

nonmatching D_8010679E_40687E_MinigameSelect, 0x2

dlabel D_8010679E_40687E_MinigameSelect
    /* 8010679E */ .space 0x02

nonmatching D_801067A0_406880_MinigameSelect, 0x4

dlabel D_801067A0_406880_MinigameSelect
    /* 801067A0 */ .space 0x04

nonmatching D_801067A4_406884_MinigameSelect, 0x2

dlabel D_801067A4_406884_MinigameSelect
    /* 801067A4 */ .space 0x02

nonmatching D_801067A6_406886_MinigameSelect, 0x2

dlabel D_801067A6_406886_MinigameSelect
    /* 801067A6 */ .space 0x02

nonmatching D_801067A8_406888_MinigameSelect, 0x2

dlabel D_801067A8_406888_MinigameSelect
    /* 801067A8 */ .space 0x02

nonmatching D_801067AA_40688A_MinigameSelect, 0x2

dlabel D_801067AA_40688A_MinigameSelect
    /* 801067AA */ .space 0x02

nonmatching D_801067AC_40688C_MinigameSelect, 0x2

dlabel D_801067AC_40688C_MinigameSelect
    /* 801067AC */ .space 0x02

nonmatching D_801067AE_40688E_MinigameSelect, 0x6

dlabel D_801067AE_40688E_MinigameSelect
    /* 801067AE */ .space 0x06

nonmatching D_801067B4_406894_MinigameSelect, 0x2

dlabel D_801067B4_406894_MinigameSelect
    /* 801067B4 */ .space 0x02

nonmatching D_801067B6_406896_MinigameSelect, 0x2

dlabel D_801067B6_406896_MinigameSelect
    /* 801067B6 */ .space 0x02

nonmatching D_801067B8_406898_MinigameSelect, 0x2

dlabel D_801067B8_406898_MinigameSelect
    /* 801067B8 */ .space 0x02

nonmatching D_801067BA_40689A_MinigameSelect, 0x6

dlabel D_801067BA_40689A_MinigameSelect
    /* 801067BA */ .space 0x06

nonmatching D_801067C0_4068A0_MinigameSelect, 0x8

dlabel D_801067C0_4068A0_MinigameSelect
    /* 801067C0 */ .space 0x08

nonmatching D_801067C8_4068A8_MinigameSelect, 0x2

dlabel D_801067C8_4068A8_MinigameSelect
    /* 801067C8 */ .space 0x02

nonmatching D_801067CA_4068AA_MinigameSelect, 0x2

dlabel D_801067CA_4068AA_MinigameSelect
    /* 801067CA */ .space 0x02

nonmatching D_801067CC_4068AC_MinigameSelect, 0xC

dlabel D_801067CC_4068AC_MinigameSelect
    /* 801067CC */ .space 0x0C

nonmatching D_801067D8_4068B8_MinigameSelect, 0x20

dlabel D_801067D8_4068B8_MinigameSelect
    /* 801067D8 */ .space 0x20

nonmatching D_801067F8_4068D8_MinigameSelect, 0x2

dlabel D_801067F8_4068D8_MinigameSelect
    /* 801067F8 */ .space 0x02

nonmatching D_801067FA_4068DA_MinigameSelect, 0x6

dlabel D_801067FA_4068DA_MinigameSelect
    /* 801067FA */ .space 0x06

nonmatching D_80106800_4068E0_MinigameSelect, 0x4

dlabel D_80106800_4068E0_MinigameSelect
    /* 80106800 */ .space 0x04

nonmatching D_80106804_4068E4_MinigameSelect, 0xC

dlabel D_80106804_4068E4_MinigameSelect
    /* 80106804 */ .space 0x0C

nonmatching D_80106810_4068F0_MinigameSelect, 0xC

dlabel D_80106810_4068F0_MinigameSelect
    /* 80106810 */ .space 0x0C

nonmatching D_8010681C_4068FC_MinigameSelect, 0xC

dlabel D_8010681C_4068FC_MinigameSelect
    /* 8010681C */ .space 0x0C

nonmatching D_80106828_406908_MinigameSelect, 0xC

dlabel D_80106828_406908_MinigameSelect
    /* 80106828 */ .space 0x0C

nonmatching D_80106834_406914_MinigameSelect, 0xC

dlabel D_80106834_406914_MinigameSelect
    /* 80106834 */ .space 0x0C

nonmatching D_80106840_406920_MinigameSelect, 0x4

dlabel D_80106840_406920_MinigameSelect
    /* 80106840 */ .space 0x04

nonmatching D_80106844_406924_MinigameSelect, 0x4

dlabel D_80106844_406924_MinigameSelect
    /* 80106844 */ .space 0x04

nonmatching D_80106848_406928_MinigameSelect, 0x4

dlabel D_80106848_406928_MinigameSelect
    /* 80106848 */ .space 0x04

nonmatching D_8010684C_40692C_MinigameSelect, 0x4

dlabel D_8010684C_40692C_MinigameSelect
    /* 8010684C */ .space 0x04

nonmatching D_80106850_406930_MinigameSelect, 0x3C50

dlabel D_80106850_406930_MinigameSelect
    /* 80106850 */ .space 0x3C50
