.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_801061F0_3EF7F0_BattleMinigame, 0x4

glabel D_801061F0_3EF7F0_BattleMinigame
    /* 801061F0 */ .space 0x04

nonmatching D_801061F4_3EF7F4_BattleMinigame, 0x2C

dlabel D_801061F4_3EF7F4_BattleMinigame
    /* 801061F4 */ .space 0x2C

nonmatching D_80106220_3EF820_BattleMinigame, 0x14

dlabel D_80106220_3EF820_BattleMinigame
    /* 80106220 */ .space 0x14

nonmatching D_80106234_3EF834_BattleMinigame, 0x18

dlabel D_80106234_3EF834_BattleMinigame
    /* 80106234 */ .space 0x18

nonmatching D_8010624C_3EF84C_BattleMinigame, 0x18

dlabel D_8010624C_3EF84C_BattleMinigame
    /* 8010624C */ .space 0x18

nonmatching D_80106264_3EF864_BattleMinigame, 0xC

dlabel D_80106264_3EF864_BattleMinigame
    /* 80106264 */ .space 0x0C

nonmatching D_80106270_3EF870_BattleMinigame, 0xC

dlabel D_80106270_3EF870_BattleMinigame
    /* 80106270 */ .space 0x0C

nonmatching D_8010627C_3EF87C_BattleMinigame, 0x2

dlabel D_8010627C_3EF87C_BattleMinigame
    /* 8010627C */ .space 0x02

nonmatching D_8010627E_3EF87E_BattleMinigame, 0xE

dlabel D_8010627E_3EF87E_BattleMinigame
    /* 8010627E */ .space 0x0E

nonmatching D_8010628C_3EF88C_BattleMinigame, 0x2

dlabel D_8010628C_3EF88C_BattleMinigame
    /* 8010628C */ .space 0x02

nonmatching D_8010628E_3EF88E_BattleMinigame, 0x2

dlabel D_8010628E_3EF88E_BattleMinigame
    /* 8010628E */ .space 0x02

nonmatching D_80106290_3EF890_BattleMinigame, 0x2

dlabel D_80106290_3EF890_BattleMinigame
    /* 80106290 */ .space 0x02

nonmatching D_80106292_3EF892_BattleMinigame, 0x2

dlabel D_80106292_3EF892_BattleMinigame
    /* 80106292 */ .space 0x02

nonmatching D_80106294_3EF894_BattleMinigame, 0x84

dlabel D_80106294_3EF894_BattleMinigame
    /* 80106294 */ .space 0x84

nonmatching D_80106318_3EF918_BattleMinigame, 0x48

dlabel D_80106318_3EF918_BattleMinigame
    /* 80106318 */ .space 0x48

nonmatching D_80106360_3EF960_BattleMinigame, 0x10

dlabel D_80106360_3EF960_BattleMinigame
    /* 80106360 */ .space 0x10

nonmatching D_80106370_3EF970_BattleMinigame, 0x8

dlabel D_80106370_3EF970_BattleMinigame
    /* 80106370 */ .space 0x08

nonmatching D_80106378_3EF978_BattleMinigame, 0x1

dlabel D_80106378_3EF978_BattleMinigame
    /* 80106378 */ .space 0x01

nonmatching D_80106379_3EF979_BattleMinigame, 0x1

dlabel D_80106379_3EF979_BattleMinigame
    /* 80106379 */ .space 0x01

nonmatching D_8010637A_3EF97A_BattleMinigame, 0x1

dlabel D_8010637A_3EF97A_BattleMinigame
    /* 8010637A */ .space 0x01

nonmatching D_8010637B_3EF97B_BattleMinigame, 0x1

dlabel D_8010637B_3EF97B_BattleMinigame
    /* 8010637B */ .space 0x01

nonmatching D_8010637C_3EF97C_BattleMinigame, 0x2

dlabel D_8010637C_3EF97C_BattleMinigame
    /* 8010637C */ .space 0x02

nonmatching D_8010637E_3EF97E_BattleMinigame, 0x1

dlabel D_8010637E_3EF97E_BattleMinigame
    /* 8010637E */ .space 0x01

nonmatching D_8010637F_3EF97F_BattleMinigame, 0x1

dlabel D_8010637F_3EF97F_BattleMinigame
    /* 8010637F */ .space 0x01

nonmatching D_80106380_3EF980_BattleMinigame, 0x2

dlabel D_80106380_3EF980_BattleMinigame
    /* 80106380 */ .space 0x02

nonmatching D_80106382_3EF982_BattleMinigame, 0x6

dlabel D_80106382_3EF982_BattleMinigame
    /* 80106382 */ .space 0x06

nonmatching D_80106388_3EF988_BattleMinigame, 0x20

dlabel D_80106388_3EF988_BattleMinigame
    /* 80106388 */ .space 0x20

nonmatching D_801063A8_3EF9A8_BattleMinigame, 0x8

dlabel D_801063A8_3EF9A8_BattleMinigame
    /* 801063A8 */ .space 0x08

nonmatching D_801063B0_3EF9B0_BattleMinigame, 0x18

dlabel D_801063B0_3EF9B0_BattleMinigame
    /* 801063B0 */ .space 0x18

nonmatching D_801063C8_3EF9C8_BattleMinigame, 0x20

dlabel D_801063C8_3EF9C8_BattleMinigame
    /* 801063C8 */ .space 0x20

nonmatching D_801063E8_3EF9E8_BattleMinigame, 0x3

dlabel D_801063E8_3EF9E8_BattleMinigame
    /* 801063E8 */ .space 0x03

nonmatching D_801063EB_3EF9EB_BattleMinigame, 0x3

dlabel D_801063EB_3EF9EB_BattleMinigame
    /* 801063EB */ .space 0x03

nonmatching D_801063EE_3EF9EE_BattleMinigame, 0x12

dlabel D_801063EE_3EF9EE_BattleMinigame
    /* 801063EE */ .space 0x12

nonmatching D_80106400_3EFA00_BattleMinigame, 0x4

dlabel D_80106400_3EFA00_BattleMinigame
    /* 80106400 */ .space 0x04

nonmatching D_80106404_3EFA04_BattleMinigame, 0x4

dlabel D_80106404_3EFA04_BattleMinigame
    /* 80106404 */ .space 0x04

nonmatching D_80106408_3EFA08_BattleMinigame, 0x8

dlabel D_80106408_3EFA08_BattleMinigame
    /* 80106408 */ .space 0x08

nonmatching D_80106410_3EFA10_BattleMinigame, 0x8

dlabel D_80106410_3EFA10_BattleMinigame
    /* 80106410 */ .space 0x08

nonmatching D_80106418_3EFA18_BattleMinigame, 0x8

dlabel D_80106418_3EFA18_BattleMinigame
    /* 80106418 */ .space 0x08

nonmatching D_80106420_3EFA20_BattleMinigame, 0x8

dlabel D_80106420_3EFA20_BattleMinigame
    /* 80106420 */ .space 0x08

nonmatching D_80106428_3EFA28_BattleMinigame, 0x8

dlabel D_80106428_3EFA28_BattleMinigame
    /* 80106428 */ .space 0x08

nonmatching D_80106430_3EFA30_BattleMinigame, 0x8

dlabel D_80106430_3EFA30_BattleMinigame
    /* 80106430 */ .space 0x08

nonmatching D_80106438_3EFA38_BattleMinigame, 0x8

dlabel D_80106438_3EFA38_BattleMinigame
    /* 80106438 */ .space 0x08

nonmatching D_80106440_3EFA40_BattleMinigame, 0x2

dlabel D_80106440_3EFA40_BattleMinigame
    /* 80106440 */ .space 0x02

nonmatching D_80106442_3EFA42_BattleMinigame, 0x2

dlabel D_80106442_3EFA42_BattleMinigame
    /* 80106442 */ .space 0x02

nonmatching D_80106444_3EFA44_BattleMinigame, 0x1

dlabel D_80106444_3EFA44_BattleMinigame
    /* 80106444 */ .space 0x01

nonmatching D_80106445_3EFA45_BattleMinigame, 0x13

dlabel D_80106445_3EFA45_BattleMinigame
    /* 80106445 */ .space 0x13

nonmatching D_80106458_3EFA58_BattleMinigame, 0x18

dlabel D_80106458_3EFA58_BattleMinigame
    /* 80106458 */ .space 0x18

nonmatching D_80106470_3EFA70_BattleMinigame, 0x4

dlabel D_80106470_3EFA70_BattleMinigame
    /* 80106470 */ .space 0x04

nonmatching D_80106474_3EFA74_BattleMinigame, 0x4

dlabel D_80106474_3EFA74_BattleMinigame
    /* 80106474 */ .space 0x04

nonmatching D_80106478_3EFA78_BattleMinigame, 0x8

dlabel D_80106478_3EFA78_BattleMinigame
    /* 80106478 */ .space 0x08

nonmatching D_80106480_3EFA80_BattleMinigame, 0x8

dlabel D_80106480_3EFA80_BattleMinigame
    /* 80106480 */ .space 0x08

nonmatching D_80106488_3EFA88_BattleMinigame, 0x8

dlabel D_80106488_3EFA88_BattleMinigame
    /* 80106488 */ .space 0x08

nonmatching D_80106490_3EFA90_BattleMinigame, 0x2

dlabel D_80106490_3EFA90_BattleMinigame
    /* 80106490 */ .space 0x02

nonmatching D_80106492_3EFA92_BattleMinigame, 0x2

dlabel D_80106492_3EFA92_BattleMinigame
    /* 80106492 */ .space 0x02

nonmatching D_80106494_3EFA94_BattleMinigame, 0x2

dlabel D_80106494_3EFA94_BattleMinigame
    /* 80106494 */ .space 0x02

nonmatching D_80106496_3EFA96_BattleMinigame, 0x2

dlabel D_80106496_3EFA96_BattleMinigame
    /* 80106496 */ .space 0x02

nonmatching D_80106498_3EFA98_BattleMinigame, 0x4

dlabel D_80106498_3EFA98_BattleMinigame
    /* 80106498 */ .space 0x04

nonmatching D_8010649C_3EFA9C_BattleMinigame, 0x2

dlabel D_8010649C_3EFA9C_BattleMinigame
    /* 8010649C */ .space 0x02

nonmatching D_8010649E_3EFA9E_BattleMinigame, 0x2

dlabel D_8010649E_3EFA9E_BattleMinigame
    /* 8010649E */ .space 0x02

nonmatching D_801064A0_3EFAA0_BattleMinigame, 0x2

dlabel D_801064A0_3EFAA0_BattleMinigame
    /* 801064A0 */ .space 0x02

nonmatching D_801064A2_3EFAA2_BattleMinigame, 0x2

dlabel D_801064A2_3EFAA2_BattleMinigame
    /* 801064A2 */ .space 0x02

nonmatching D_801064A4_3EFAA4_BattleMinigame, 0x2

dlabel D_801064A4_3EFAA4_BattleMinigame
    /* 801064A4 */ .space 0x02

nonmatching D_801064A6_3EFAA6_BattleMinigame, 0x6

dlabel D_801064A6_3EFAA6_BattleMinigame
    /* 801064A6 */ .space 0x06

nonmatching D_801064AC_3EFAAC_BattleMinigame, 0x2

dlabel D_801064AC_3EFAAC_BattleMinigame
    /* 801064AC */ .space 0x02

nonmatching D_801064AE_3EFAAE_BattleMinigame, 0x2

dlabel D_801064AE_3EFAAE_BattleMinigame
    /* 801064AE */ .space 0x02

nonmatching D_801064B0_3EFAB0_BattleMinigame, 0x2

dlabel D_801064B0_3EFAB0_BattleMinigame
    /* 801064B0 */ .space 0x02

nonmatching D_801064B2_3EFAB2_BattleMinigame, 0x6

dlabel D_801064B2_3EFAB2_BattleMinigame
    /* 801064B2 */ .space 0x06

nonmatching D_801064B8_3EFAB8_BattleMinigame, 0x8

dlabel D_801064B8_3EFAB8_BattleMinigame
    /* 801064B8 */ .space 0x08

nonmatching D_801064C0_3EFAC0_BattleMinigame, 0x2

dlabel D_801064C0_3EFAC0_BattleMinigame
    /* 801064C0 */ .space 0x02

nonmatching D_801064C2_3EFAC2_BattleMinigame, 0x2

dlabel D_801064C2_3EFAC2_BattleMinigame
    /* 801064C2 */ .space 0x02

nonmatching D_801064C4_3EFAC4_BattleMinigame, 0xC

dlabel D_801064C4_3EFAC4_BattleMinigame
    /* 801064C4 */ .space 0x0C

nonmatching D_801064D0_3EFAD0_BattleMinigame, 0x20

dlabel D_801064D0_3EFAD0_BattleMinigame
    /* 801064D0 */ .space 0x20

nonmatching D_801064F0_3EFAF0_BattleMinigame, 0x2

dlabel D_801064F0_3EFAF0_BattleMinigame
    /* 801064F0 */ .space 0x02

nonmatching D_801064F2_3EFAF2_BattleMinigame, 0x6

dlabel D_801064F2_3EFAF2_BattleMinigame
    /* 801064F2 */ .space 0x06

nonmatching D_801064F8_3EFAF8_BattleMinigame, 0x4

dlabel D_801064F8_3EFAF8_BattleMinigame
    /* 801064F8 */ .space 0x04

nonmatching D_801064FC_3EFAFC_BattleMinigame, 0xC

dlabel D_801064FC_3EFAFC_BattleMinigame
    /* 801064FC */ .space 0x0C

nonmatching D_80106508_3EFB08_BattleMinigame, 0xC

dlabel D_80106508_3EFB08_BattleMinigame
    /* 80106508 */ .space 0x0C

nonmatching D_80106514_3EFB14_BattleMinigame, 0xC

dlabel D_80106514_3EFB14_BattleMinigame
    /* 80106514 */ .space 0x0C

nonmatching D_80106520_3EFB20_BattleMinigame, 0xC

dlabel D_80106520_3EFB20_BattleMinigame
    /* 80106520 */ .space 0x0C

nonmatching D_8010652C_3EFB2C_BattleMinigame, 0xC

dlabel D_8010652C_3EFB2C_BattleMinigame
    /* 8010652C */ .space 0x0C

nonmatching D_80106538_3EFB38_BattleMinigame, 0x4

dlabel D_80106538_3EFB38_BattleMinigame
    /* 80106538 */ .space 0x04

nonmatching D_8010653C_3EFB3C_BattleMinigame, 0x4

dlabel D_8010653C_3EFB3C_BattleMinigame
    /* 8010653C */ .space 0x04

nonmatching D_80106540_3EFB40_BattleMinigame, 0x4

dlabel D_80106540_3EFB40_BattleMinigame
    /* 80106540 */ .space 0x04

nonmatching D_80106544_3EFB44_BattleMinigame, 0x4

dlabel D_80106544_3EFB44_BattleMinigame
    /* 80106544 */ .space 0x04

nonmatching D_80106548_3EFB48_BattleMinigame, 0x38E8

dlabel D_80106548_3EFB48_BattleMinigame
    /* 80106548 */ .space 0x38E8
