.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching func_80102800_360670_SlotMachine1P, 0xB4

glabel func_80102800_360670_SlotMachine1P
    /* 360670 80102800 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 360674 80102804 AFBF0018 */  sw         $ra, 0x18($sp)
    /* 360678 80102808 3C028010 */  lui        $v0, %hi(D_800F93C6_F9FC6)
    /* 36067C 8010280C 844293C6 */  lh         $v0, %lo(D_800F93C6_F9FC6)($v0)
    /* 360680 80102810 3C018010 */  lui        $at, %hi(D_8010388C_3617AC_SlotMachine1P)
    /* 360684 80102814 AC22388C */  sw         $v0, %lo(D_8010388C_3617AC_SlotMachine1P)($at)
    /* 360688 80102818 24040050 */  addiu      $a0, $zero, 0x50
    /* 36068C 8010281C 0C01D830 */  jal        InitObjSys
    /* 360690 80102820 24050050 */   addiu     $a1, $zero, 0x50
    /* 360694 80102824 0C040DBB */  jal        func_801036EC_36155C_SlotMachine1P
    /* 360698 80102828 00000000 */   nop
    /* 36069C 8010282C 0C040D32 */  jal        func_801034C8_361338_SlotMachine1P
    /* 3606A0 80102830 00000000 */   nop
    /* 3606A4 80102834 0C022190 */  jal        func_80088640_89240
    /* 3606A8 80102838 00000000 */   nop
    /* 3606AC 8010283C 3C048010 */  lui        $a0, %hi(func_80102ACC_36093C_SlotMachine1P)
    /* 3606B0 80102840 24842ACC */  addiu      $a0, $a0, %lo(func_80102ACC_36093C_SlotMachine1P)
    /* 3606B4 80102844 24050300 */  addiu      $a1, $zero, 0x300
    /* 3606B8 80102848 24064000 */  addiu      $a2, $zero, 0x4000
    /* 3606BC 8010284C 0C01DB99 */  jal        InitProcess
    /* 3606C0 80102850 00003821 */   addu      $a3, $zero, $zero
    /* 3606C4 80102854 3C028010 */  lui        $v0, %hi(func_80103474_3612E4_SlotMachine1P)
    /* 3606C8 80102858 24423474 */  addiu      $v0, $v0, %lo(func_80103474_3612E4_SlotMachine1P)
    /* 3606CC 8010285C AFA20010 */  sw         $v0, 0x10($sp)
    /* 3606D0 80102860 24041000 */  addiu      $a0, $zero, 0x1000
    /* 3606D4 80102864 00002821 */  addu       $a1, $zero, $zero
    /* 3606D8 80102868 00003021 */  addu       $a2, $zero, $zero
    /* 3606DC 8010286C 0C01D966 */  jal        func_80076598_77198
    /* 3606E0 80102870 2407FFFF */   addiu     $a3, $zero, -0x1
    /* 3606E4 80102874 0C01E50A */  jal        func_80079428_7A028
    /* 3606E8 80102878 2404005E */   addiu     $a0, $zero, 0x5E
    /* 3606EC 8010287C 3C01800F */  lui        $at, %hi(D_800F64B0_F70B0)
    /* 3606F0 80102880 A42264B0 */  sh         $v0, %lo(D_800F64B0_F70B0)($at)
    /* 3606F4 80102884 0C01E567 */  jal        func_8007959C_7A19C
    /* 3606F8 80102888 24040367 */   addiu     $a0, $zero, 0x367
    /* 3606FC 8010288C 240400FF */  addiu      $a0, $zero, 0xFF
    /* 360700 80102890 240500FF */  addiu      $a1, $zero, 0xFF
    /* 360704 80102894 0C023D89 */  jal        func_8008F624_90224
    /* 360708 80102898 240600FF */   addiu     $a2, $zero, 0xFF
    /* 36070C 8010289C 00002021 */  addu       $a0, $zero, $zero
    /* 360710 801028A0 0C023D51 */  jal        InitFadeIn
    /* 360714 801028A4 24050010 */   addiu     $a1, $zero, 0x10
    /* 360718 801028A8 8FBF0018 */  lw         $ra, 0x18($sp)
    /* 36071C 801028AC 03E00008 */  jr         $ra
    /* 360720 801028B0 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_80102800_360670_SlotMachine1P

nonmatching func_801028B4_360724_SlotMachine1P, 0x218

glabel func_801028B4_360724_SlotMachine1P
    /* 360724 801028B4 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 360728 801028B8 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 36072C 801028BC AFB00010 */  sw         $s0, 0x10($sp)
    /* 360730 801028C0 F7BA0030 */  sdc1       $f26, 0x30($sp)
    /* 360734 801028C4 F7B80028 */  sdc1       $f24, 0x28($sp)
    /* 360738 801028C8 F7B60020 */  sdc1       $f22, 0x20($sp)
    /* 36073C 801028CC F7B40018 */  sdc1       $f20, 0x18($sp)
    /* 360740 801028D0 3C038010 */  lui        $v1, %hi(D_801037D0_3616F0_SlotMachine1P)
    /* 360744 801028D4 846337D0 */  lh         $v1, %lo(D_801037D0_3616F0_SlotMachine1P)($v1)
    /* 360748 801028D8 24020001 */  addiu      $v0, $zero, 0x1
    /* 36074C 801028DC 14620022 */  bne        $v1, $v0, .L80102968_3607D8_SlotMachine1P
    /* 360750 801028E0 00808021 */   addu      $s0, $a0, $zero
    /* 360754 801028E4 C60C0030 */  lwc1       $f12, 0x30($s0)
    /* 360758 801028E8 0C02E0F0 */  jal        func_800B83C0_B8FC0
    /* 36075C 801028EC 00000000 */   nop
    /* 360760 801028F0 3C0140A0 */  lui        $at, (0x40A00000 >> 16)
    /* 360764 801028F4 4481B000 */  mtc1       $at, $f22
    /* 360768 801028F8 00000000 */  nop
    /* 36076C 801028FC 46160603 */  div.s      $f24, $f0, $f22
    /* 360770 80102900 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 360774 80102904 4481D000 */  mtc1       $at, $f26
    /* 360778 80102908 C60C0030 */  lwc1       $f12, 0x30($s0)
    /* 36077C 8010290C 0C02E0F0 */  jal        func_800B83C0_B8FC0
    /* 360780 80102910 4618D601 */   sub.s     $f24, $f26, $f24
    /* 360784 80102914 46160503 */  div.s      $f20, $f0, $f22
    /* 360788 80102918 C60C0030 */  lwc1       $f12, 0x30($s0)
    /* 36078C 8010291C 0C02E0F0 */  jal        func_800B83C0_B8FC0
    /* 360790 80102920 4614D501 */   sub.s     $f20, $f26, $f20
    /* 360794 80102924 46160003 */  div.s      $f0, $f0, $f22
    /* 360798 80102928 3C048010 */  lui        $a0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 36079C 8010292C 8C843880 */  lw         $a0, %lo(D_80103880_3617A0_SlotMachine1P)($a0)
    /* 3607A0 80102930 4405C000 */  mfc1       $a1, $f24
    /* 3607A4 80102934 4406A000 */  mfc1       $a2, $f20
    /* 3607A8 80102938 4600D001 */  sub.s      $f0, $f26, $f0
    /* 3607AC 8010293C 44070000 */  mfc1       $a3, $f0
    /* 3607B0 80102940 00000000 */  nop
    /* 3607B4 80102944 0C02CC58 */  jal        func_800B3160_B3D60
    /* 3607B8 80102948 24840024 */   addiu     $a0, $a0, 0x24
    /* 3607BC 8010294C C6000030 */  lwc1       $f0, 0x30($s0)
    /* 3607C0 80102950 3C014220 */  lui        $at, (0x42200000 >> 16)
    /* 3607C4 80102954 44811000 */  mtc1       $at, $f2
    /* 3607C8 80102958 00000000 */  nop
    /* 3607CC 8010295C 46020000 */  add.s      $f0, $f0, $f2
    /* 3607D0 80102960 08040A65 */  j          .L80102994_360804_SlotMachine1P
    /* 3607D4 80102964 E6000030 */   swc1      $f0, 0x30($s0)
  .L80102968_3607D8_SlotMachine1P:
    /* 3607D8 80102968 3C028010 */  lui        $v0, %hi(D_801037D0_3616F0_SlotMachine1P)
    /* 3607DC 8010296C 844237D0 */  lh         $v0, %lo(D_801037D0_3616F0_SlotMachine1P)($v0)
    /* 3607E0 80102970 14400008 */  bnez       $v0, .L80102994_360804_SlotMachine1P
    /* 3607E4 80102974 00000000 */   nop
    /* 3607E8 80102978 3C048010 */  lui        $a0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 3607EC 8010297C 8C843880 */  lw         $a0, %lo(D_80103880_3617A0_SlotMachine1P)($a0)
    /* 3607F0 80102980 24840024 */  addiu      $a0, $a0, 0x24
    /* 3607F4 80102984 3C053F80 */  lui        $a1, (0x3F800000 >> 16)
    /* 3607F8 80102988 00A03021 */  addu       $a2, $a1, $zero
    /* 3607FC 8010298C 0C02CC58 */  jal        func_800B3160_B3D60
    /* 360800 80102990 00A03821 */   addu      $a3, $a1, $zero
  .L80102994_360804_SlotMachine1P:
    /* 360804 80102994 3C028010 */  lui        $v0, %hi(D_801037D6_3616F6_SlotMachine1P)
    /* 360808 80102998 844237D6 */  lh         $v0, %lo(D_801037D6_3616F6_SlotMachine1P)($v0)
    /* 36080C 8010299C 10400019 */  beqz       $v0, .L80102A04_360874_SlotMachine1P
    /* 360810 801029A0 00000000 */   nop
    /* 360814 801029A4 0C02E0F0 */  jal        func_800B83C0_B8FC0
    /* 360818 801029A8 C60C0028 */   lwc1      $f12, 0x28($s0)
    /* 36081C 801029AC 3C028010 */  lui        $v0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360820 801029B0 8C423880 */  lw         $v0, %lo(D_80103880_3617A0_SlotMachine1P)($v0)
    /* 360824 801029B4 3C0141F0 */  lui        $at, (0x41F00000 >> 16)
    /* 360828 801029B8 44811000 */  mtc1       $at, $f2
    /* 36082C 801029BC 00000000 */  nop
    /* 360830 801029C0 46020002 */  mul.s      $f0, $f0, $f2
    /* 360834 801029C4 E4400030 */  swc1       $f0, 0x30($v0)
    /* 360838 801029C8 C6020028 */  lwc1       $f2, 0x28($s0)
    /* 36083C 801029CC 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* 360840 801029D0 44810000 */  mtc1       $at, $f0
    /* 360844 801029D4 00000000 */  nop
    /* 360848 801029D8 46001000 */  add.s      $f0, $f2, $f0
    /* 36084C 801029DC 3C0143B4 */  lui        $at, (0x43B40000 >> 16)
    /* 360850 801029E0 44811000 */  mtc1       $at, $f2
    /* 360854 801029E4 00000000 */  nop
    /* 360858 801029E8 4600103E */  c.le.s     $f2, $f0
    /* 36085C 801029EC 00000000 */  nop
    /* 360860 801029F0 00000000 */  nop
    /* 360864 801029F4 45000003 */  bc1f       .L80102A04_360874_SlotMachine1P
    /* 360868 801029F8 E6000028 */   swc1      $f0, 0x28($s0)
    /* 36086C 801029FC 46020001 */  sub.s      $f0, $f0, $f2
    /* 360870 80102A00 E6000028 */  swc1       $f0, 0x28($s0)
  .L80102A04_360874_SlotMachine1P:
    /* 360874 80102A04 3C028010 */  lui        $v0, %hi(D_801037D2_3616F2_SlotMachine1P)
    /* 360878 80102A08 844237D2 */  lh         $v0, %lo(D_801037D2_3616F2_SlotMachine1P)($v0)
    /* 36087C 80102A0C 10400019 */  beqz       $v0, .L80102A74_3608E4_SlotMachine1P
    /* 360880 80102A10 00000000 */   nop
    /* 360884 80102A14 3C028010 */  lui        $v0, %hi(D_80103884_3617A4_SlotMachine1P)
    /* 360888 80102A18 8C423884 */  lw         $v0, %lo(D_80103884_3617A4_SlotMachine1P)($v0)
    /* 36088C 80102A1C 8C430024 */  lw         $v1, 0x24($v0)
    /* 360890 80102A20 3C058010 */  lui        $a1, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360894 80102A24 8CA53880 */  lw         $a1, %lo(D_80103880_3617A0_SlotMachine1P)($a1)
    /* 360898 80102A28 3C018010 */  lui        $at, %hi(D_801037D8_3616F8_SlotMachine1P)
    /* 36089C 80102A2C C42037D8 */  lwc1       $f0, %lo(D_801037D8_3616F8_SlotMachine1P)($at)
    /* 3608A0 80102A30 C4A20024 */  lwc1       $f2, 0x24($a1)
    /* 3608A4 80102A34 46020002 */  mul.s      $f0, $f0, $f2
    /* 3608A8 80102A38 C4A20030 */  lwc1       $f2, 0x30($a1)
    /* 3608AC 80102A3C 46020000 */  add.s      $f0, $f0, $f2
    /* 3608B0 80102A40 E4600030 */  swc1       $f0, 0x30($v1)
    /* 3608B4 80102A44 8C440024 */  lw         $a0, 0x24($v0)
    /* 3608B8 80102A48 2484000C */  addiu      $a0, $a0, 0xC
    /* 3608BC 80102A4C 0C02CC5C */  jal        func_800B3170_B3D70
    /* 3608C0 80102A50 24A5000C */   addiu     $a1, $a1, 0xC
    /* 3608C4 80102A54 3C028010 */  lui        $v0, %hi(D_80103884_3617A4_SlotMachine1P)
    /* 3608C8 80102A58 8C423884 */  lw         $v0, %lo(D_80103884_3617A4_SlotMachine1P)($v0)
    /* 3608CC 80102A5C 8C440024 */  lw         $a0, 0x24($v0)
    /* 3608D0 80102A60 3C058010 */  lui        $a1, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 3608D4 80102A64 8CA53880 */  lw         $a1, %lo(D_80103880_3617A0_SlotMachine1P)($a1)
    /* 3608D8 80102A68 24840024 */  addiu      $a0, $a0, 0x24
    /* 3608DC 80102A6C 0C02CC5C */  jal        func_800B3170_B3D70
    /* 3608E0 80102A70 24A50024 */   addiu     $a1, $a1, 0x24
  .L80102A74_3608E4_SlotMachine1P:
    /* 3608E4 80102A74 3C028010 */  lui        $v0, %hi(D_801037D4_3616F4_SlotMachine1P)
    /* 3608E8 80102A78 844237D4 */  lh         $v0, %lo(D_801037D4_3616F4_SlotMachine1P)($v0)
    /* 3608EC 80102A7C 1040000B */  beqz       $v0, .L80102AAC_36091C_SlotMachine1P
    /* 3608F0 80102A80 00000000 */   nop
    /* 3608F4 80102A84 3C048010 */  lui        $a0, %hi(D_80103884_3617A4_SlotMachine1P)
    /* 3608F8 80102A88 8C843884 */  lw         $a0, %lo(D_80103884_3617A4_SlotMachine1P)($a0)
    /* 3608FC 80102A8C 8C820024 */  lw         $v0, 0x24($a0)
    /* 360900 80102A90 3C038010 */  lui        $v1, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360904 80102A94 8C633880 */  lw         $v1, %lo(D_80103880_3617A0_SlotMachine1P)($v1)
    /* 360908 80102A98 C4600018 */  lwc1       $f0, 0x18($v1)
    /* 36090C 80102A9C E4400018 */  swc1       $f0, 0x18($v0)
    /* 360910 80102AA0 8C820024 */  lw         $v0, 0x24($a0)
    /* 360914 80102AA4 C4600020 */  lwc1       $f0, 0x20($v1)
    /* 360918 80102AA8 E4400020 */  swc1       $f0, 0x20($v0)
  .L80102AAC_36091C_SlotMachine1P:
    /* 36091C 80102AAC 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 360920 80102AB0 8FB00010 */  lw         $s0, 0x10($sp)
    /* 360924 80102AB4 D7BA0030 */  ldc1       $f26, 0x30($sp)
    /* 360928 80102AB8 D7B80028 */  ldc1       $f24, 0x28($sp)
    /* 36092C 80102ABC D7B60020 */  ldc1       $f22, 0x20($sp)
    /* 360930 80102AC0 D7B40018 */  ldc1       $f20, 0x18($sp)
    /* 360934 80102AC4 03E00008 */  jr         $ra
    /* 360938 80102AC8 27BD0038 */   addiu     $sp, $sp, 0x38
endlabel func_801028B4_360724_SlotMachine1P

nonmatching func_80102ACC_36093C_SlotMachine1P, 0x964

glabel func_80102ACC_36093C_SlotMachine1P
    /* 36093C 80102ACC 27BDFEE8 */  addiu      $sp, $sp, -0x118
    /* 360940 80102AD0 AFBF00F4 */  sw         $ra, 0xF4($sp)
    /* 360944 80102AD4 AFB200F0 */  sw         $s2, 0xF0($sp)
    /* 360948 80102AD8 AFB100EC */  sw         $s1, 0xEC($sp)
    /* 36094C 80102ADC AFB000E8 */  sw         $s0, 0xE8($sp)
    /* 360950 80102AE0 F7BA0110 */  sdc1       $f26, 0x110($sp)
    /* 360954 80102AE4 F7B80108 */  sdc1       $f24, 0x108($sp)
    /* 360958 80102AE8 F7B60100 */  sdc1       $f22, 0x100($sp)
    /* 36095C 80102AEC F7B400F8 */  sdc1       $f20, 0xF8($sp)
    /* 360960 80102AF0 0C01F678 */  jal        SleepProcess
    /* 360964 80102AF4 24040010 */   addiu     $a0, $zero, 0x10
    /* 360968 80102AF8 0C01F678 */  jal        SleepProcess
    /* 36096C 80102AFC 2404001E */   addiu     $a0, $zero, 0x1E
    /* 360970 80102B00 24020002 */  addiu      $v0, $zero, 0x2
    /* 360974 80102B04 AFA20010 */  sw         $v0, 0x10($sp)
    /* 360978 80102B08 3C048010 */  lui        $a0, %hi(D_8010388C_3617AC_SlotMachine1P)
    /* 36097C 80102B0C 8C84388C */  lw         $a0, %lo(D_8010388C_3617AC_SlotMachine1P)($a0)
    /* 360980 80102B10 2405FFFF */  addiu      $a1, $zero, -0x1
    /* 360984 80102B14 00003021 */  addu       $a2, $zero, $zero
    /* 360988 80102B18 0C01777B */  jal        func_8005DDEC_5E9EC
    /* 36098C 80102B1C 2407000A */   addiu     $a3, $zero, 0xA
    /* 360990 80102B20 0C01F678 */  jal        SleepProcess
    /* 360994 80102B24 2404000F */   addiu     $a0, $zero, 0xF
    /* 360998 80102B28 3C018010 */  lui        $at, %hi(D_801037D0_3616F0_SlotMachine1P)
    /* 36099C 80102B2C A42037D0 */  sh         $zero, %lo(D_801037D0_3616F0_SlotMachine1P)($at)
    /* 3609A0 80102B30 0C0157A4 */  jal        func_80055E90_56A90
    /* 3609A4 80102B34 240401E9 */   addiu     $a0, $zero, 0x1E9
    /* 3609A8 80102B38 3C018010 */  lui        $at, %hi(D_801037D6_3616F6_SlotMachine1P)
    /* 3609AC 80102B3C A42037D6 */  sh         $zero, %lo(D_801037D6_3616F6_SlotMachine1P)($at)
    /* 3609B0 80102B40 3C0141A0 */  lui        $at, (0x41A00000 >> 16)
    /* 3609B4 80102B44 4481A000 */  mtc1       $at, $f20
    /* 3609B8 80102B48 3C028010 */  lui        $v0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 3609BC 80102B4C 8C423880 */  lw         $v0, %lo(D_80103880_3617A0_SlotMachine1P)($v0)
    /* 3609C0 80102B50 3C01447A */  lui        $at, (0x447A0000 >> 16)
    /* 3609C4 80102B54 44811000 */  mtc1       $at, $f2
    /* 3609C8 80102B58 C4400030 */  lwc1       $f0, 0x30($v0)
    /* 3609CC 80102B5C 4602003C */  c.lt.s     $f0, $f2
    /* 3609D0 80102B60 00000000 */  nop
    /* 3609D4 80102B64 00000000 */  nop
    /* 3609D8 80102B68 45000013 */  bc1f       .L80102BB8_360A28_SlotMachine1P
    /* 3609DC 80102B6C 00401821 */   addu      $v1, $v0, $zero
    /* 3609E0 80102B70 3C0140A0 */  lui        $at, (0x40A00000 >> 16)
    /* 3609E4 80102B74 4481C000 */  mtc1       $at, $f24
    /* 3609E8 80102B78 3C01447A */  lui        $at, (0x447A0000 >> 16)
    /* 3609EC 80102B7C 4481B000 */  mtc1       $at, $f22
    /* 3609F0 80102B80 00601021 */  addu       $v0, $v1, $zero
  .L80102B84_3609F4_SlotMachine1P:
    /* 3609F4 80102B84 C4400030 */  lwc1       $f0, 0x30($v0)
    /* 3609F8 80102B88 4600A000 */  add.s      $f0, $f20, $f0
    /* 3609FC 80102B8C E4400030 */  swc1       $f0, 0x30($v0)
    /* 360A00 80102B90 0C01F691 */  jal        SleepVProcess
    /* 360A04 80102B94 4618A500 */   add.s     $f20, $f20, $f24
    /* 360A08 80102B98 3C038010 */  lui        $v1, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360A0C 80102B9C 8C633880 */  lw         $v1, %lo(D_80103880_3617A0_SlotMachine1P)($v1)
    /* 360A10 80102BA0 C4600030 */  lwc1       $f0, 0x30($v1)
    /* 360A14 80102BA4 4616003C */  c.lt.s     $f0, $f22
    /* 360A18 80102BA8 00000000 */  nop
    /* 360A1C 80102BAC 00000000 */  nop
    /* 360A20 80102BB0 4501FFF4 */  bc1t       .L80102B84_3609F4_SlotMachine1P
    /* 360A24 80102BB4 00601021 */   addu      $v0, $v1, $zero
  .L80102BB8_360A28_SlotMachine1P:
    /* 360A28 80102BB8 3C048010 */  lui        $a0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360A2C 80102BBC 8C843880 */  lw         $a0, %lo(D_80103880_3617A0_SlotMachine1P)($a0)
    /* 360A30 80102BC0 3C05C4C8 */  lui        $a1, (0xC4C80000 >> 16)
    /* 360A34 80102BC4 3C06C2C8 */  lui        $a2, (0xC2C80000 >> 16)
    /* 360A38 80102BC8 3C0744C8 */  lui        $a3, (0x44C80000 >> 16)
    /* 360A3C 80102BCC 0C02CC58 */  jal        func_800B3160_B3D60
    /* 360A40 80102BD0 2484000C */   addiu     $a0, $a0, 0xC
    /* 360A44 80102BD4 24020001 */  addiu      $v0, $zero, 0x1
    /* 360A48 80102BD8 3C018010 */  lui        $at, %hi(D_801037D6_3616F6_SlotMachine1P)
    /* 360A4C 80102BDC A42237D6 */  sh         $v0, %lo(D_801037D6_3616F6_SlotMachine1P)($at)
    /* 360A50 80102BE0 3C028010 */  lui        $v0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360A54 80102BE4 8C423880 */  lw         $v0, %lo(D_80103880_3617A0_SlotMachine1P)($v0)
    /* 360A58 80102BE8 8C42003C */  lw         $v0, 0x3C($v0)
    /* 360A5C 80102BEC 8C420040 */  lw         $v0, 0x40($v0)
    /* 360A60 80102BF0 84420000 */  lh         $v0, 0x0($v0)
    /* 360A64 80102BF4 00022040 */  sll        $a0, $v0, 1
    /* 360A68 80102BF8 00822021 */  addu       $a0, $a0, $v0
    /* 360A6C 80102BFC 00042180 */  sll        $a0, $a0, 6
    /* 360A70 80102C00 3C028010 */  lui        $v0, %hi(D_800FC834_FD434)
    /* 360A74 80102C04 8C42C834 */  lw         $v0, %lo(D_800FC834_FD434)($v0)
    /* 360A78 80102C08 00822021 */  addu       $a0, $a0, $v0
    /* 360A7C 80102C0C 24840074 */  addiu      $a0, $a0, 0x74
    /* 360A80 80102C10 0C02CE1C */  jal        func_800B3870_B4470
    /* 360A84 80102C14 00002821 */   addu      $a1, $zero, $zero
    /* 360A88 80102C18 3C014234 */  lui        $at, (0x42340000 >> 16)
    /* 360A8C 80102C1C 44816000 */  mtc1       $at, $f12
    /* 360A90 80102C20 0C02E0F0 */  jal        func_800B83C0_B8FC0
    /* 360A94 80102C24 00000000 */   nop
    /* 360A98 80102C28 3C028010 */  lui        $v0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360A9C 80102C2C 8C423880 */  lw         $v0, %lo(D_80103880_3617A0_SlotMachine1P)($v0)
    /* 360AA0 80102C30 3C014234 */  lui        $at, (0x42340000 >> 16)
    /* 360AA4 80102C34 44816000 */  mtc1       $at, $f12
    /* 360AA8 80102C38 00000000 */  nop
    /* 360AAC 80102C3C 0C02DE24 */  jal        func_800B7890_B8490
    /* 360AB0 80102C40 E4400018 */   swc1      $f0, 0x18($v0)
    /* 360AB4 80102C44 3C028010 */  lui        $v0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360AB8 80102C48 8C423880 */  lw         $v0, %lo(D_80103880_3617A0_SlotMachine1P)($v0)
    /* 360ABC 80102C4C E4400020 */  swc1       $f0, 0x20($v0)
    /* 360AC0 80102C50 3C014248 */  lui        $at, (0x42480000 >> 16)
    /* 360AC4 80102C54 4481A000 */  mtc1       $at, $f20
    /* 360AC8 80102C58 44801000 */  mtc1       $zero, $f2
    /* 360ACC 80102C5C C440000C */  lwc1       $f0, 0xC($v0)
    /* 360AD0 80102C60 4602003C */  c.lt.s     $f0, $f2
    /* 360AD4 80102C64 00000000 */  nop
    /* 360AD8 80102C68 45000020 */  bc1f       .L80102CEC_360B5C_SlotMachine1P
    /* 360ADC 80102C6C 00000000 */   nop
    /* 360AE0 80102C70 3C013FCC */  lui        $at, (0x3FCCCCCD >> 16)
    /* 360AE4 80102C74 3421CCCD */  ori        $at, $at, (0x3FCCCCCD & 0xFFFF)
    /* 360AE8 80102C78 4481D000 */  mtc1       $at, $f26
    /* 360AEC 80102C7C 3C0140A0 */  lui        $at, (0x40A00000 >> 16)
    /* 360AF0 80102C80 4481B000 */  mtc1       $at, $f22
    /* 360AF4 80102C84 4480C000 */  mtc1       $zero, $f24
    /* 360AF8 80102C88 3C028010 */  lui        $v0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360AFC 80102C8C 8C423880 */  lw         $v0, %lo(D_80103880_3617A0_SlotMachine1P)($v0)
    /* 360B00 80102C90 4614A080 */  add.s      $f2, $f20, $f20
    /* 360B04 80102C94 C440000C */  lwc1       $f0, 0xC($v0)
  .L80102C98_360B08_SlotMachine1P:
    /* 360B08 80102C98 46001000 */  add.s      $f0, $f2, $f0
    /* 360B0C 80102C9C E440000C */  swc1       $f0, 0xC($v0)
    /* 360B10 80102CA0 C4400014 */  lwc1       $f0, 0x14($v0)
    /* 360B14 80102CA4 46001080 */  add.s      $f2, $f2, $f0
    /* 360B18 80102CA8 461AA501 */  sub.s      $f20, $f20, $f26
    /* 360B1C 80102CAC 4616A03E */  c.le.s     $f20, $f22
    /* 360B20 80102CB0 00000000 */  nop
    /* 360B24 80102CB4 00000000 */  nop
    /* 360B28 80102CB8 45000002 */  bc1f       .L80102CC4_360B34_SlotMachine1P
    /* 360B2C 80102CBC E4420014 */   swc1      $f2, 0x14($v0)
    /* 360B30 80102CC0 4600B506 */  mov.s      $f20, $f22
  .L80102CC4_360B34_SlotMachine1P:
    /* 360B34 80102CC4 0C01F691 */  jal        SleepVProcess
    /* 360B38 80102CC8 00000000 */   nop
    /* 360B3C 80102CCC 3C028010 */  lui        $v0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360B40 80102CD0 8C423880 */  lw         $v0, %lo(D_80103880_3617A0_SlotMachine1P)($v0)
    /* 360B44 80102CD4 C440000C */  lwc1       $f0, 0xC($v0)
    /* 360B48 80102CD8 4618003C */  c.lt.s     $f0, $f24
    /* 360B4C 80102CDC 00000000 */  nop
    /* 360B50 80102CE0 00000000 */  nop
    /* 360B54 80102CE4 4503FFEC */  bc1tl      .L80102C98_360B08_SlotMachine1P
    /* 360B58 80102CE8 4614A080 */   add.s     $f2, $f20, $f20
  .L80102CEC_360B5C_SlotMachine1P:
    /* 360B5C 80102CEC 3C048010 */  lui        $a0, %hi(D_8010388C_3617AC_SlotMachine1P)
    /* 360B60 80102CF0 8C84388C */  lw         $a0, %lo(D_8010388C_3617AC_SlotMachine1P)($a0)
    /* 360B64 80102CF4 24050002 */  addiu      $a1, $zero, 0x2
    /* 360B68 80102CF8 0C01775A */  jal        SetBoardPlayerAnimation
    /* 360B6C 80102CFC 00003021 */   addu      $a2, $zero, $zero
    /* 360B70 80102D00 3C058010 */  lui        $a1, %hi(D_801037E0_361700_SlotMachine1P)
    /* 360B74 80102D04 24A537E0 */  addiu      $a1, $a1, %lo(D_801037E0_361700_SlotMachine1P)
    /* 360B78 80102D08 8CA20000 */  lw         $v0, 0x0($a1)
    /* 360B7C 80102D0C 8CA30004 */  lw         $v1, 0x4($a1)
    /* 360B80 80102D10 8CA40008 */  lw         $a0, 0x8($a1)
    /* 360B84 80102D14 AFA20018 */  sw         $v0, 0x18($sp)
    /* 360B88 80102D18 AFA3001C */  sw         $v1, 0x1C($sp)
    /* 360B8C 80102D1C AFA40020 */  sw         $a0, 0x20($sp)
    /* 360B90 80102D20 3C058010 */  lui        $a1, %hi(D_801037EC_36170C_SlotMachine1P)
    /* 360B94 80102D24 24A537EC */  addiu      $a1, $a1, %lo(D_801037EC_36170C_SlotMachine1P)
    /* 360B98 80102D28 8CA20000 */  lw         $v0, 0x0($a1)
    /* 360B9C 80102D2C 8CA30004 */  lw         $v1, 0x4($a1)
    /* 360BA0 80102D30 8CA40008 */  lw         $a0, 0x8($a1)
    /* 360BA4 80102D34 AFA20028 */  sw         $v0, 0x28($sp)
    /* 360BA8 80102D38 AFA3002C */  sw         $v1, 0x2C($sp)
    /* 360BAC 80102D3C AFA40030 */  sw         $a0, 0x30($sp)
    /* 360BB0 80102D40 3C048010 */  lui        $a0, %hi(D_8010388C_3617AC_SlotMachine1P)
    /* 360BB4 80102D44 8C84388C */  lw         $a0, %lo(D_8010388C_3617AC_SlotMachine1P)($a0)
    /* 360BB8 80102D48 27A50018 */  addiu      $a1, $sp, 0x18
    /* 360BBC 80102D4C 24060014 */  addiu      $a2, $zero, 0x14
    /* 360BC0 80102D50 0C0162D6 */  jal        func_80058B58
    /* 360BC4 80102D54 27A70028 */   addiu     $a3, $sp, 0x28
    /* 360BC8 80102D58 3C038010 */  lui        $v1, %hi(D_80103884_3617A4_SlotMachine1P)
    /* 360BCC 80102D5C 8C633884 */  lw         $v1, %lo(D_80103884_3617A4_SlotMachine1P)($v1)
    /* 360BD0 80102D60 8C620024 */  lw         $v0, 0x24($v1)
    /* 360BD4 80102D64 3C0141F0 */  lui        $at, (0x41F00000 >> 16)
    /* 360BD8 80102D68 44810000 */  mtc1       $at, $f0
    /* 360BDC 80102D6C 00000000 */  nop
    /* 360BE0 80102D70 E4400034 */  swc1       $f0, 0x34($v0)
    /* 360BE4 80102D74 8C620024 */  lw         $v0, 0x24($v1)
    /* 360BE8 80102D78 3C01C020 */  lui        $at, (0xC0200000 >> 16)
    /* 360BEC 80102D7C 44810000 */  mtc1       $at, $f0
    /* 360BF0 80102D80 00000000 */  nop
    /* 360BF4 80102D84 E4400038 */  swc1       $f0, 0x38($v0)
    /* 360BF8 80102D88 0C01F678 */  jal        SleepProcess
    /* 360BFC 80102D8C 24040014 */   addiu     $a0, $zero, 0x14
    /* 360C00 80102D90 3C038010 */  lui        $v1, %hi(D_80103884_3617A4_SlotMachine1P)
    /* 360C04 80102D94 8C633884 */  lw         $v1, %lo(D_80103884_3617A4_SlotMachine1P)($v1)
    /* 360C08 80102D98 8C620024 */  lw         $v0, 0x24($v1)
    /* 360C0C 80102D9C 4480A000 */  mtc1       $zero, $f20
    /* 360C10 80102DA0 00000000 */  nop
    /* 360C14 80102DA4 E4540038 */  swc1       $f20, 0x38($v0)
    /* 360C18 80102DA8 E4540034 */  swc1       $f20, 0x34($v0)
    /* 360C1C 80102DAC 8C620024 */  lw         $v0, 0x24($v1)
    /* 360C20 80102DB0 3C038010 */  lui        $v1, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360C24 80102DB4 8C633880 */  lw         $v1, %lo(D_80103880_3617A0_SlotMachine1P)($v1)
    /* 360C28 80102DB8 C4400010 */  lwc1       $f0, 0x10($v0)
    /* 360C2C 80102DBC C4620010 */  lwc1       $f2, 0x10($v1)
    /* 360C30 80102DC0 46020001 */  sub.s      $f0, $f0, $f2
    /* 360C34 80102DC4 3C014120 */  lui        $at, (0x41200000 >> 16)
    /* 360C38 80102DC8 44811000 */  mtc1       $at, $f2
    /* 360C3C 80102DCC 00000000 */  nop
    /* 360C40 80102DD0 46020001 */  sub.s      $f0, $f0, $f2
    /* 360C44 80102DD4 3C018010 */  lui        $at, %hi(D_801037D8_3616F8_SlotMachine1P)
    /* 360C48 80102DD8 E42037D8 */  swc1       $f0, %lo(D_801037D8_3616F8_SlotMachine1P)($at)
    /* 360C4C 80102DDC 24020001 */  addiu      $v0, $zero, 0x1
    /* 360C50 80102DE0 3C018010 */  lui        $at, %hi(D_801037D2_3616F2_SlotMachine1P)
    /* 360C54 80102DE4 A42237D2 */  sh         $v0, %lo(D_801037D2_3616F2_SlotMachine1P)($at)
    /* 360C58 80102DE8 3C018010 */  lui        $at, %hi(D_801037D4_3616F4_SlotMachine1P)
    /* 360C5C 80102DEC A42237D4 */  sh         $v0, %lo(D_801037D4_3616F4_SlotMachine1P)($at)
    /* 360C60 80102DF0 3C048010 */  lui        $a0, %hi(D_8010388C_3617AC_SlotMachine1P)
    /* 360C64 80102DF4 8C84388C */  lw         $a0, %lo(D_8010388C_3617AC_SlotMachine1P)($a0)
    /* 360C68 80102DF8 2405FFFF */  addiu      $a1, $zero, -0x1
    /* 360C6C 80102DFC 0C01775A */  jal        SetBoardPlayerAnimation
    /* 360C70 80102E00 24060002 */   addiu     $a2, $zero, 0x2
    /* 360C74 80102E04 3C058010 */  lui        $a1, %hi(D_801037F8_361718_SlotMachine1P)
    /* 360C78 80102E08 24A537F8 */  addiu      $a1, $a1, %lo(D_801037F8_361718_SlotMachine1P)
    /* 360C7C 80102E0C 8CA20000 */  lw         $v0, 0x0($a1)
    /* 360C80 80102E10 8CA30004 */  lw         $v1, 0x4($a1)
    /* 360C84 80102E14 8CA40008 */  lw         $a0, 0x8($a1)
    /* 360C88 80102E18 AFA20038 */  sw         $v0, 0x38($sp)
    /* 360C8C 80102E1C AFA3003C */  sw         $v1, 0x3C($sp)
    /* 360C90 80102E20 AFA40040 */  sw         $a0, 0x40($sp)
    /* 360C94 80102E24 3C048010 */  lui        $a0, %hi(D_8010388C_3617AC_SlotMachine1P)
    /* 360C98 80102E28 8C84388C */  lw         $a0, %lo(D_8010388C_3617AC_SlotMachine1P)($a0)
    /* 360C9C 80102E2C 27A50038 */  addiu      $a1, $sp, 0x38
    /* 360CA0 80102E30 24060005 */  addiu      $a2, $zero, 0x5
    /* 360CA4 80102E34 0C0163C6 */  jal        func_80058F18
    /* 360CA8 80102E38 00003821 */   addu      $a3, $zero, $zero
    /* 360CAC 80102E3C 0C01F678 */  jal        SleepProcess
    /* 360CB0 80102E40 24040005 */   addiu     $a0, $zero, 0x5
    /* 360CB4 80102E44 2404FFFF */  addiu      $a0, $zero, -0x1
    /* 360CB8 80102E48 240501EA */  addiu      $a1, $zero, 0x1EA
    /* 360CBC 80102E4C 0C0157D8 */  jal        func_80055F60_56B60
    /* 360CC0 80102E50 24060028 */   addiu     $a2, $zero, 0x28
    /* 360CC4 80102E54 27B00048 */  addiu      $s0, $sp, 0x48
    /* 360CC8 80102E58 3C058010 */  lui        $a1, %hi(D_80103804_361724_SlotMachine1P)
    /* 360CCC 80102E5C 24A53804 */  addiu      $a1, $a1, %lo(D_80103804_361724_SlotMachine1P)
    /* 360CD0 80102E60 8CA20000 */  lw         $v0, 0x0($a1)
    /* 360CD4 80102E64 8CA30004 */  lw         $v1, 0x4($a1)
    /* 360CD8 80102E68 8CA40008 */  lw         $a0, 0x8($a1)
    /* 360CDC 80102E6C AFA20048 */  sw         $v0, 0x48($sp)
    /* 360CE0 80102E70 AFA3004C */  sw         $v1, 0x4C($sp)
    /* 360CE4 80102E74 AFA40050 */  sw         $a0, 0x50($sp)
    /* 360CE8 80102E78 27B10058 */  addiu      $s1, $sp, 0x58
    /* 360CEC 80102E7C 3C058010 */  lui        $a1, %hi(D_80103810_361730_SlotMachine1P)
    /* 360CF0 80102E80 24A53810 */  addiu      $a1, $a1, %lo(D_80103810_361730_SlotMachine1P)
    /* 360CF4 80102E84 8CA20000 */  lw         $v0, 0x0($a1)
    /* 360CF8 80102E88 8CA30004 */  lw         $v1, 0x4($a1)
    /* 360CFC 80102E8C 8CA40008 */  lw         $a0, 0x8($a1)
    /* 360D00 80102E90 AFA20058 */  sw         $v0, 0x58($sp)
    /* 360D04 80102E94 AFA3005C */  sw         $v1, 0x5C($sp)
    /* 360D08 80102E98 AFA40060 */  sw         $a0, 0x60($sp)
    /* 360D0C 80102E9C 00002021 */  addu       $a0, $zero, $zero
    /* 360D10 80102EA0 02002821 */  addu       $a1, $s0, $zero
    /* 360D14 80102EA4 3C078010 */  lui        $a3, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360D18 80102EA8 8CE73880 */  lw         $a3, %lo(D_80103880_3617A0_SlotMachine1P)($a3)
    /* 360D1C 80102EAC 0C0163C6 */  jal        func_80058F18
    /* 360D20 80102EB0 2406001E */   addiu     $a2, $zero, 0x1E
    /* 360D24 80102EB4 3C048010 */  lui        $a0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360D28 80102EB8 8C843880 */  lw         $a0, %lo(D_80103880_3617A0_SlotMachine1P)($a0)
    /* 360D2C 80102EBC 02002821 */  addu       $a1, $s0, $zero
    /* 360D30 80102EC0 2406001E */  addiu      $a2, $zero, 0x1E
    /* 360D34 80102EC4 0C0162D6 */  jal        func_80058B58
    /* 360D38 80102EC8 02203821 */   addu      $a3, $s1, $zero
    /* 360D3C 80102ECC 00008021 */  addu       $s0, $zero, $zero
    /* 360D40 80102ED0 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* 360D44 80102ED4 4481B000 */  mtc1       $at, $f22
  .L80102ED8_360D48_SlotMachine1P:
    /* 360D48 80102ED8 3C028010 */  lui        $v0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360D4C 80102EDC 8C423880 */  lw         $v0, %lo(D_80103880_3617A0_SlotMachine1P)($v0)
    /* 360D50 80102EE0 8C42003C */  lw         $v0, 0x3C($v0)
    /* 360D54 80102EE4 8C420040 */  lw         $v0, 0x40($v0)
    /* 360D58 80102EE8 84420000 */  lh         $v0, 0x0($v0)
    /* 360D5C 80102EEC 00022040 */  sll        $a0, $v0, 1
    /* 360D60 80102EF0 00822021 */  addu       $a0, $a0, $v0
    /* 360D64 80102EF4 00042180 */  sll        $a0, $a0, 6
    /* 360D68 80102EF8 3C028010 */  lui        $v0, %hi(D_800FC834_FD434)
    /* 360D6C 80102EFC 8C42C834 */  lw         $v0, %lo(D_800FC834_FD434)($v0)
    /* 360D70 80102F00 00822021 */  addu       $a0, $a0, $v0
    /* 360D74 80102F04 4405A000 */  mfc1       $a1, $f20
    /* 360D78 80102F08 00000000 */  nop
    /* 360D7C 80102F0C 0C02CE1C */  jal        func_800B3870_B4470
    /* 360D80 80102F10 24840074 */   addiu     $a0, $a0, 0x74
    /* 360D84 80102F14 3C028010 */  lui        $v0, %hi(D_80103884_3617A4_SlotMachine1P)
    /* 360D88 80102F18 8C423884 */  lw         $v0, %lo(D_80103884_3617A4_SlotMachine1P)($v0)
    /* 360D8C 80102F1C 8C420024 */  lw         $v0, 0x24($v0)
    /* 360D90 80102F20 8C42003C */  lw         $v0, 0x3C($v0)
    /* 360D94 80102F24 8C420040 */  lw         $v0, 0x40($v0)
    /* 360D98 80102F28 84420000 */  lh         $v0, 0x0($v0)
    /* 360D9C 80102F2C 00022040 */  sll        $a0, $v0, 1
    /* 360DA0 80102F30 00822021 */  addu       $a0, $a0, $v0
    /* 360DA4 80102F34 00042180 */  sll        $a0, $a0, 6
    /* 360DA8 80102F38 3C028010 */  lui        $v0, %hi(D_800FC834_FD434)
    /* 360DAC 80102F3C 8C42C834 */  lw         $v0, %lo(D_800FC834_FD434)($v0)
    /* 360DB0 80102F40 00822021 */  addu       $a0, $a0, $v0
    /* 360DB4 80102F44 4405A000 */  mfc1       $a1, $f20
    /* 360DB8 80102F48 00000000 */  nop
    /* 360DBC 80102F4C 0C02CE1C */  jal        func_800B3870_B4470
    /* 360DC0 80102F50 24840074 */   addiu     $a0, $a0, 0x74
    /* 360DC4 80102F54 0C01F691 */  jal        SleepVProcess
    /* 360DC8 80102F58 4616A501 */   sub.s     $f20, $f20, $f22
    /* 360DCC 80102F5C 26100001 */  addiu      $s0, $s0, 0x1
    /* 360DD0 80102F60 2A02001E */  slti       $v0, $s0, 0x1E
    /* 360DD4 80102F64 1440FFDC */  bnez       $v0, .L80102ED8_360D48_SlotMachine1P
    /* 360DD8 80102F68 00000000 */   nop
    /* 360DDC 80102F6C 0C01F678 */  jal        SleepProcess
    /* 360DE0 80102F70 24040005 */   addiu     $a0, $zero, 0x5
    /* 360DE4 80102F74 2402FFFF */  addiu      $v0, $zero, -0x1
    /* 360DE8 80102F78 3C018010 */  lui        $at, %hi(D_801037D0_3616F0_SlotMachine1P)
    /* 360DEC 80102F7C A42237D0 */  sh         $v0, %lo(D_801037D0_3616F0_SlotMachine1P)($at)
    /* 360DF0 80102F80 24100100 */  addiu      $s0, $zero, 0x100
  .L80102F84_360DF4_SlotMachine1P:
    /* 360DF4 80102F84 3C048010 */  lui        $a0, %hi(D_80103888_3617A8_SlotMachine1P)
    /* 360DF8 80102F88 84843888 */  lh         $a0, %lo(D_80103888_3617A8_SlotMachine1P)($a0)
    /* 360DFC 80102F8C 00002821 */  addu       $a1, $zero, $zero
    /* 360E00 80102F90 0C020922 */  jal        func_80082488_83088
    /* 360E04 80102F94 3206FFFF */   andi      $a2, $s0, 0xFFFF
    /* 360E08 80102F98 0C01F691 */  jal        SleepVProcess
    /* 360E0C 80102F9C 2610FFF8 */   addiu     $s0, $s0, -0x8
    /* 360E10 80102FA0 0601FFF8 */  bgez       $s0, .L80102F84_360DF4_SlotMachine1P
    /* 360E14 80102FA4 00002821 */   addu      $a1, $zero, $zero
    /* 360E18 80102FA8 3C048010 */  lui        $a0, %hi(D_80103888_3617A8_SlotMachine1P)
    /* 360E1C 80102FAC 84843888 */  lh         $a0, %lo(D_80103888_3617A8_SlotMachine1P)($a0)
    /* 360E20 80102FB0 0C020922 */  jal        func_80082488_83088
    /* 360E24 80102FB4 00003021 */   addu      $a2, $zero, $zero
    /* 360E28 80102FB8 0C01E567 */  jal        func_8007959C_7A19C
    /* 360E2C 80102FBC 24040361 */   addiu     $a0, $zero, 0x361
    /* 360E30 80102FC0 27B00068 */  addiu      $s0, $sp, 0x68
    /* 360E34 80102FC4 3C058010 */  lui        $a1, %hi(D_8010381C_36173C_SlotMachine1P)
    /* 360E38 80102FC8 24A5381C */  addiu      $a1, $a1, %lo(D_8010381C_36173C_SlotMachine1P)
    /* 360E3C 80102FCC 8CA20000 */  lw         $v0, 0x0($a1)
    /* 360E40 80102FD0 8CA30004 */  lw         $v1, 0x4($a1)
    /* 360E44 80102FD4 8CA40008 */  lw         $a0, 0x8($a1)
    /* 360E48 80102FD8 AFA20068 */  sw         $v0, 0x68($sp)
    /* 360E4C 80102FDC AFA3006C */  sw         $v1, 0x6C($sp)
    /* 360E50 80102FE0 AFA40070 */  sw         $a0, 0x70($sp)
    /* 360E54 80102FE4 3C058010 */  lui        $a1, %hi(D_80103828_361748_SlotMachine1P)
    /* 360E58 80102FE8 24A53828 */  addiu      $a1, $a1, %lo(D_80103828_361748_SlotMachine1P)
    /* 360E5C 80102FEC 8CA20000 */  lw         $v0, 0x0($a1)
    /* 360E60 80102FF0 8CA30004 */  lw         $v1, 0x4($a1)
    /* 360E64 80102FF4 8CA40008 */  lw         $a0, 0x8($a1)
    /* 360E68 80102FF8 AFA20078 */  sw         $v0, 0x78($sp)
    /* 360E6C 80102FFC AFA3007C */  sw         $v1, 0x7C($sp)
    /* 360E70 80103000 AFA40080 */  sw         $a0, 0x80($sp)
    /* 360E74 80103004 27B10088 */  addiu      $s1, $sp, 0x88
    /* 360E78 80103008 3C058010 */  lui        $a1, %hi(D_80103834_361754_SlotMachine1P)
    /* 360E7C 8010300C 24A53834 */  addiu      $a1, $a1, %lo(D_80103834_361754_SlotMachine1P)
    /* 360E80 80103010 8CA20000 */  lw         $v0, 0x0($a1)
    /* 360E84 80103014 8CA30004 */  lw         $v1, 0x4($a1)
    /* 360E88 80103018 8CA40008 */  lw         $a0, 0x8($a1)
    /* 360E8C 8010301C AFA20088 */  sw         $v0, 0x88($sp)
    /* 360E90 80103020 AFA3008C */  sw         $v1, 0x8C($sp)
    /* 360E94 80103024 AFA40090 */  sw         $a0, 0x90($sp)
    /* 360E98 80103028 27B20098 */  addiu      $s2, $sp, 0x98
    /* 360E9C 8010302C 3C058010 */  lui        $a1, %hi(D_80103840_361760_SlotMachine1P)
    /* 360EA0 80103030 24A53840 */  addiu      $a1, $a1, %lo(D_80103840_361760_SlotMachine1P)
    /* 360EA4 80103034 8CA20000 */  lw         $v0, 0x0($a1)
    /* 360EA8 80103038 8CA30004 */  lw         $v1, 0x4($a1)
    /* 360EAC 8010303C 8CA40008 */  lw         $a0, 0x8($a1)
    /* 360EB0 80103040 AFA20098 */  sw         $v0, 0x98($sp)
    /* 360EB4 80103044 AFA3009C */  sw         $v1, 0x9C($sp)
    /* 360EB8 80103048 AFA400A0 */  sw         $a0, 0xA0($sp)
    /* 360EBC 8010304C 3C048010 */  lui        $a0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360EC0 80103050 8C843880 */  lw         $a0, %lo(D_80103880_3617A0_SlotMachine1P)($a0)
    /* 360EC4 80103054 2484000C */  addiu      $a0, $a0, 0xC
    /* 360EC8 80103058 0C02CC5C */  jal        func_800B3170_B3D70
    /* 360ECC 8010305C 27A50078 */   addiu     $a1, $sp, 0x78
    /* 360ED0 80103060 3C048010 */  lui        $a0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360ED4 80103064 8C843880 */  lw         $a0, %lo(D_80103880_3617A0_SlotMachine1P)($a0)
    /* 360ED8 80103068 24840024 */  addiu      $a0, $a0, 0x24
    /* 360EDC 8010306C 3C053DCC */  lui        $a1, (0x3DCCCCCD >> 16)
    /* 360EE0 80103070 34A5CCCD */  ori        $a1, $a1, (0x3DCCCCCD & 0xFFFF)
    /* 360EE4 80103074 00A03021 */  addu       $a2, $a1, $zero
    /* 360EE8 80103078 0C02CC58 */  jal        func_800B3160_B3D60
    /* 360EEC 8010307C 00A03821 */   addu      $a3, $a1, $zero
    /* 360EF0 80103080 3C028010 */  lui        $v0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360EF4 80103084 8C423880 */  lw         $v0, %lo(D_80103880_3617A0_SlotMachine1P)($v0)
    /* 360EF8 80103088 8C42003C */  lw         $v0, 0x3C($v0)
    /* 360EFC 8010308C 8C420040 */  lw         $v0, 0x40($v0)
    /* 360F00 80103090 84420000 */  lh         $v0, 0x0($v0)
    /* 360F04 80103094 00022040 */  sll        $a0, $v0, 1
    /* 360F08 80103098 00822021 */  addu       $a0, $a0, $v0
    /* 360F0C 8010309C 00042180 */  sll        $a0, $a0, 6
    /* 360F10 801030A0 3C028010 */  lui        $v0, %hi(D_800FC834_FD434)
    /* 360F14 801030A4 8C42C834 */  lw         $v0, %lo(D_800FC834_FD434)($v0)
    /* 360F18 801030A8 00822021 */  addu       $a0, $a0, $v0
    /* 360F1C 801030AC 24840074 */  addiu      $a0, $a0, 0x74
    /* 360F20 801030B0 0C02CE1C */  jal        func_800B3870_B4470
    /* 360F24 801030B4 00002821 */   addu      $a1, $zero, $zero
    /* 360F28 801030B8 3C028010 */  lui        $v0, %hi(D_80103884_3617A4_SlotMachine1P)
    /* 360F2C 801030BC 8C423884 */  lw         $v0, %lo(D_80103884_3617A4_SlotMachine1P)($v0)
    /* 360F30 801030C0 8C420024 */  lw         $v0, 0x24($v0)
    /* 360F34 801030C4 8C42003C */  lw         $v0, 0x3C($v0)
    /* 360F38 801030C8 8C420040 */  lw         $v0, 0x40($v0)
    /* 360F3C 801030CC 84420000 */  lh         $v0, 0x0($v0)
    /* 360F40 801030D0 00022040 */  sll        $a0, $v0, 1
    /* 360F44 801030D4 00822021 */  addu       $a0, $a0, $v0
    /* 360F48 801030D8 00042180 */  sll        $a0, $a0, 6
    /* 360F4C 801030DC 3C028010 */  lui        $v0, %hi(D_800FC834_FD434)
    /* 360F50 801030E0 8C42C834 */  lw         $v0, %lo(D_800FC834_FD434)($v0)
    /* 360F54 801030E4 00822021 */  addu       $a0, $a0, $v0
    /* 360F58 801030E8 24840074 */  addiu      $a0, $a0, 0x74
    /* 360F5C 801030EC 0C02CE1C */  jal        func_800B3870_B4470
    /* 360F60 801030F0 00002821 */   addu      $a1, $zero, $zero
    /* 360F64 801030F4 3C01C2B4 */  lui        $at, (0xC2B40000 >> 16)
    /* 360F68 801030F8 44816000 */  mtc1       $at, $f12
    /* 360F6C 801030FC 0C02E0F0 */  jal        func_800B83C0_B8FC0
    /* 360F70 80103100 00000000 */   nop
    /* 360F74 80103104 3C028010 */  lui        $v0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360F78 80103108 8C423880 */  lw         $v0, %lo(D_80103880_3617A0_SlotMachine1P)($v0)
    /* 360F7C 8010310C 3C01C2B4 */  lui        $at, (0xC2B40000 >> 16)
    /* 360F80 80103110 44816000 */  mtc1       $at, $f12
    /* 360F84 80103114 00000000 */  nop
    /* 360F88 80103118 0C02DE24 */  jal        func_800B7890_B8490
    /* 360F8C 8010311C E4400018 */   swc1      $f0, 0x18($v0)
    /* 360F90 80103120 3C078010 */  lui        $a3, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360F94 80103124 8CE73880 */  lw         $a3, %lo(D_80103880_3617A0_SlotMachine1P)($a3)
    /* 360F98 80103128 E4E00020 */  swc1       $f0, 0x20($a3)
    /* 360F9C 8010312C 00002021 */  addu       $a0, $zero, $zero
    /* 360FA0 80103130 02002821 */  addu       $a1, $s0, $zero
    /* 360FA4 80103134 0C0163C6 */  jal        func_80058F18
    /* 360FA8 80103138 2406003C */   addiu     $a2, $zero, 0x3C
    /* 360FAC 8010313C 3C048010 */  lui        $a0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360FB0 80103140 8C843880 */  lw         $a0, %lo(D_80103880_3617A0_SlotMachine1P)($a0)
    /* 360FB4 80103144 02202821 */  addu       $a1, $s1, $zero
    /* 360FB8 80103148 2406003C */  addiu      $a2, $zero, 0x3C
    /* 360FBC 8010314C 0C0162D6 */  jal        func_80058B58
    /* 360FC0 80103150 02403821 */   addu      $a3, $s2, $zero
    /* 360FC4 80103154 3C013D4C */  lui        $at, (0x3D4CCCCD >> 16)
    /* 360FC8 80103158 3421CCCD */  ori        $at, $at, (0x3D4CCCCD & 0xFFFF)
    /* 360FCC 8010315C 4481A000 */  mtc1       $at, $f20
    /* 360FD0 80103160 00008021 */  addu       $s0, $zero, $zero
    /* 360FD4 80103164 3C018010 */  lui        $at, %hi(D_80103870_361790_SlotMachine1P)
    /* 360FD8 80103168 D4383870 */  ldc1       $f24, %lo(D_80103870_361790_SlotMachine1P)($at)
    /* 360FDC 8010316C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 360FE0 80103170 4481B000 */  mtc1       $at, $f22
  .L80103174_360FE4_SlotMachine1P:
    /* 360FE4 80103174 3C048010 */  lui        $a0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 360FE8 80103178 8C843880 */  lw         $a0, %lo(D_80103880_3617A0_SlotMachine1P)($a0)
    /* 360FEC 8010317C 4405A000 */  mfc1       $a1, $f20
    /* 360FF0 80103180 4406A000 */  mfc1       $a2, $f20
    /* 360FF4 80103184 4407A000 */  mfc1       $a3, $f20
    /* 360FF8 80103188 00000000 */  nop
    /* 360FFC 8010318C 0C02CC58 */  jal        func_800B3160_B3D60
    /* 361000 80103190 24840024 */   addiu     $a0, $a0, 0x24
    /* 361004 80103194 4600A021 */  cvt.d.s    $f0, $f20
    /* 361008 80103198 46380000 */  add.d      $f0, $f0, $f24
    /* 36100C 8010319C 46200520 */  cvt.s.d    $f20, $f0
    /* 361010 801031A0 4614B03C */  c.lt.s     $f22, $f20
    /* 361014 801031A4 00000000 */  nop
    /* 361018 801031A8 00000000 */  nop
    /* 36101C 801031AC 45030001 */  bc1tl      .L801031B4_361024_SlotMachine1P
    /* 361020 801031B0 4600B506 */   mov.s     $f20, $f22
  .L801031B4_361024_SlotMachine1P:
    /* 361024 801031B4 0C01F691 */  jal        SleepVProcess
    /* 361028 801031B8 26100001 */   addiu     $s0, $s0, 0x1
    /* 36102C 801031BC 2A02003C */  slti       $v0, $s0, 0x3C
    /* 361030 801031C0 1440FFEC */  bnez       $v0, .L80103174_360FE4_SlotMachine1P
    /* 361034 801031C4 00000000 */   nop
    /* 361038 801031C8 3C048010 */  lui        $a0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 36103C 801031CC 8C843880 */  lw         $a0, %lo(D_80103880_3617A0_SlotMachine1P)($a0)
    /* 361040 801031D0 24840024 */  addiu      $a0, $a0, 0x24
    /* 361044 801031D4 3C053F80 */  lui        $a1, (0x3F800000 >> 16)
    /* 361048 801031D8 00A03021 */  addu       $a2, $a1, $zero
    /* 36104C 801031DC 0C02CC58 */  jal        func_800B3160_B3D60
    /* 361050 801031E0 00A03821 */   addu      $a3, $a1, $zero
    /* 361054 801031E4 3C018010 */  lui        $at, %hi(D_801037D4_3616F4_SlotMachine1P)
    /* 361058 801031E8 A42037D4 */  sh         $zero, %lo(D_801037D4_3616F4_SlotMachine1P)($at)
    /* 36105C 801031EC 27B000A8 */  addiu      $s0, $sp, 0xA8
    /* 361060 801031F0 0C0159C3 */  jal        func_8005670C_5730C
    /* 361064 801031F4 02002021 */   addu      $a0, $s0, $zero
    /* 361068 801031F8 3C028010 */  lui        $v0, %hi(D_80103884_3617A4_SlotMachine1P)
    /* 36106C 801031FC 8C423884 */  lw         $v0, %lo(D_80103884_3617A4_SlotMachine1P)($v0)
    /* 361070 80103200 8C460024 */  lw         $a2, 0x24($v0)
    /* 361074 80103204 24C60018 */  addiu      $a2, $a2, 0x18
    /* 361078 80103208 00C02021 */  addu       $a0, $a2, $zero
    /* 36107C 8010320C 02002821 */  addu       $a1, $s0, $zero
    /* 361080 80103210 0C015ADE */  jal        func_80056B78_57778
    /* 361084 80103214 2407000A */   addiu     $a3, $zero, 0xA
    /* 361088 80103218 0C01F678 */  jal        SleepProcess
    /* 36108C 8010321C 2404000A */   addiu     $a0, $zero, 0xA
    /* 361090 80103220 3C048010 */  lui        $a0, %hi(D_8010388C_3617AC_SlotMachine1P)
    /* 361094 80103224 8C84388C */  lw         $a0, %lo(D_8010388C_3617AC_SlotMachine1P)($a0)
    /* 361098 80103228 24050005 */  addiu      $a1, $zero, 0x5
    /* 36109C 8010322C 0C01775A */  jal        SetBoardPlayerAnimation
    /* 3610A0 80103230 00003021 */   addu      $a2, $zero, $zero
    /* 3610A4 80103234 3C038010 */  lui        $v1, %hi(D_8010388C_3617AC_SlotMachine1P)
    /* 3610A8 80103238 8C63388C */  lw         $v1, %lo(D_8010388C_3617AC_SlotMachine1P)($v1)
    /* 3610AC 8010323C 00031040 */  sll        $v0, $v1, 1
    /* 3610B0 80103240 00431021 */  addu       $v0, $v0, $v1
    /* 3610B4 80103244 00021080 */  sll        $v0, $v0, 2
    /* 3610B8 80103248 00431021 */  addu       $v0, $v0, $v1
    /* 3610BC 8010324C 00021080 */  sll        $v0, $v0, 2
    /* 3610C0 80103250 3C058010 */  lui        $a1, %hi(D_800FD2C4_FDEC4)
    /* 3610C4 80103254 00A22821 */  addu       $a1, $a1, $v0
    /* 3610C8 80103258 90A5D2C4 */  lbu        $a1, %lo(D_800FD2C4_FDEC4)($a1)
    /* 3610CC 8010325C 0C01E5C6 */  jal        func_80079718_7A318
    /* 3610D0 80103260 24040103 */   addiu     $a0, $zero, 0x103
    /* 3610D4 80103264 0C01F678 */  jal        SleepProcess
    /* 3610D8 80103268 24040032 */   addiu     $a0, $zero, 0x32
    /* 3610DC 8010326C 3C048010 */  lui        $a0, %hi(D_8010388C_3617AC_SlotMachine1P)
    /* 3610E0 80103270 8C84388C */  lw         $a0, %lo(D_8010388C_3617AC_SlotMachine1P)($a0)
    /* 3610E4 80103274 2405FFFF */  addiu      $a1, $zero, -0x1
    /* 3610E8 80103278 0C01775A */  jal        SetBoardPlayerAnimation
    /* 3610EC 8010327C 24060002 */   addiu     $a2, $zero, 0x2
    /* 3610F0 80103280 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 3610F4 80103284 4481A000 */  mtc1       $at, $f20
    /* 3610F8 80103288 00000000 */  nop
    /* 3610FC 8010328C E7B400A8 */  swc1       $f20, 0xA8($sp)
    /* 361100 80103290 AFA000B0 */  sw         $zero, 0xB0($sp)
    /* 361104 80103294 3C028010 */  lui        $v0, %hi(D_80103884_3617A4_SlotMachine1P)
    /* 361108 80103298 8C423884 */  lw         $v0, %lo(D_80103884_3617A4_SlotMachine1P)($v0)
    /* 36110C 8010329C 8C460024 */  lw         $a2, 0x24($v0)
    /* 361110 801032A0 24C60018 */  addiu      $a2, $a2, 0x18
    /* 361114 801032A4 00C02021 */  addu       $a0, $a2, $zero
    /* 361118 801032A8 02002821 */  addu       $a1, $s0, $zero
    /* 36111C 801032AC 0C015ADE */  jal        func_80056B78_57778
    /* 361120 801032B0 2407000A */   addiu     $a3, $zero, 0xA
    /* 361124 801032B4 0C01F678 */  jal        SleepProcess
    /* 361128 801032B8 2404000A */   addiu     $a0, $zero, 0xA
    /* 36112C 801032BC 24020001 */  addiu      $v0, $zero, 0x1
    /* 361130 801032C0 3C018010 */  lui        $at, %hi(D_801037D4_3616F4_SlotMachine1P)
    /* 361134 801032C4 A42237D4 */  sh         $v0, %lo(D_801037D4_3616F4_SlotMachine1P)($at)
    /* 361138 801032C8 0C01E567 */  jal        func_8007959C_7A19C
    /* 36113C 801032CC 24040362 */   addiu     $a0, $zero, 0x362
    /* 361140 801032D0 3C058010 */  lui        $a1, %hi(D_8010384C_36176C_SlotMachine1P)
    /* 361144 801032D4 24A5384C */  addiu      $a1, $a1, %lo(D_8010384C_36176C_SlotMachine1P)
    /* 361148 801032D8 8CA20000 */  lw         $v0, 0x0($a1)
    /* 36114C 801032DC 8CA30004 */  lw         $v1, 0x4($a1)
    /* 361150 801032E0 8CA40008 */  lw         $a0, 0x8($a1)
    /* 361154 801032E4 AFA200B8 */  sw         $v0, 0xB8($sp)
    /* 361158 801032E8 AFA300BC */  sw         $v1, 0xBC($sp)
    /* 36115C 801032EC AFA400C0 */  sw         $a0, 0xC0($sp)
    /* 361160 801032F0 27B000C8 */  addiu      $s0, $sp, 0xC8
    /* 361164 801032F4 3C058010 */  lui        $a1, %hi(D_80103858_361778_SlotMachine1P)
    /* 361168 801032F8 24A53858 */  addiu      $a1, $a1, %lo(D_80103858_361778_SlotMachine1P)
    /* 36116C 801032FC 8CA20000 */  lw         $v0, 0x0($a1)
    /* 361170 80103300 8CA30004 */  lw         $v1, 0x4($a1)
    /* 361174 80103304 8CA40008 */  lw         $a0, 0x8($a1)
    /* 361178 80103308 AFA200C8 */  sw         $v0, 0xC8($sp)
    /* 36117C 8010330C AFA300CC */  sw         $v1, 0xCC($sp)
    /* 361180 80103310 AFA400D0 */  sw         $a0, 0xD0($sp)
    /* 361184 80103314 27B100D8 */  addiu      $s1, $sp, 0xD8
    /* 361188 80103318 3C058010 */  lui        $a1, %hi(D_80103864_361784_SlotMachine1P)
    /* 36118C 8010331C 24A53864 */  addiu      $a1, $a1, %lo(D_80103864_361784_SlotMachine1P)
    /* 361190 80103320 8CA20000 */  lw         $v0, 0x0($a1)
    /* 361194 80103324 8CA30004 */  lw         $v1, 0x4($a1)
    /* 361198 80103328 8CA40008 */  lw         $a0, 0x8($a1)
    /* 36119C 8010332C AFA200D8 */  sw         $v0, 0xD8($sp)
    /* 3611A0 80103330 AFA300DC */  sw         $v1, 0xDC($sp)
    /* 3611A4 80103334 AFA400E0 */  sw         $a0, 0xE0($sp)
    /* 3611A8 80103338 00002021 */  addu       $a0, $zero, $zero
    /* 3611AC 8010333C 27A500B8 */  addiu      $a1, $sp, 0xB8
    /* 3611B0 80103340 3C078010 */  lui        $a3, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 3611B4 80103344 8CE73880 */  lw         $a3, %lo(D_80103880_3617A0_SlotMachine1P)($a3)
    /* 3611B8 80103348 0C0163C6 */  jal        func_80058F18
    /* 3611BC 8010334C 2406003C */   addiu     $a2, $zero, 0x3C
    /* 3611C0 80103350 3C048010 */  lui        $a0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 3611C4 80103354 8C843880 */  lw         $a0, %lo(D_80103880_3617A0_SlotMachine1P)($a0)
    /* 3611C8 80103358 02002821 */  addu       $a1, $s0, $zero
    /* 3611CC 8010335C 2406003C */  addiu      $a2, $zero, 0x3C
    /* 3611D0 80103360 0C0162D6 */  jal        func_80058B58
    /* 3611D4 80103364 02203821 */   addu      $a3, $s1, $zero
    /* 3611D8 80103368 00008021 */  addu       $s0, $zero, $zero
    /* 3611DC 8010336C 3C018010 */  lui        $at, %hi(D_80103878_361798_SlotMachine1P)
    /* 3611E0 80103370 D4363878 */  ldc1       $f22, %lo(D_80103878_361798_SlotMachine1P)($at)
    /* 3611E4 80103374 3C013DCC */  lui        $at, (0x3DCCCCCD >> 16)
    /* 3611E8 80103378 3421CCCD */  ori        $at, $at, (0x3DCCCCCD & 0xFFFF)
    /* 3611EC 8010337C 4481C000 */  mtc1       $at, $f24
  .L80103380_3611F0_SlotMachine1P:
    /* 3611F0 80103380 3C048010 */  lui        $a0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 3611F4 80103384 8C843880 */  lw         $a0, %lo(D_80103880_3617A0_SlotMachine1P)($a0)
    /* 3611F8 80103388 4405A000 */  mfc1       $a1, $f20
    /* 3611FC 8010338C 4406A000 */  mfc1       $a2, $f20
    /* 361200 80103390 4407A000 */  mfc1       $a3, $f20
    /* 361204 80103394 00000000 */  nop
    /* 361208 80103398 0C02CC58 */  jal        func_800B3160_B3D60
    /* 36120C 8010339C 24840024 */   addiu     $a0, $a0, 0x24
    /* 361210 801033A0 4600A021 */  cvt.d.s    $f0, $f20
    /* 361214 801033A4 46360001 */  sub.d      $f0, $f0, $f22
    /* 361218 801033A8 46200520 */  cvt.s.d    $f20, $f0
    /* 36121C 801033AC 4618A03C */  c.lt.s     $f20, $f24
    /* 361220 801033B0 00000000 */  nop
    /* 361224 801033B4 45010006 */  bc1t       .L801033D0_361240_SlotMachine1P
    /* 361228 801033B8 00000000 */   nop
    /* 36122C 801033BC 0C01F691 */  jal        SleepVProcess
    /* 361230 801033C0 26100001 */   addiu     $s0, $s0, 0x1
    /* 361234 801033C4 2A02003C */  slti       $v0, $s0, 0x3C
    /* 361238 801033C8 1440FFED */  bnez       $v0, .L80103380_3611F0_SlotMachine1P
    /* 36123C 801033CC 00000000 */   nop
  .L801033D0_361240_SlotMachine1P:
    /* 361240 801033D0 3C048010 */  lui        $a0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 361244 801033D4 8C843880 */  lw         $a0, %lo(D_80103880_3617A0_SlotMachine1P)($a0)
    /* 361248 801033D8 24840024 */  addiu      $a0, $a0, 0x24
    /* 36124C 801033DC 00002821 */  addu       $a1, $zero, $zero
    /* 361250 801033E0 00A03021 */  addu       $a2, $a1, $zero
    /* 361254 801033E4 0C02CC58 */  jal        func_800B3160_B3D60
    /* 361258 801033E8 00A03821 */   addu      $a3, $a1, $zero
    /* 36125C 801033EC 24020001 */  addiu      $v0, $zero, 0x1
    /* 361260 801033F0 3C018010 */  lui        $at, %hi(D_801011FC_101DFC)
    /* 361264 801033F4 A42211FC */  sh         $v0, %lo(D_801011FC_101DFC)($at)
  .L801033F8_361268_SlotMachine1P:
    /* 361268 801033F8 0C01F691 */  jal        SleepVProcess
    /* 36126C 801033FC 00000000 */   nop
    /* 361270 80103400 08040CFE */  j          .L801033F8_361268_SlotMachine1P
    /* 361274 80103404 00000000 */   nop
    /* 361278 80103408 8FBF00F4 */  lw         $ra, 0xF4($sp)
    /* 36127C 8010340C 8FB200F0 */  lw         $s2, 0xF0($sp)
    /* 361280 80103410 8FB100EC */  lw         $s1, 0xEC($sp)
    /* 361284 80103414 8FB000E8 */  lw         $s0, 0xE8($sp)
    /* 361288 80103418 D7BA0110 */  ldc1       $f26, 0x110($sp)
    /* 36128C 8010341C D7B80108 */  ldc1       $f24, 0x108($sp)
    /* 361290 80103420 D7B60100 */  ldc1       $f22, 0x100($sp)
    /* 361294 80103424 D7B400F8 */  ldc1       $f20, 0xF8($sp)
    /* 361298 80103428 03E00008 */  jr         $ra
    /* 36129C 8010342C 27BD0118 */   addiu     $sp, $sp, 0x118
endlabel func_80102ACC_36093C_SlotMachine1P

nonmatching func_80103430_3612A0_SlotMachine1P, 0x44

glabel func_80103430_3612A0_SlotMachine1P
    /* 3612A0 80103430 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3612A4 80103434 AFBF0010 */  sw         $ra, 0x10($sp)
    /* 3612A8 80103438 0C023D86 */  jal        func_8008F618_90218
    /* 3612AC 8010343C 00000000 */   nop
    /* 3612B0 80103440 14400009 */  bnez       $v0, .L80103468_3612D8_SlotMachine1P
    /* 3612B4 80103444 00000000 */   nop
    /* 3612B8 80103448 0C040DEA */  jal        func_801037A8_361618_SlotMachine1P
    /* 3612BC 8010344C 00000000 */   nop
    /* 3612C0 80103450 0C040DAA */  jal        func_801036A8_361518_SlotMachine1P
    /* 3612C4 80103454 00000000 */   nop
    /* 3612C8 80103458 0C023397 */  jal        func_8008CE5C_8DA5C
    /* 3612CC 8010345C 00000000 */   nop
    /* 3612D0 80103460 0C01DC58 */  jal        func_80077160_77D60
    /* 3612D4 80103464 24040001 */   addiu     $a0, $zero, 0x1
  .L80103468_3612D8_SlotMachine1P:
    /* 3612D8 80103468 8FBF0010 */  lw         $ra, 0x10($sp)
    /* 3612DC 8010346C 03E00008 */  jr         $ra
    /* 3612E0 80103470 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_80103430_3612A0_SlotMachine1P

nonmatching func_80103474_3612E4_SlotMachine1P, 0x54

glabel func_80103474_3612E4_SlotMachine1P
    /* 3612E4 80103474 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3612E8 80103478 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 3612EC 8010347C AFB00010 */  sw         $s0, 0x10($sp)
    /* 3612F0 80103480 3C028010 */  lui        $v0, %hi(D_801011FC_101DFC)
    /* 3612F4 80103484 944211FC */  lhu        $v0, %lo(D_801011FC_101DFC)($v0)
    /* 3612F8 80103488 1040000B */  beqz       $v0, .L801034B8_361328_SlotMachine1P
    /* 3612FC 8010348C 00808021 */   addu      $s0, $a0, $zero
    /* 361300 80103490 240400FF */  addiu      $a0, $zero, 0xFF
    /* 361304 80103494 240500FF */  addiu      $a1, $zero, 0xFF
    /* 361308 80103498 0C023D89 */  jal        func_8008F624_90224
    /* 36130C 8010349C 240600FF */   addiu     $a2, $zero, 0xFF
    /* 361310 801034A0 00002021 */  addu       $a0, $zero, $zero
    /* 361314 801034A4 0C023D6B */  jal        InitFadeOut
    /* 361318 801034A8 24050014 */   addiu     $a1, $zero, 0x14
    /* 36131C 801034AC 3C028010 */  lui        $v0, %hi(func_80103430_3612A0_SlotMachine1P)
    /* 361320 801034B0 24423430 */  addiu      $v0, $v0, %lo(func_80103430_3612A0_SlotMachine1P)
    /* 361324 801034B4 AE020014 */  sw         $v0, 0x14($s0)
  .L801034B8_361328_SlotMachine1P:
    /* 361328 801034B8 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 36132C 801034BC 8FB00010 */  lw         $s0, 0x10($sp)
    /* 361330 801034C0 03E00008 */  jr         $ra
    /* 361334 801034C4 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_80103474_3612E4_SlotMachine1P

nonmatching func_801034C8_361338_SlotMachine1P, 0x1E0

glabel func_801034C8_361338_SlotMachine1P
    /* 361338 801034C8 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 36133C 801034CC AFBF001C */  sw         $ra, 0x1C($sp)
    /* 361340 801034D0 0C010CF6 */  jal        func_800433D8_43FD8
    /* 361344 801034D4 AFB00018 */   sw        $s0, 0x18($sp)
    /* 361348 801034D8 0C0178AE */  jal        func_8005E2B8_5EEB8
    /* 36134C 801034DC 00000000 */   nop
    /* 361350 801034E0 24040001 */  addiu      $a0, $zero, 0x1
    /* 361354 801034E4 0C01FE9B */  jal        func_8007FA6C_8066C
    /* 361358 801034E8 24050005 */   addiu     $a1, $zero, 0x5
    /* 36135C 801034EC 3C018010 */  lui        $at, %hi(D_80103888_3617A8_SlotMachine1P)
    /* 361360 801034F0 A4223888 */  sh         $v0, %lo(D_80103888_3617A8_SlotMachine1P)($at)
    /* 361364 801034F4 3C04000A */  lui        $a0, (0xA0189 >> 16)
    /* 361368 801034F8 0C005DA0 */  jal        ReadMainFS
    /* 36136C 801034FC 34840189 */   ori       $a0, $a0, (0xA0189 & 0xFFFF)
    /* 361370 80103500 00408021 */  addu       $s0, $v0, $zero
    /* 361374 80103504 0C020A00 */  jal        func_80082800_83400
    /* 361378 80103508 02002021 */   addu      $a0, $s0, $zero
    /* 36137C 8010350C 3C018010 */  lui        $at, %hi(D_8010388A_3617AA_SlotMachine1P)
    /* 361380 80103510 A422388A */  sh         $v0, %lo(D_8010388A_3617AA_SlotMachine1P)($at)
    /* 361384 80103514 0C005E00 */  jal        FreeMainFS
    /* 361388 80103518 02002021 */   addu      $a0, $s0, $zero
    /* 36138C 8010351C 3C048010 */  lui        $a0, %hi(D_80103888_3617A8_SlotMachine1P)
    /* 361390 80103520 84843888 */  lh         $a0, %lo(D_80103888_3617A8_SlotMachine1P)($a0)
    /* 361394 80103524 00002821 */  addu       $a1, $zero, $zero
    /* 361398 80103528 3C068010 */  lui        $a2, %hi(D_8010388A_3617AA_SlotMachine1P)
    /* 36139C 8010352C 84C6388A */  lh         $a2, %lo(D_8010388A_3617AA_SlotMachine1P)($a2)
    /* 3613A0 80103530 0C020863 */  jal        func_8008218C_82D8C
    /* 3613A4 80103534 00003821 */   addu      $a3, $zero, $zero
    /* 3613A8 80103538 3C048010 */  lui        $a0, %hi(D_80103888_3617A8_SlotMachine1P)
    /* 3613AC 8010353C 84843888 */  lh         $a0, %lo(D_80103888_3617A8_SlotMachine1P)($a0)
    /* 3613B0 80103540 00002821 */  addu       $a1, $zero, $zero
    /* 3613B4 80103544 0C0208E1 */  jal        func_80082384_82F84
    /* 3613B8 80103548 2406000A */   addiu     $a2, $zero, 0xA
    /* 3613BC 8010354C 3C048010 */  lui        $a0, %hi(D_80103888_3617A8_SlotMachine1P)
    /* 3613C0 80103550 84843888 */  lh         $a0, %lo(D_80103888_3617A8_SlotMachine1P)($a0)
    /* 3613C4 80103554 00002821 */  addu       $a1, $zero, $zero
    /* 3613C8 80103558 0C020897 */  jal        func_8008225C_82E5C
    /* 3613CC 8010355C 24060001 */   addiu     $a2, $zero, 0x1
    /* 3613D0 80103560 3C048010 */  lui        $a0, %hi(D_80103888_3617A8_SlotMachine1P)
    /* 3613D4 80103564 84843888 */  lh         $a0, %lo(D_80103888_3617A8_SlotMachine1P)($a0)
    /* 3613D8 80103568 00002821 */  addu       $a1, $zero, $zero
    /* 3613DC 8010356C 0C020906 */  jal        func_80082418_83018
    /* 3613E0 80103570 24065000 */   addiu     $a2, $zero, 0x5000
    /* 3613E4 80103574 3C048010 */  lui        $a0, %hi(D_80103888_3617A8_SlotMachine1P)
    /* 3613E8 80103578 84843888 */  lh         $a0, %lo(D_80103888_3617A8_SlotMachine1P)($a0)
    /* 3613EC 8010357C 00002821 */  addu       $a1, $zero, $zero
    /* 3613F0 80103580 240600A0 */  addiu      $a2, $zero, 0xA0
    /* 3613F4 80103584 0C0206B4 */  jal        func_80081AD0_826D0
    /* 3613F8 80103588 24070078 */   addiu     $a3, $zero, 0x78
    /* 3613FC 8010358C 3C048010 */  lui        $a0, %hi(D_80103888_3617A8_SlotMachine1P)
    /* 361400 80103590 84843888 */  lh         $a0, %lo(D_80103888_3617A8_SlotMachine1P)($a0)
    /* 361404 80103594 00002821 */  addu       $a1, $zero, $zero
    /* 361408 80103598 3C0641A0 */  lui        $a2, (0x41A00000 >> 16)
    /* 36140C 8010359C 0C0208D0 */  jal        func_80082340_82F40
    /* 361410 801035A0 00C03821 */   addu      $a3, $a2, $zero
    /* 361414 801035A4 3C048010 */  lui        $a0, %hi(D_8010388E_3617AE_SlotMachine1P)
    /* 361418 801035A8 0C017855 */  jal        func_8005E154_5ED54
    /* 36141C 801035AC 8484388E */   lh        $a0, %lo(D_8010388E_3617AE_SlotMachine1P)($a0)
    /* 361420 801035B0 3C048010 */  lui        $a0, %hi(D_8010388C_3617AC_SlotMachine1P)
    /* 361424 801035B4 8C84388C */  lw         $a0, %lo(D_8010388C_3617AC_SlotMachine1P)($a0)
    /* 361428 801035B8 24050004 */  addiu      $a1, $zero, 0x4
    /* 36142C 801035BC 0C01775A */  jal        SetBoardPlayerAnimation
    /* 361430 801035C0 24060002 */   addiu     $a2, $zero, 0x2
    /* 361434 801035C4 3C048010 */  lui        $a0, %hi(D_8010388C_3617AC_SlotMachine1P)
    /* 361438 801035C8 0C01770F */  jal        GetPlayerStruct
    /* 36143C 801035CC 8C84388C */   lw        $a0, %lo(D_8010388C_3617AC_SlotMachine1P)($a0)
    /* 361440 801035D0 3C018010 */  lui        $at, %hi(D_80103884_3617A4_SlotMachine1P)
    /* 361444 801035D4 AC223884 */  sw         $v0, %lo(D_80103884_3617A4_SlotMachine1P)($at)
    /* 361448 801035D8 8C440024 */  lw         $a0, 0x24($v0)
    /* 36144C 801035DC 3C054316 */  lui        $a1, (0x43160000 >> 16)
    /* 361450 801035E0 3C06C2C8 */  lui        $a2, (0xC2C80000 >> 16)
    /* 361454 801035E4 3C07453B */  lui        $a3, (0x453B8000 >> 16)
    /* 361458 801035E8 34E78000 */  ori        $a3, $a3, (0x453B8000 & 0xFFFF)
    /* 36145C 801035EC 0C02CC58 */  jal        func_800B3160_B3D60
    /* 361460 801035F0 2484000C */   addiu     $a0, $a0, 0xC
    /* 361464 801035F4 3C028010 */  lui        $v0, %hi(D_80103884_3617A4_SlotMachine1P)
    /* 361468 801035F8 8C423884 */  lw         $v0, %lo(D_80103884_3617A4_SlotMachine1P)($v0)
    /* 36146C 801035FC 8C430024 */  lw         $v1, 0x24($v0)
    /* 361470 80103600 9462000A */  lhu        $v0, 0xA($v1)
    /* 361474 80103604 34420001 */  ori        $v0, $v0, 0x1
    /* 361478 80103608 A462000A */  sh         $v0, 0xA($v1)
    /* 36147C 8010360C 24040072 */  addiu      $a0, $zero, 0x72
    /* 361480 80103610 0C010D44 */  jal        func_80043510_44110
    /* 361484 80103614 00002821 */   addu      $a1, $zero, $zero
    /* 361488 80103618 3C018010 */  lui        $at, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 36148C 8010361C AC223880 */  sw         $v0, %lo(D_80103880_3617A0_SlotMachine1P)($at)
    /* 361490 80103620 3C05C316 */  lui        $a1, (0xC3160000 >> 16)
    /* 361494 80103624 3C06C248 */  lui        $a2, (0xC2480000 >> 16)
    /* 361498 80103628 3C07453B */  lui        $a3, (0x453B8000 >> 16)
    /* 36149C 8010362C 34E78000 */  ori        $a3, $a3, (0x453B8000 & 0xFFFF)
    /* 3614A0 80103630 0C02CC58 */  jal        func_800B3160_B3D60
    /* 3614A4 80103634 2444000C */   addiu     $a0, $v0, 0xC
    /* 3614A8 80103638 3C028010 */  lui        $v0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 3614AC 8010363C 8C423880 */  lw         $v0, %lo(D_80103880_3617A0_SlotMachine1P)($v0)
    /* 3614B0 80103640 8C42003C */  lw         $v0, 0x3C($v0)
    /* 3614B4 80103644 8C420040 */  lw         $v0, 0x40($v0)
    /* 3614B8 80103648 84420000 */  lh         $v0, 0x0($v0)
    /* 3614BC 8010364C 00022040 */  sll        $a0, $v0, 1
    /* 3614C0 80103650 00822021 */  addu       $a0, $a0, $v0
    /* 3614C4 80103654 00042180 */  sll        $a0, $a0, 6
    /* 3614C8 80103658 3C028010 */  lui        $v0, %hi(D_800FC834_FD434)
    /* 3614CC 8010365C 8C42C834 */  lw         $v0, %lo(D_800FC834_FD434)($v0)
    /* 3614D0 80103660 00822021 */  addu       $a0, $a0, $v0
    /* 3614D4 80103664 3C05C270 */  lui        $a1, (0xC2700000 >> 16)
    /* 3614D8 80103668 0C02CE1C */  jal        func_800B3870_B4470
    /* 3614DC 8010366C 24840074 */   addiu     $a0, $a0, 0x74
    /* 3614E0 80103670 3C028010 */  lui        $v0, %hi(func_801028B4_360724_SlotMachine1P)
    /* 3614E4 80103674 244228B4 */  addiu      $v0, $v0, %lo(func_801028B4_360724_SlotMachine1P)
    /* 3614E8 80103678 AFA20010 */  sw         $v0, 0x10($sp)
    /* 3614EC 8010367C 24041000 */  addiu      $a0, $zero, 0x1000
    /* 3614F0 80103680 00002821 */  addu       $a1, $zero, $zero
    /* 3614F4 80103684 00003021 */  addu       $a2, $zero, $zero
    /* 3614F8 80103688 0C01D966 */  jal        func_80076598_77198
    /* 3614FC 8010368C 2407FFFF */   addiu     $a3, $zero, -0x1
    /* 361500 80103690 AC400028 */  sw         $zero, 0x28($v0)
    /* 361504 80103694 AC400030 */  sw         $zero, 0x30($v0)
    /* 361508 80103698 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 36150C 8010369C 8FB00018 */  lw         $s0, 0x18($sp)
    /* 361510 801036A0 03E00008 */  jr         $ra
    /* 361514 801036A4 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_801034C8_361338_SlotMachine1P

nonmatching func_801036A8_361518_SlotMachine1P, 0x44

glabel func_801036A8_361518_SlotMachine1P
    /* 361518 801036A8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 36151C 801036AC AFBF0010 */  sw         $ra, 0x10($sp)
    /* 361520 801036B0 3C048010 */  lui        $a0, %hi(D_80103880_3617A0_SlotMachine1P)
    /* 361524 801036B4 0C0110C3 */  jal        func_8004430C_44F0C
    /* 361528 801036B8 8C843880 */   lw        $a0, %lo(D_80103880_3617A0_SlotMachine1P)($a0)
    /* 36152C 801036BC 3C048010 */  lui        $a0, %hi(D_8010388E_3617AE_SlotMachine1P)
    /* 361530 801036C0 0C017898 */  jal        func_8005E260_5EE60
    /* 361534 801036C4 8484388E */   lh        $a0, %lo(D_8010388E_3617AE_SlotMachine1P)($a0)
    /* 361538 801036C8 3C048010 */  lui        $a0, %hi(D_8010388A_3617AA_SlotMachine1P)
    /* 36153C 801036CC 0C020998 */  jal        func_80082660_83260
    /* 361540 801036D0 8484388A */   lh        $a0, %lo(D_8010388A_3617AA_SlotMachine1P)($a0)
    /* 361544 801036D4 3C048010 */  lui        $a0, %hi(D_80103888_3617A8_SlotMachine1P)
    /* 361548 801036D8 0C01FE2C */  jal        func_8007F8B0_804B0
    /* 36154C 801036DC 84843888 */   lh        $a0, %lo(D_80103888_3617A8_SlotMachine1P)($a0)
    /* 361550 801036E0 8FBF0010 */  lw         $ra, 0x10($sp)
    /* 361554 801036E4 03E00008 */  jr         $ra
    /* 361558 801036E8 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_801036A8_361518_SlotMachine1P

nonmatching func_801036EC_36155C_SlotMachine1P, 0xBC

glabel func_801036EC_36155C_SlotMachine1P
    /* 36155C 801036EC 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 361560 801036F0 AFBF0020 */  sw         $ra, 0x20($sp)
    /* 361564 801036F4 0C00638C */  jal        func_80018E30
    /* 361568 801036F8 24040001 */   addiu     $a0, $zero, 0x1
    /* 36156C 801036FC 3C014370 */  lui        $at, (0x43700000 >> 16)
    /* 361570 80103700 44810000 */  mtc1       $at, $f0
    /* 361574 80103704 00000000 */  nop
    /* 361578 80103708 E7A00010 */  swc1       $f0, 0x10($sp)
    /* 36157C 8010370C 00002021 */  addu       $a0, $zero, $zero
    /* 361580 80103710 00002821 */  addu       $a1, $zero, $zero
    /* 361584 80103714 3C0743A0 */  lui        $a3, (0x43A00000 >> 16)
    /* 361588 80103718 0C0062F4 */  jal        func_80018BD0
    /* 36158C 8010371C 00A03021 */   addu      $a2, $a1, $zero
    /* 361590 80103720 3C014420 */  lui        $at, (0x44200000 >> 16)
    /* 361594 80103724 44812000 */  mtc1       $at, $f4
    /* 361598 80103728 00000000 */  nop
    /* 36159C 8010372C E7A40010 */  swc1       $f4, 0x10($sp)
    /* 3615A0 80103730 3C0143F0 */  lui        $at, (0x43F00000 >> 16)
    /* 3615A4 80103734 44811000 */  mtc1       $at, $f2
    /* 3615A8 80103738 00000000 */  nop
    /* 3615AC 8010373C E7A20014 */  swc1       $f2, 0x14($sp)
    /* 3615B0 80103740 3C0143FF */  lui        $at, (0x43FF8000 >> 16)
    /* 3615B4 80103744 34218000 */  ori        $at, $at, (0x43FF8000 & 0xFFFF)
    /* 3615B8 80103748 44810000 */  mtc1       $at, $f0
    /* 3615BC 8010374C 00000000 */  nop
    /* 3615C0 80103750 E7A00018 */  swc1       $f0, 0x18($sp)
    /* 3615C4 80103754 44052000 */  mfc1       $a1, $f4
    /* 3615C8 80103758 44061000 */  mfc1       $a2, $f2
    /* 3615CC 8010375C 44070000 */  mfc1       $a3, $f0
    /* 3615D0 80103760 00000000 */  nop
    /* 3615D4 80103764 0C00630D */  jal        func_80018C34
    /* 3615D8 80103768 00002021 */   addu      $a0, $zero, $zero
    /* 3615DC 8010376C 3C040116 */  lui        $a0, %hi(D_01164160)
    /* 3615E0 80103770 0C01428C */  jal        func_80050A30_51630
    /* 3615E4 80103774 24844160 */   addiu     $a0, $a0, %lo(D_01164160)
    /* 3615E8 80103778 0C014380 */  jal        func_80050E00_51A00
    /* 3615EC 8010377C 00002021 */   addu      $a0, $zero, $zero
    /* 3615F0 80103780 3C014348 */  lui        $at, (0x43480000 >> 16)
    /* 3615F4 80103784 44816000 */  mtc1       $at, $f12
    /* 3615F8 80103788 3C01453B */  lui        $at, (0x453B8000 >> 16)
    /* 3615FC 8010378C 34218000 */  ori        $at, $at, (0x453B8000 & 0xFFFF)
    /* 361600 80103790 44817000 */  mtc1       $at, $f14
    /* 361604 80103794 0C014C87 */  jal        func_8005321C_53E1C
    /* 361608 80103798 00000000 */   nop
    /* 36160C 8010379C 8FBF0020 */  lw         $ra, 0x20($sp)
    /* 361610 801037A0 03E00008 */  jr         $ra
    /* 361614 801037A4 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_801036EC_36155C_SlotMachine1P

nonmatching func_801037A8_361618_SlotMachine1P, 0x24

glabel func_801037A8_361618_SlotMachine1P
    /* 361618 801037A8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 36161C 801037AC AFBF0010 */  sw         $ra, 0x10($sp)
    /* 361620 801037B0 0C014387 */  jal        func_80050E1C_51A1C
    /* 361624 801037B4 00000000 */   nop
    /* 361628 801037B8 0C0142B8 */  jal        func_80050AE0_516E0
    /* 36162C 801037BC 00000000 */   nop
    /* 361630 801037C0 8FBF0010 */  lw         $ra, 0x10($sp)
    /* 361634 801037C4 03E00008 */  jr         $ra
    /* 361638 801037C8 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_801037A8_361618_SlotMachine1P
    /* 36163C 801037CC 00000000 */  nop

nonmatching D_801037D0_3616F0_SlotMachine1P

dlabel D_801037D0_3616F0_SlotMachine1P
    /* 361640 801037D0 */ .short 0x0001
enddlabel D_801037D0_3616F0_SlotMachine1P

nonmatching D_801037D2_3616F2_SlotMachine1P

dlabel D_801037D2_3616F2_SlotMachine1P
    /* 361642 801037D2 */ .short 0x0000
    /* 361644 801037D4 */ .short 0x0000
enddlabel D_801037D2_3616F2_SlotMachine1P

nonmatching D_801037D6_3616F6_SlotMachine1P

dlabel D_801037D6_3616F6_SlotMachine1P
    /* 361646 801037D6 */ .short 0x0001

nonmatching D_801037D8_3616F8_SlotMachine1P

dlabel D_801037D8_3616F8_SlotMachine1P
    /* 361648 801037D8 00000000 */ .word 0x00000000
    /* 36164C 801037DC 00000000 */ .word 0x00000000

nonmatching D_801037E0_361700_SlotMachine1P

dlabel D_801037E0_361700_SlotMachine1P
    /* 361650 801037E0 00000000 */ .word 0x00000000
    /* 361654 801037E4 C1F00000 */ .word 0xC1F00000
    /* 361658 801037E8 45480000 */ .word 0x45480000 /* invalid instruction */

nonmatching D_801037EC_36170C_SlotMachine1P

dlabel D_801037EC_36170C_SlotMachine1P
    /* 36165C 801037EC 00000000 */ .word 0x00000000
    /* 361660 801037F0 00000000 */ .word 0x00000000
    /* 361664 801037F4 00000000 */ .word 0x00000000

nonmatching D_801037F8_361718_SlotMachine1P

dlabel D_801037F8_361718_SlotMachine1P
    /* 361668 801037F8 43FA0000 */ .word 0x43FA0000 /* invalid instruction */
    /* 36166C 801037FC 00000000 */ .word 0x00000000
    /* 361670 80103800 457A0000 */ .word 0x457A0000 /* invalid instruction */

nonmatching D_80103804_361724_SlotMachine1P

dlabel D_80103804_361724_SlotMachine1P
    /* 361674 80103804 43480000 */ .word 0x43480000 /* invalid instruction */
    /* 361678 80103808 43480000 */ .word 0x43480000 /* invalid instruction */
    /* 36167C 8010380C 459C4000 */ .word 0x459C4000 /* invalid instruction */

nonmatching D_80103810_361730_SlotMachine1P

dlabel D_80103810_361730_SlotMachine1P
    /* 361680 80103810 00000000 */ .word 0x00000000
    /* 361684 80103814 00000000 */ .word 0x00000000
    /* 361688 80103818 C3480000 */ .word 0xC3480000

nonmatching D_8010381C_36173C_SlotMachine1P

dlabel D_8010381C_36173C_SlotMachine1P
    /* 36168C 8010381C 43960000 */ .word 0x43960000 /* invalid instruction */
    /* 361690 80103820 C2C80000 */ .word 0xC2C80000
    /* 361694 80103824 45481000 */ .word 0x45481000 /* invalid instruction */

nonmatching D_80103828_361748_SlotMachine1P

dlabel D_80103828_361748_SlotMachine1P
    /* 361698 80103828 C3480000 */ .word 0xC3480000
    /* 36169C 8010382C 00000000 */ .word 0x00000000
    /* 3616A0 80103830 45480000 */ .word 0x45480000 /* invalid instruction */

nonmatching D_80103834_361754_SlotMachine1P

dlabel D_80103834_361754_SlotMachine1P
    /* 3616A4 80103834 00000000 */ .word 0x00000000
    /* 3616A8 80103838 C2C80000 */ .word 0xC2C80000
    /* 3616AC 8010383C 45480000 */ .word 0x45480000 /* invalid instruction */

nonmatching D_80103840_361760_SlotMachine1P

dlabel D_80103840_361760_SlotMachine1P
    /* 3616B0 80103840 C3960000 */ .word 0xC3960000
    /* 3616B4 80103844 00000000 */ .word 0x00000000
    /* 3616B8 80103848 00000000 */ .word 0x00000000

nonmatching D_8010384C_36176C_SlotMachine1P

dlabel D_8010384C_36176C_SlotMachine1P
    /* 3616BC 8010384C 00000000 */ .word 0x00000000
    /* 3616C0 80103850 C2C80000 */ .word 0xC2C80000
    /* 3616C4 80103854 4547F000 */ .word 0x4547F000 /* invalid instruction */

nonmatching D_80103858_361778_SlotMachine1P

dlabel D_80103858_361778_SlotMachine1P
    /* 3616C8 80103858 43480000 */ .word 0x43480000 /* invalid instruction */
    /* 3616CC 8010385C 00000000 */ .word 0x00000000
    /* 3616D0 80103860 45480000 */ .word 0x45480000 /* invalid instruction */

nonmatching D_80103864_361784_SlotMachine1P

dlabel D_80103864_361784_SlotMachine1P
    /* 3616D4 80103864 43960000 */ .word 0x43960000 /* invalid instruction */
    /* 3616D8 80103868 00000000 */ .word 0x00000000
    /* 3616DC 8010386C 00000000 */ .word 0x00000000

nonmatching D_80103870_361790_SlotMachine1P

dlabel D_80103870_361790_SlotMachine1P
    /* 3616E0 80103870 3F916872 */ .word 0x3F916872 /* invalid instruction */
    /* 3616E4 80103874 B020C49C */ .word 0xB020C49C

nonmatching D_80103878_361798_SlotMachine1P

dlabel D_80103878_361798_SlotMachine1P
    /* 3616E8 80103878 3F916872 */ .word 0x3F916872 /* invalid instruction */
    /* 3616EC 8010387C B020C49C */ .word 0xB020C49C
enddlabel D_801037D6_3616F6_SlotMachine1P
