import Foundation
import MP2Core

public enum OverlayBootstrap {
    public static func registerAll() {
        register(Ovl00_Debug.overlayID, name: Ovl00_Debug.name) { Ovl00_Debug() }
register(Ovl01_BowserSlots.overlayID, name: Ovl01_BowserSlots.name) { Ovl01_BowserSlots() }
register(Ovl02_RollOutTheBarrels.overlayID, name: Ovl02_RollOutTheBarrels.name) { Ovl02_RollOutTheBarrels() }
register(Ovl03_CoffinCongestion.overlayID, name: Ovl03_CoffinCongestion.name) { Ovl03_CoffinCongestion() }
register(Ovl04_HammerSlammer.overlayID, name: Ovl04_HammerSlammer.name) { Ovl04_HammerSlammer() }
register(Ovl05_GiveMeABrake.overlayID, name: Ovl05_GiveMeABrake.name) { Ovl05_GiveMeABrake() }
register(Ovl06_MalletGoRound.overlayID, name: Ovl06_MalletGoRound.name) { Ovl06_MalletGoRound() }
register(Ovl07_GrabBag.overlayID, name: Ovl07_GrabBag.name) { Ovl07_GrabBag() }
register(Ovl08_LavaTileIsle.overlayID, name: Ovl08_LavaTileIsle.name) { Ovl08_LavaTileIsle() }
register(Ovl09_BumperBalloonCars.overlayID, name: Ovl09_BumperBalloonCars.name) { Ovl09_BumperBalloonCars() }
register(Ovl0A_RakinEmIn.overlayID, name: Ovl0A_RakinEmIn.name) { Ovl0A_RakinEmIn() }
register(Ovl0B_DayAtTheRaces.overlayID, name: Ovl0B_DayAtTheRaces.name) { Ovl0B_DayAtTheRaces() }
register(Ovl0C_HotRopeJump.overlayID, name: Ovl0C_HotRopeJump.name) { Ovl0C_HotRopeJump() }
register(Ovl0D_HotBobOmb.overlayID, name: Ovl0D_HotBobOmb.name) { Ovl0D_HotBobOmb() }
register(Ovl0E_BowlOver.overlayID, name: Ovl0E_BowlOver.name) { Ovl0E_BowlOver() }
register(Ovl0F_RainbowRun.overlayID, name: Ovl0F_RainbowRun.name) { Ovl0F_RainbowRun() }
register(Ovl10_CraneGame.overlayID, name: Ovl10_CraneGame.name) { Ovl10_CraneGame() }
register(Ovl11_MoveToTheMusic.overlayID, name: Ovl11_MoveToTheMusic.name) { Ovl11_MoveToTheMusic() }
register(Ovl12_BobOmbBarrage.overlayID, name: Ovl12_BobOmbBarrage.name) { Ovl12_BobOmbBarrage() }
register(Ovl13_LookAway.overlayID, name: Ovl13_LookAway.name) { Ovl13_LookAway() }
register(Ovl14_ShockDropRoll.overlayID, name: Ovl14_ShockDropRoll.name) { Ovl14_ShockDropRoll() }
register(Ovl15_LightsOut.overlayID, name: Ovl15_LightsOut.name) { Ovl15_LightsOut() }
register(Ovl16_FiletRelay.overlayID, name: Ovl16_FiletRelay.name) { Ovl16_FiletRelay() }
register(Ovl17_ArcherAttack.overlayID, name: Ovl17_ArcherAttack.name) { Ovl17_ArcherAttack() }
register(Ovl18_ToadtressScramble.overlayID, name: Ovl18_ToadtressScramble.name) { Ovl18_ToadtressScramble() }
register(Ovl19_BobsledRun.overlayID, name: Ovl19_BobsledRun.name) { Ovl19_BobsledRun() }
register(Ovl1A_HandcarHavoc.overlayID, name: Ovl1A_HandcarHavoc.name) { Ovl1A_HandcarHavoc() }
register(Ovl1B_BalloonBurst.overlayID, name: Ovl1B_BalloonBurst.name) { Ovl1B_BalloonBurst() }
register(Ovl1C_SkyPilots.overlayID, name: Ovl1C_SkyPilots.name) { Ovl1C_SkyPilots() }
register(Ovl1D_SpeedHikers.overlayID, name: Ovl1D_SpeedHikers.name) { Ovl1D_SpeedHikers() }
register(Ovl1E_HoneycombTreasureHunt.overlayID, name: Ovl1E_HoneycombTreasureHunt.name) { Ovl1E_HoneycombTreasureHunt() }
register(Ovl1F_SlotMachine.overlayID, name: Ovl1F_SlotMachine.name) { Ovl1F_SlotMachine() }
register(Ovl20_MechaMarathon.overlayID, name: Ovl20_MechaMarathon.name) { Ovl20_MechaMarathon() }
register(Ovl21_RollCall.overlayID, name: Ovl21_RollCall.name) { Ovl21_RollCall() }
register(Ovl22_AbandonShip.overlayID, name: Ovl22_AbandonShip.name) { Ovl22_AbandonShip() }
register(Ovl23_PlatformPeril.overlayID, name: Ovl23_PlatformPeril.name) { Ovl23_PlatformPeril() }
register(Ovl24_TotemPolePerturbation.overlayID, name: Ovl24_TotemPolePerturbation.name) { Ovl24_TotemPolePerturbation() }
register(Ovl25_BumperBallMaze.overlayID, name: Ovl25_BumperBallMaze.name) { Ovl25_BumperBallMaze() }
register(Ovl26_KarateChop.overlayID, name: Ovl26_KarateChop.name) { Ovl26_KarateChop() }
register(Ovl27_StackingStored.overlayID, name: Ovl27_StackingStored.name) { Ovl27_StackingStored() }
register(Ovl28_ShuffleAdventure.overlayID, name: Ovl28_ShuffleAdventure.name) { Ovl28_ShuffleAdventure() }
register(Ovl29_BobsledRun2P.overlayID, name: Ovl29_BobsledRun2P.name) { Ovl29_BobsledRun2P() }
register(Ovl2A_HandcarHavoc2P.overlayID, name: Ovl2A_HandcarHavoc2P.name) { Ovl2A_HandcarHavoc2P() }
register(Ovl2B_BalloonBurst2P.overlayID, name: Ovl2B_BalloonBurst2P.name) { Ovl2B_BalloonBurst2P() }
register(Ovl2C_SkyPilots2P.overlayID, name: Ovl2C_SkyPilots2P.name) { Ovl2C_SkyPilots2P() }
register(Ovl2D_SpeedHikers2P.overlayID, name: Ovl2D_SpeedHikers2P.name) { Ovl2D_SpeedHikers2P() }
register(Ovl2E_CrazyCutter.overlayID, name: Ovl2E_CrazyCutter.name) { Ovl2E_CrazyCutter() }
register(Ovl2F_BombsAway.overlayID, name: Ovl2F_BombsAway.name) { Ovl2F_BombsAway() }
register(Ovl30_RainbowRun2P.overlayID, name: Ovl30_RainbowRun2P.name) { Ovl30_RainbowRun2P() }
register(Ovl31_ConveyorBeltChase.overlayID, name: Ovl31_ConveyorBeltChase.name) { Ovl31_ConveyorBeltChase() }
register(Ovl32_TorpedoTargets.overlayID, name: Ovl32_TorpedoTargets.name) { Ovl32_TorpedoTargets() }
register(Ovl33_LuckySeven.overlayID, name: Ovl33_LuckySeven.name) { Ovl33_LuckySeven() }
register(Ovl34_LightUpMyNight.overlayID, name: Ovl34_LightUpMyNight.name) { Ovl34_LightUpMyNight() }
register(Ovl35_FaceOff.overlayID, name: Ovl35_FaceOff.name) { Ovl35_FaceOff() }
register(Ovl36_MagnetCarta.overlayID, name: Ovl36_MagnetCarta.name) { Ovl36_MagnetCarta() }
register(Ovl37_RollOutTheBarrels2P.overlayID, name: Ovl37_RollOutTheBarrels2P.name) { Ovl37_RollOutTheBarrels2P() }
register(Ovl38_CoffinCongestion2P.overlayID, name: Ovl38_CoffinCongestion2P.name) { Ovl38_CoffinCongestion2P() }
register(Ovl39_HammerSlammer2P.overlayID, name: Ovl39_HammerSlammer2P.name) { Ovl39_HammerSlammer2P() }
register(Ovl3A_GiveMeABrake2P.overlayID, name: Ovl3A_GiveMeABrake2P.name) { Ovl3A_GiveMeABrake2P() }
register(Ovl3B_MalletGoRound2P.overlayID, name: Ovl3B_MalletGoRound2P.name) { Ovl3B_MalletGoRound2P() }
register(Ovl3C_GrabBag2P.overlayID, name: Ovl3C_GrabBag2P.name) { Ovl3C_GrabBag2P() }
register(Ovl3D_LavaTileIsle2P.overlayID, name: Ovl3D_LavaTileIsle2P.name) { Ovl3D_LavaTileIsle2P() }
register(Ovl3E_BumperBalloonCars2P.overlayID, name: Ovl3E_BumperBalloonCars2P.name) { Ovl3E_BumperBalloonCars2P() }
register(Ovl3F_RakinEmIn2P.overlayID, name: Ovl3F_RakinEmIn2P.name) { Ovl3F_RakinEmIn2P() }
register(Ovl40_DayAtTheRaces2P.overlayID, name: Ovl40_DayAtTheRaces2P.name) { Ovl40_DayAtTheRaces2P() }
register(Ovl41_HotRopeJump2P.overlayID, name: Ovl41_HotRopeJump2P.name) { Ovl41_HotRopeJump2P() }
register(Ovl42_HotBobOmb2P.overlayID, name: Ovl42_HotBobOmb2P.name) { Ovl42_HotBobOmb2P() }
register(Ovl43_BowlOver2P.overlayID, name: Ovl43_BowlOver2P.name) { Ovl43_BowlOver2P() }
register(Ovl44_RainbowRun4P.overlayID, name: Ovl44_RainbowRun4P.name) { Ovl44_RainbowRun4P() }
register(Ovl45_CraneGame2P.overlayID, name: Ovl45_CraneGame2P.name) { Ovl45_CraneGame2P() }
register(Ovl46_MoveToTheMusic2P.overlayID, name: Ovl46_MoveToTheMusic2P.name) { Ovl46_MoveToTheMusic2P() }
register(Ovl47_BobOmbBarrage2P.overlayID, name: Ovl47_BobOmbBarrage2P.name) { Ovl47_BobOmbBarrage2P() }
register(Ovl48_LookAway2P.overlayID, name: Ovl48_LookAway2P.name) { Ovl48_LookAway2P() }
register(Ovl49_ShockDropRoll2P.overlayID, name: Ovl49_ShockDropRoll2P.name) { Ovl49_ShockDropRoll2P() }
register(Ovl4A_LightsOut2P.overlayID, name: Ovl4A_LightsOut2P.name) { Ovl4A_LightsOut2P() }
register(Ovl4B_FiletRelay2P.overlayID, name: Ovl4B_FiletRelay2P.name) { Ovl4B_FiletRelay2P() }
register(Ovl4C_ArcherAttack2P.overlayID, name: Ovl4C_ArcherAttack2P.name) { Ovl4C_ArcherAttack2P() }
register(Ovl4D_ToadtressScramble2P.overlayID, name: Ovl4D_ToadtressScramble2P.name) { Ovl4D_ToadtressScramble2P() }
register(Ovl4E_BobsledRun1P.overlayID, name: Ovl4E_BobsledRun1P.name) { Ovl4E_BobsledRun1P() }
register(Ovl4F_HandcarHavoc1P.overlayID, name: Ovl4F_HandcarHavoc1P.name) { Ovl4F_HandcarHavoc1P() }
register(Ovl50_BalloonBurst1P.overlayID, name: Ovl50_BalloonBurst1P.name) { Ovl50_BalloonBurst1P() }
register(Ovl51_SkyPilots1P.overlayID, name: Ovl51_SkyPilots1P.name) { Ovl51_SkyPilots1P() }
register(Ovl52_SpeedHikers1P.overlayID, name: Ovl52_SpeedHikers1P.name) { Ovl52_SpeedHikers1P() }
register(Ovl53_HoneycombTreasureHunt1P.overlayID, name: Ovl53_HoneycombTreasureHunt1P.name) { Ovl53_HoneycombTreasureHunt1P() }
register(Ovl54_SlotMachine1P.overlayID, name: Ovl54_SlotMachine1P.name) { Ovl54_SlotMachine1P() }
register(Ovl55_MechaMarathon1P.overlayID, name: Ovl55_MechaMarathon1P.name) { Ovl55_MechaMarathon1P() }
register(Ovl56_RollCall1P.overlayID, name: Ovl56_RollCall1P.name) { Ovl56_RollCall1P() }
register(Ovl57_AbandonShip1P.overlayID, name: Ovl57_AbandonShip1P.name) { Ovl57_AbandonShip1P() }
register(Ovl58_PlatformPeril1P.overlayID, name: Ovl58_PlatformPeril1P.name) { Ovl58_PlatformPeril1P() }
register(Ovl59_TotemPolePerturbation1P.overlayID, name: Ovl59_TotemPolePerturbation1P.name) { Ovl59_TotemPolePerturbation1P() }
register(Ovl5A_BumperBallMaze1P.overlayID, name: Ovl5A_BumperBallMaze1P.name) { Ovl5A_BumperBallMaze1P() }
register(Ovl5B_KarateChop1P.overlayID, name: Ovl5B_KarateChop1P.name) { Ovl5B_KarateChop1P() }
register(Ovl5C_StackingStored1P.overlayID, name: Ovl5C_StackingStored1P.name) { Ovl5C_StackingStored1P() }
register(Ovl5D_ShuffleAdventure1P.overlayID, name: Ovl5D_ShuffleAdventure1P.name) { Ovl5D_ShuffleAdventure1P() }
register(Ovl5E_BoardSelect.overlayID, name: Ovl5E_BoardSelect.name) { Ovl5E_BoardSelect() }
register(Ovl5F_BoardMain.overlayID, name: Ovl5F_BoardMain.name) { Ovl5F_BoardMain() }
register(Ovl60_BoardEvents.overlayID, name: Ovl60_BoardEvents.name) { Ovl60_BoardEvents() }
register(Ovl61_BoardShop.overlayID, name: Ovl61_BoardShop.name) { Ovl61_BoardShop() }
register(Ovl62_TitleScreenAndIntro.overlayID, name: Ovl62_TitleScreenAndIntro.name) { Ovl62_TitleScreenAndIntro() }
register(Ovl63_MainMenu.overlayID, name: Ovl63_MainMenu.name) { Ovl63_MainMenu() }
register(Ovl64_GameSetup.overlayID, name: Ovl64_GameSetup.name) { Ovl64_GameSetup() }
register(Ovl65_MinigameLand.overlayID, name: Ovl65_MinigameLand.name) { Ovl65_MinigameLand() }
register(Ovl66_BattleMinigame.overlayID, name: Ovl66_BattleMinigame.name) { Ovl66_BattleMinigame() }
register(Ovl67_StoryMode.overlayID, name: Ovl67_StoryMode.name) { Ovl67_StoryMode() }
register(Ovl68_OptionsMenu.overlayID, name: Ovl68_OptionsMenu.name) { Ovl68_OptionsMenu() }
register(Ovl69_SaveLoad.overlayID, name: Ovl69_SaveLoad.name) { Ovl69_SaveLoad() }
register(Ovl6A_BoardIntro.overlayID, name: Ovl6A_BoardIntro.name) { Ovl6A_BoardIntro() }
register(Ovl6B_MinigameInstructions.overlayID, name: Ovl6B_MinigameInstructions.name) { Ovl6B_MinigameInstructions() }
register(Ovl6C_MinigameSelect.overlayID, name: Ovl6C_MinigameSelect.name) { Ovl6C_MinigameSelect() }
register(Ovl6D_FinalMinigameCoaster.overlayID, name: Ovl6D_FinalMinigameCoaster.name) { Ovl6D_FinalMinigameCoaster() }
register(Ovl6E_MinigameCoaster.overlayID, name: Ovl6E_MinigameCoaster.name) { Ovl6E_MinigameCoaster() }
register(Ovl6F_BattleResults.overlayID, name: Ovl6F_BattleResults.name) { Ovl6F_BattleResults() }
register(Ovl70_Results.overlayID, name: Ovl70_Results.name) { Ovl70_Results() }
register(Ovl71_MsgTest.overlayID, name: Ovl71_MsgTest.name) { Ovl71_MsgTest() }
register(Ovl72_Credits.overlayID, name: Ovl72_Credits.name) { Ovl72_Credits() }
    }

    private static func register(_ id: UInt8, name: String, factory: @escaping OverlayFactory) {
        OverlayRegistry.register(id, name: name, factory: factory)
    }
}
