.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80104940_2B10C0_DayAtTheRaces2P, 0x4

dlabel D_80104940_2B10C0_DayAtTheRaces2P
    /* 80104940 */ .space 0x04

nonmatching D_80104944_2B10C4_DayAtTheRaces2P, 0x4

dlabel D_80104944_2B10C4_DayAtTheRaces2P
    /* 80104944 */ .space 0x04

nonmatching D_80104948_2B10C8_DayAtTheRaces2P, 0x10

dlabel D_80104948_2B10C8_DayAtTheRaces2P
    /* 80104948 */ .space 0x10

nonmatching D_80104958_2B10D8_DayAtTheRaces2P, 0x2

dlabel D_80104958_2B10D8_DayAtTheRaces2P
    /* 80104958 */ .space 0x02

nonmatching D_8010495A_2B10DA_DayAtTheRaces2P, 0x2

dlabel D_8010495A_2B10DA_DayAtTheRaces2P
    /* 8010495A */ .space 0x02

nonmatching D_8010495C_2B10DC_DayAtTheRaces2P, 0x2

dlabel D_8010495C_2B10DC_DayAtTheRaces2P
    /* 8010495C */ .space 0x02

nonmatching D_8010495E_2B10DE_DayAtTheRaces2P, 0x1C

dlabel D_8010495E_2B10DE_DayAtTheRaces2P
    /* 8010495E */ .space 0x1C

nonmatching D_8010497A_2B10FA_DayAtTheRaces2P, 0x26

dlabel D_8010497A_2B10FA_DayAtTheRaces2P
    /* 8010497A */ .space 0x26

nonmatching D_801049A0_2B1120_DayAtTheRaces2P, 0x4

dlabel D_801049A0_2B1120_DayAtTheRaces2P
    /* 801049A0 */ .space 0x04

nonmatching D_801049A4_2B1124_DayAtTheRaces2P, 0x4

dlabel D_801049A4_2B1124_DayAtTheRaces2P
    /* 801049A4 */ .space 0x04

nonmatching D_801049A8_2B1128_DayAtTheRaces2P, 0x8

dlabel D_801049A8_2B1128_DayAtTheRaces2P
    /* 801049A8 */ .space 0x08

nonmatching D_801049B0_2B1130_DayAtTheRaces2P, 0xC

dlabel D_801049B0_2B1130_DayAtTheRaces2P
    /* 801049B0 */ .space 0x0C

nonmatching D_801049BC_2B113C_DayAtTheRaces2P, 0xC

dlabel D_801049BC_2B113C_DayAtTheRaces2P
    /* 801049BC */ .space 0x0C

nonmatching D_801049C8_2B1148_DayAtTheRaces2P, 0xC

dlabel D_801049C8_2B1148_DayAtTheRaces2P
    /* 801049C8 */ .space 0x0C

nonmatching D_801049D4_2B1154_DayAtTheRaces2P, 0x5C

dlabel D_801049D4_2B1154_DayAtTheRaces2P
    /* 801049D4 */ .space 0x5C

nonmatching D_80104A30_2B11B0_DayAtTheRaces2P, 0x14

dlabel D_80104A30_2B11B0_DayAtTheRaces2P
    /* 80104A30 */ .space 0x14

nonmatching D_80104A44_2B11C4_DayAtTheRaces2P, 0x1C

dlabel D_80104A44_2B11C4_DayAtTheRaces2P
    /* 80104A44 */ .space 0x1C

nonmatching D_80104A60_2B11E0_DayAtTheRaces2P, 0x10

dlabel D_80104A60_2B11E0_DayAtTheRaces2P
    /* 80104A60 */ .space 0x10

nonmatching D_80104A70_2B11F0_DayAtTheRaces2P, 0x10

dlabel D_80104A70_2B11F0_DayAtTheRaces2P
    /* 80104A70 */ .space 0x10

nonmatching D_80104A80_2B1200_DayAtTheRaces2P, 0x10

dlabel D_80104A80_2B1200_DayAtTheRaces2P
    /* 80104A80 */ .space 0x10

nonmatching D_80104A90_2B1210_DayAtTheRaces2P, 0x18

dlabel D_80104A90_2B1210_DayAtTheRaces2P
    /* 80104A90 */ .space 0x18

nonmatching D_80104AA8_2B1228_DayAtTheRaces2P, 0x18

dlabel D_80104AA8_2B1228_DayAtTheRaces2P
    /* 80104AA8 */ .space 0x18

nonmatching D_80104AC0_2B1240_DayAtTheRaces2P, 0xC

dlabel D_80104AC0_2B1240_DayAtTheRaces2P
    /* 80104AC0 */ .space 0x0C

nonmatching D_80104ACC_2B124C_DayAtTheRaces2P, 0x10

dlabel D_80104ACC_2B124C_DayAtTheRaces2P
    /* 80104ACC */ .space 0x10

nonmatching D_80104ADC_2B125C_DayAtTheRaces2P, 0x10

dlabel D_80104ADC_2B125C_DayAtTheRaces2P
    /* 80104ADC */ .space 0x10

nonmatching D_80104AEC_2B126C_DayAtTheRaces2P, 0x10

dlabel D_80104AEC_2B126C_DayAtTheRaces2P
    /* 80104AEC */ .space 0x10

nonmatching D_80104AFC_2B127C_DayAtTheRaces2P, 0x4

dlabel D_80104AFC_2B127C_DayAtTheRaces2P
    /* 80104AFC */ .space 0x04

nonmatching D_80104B00_2B1280_DayAtTheRaces2P, 0x10

dlabel D_80104B00_2B1280_DayAtTheRaces2P
    /* 80104B00 */ .space 0x10

nonmatching D_80104B10_2B1290_DayAtTheRaces2P, 0x4

dlabel D_80104B10_2B1290_DayAtTheRaces2P
    /* 80104B10 */ .space 0x04

nonmatching D_80104B14_2B1294_DayAtTheRaces2P, 0x4

dlabel D_80104B14_2B1294_DayAtTheRaces2P
    /* 80104B14 */ .space 0x04

nonmatching D_80104B18_2B1298_DayAtTheRaces2P, 0x4

dlabel D_80104B18_2B1298_DayAtTheRaces2P
    /* 80104B18 */ .space 0x04

nonmatching D_80104B1C_2B129C_DayAtTheRaces2P, 0x4

dlabel D_80104B1C_2B129C_DayAtTheRaces2P
    /* 80104B1C */ .space 0x04

nonmatching D_80104B20_2B12A0_DayAtTheRaces2P, 0x4

dlabel D_80104B20_2B12A0_DayAtTheRaces2P
    /* 80104B20 */ .space 0x04

nonmatching D_80104B24_2B12A4_DayAtTheRaces2P, 0x2

dlabel D_80104B24_2B12A4_DayAtTheRaces2P
    /* 80104B24 */ .space 0x02

nonmatching D_80104B26_2B12A6_DayAtTheRaces2P, 0x2

dlabel D_80104B26_2B12A6_DayAtTheRaces2P
    /* 80104B26 */ .space 0x02

nonmatching D_80104B28_2B12A8_DayAtTheRaces2P, 0x2

dlabel D_80104B28_2B12A8_DayAtTheRaces2P
    /* 80104B28 */ .space 0x02

nonmatching D_80104B2A_2B12AA_DayAtTheRaces2P, 0x2

dlabel D_80104B2A_2B12AA_DayAtTheRaces2P
    /* 80104B2A */ .space 0x02

nonmatching D_80104B2C_2B12AC_DayAtTheRaces2P, 0x4

dlabel D_80104B2C_2B12AC_DayAtTheRaces2P
    /* 80104B2C */ .space 0x04

nonmatching D_80104B30_2B12B0_DayAtTheRaces2P, 0x4

dlabel D_80104B30_2B12B0_DayAtTheRaces2P
    /* 80104B30 */ .space 0x04

nonmatching D_80104B34_2B12B4_DayAtTheRaces2P, 0x4

dlabel D_80104B34_2B12B4_DayAtTheRaces2P
    /* 80104B34 */ .space 0x04

nonmatching D_80104B38_2B12B8_DayAtTheRaces2P, 0x4

dlabel D_80104B38_2B12B8_DayAtTheRaces2P
    /* 80104B38 */ .space 0x04

nonmatching D_80104B3C_2B12BC_DayAtTheRaces2P, 0x4

dlabel D_80104B3C_2B12BC_DayAtTheRaces2P
    /* 80104B3C */ .space 0x04

nonmatching D_80104B40_2B12C0_DayAtTheRaces2P, 0x4

dlabel D_80104B40_2B12C0_DayAtTheRaces2P
    /* 80104B40 */ .space 0x04

nonmatching D_80104B44_2B12C4_DayAtTheRaces2P, 0x4

dlabel D_80104B44_2B12C4_DayAtTheRaces2P
    /* 80104B44 */ .space 0x04

nonmatching D_80104B48_2B12C8_DayAtTheRaces2P, 0x10

dlabel D_80104B48_2B12C8_DayAtTheRaces2P
    /* 80104B48 */ .space 0x10

nonmatching D_80104B58_2B12D8_DayAtTheRaces2P, 0x8

dlabel D_80104B58_2B12D8_DayAtTheRaces2P
    /* 80104B58 */ .space 0x08

nonmatching D_80104B60_2B12E0_DayAtTheRaces2P, 0x10

dlabel D_80104B60_2B12E0_DayAtTheRaces2P
    /* 80104B60 */ .space 0x10

nonmatching D_80104B70_2B12F0_DayAtTheRaces2P, 0x10

dlabel D_80104B70_2B12F0_DayAtTheRaces2P
    /* 80104B70 */ .space 0x10

nonmatching D_80104B80_2B1300_DayAtTheRaces2P, 0x20D0

dlabel D_80104B80_2B1300_DayAtTheRaces2P
    /* 80104B80 */ .space 0x20D0
