.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80104E80_418A50_Credits, 0x4

glabel D_80104E80_418A50_Credits
    /* 80104E80 */ .space 0x04

nonmatching D_80104E84_418A54_Credits, 0x4

glabel D_80104E84_418A54_Credits
    /* 80104E84 */ .space 0x04

nonmatching D_80104E88_418A58_Credits, 0x4

glabel D_80104E88_418A58_Credits
    /* 80104E88 */ .space 0x04

nonmatching D_80104E8C_418A5C_Credits, 0x4

glabel D_80104E8C_418A5C_Credits
    /* 80104E8C */ .space 0x04

nonmatching D_80104E90_418A60_Credits, 0x4

glabel D_80104E90_418A60_Credits
    /* 80104E90 */ .space 0x04

nonmatching D_80104E94_418A64_Credits, 0x4

glabel D_80104E94_418A64_Credits
    /* 80104E94 */ .space 0x04

nonmatching D_80104E98_418A68_Credits, 0x4

glabel D_80104E98_418A68_Credits
    /* 80104E98 */ .space 0x04

nonmatching D_80104E9C_418A6C_Credits, 0x4

glabel D_80104E9C_418A6C_Credits
    /* 80104E9C */ .space 0x04

nonmatching D_80104EA0_418A70_Credits, 0x38

dlabel D_80104EA0_418A70_Credits
    /* 80104EA0 */ .space 0x38

nonmatching D_80104ED8_418AA8_Credits, 0x4

dlabel D_80104ED8_418AA8_Credits
    /* 80104ED8 */ .space 0x04

nonmatching D_80104EDC_418AAC_Credits, 0x6F8

dlabel D_80104EDC_418AAC_Credits
    /* 80104EDC */ .space 0x6F8

nonmatching func_801055D4_4191A4_Credits, 0x84

dlabel func_801055D4_4191A4_Credits
    /* 801055D4 */ .space 0x84

nonmatching func_80105658_419228_Credits, 0x28

dlabel func_80105658_419228_Credits
    /* 80105658 */ .space 0x28

nonmatching func_80105680_419250_Credits, 0x48

dlabel func_80105680_419250_Credits
    /* 80105680 */ .space 0x48

nonmatching func_801056C8_419298_Credits, 0x2CC

dlabel func_801056C8_419298_Credits
    /* 801056C8 */ .space 0x2CC

nonmatching D_80105994_419564_Credits, 0x4

dlabel D_80105994_419564_Credits
    /* 80105994 */ .space 0x04

nonmatching func_80105998_419568_Credits, 0x80

dlabel func_80105998_419568_Credits
    /* 80105998 */ .space 0x80

nonmatching func_80105A18_4195E8_Credits, 0x8

dlabel func_80105A18_4195E8_Credits
    /* 80105A18 */ .space 0x08

nonmatching func_80105A20_4195F0_Credits, 0x8

dlabel func_80105A20_4195F0_Credits
    /* 80105A20 */ .space 0x08

nonmatching func_80105A28_4195F8_Credits, 0x8

dlabel func_80105A28_4195F8_Credits
    /* 80105A28 */ .space 0x08

nonmatching func_80105A30_419600_Credits, 0x80

dlabel func_80105A30_419600_Credits
    /* 80105A30 */ .space 0x80

nonmatching D_80105AB0_419680_Credits, 0x10

dlabel D_80105AB0_419680_Credits
    /* 80105AB0 */ .space 0x10

nonmatching D_80105AC0_419690_Credits, 0x2

dlabel D_80105AC0_419690_Credits
    /* 80105AC0 */ .space 0x02

nonmatching D_80105AC2_419692_Credits, 0x2

dlabel D_80105AC2_419692_Credits
    /* 80105AC2 */ .space 0x02

nonmatching D_80105AC4_419694_Credits, 0x2

dlabel D_80105AC4_419694_Credits
    /* 80105AC4 */ .space 0x02

nonmatching D_80105AC6_419696_Credits, 0x2

dlabel D_80105AC6_419696_Credits
    /* 80105AC6 */ .space 0x02

nonmatching D_80105AC8_419698_Credits, 0x2

dlabel D_80105AC8_419698_Credits
    /* 80105AC8 */ .space 0x02

nonmatching D_80105ACA_41969A_Credits, 0x6

dlabel D_80105ACA_41969A_Credits
    /* 80105ACA */ .space 0x06

nonmatching D_80105AD0_4196A0_Credits, 0x154

dlabel D_80105AD0_4196A0_Credits
    /* 80105AD0 */ .space 0x154

nonmatching D_80105C24_4197F4_Credits, 0x2

dlabel D_80105C24_4197F4_Credits
    /* 80105C24 */ .space 0x02

nonmatching D_80105C26_4197F6_Credits, 0x2

dlabel D_80105C26_4197F6_Credits
    /* 80105C26 */ .space 0x02

nonmatching D_80105C28_4197F8_Credits, 0x2

dlabel D_80105C28_4197F8_Credits
    /* 80105C28 */ .space 0x02

nonmatching D_80105C2A_4197FA_Credits, 0x6

dlabel D_80105C2A_4197FA_Credits
    /* 80105C2A */ .space 0x06

nonmatching D_80105C30_419800_Credits, 0xF0

dlabel D_80105C30_419800_Credits
    /* 80105C30 */ .space 0xF0

nonmatching D_80105D20_4198F0_Credits, 0x80

dlabel D_80105D20_4198F0_Credits
    /* 80105D20 */ .space 0x80

nonmatching D_80105DA0_419970_Credits, 0x10

dlabel D_80105DA0_419970_Credits
    /* 80105DA0 */ .space 0x10

nonmatching D_80105DB0_419980_Credits, 0x8

dlabel D_80105DB0_419980_Credits
    /* 80105DB0 */ .space 0x08

nonmatching D_80105DB8_419988_Credits, 0x18

dlabel D_80105DB8_419988_Credits
    /* 80105DB8 */ .space 0x18

nonmatching D_80105DD0_4199A0_Credits, 0x9B0

dlabel D_80105DD0_4199A0_Credits
    /* 80105DD0 */ .space 0x9B0

nonmatching func_80106780_41A350_Credits, 0xC4

dlabel func_80106780_41A350_Credits
    /* 80106780 */ .space 0xC4

nonmatching func_80106844_41A414_Credits, 0x124

dlabel func_80106844_41A414_Credits
    /* 80106844 */ .space 0x124

nonmatching func_80106968_41A538_Credits, 0x4C

dlabel func_80106968_41A538_Credits
    /* 80106968 */ .space 0x4C

nonmatching func_801069B4_41A584_Credits, 0x18

dlabel func_801069B4_41A584_Credits
    /* 801069B4 */ .space 0x18

nonmatching func_801069CC_41A59C_Credits, 0x1774

dlabel func_801069CC_41A59C_Credits
    /* 801069CC */ .space 0x1774
