.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_801037D0_3616F0_SlotMachine1P, 0x2

dlabel D_801037D0_3616F0_SlotMachine1P
    /* 801037D0 */ .space 0x02

nonmatching D_801037D2_3616F2_SlotMachine1P, 0x2

dlabel D_801037D2_3616F2_SlotMachine1P
    /* 801037D2 */ .space 0x02

nonmatching D_801037D4_3616F4_SlotMachine1P, 0x2

dlabel D_801037D4_3616F4_SlotMachine1P
    /* 801037D4 */ .space 0x02

nonmatching D_801037D6_3616F6_SlotMachine1P, 0x2

dlabel D_801037D6_3616F6_SlotMachine1P
    /* 801037D6 */ .space 0x02

nonmatching D_801037D8_3616F8_SlotMachine1P, 0x8

dlabel D_801037D8_3616F8_SlotMachine1P
    /* 801037D8 */ .space 0x08

nonmatching D_801037E0_361700_SlotMachine1P, 0xC

dlabel D_801037E0_361700_SlotMachine1P
    /* 801037E0 */ .space 0x0C

nonmatching D_801037EC_36170C_SlotMachine1P, 0xC

dlabel D_801037EC_36170C_SlotMachine1P
    /* 801037EC */ .space 0x0C

nonmatching D_801037F8_361718_SlotMachine1P, 0xC

dlabel D_801037F8_361718_SlotMachine1P
    /* 801037F8 */ .space 0x0C

nonmatching D_80103804_361724_SlotMachine1P, 0xC

dlabel D_80103804_361724_SlotMachine1P
    /* 80103804 */ .space 0x0C

nonmatching D_80103810_361730_SlotMachine1P, 0xC

dlabel D_80103810_361730_SlotMachine1P
    /* 80103810 */ .space 0x0C

nonmatching D_8010381C_36173C_SlotMachine1P, 0xC

dlabel D_8010381C_36173C_SlotMachine1P
    /* 8010381C */ .space 0x0C

nonmatching D_80103828_361748_SlotMachine1P, 0xC

dlabel D_80103828_361748_SlotMachine1P
    /* 80103828 */ .space 0x0C

nonmatching D_80103834_361754_SlotMachine1P, 0xC

dlabel D_80103834_361754_SlotMachine1P
    /* 80103834 */ .space 0x0C

nonmatching D_80103840_361760_SlotMachine1P, 0xC

dlabel D_80103840_361760_SlotMachine1P
    /* 80103840 */ .space 0x0C

nonmatching D_8010384C_36176C_SlotMachine1P, 0xC

dlabel D_8010384C_36176C_SlotMachine1P
    /* 8010384C */ .space 0x0C

nonmatching D_80103858_361778_SlotMachine1P, 0xC

dlabel D_80103858_361778_SlotMachine1P
    /* 80103858 */ .space 0x0C

nonmatching D_80103864_361784_SlotMachine1P, 0xC

dlabel D_80103864_361784_SlotMachine1P
    /* 80103864 */ .space 0x0C

nonmatching D_80103870_361790_SlotMachine1P, 0x8

dlabel D_80103870_361790_SlotMachine1P
    /* 80103870 */ .space 0x08

nonmatching D_80103878_361798_SlotMachine1P, 0x8

dlabel D_80103878_361798_SlotMachine1P
    /* 80103878 */ .space 0x08

nonmatching D_80103880_3617A0_SlotMachine1P, 0x4

dlabel D_80103880_3617A0_SlotMachine1P
    /* 80103880 */ .space 0x04

nonmatching D_80103884_3617A4_SlotMachine1P, 0x4

dlabel D_80103884_3617A4_SlotMachine1P
    /* 80103884 */ .space 0x04

nonmatching D_80103888_3617A8_SlotMachine1P, 0x2

dlabel D_80103888_3617A8_SlotMachine1P
    /* 80103888 */ .space 0x02

nonmatching D_8010388A_3617AA_SlotMachine1P, 0x2

dlabel D_8010388A_3617AA_SlotMachine1P
    /* 8010388A */ .space 0x02

nonmatching D_8010388C_3617AC_SlotMachine1P, 0x2

dlabel D_8010388C_3617AC_SlotMachine1P
    /* 8010388C */ .space 0x02

nonmatching D_8010388E_3617AE_SlotMachine1P, 0xFC2

dlabel D_8010388E_3617AE_SlotMachine1P
    /* 8010388E */ .space 0xFC2
