.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80111010_3E4250_TitleScreenAndIntro, 0x4

glabel D_80111010_3E4250_TitleScreenAndIntro
    /* 80111010 */ .space 0x04

nonmatching D_80111014_3E4254_TitleScreenAndIntro, 0x1C

dlabel D_80111014_3E4254_TitleScreenAndIntro
    /* 80111014 */ .space 0x1C

nonmatching D_80111030_3E4270_TitleScreenAndIntro, 0x10

dlabel D_80111030_3E4270_TitleScreenAndIntro
    /* 80111030 */ .space 0x10

nonmatching D_80111040_3E4280_TitleScreenAndIntro, 0x50

dlabel D_80111040_3E4280_TitleScreenAndIntro
    /* 80111040 */ .space 0x50

nonmatching D_80111090_3E42D0_TitleScreenAndIntro, 0x50

dlabel D_80111090_3E42D0_TitleScreenAndIntro
    /* 80111090 */ .space 0x50

nonmatching D_801110E0_3E4320_TitleScreenAndIntro, 0x8

dlabel D_801110E0_3E4320_TitleScreenAndIntro
    /* 801110E0 */ .space 0x08

nonmatching D_801110E8_3E4328_TitleScreenAndIntro, 0x40

dlabel D_801110E8_3E4328_TitleScreenAndIntro
    /* 801110E8 */ .space 0x40

nonmatching D_80111128_3E4368_TitleScreenAndIntro, 0xF0

dlabel D_80111128_3E4368_TitleScreenAndIntro
    /* 80111128 */ .space 0xF0

nonmatching D_80111218_3E4458_TitleScreenAndIntro, 0x8

dlabel D_80111218_3E4458_TitleScreenAndIntro
    /* 80111218 */ .space 0x08

nonmatching D_80111220_3E4460_TitleScreenAndIntro, 0x8

dlabel D_80111220_3E4460_TitleScreenAndIntro
    /* 80111220 */ .space 0x08

nonmatching D_80111228_3E4468_TitleScreenAndIntro, 0x10

dlabel D_80111228_3E4468_TitleScreenAndIntro
    /* 80111228 */ .space 0x10

nonmatching D_80111238_3E4478_TitleScreenAndIntro, 0xC8

dlabel D_80111238_3E4478_TitleScreenAndIntro
    /* 80111238 */ .space 0xC8

nonmatching D_80111300_3E4540_TitleScreenAndIntro, 0x10

dlabel D_80111300_3E4540_TitleScreenAndIntro
    /* 80111300 */ .space 0x10

nonmatching D_80111310_3E4550_TitleScreenAndIntro, 0xD0

dlabel D_80111310_3E4550_TitleScreenAndIntro
    /* 80111310 */ .space 0xD0

nonmatching D_801113E0_3E4620_TitleScreenAndIntro, 0x8

dlabel D_801113E0_3E4620_TitleScreenAndIntro
    /* 801113E0 */ .space 0x08

nonmatching D_801113E8_3E4628_TitleScreenAndIntro, 0x8

dlabel D_801113E8_3E4628_TitleScreenAndIntro
    /* 801113E8 */ .space 0x08

nonmatching D_801113F0_3E4630_TitleScreenAndIntro, 0x8

dlabel D_801113F0_3E4630_TitleScreenAndIntro
    /* 801113F0 */ .space 0x08

nonmatching D_801113F8_3E4638_TitleScreenAndIntro, 0xD4

dlabel D_801113F8_3E4638_TitleScreenAndIntro
    /* 801113F8 */ .space 0xD4

nonmatching D_801114CC_3E470C_TitleScreenAndIntro, 0x8

dlabel D_801114CC_3E470C_TitleScreenAndIntro
    /* 801114CC */ .space 0x08

nonmatching D_801114D4_3E4714_TitleScreenAndIntro, 0x14C

dlabel D_801114D4_3E4714_TitleScreenAndIntro
    /* 801114D4 */ .space 0x14C

nonmatching D_80111620_3E4860_TitleScreenAndIntro, 0x160

dlabel D_80111620_3E4860_TitleScreenAndIntro
    /* 80111620 */ .space 0x160

nonmatching D_80111780_3E49C0_TitleScreenAndIntro, 0x8C

dlabel D_80111780_3E49C0_TitleScreenAndIntro
    /* 80111780 */ .space 0x8C

nonmatching D_8011180C_3E4A4C_TitleScreenAndIntro, 0x8

dlabel D_8011180C_3E4A4C_TitleScreenAndIntro
    /* 8011180C */ .space 0x08

nonmatching D_80111814_3E4A54_TitleScreenAndIntro, 0x50

dlabel D_80111814_3E4A54_TitleScreenAndIntro
    /* 80111814 */ .space 0x50

nonmatching D_80111864_3E4AA4_TitleScreenAndIntro, 0x8

dlabel D_80111864_3E4AA4_TitleScreenAndIntro
    /* 80111864 */ .space 0x08

nonmatching D_8011186C_3E4AAC_TitleScreenAndIntro, 0x8

dlabel D_8011186C_3E4AAC_TitleScreenAndIntro
    /* 8011186C */ .space 0x08

nonmatching D_80111874_3E4AB4_TitleScreenAndIntro, 0x4

dlabel D_80111874_3E4AB4_TitleScreenAndIntro
    /* 80111874 */ .space 0x04

nonmatching D_80111878_3E4AB8_TitleScreenAndIntro, 0x8

dlabel D_80111878_3E4AB8_TitleScreenAndIntro
    /* 80111878 */ .space 0x08

nonmatching D_80111880_3E4AC0_TitleScreenAndIntro, 0x4

dlabel D_80111880_3E4AC0_TitleScreenAndIntro
    /* 80111880 */ .space 0x04

nonmatching D_80111884_3E4AC4_TitleScreenAndIntro, 0x4

dlabel D_80111884_3E4AC4_TitleScreenAndIntro
    /* 80111884 */ .space 0x04

nonmatching D_80111888_3E4AC8_TitleScreenAndIntro, 0x8

dlabel D_80111888_3E4AC8_TitleScreenAndIntro
    /* 80111888 */ .space 0x08

nonmatching D_80111890_3E4AD0_TitleScreenAndIntro, 0x8

dlabel D_80111890_3E4AD0_TitleScreenAndIntro
    /* 80111890 */ .space 0x08

nonmatching D_80111898_3E4AD8_TitleScreenAndIntro, 0x4

dlabel D_80111898_3E4AD8_TitleScreenAndIntro
    /* 80111898 */ .space 0x04

nonmatching D_8011189C_3E4ADC_TitleScreenAndIntro, 0x4

dlabel D_8011189C_3E4ADC_TitleScreenAndIntro
    /* 8011189C */ .space 0x04

nonmatching D_801118A0_3E4AE0_TitleScreenAndIntro, 0x8

dlabel D_801118A0_3E4AE0_TitleScreenAndIntro
    /* 801118A0 */ .space 0x08

nonmatching D_801118A8_3E4AE8_TitleScreenAndIntro, 0x8

dlabel D_801118A8_3E4AE8_TitleScreenAndIntro
    /* 801118A8 */ .space 0x08

nonmatching D_801118B0_3E4AF0_TitleScreenAndIntro, 0x4

dlabel D_801118B0_3E4AF0_TitleScreenAndIntro
    /* 801118B0 */ .space 0x04

nonmatching D_801118B4_3E4AF4_TitleScreenAndIntro, 0x4

dlabel D_801118B4_3E4AF4_TitleScreenAndIntro
    /* 801118B4 */ .space 0x04

nonmatching D_801118B8_3E4AF8_TitleScreenAndIntro, 0x8

dlabel D_801118B8_3E4AF8_TitleScreenAndIntro
    /* 801118B8 */ .space 0x08

nonmatching D_801118C0_3E4B00_TitleScreenAndIntro, 0x8

dlabel D_801118C0_3E4B00_TitleScreenAndIntro
    /* 801118C0 */ .space 0x08

nonmatching D_801118C8_3E4B08_TitleScreenAndIntro, 0x4

dlabel D_801118C8_3E4B08_TitleScreenAndIntro
    /* 801118C8 */ .space 0x04

nonmatching D_801118CC_3E4B0C_TitleScreenAndIntro, 0x4

dlabel D_801118CC_3E4B0C_TitleScreenAndIntro
    /* 801118CC */ .space 0x04

nonmatching D_801118D0_3E4B10_TitleScreenAndIntro, 0x8

dlabel D_801118D0_3E4B10_TitleScreenAndIntro
    /* 801118D0 */ .space 0x08

nonmatching D_801118D8_3E4B18_TitleScreenAndIntro, 0x8

dlabel D_801118D8_3E4B18_TitleScreenAndIntro
    /* 801118D8 */ .space 0x08

nonmatching D_801118E0_3E4B20_TitleScreenAndIntro, 0x4

dlabel D_801118E0_3E4B20_TitleScreenAndIntro
    /* 801118E0 */ .space 0x04

nonmatching D_801118E4_3E4B24_TitleScreenAndIntro, 0x4

dlabel D_801118E4_3E4B24_TitleScreenAndIntro
    /* 801118E4 */ .space 0x04

nonmatching D_801118E8_3E4B28_TitleScreenAndIntro, 0x8

dlabel D_801118E8_3E4B28_TitleScreenAndIntro
    /* 801118E8 */ .space 0x08

nonmatching D_801118F0_3E4B30_TitleScreenAndIntro, 0x8

dlabel D_801118F0_3E4B30_TitleScreenAndIntro
    /* 801118F0 */ .space 0x08

nonmatching D_801118F8_3E4B38_TitleScreenAndIntro, 0x4

dlabel D_801118F8_3E4B38_TitleScreenAndIntro
    /* 801118F8 */ .space 0x04

nonmatching D_801118FC_3E4B3C_TitleScreenAndIntro, 0x4

dlabel D_801118FC_3E4B3C_TitleScreenAndIntro
    /* 801118FC */ .space 0x04

nonmatching D_80111900_3E4B40_TitleScreenAndIntro, 0x8

dlabel D_80111900_3E4B40_TitleScreenAndIntro
    /* 80111900 */ .space 0x08

nonmatching D_80111908_3E4B48_TitleScreenAndIntro, 0x8

dlabel D_80111908_3E4B48_TitleScreenAndIntro
    /* 80111908 */ .space 0x08

nonmatching D_80111910_3E4B50_TitleScreenAndIntro, 0x4

dlabel D_80111910_3E4B50_TitleScreenAndIntro
    /* 80111910 */ .space 0x04

nonmatching D_80111914_3E4B54_TitleScreenAndIntro, 0x4

dlabel D_80111914_3E4B54_TitleScreenAndIntro
    /* 80111914 */ .space 0x04

nonmatching D_80111918_3E4B58_TitleScreenAndIntro, 0x8

dlabel D_80111918_3E4B58_TitleScreenAndIntro
    /* 80111918 */ .space 0x08

nonmatching D_80111920_3E4B60_TitleScreenAndIntro, 0x8

dlabel D_80111920_3E4B60_TitleScreenAndIntro
    /* 80111920 */ .space 0x08

nonmatching D_80111928_3E4B68_TitleScreenAndIntro, 0x4

dlabel D_80111928_3E4B68_TitleScreenAndIntro
    /* 80111928 */ .space 0x04

nonmatching D_8011192C_3E4B6C_TitleScreenAndIntro, 0x4

dlabel D_8011192C_3E4B6C_TitleScreenAndIntro
    /* 8011192C */ .space 0x04

nonmatching D_80111930_3E4B70_TitleScreenAndIntro, 0x4

dlabel D_80111930_3E4B70_TitleScreenAndIntro
    /* 80111930 */ .space 0x04

nonmatching D_80111934_3E4B74_TitleScreenAndIntro, 0x4

dlabel D_80111934_3E4B74_TitleScreenAndIntro
    /* 80111934 */ .space 0x04

nonmatching D_80111938_3E4B78_TitleScreenAndIntro, 0x8

dlabel D_80111938_3E4B78_TitleScreenAndIntro
    /* 80111938 */ .space 0x08

nonmatching D_80111940_3E4B80_TitleScreenAndIntro, 0x4

dlabel D_80111940_3E4B80_TitleScreenAndIntro
    /* 80111940 */ .space 0x04

nonmatching D_80111944_3E4B84_TitleScreenAndIntro, 0x4

dlabel D_80111944_3E4B84_TitleScreenAndIntro
    /* 80111944 */ .space 0x04

nonmatching D_80111948_3E4B88_TitleScreenAndIntro, 0x4

dlabel D_80111948_3E4B88_TitleScreenAndIntro
    /* 80111948 */ .space 0x04

nonmatching D_8011194C_3E4B8C_TitleScreenAndIntro, 0x30

dlabel D_8011194C_3E4B8C_TitleScreenAndIntro
    /* 8011194C */ .space 0x30

nonmatching D_8011197C_3E4BBC_TitleScreenAndIntro, 0x48

dlabel D_8011197C_3E4BBC_TitleScreenAndIntro
    /* 8011197C */ .space 0x48

nonmatching D_801119C4_3E4C04_TitleScreenAndIntro, 0x18

dlabel D_801119C4_3E4C04_TitleScreenAndIntro
    /* 801119C4 */ .space 0x18

nonmatching D_801119DC_3E4C1C_TitleScreenAndIntro, 0x18

dlabel D_801119DC_3E4C1C_TitleScreenAndIntro
    /* 801119DC */ .space 0x18

nonmatching D_801119F4_3E4C34_TitleScreenAndIntro, 0x18

dlabel D_801119F4_3E4C34_TitleScreenAndIntro
    /* 801119F4 */ .space 0x18

nonmatching D_80111A0C_3E4C4C_TitleScreenAndIntro, 0x30

dlabel D_80111A0C_3E4C4C_TitleScreenAndIntro
    /* 80111A0C */ .space 0x30

nonmatching D_80111A3C_3E4C7C_TitleScreenAndIntro, 0x18

dlabel D_80111A3C_3E4C7C_TitleScreenAndIntro
    /* 80111A3C */ .space 0x18

nonmatching D_80111A54_3E4C94_TitleScreenAndIntro, 0x30

dlabel D_80111A54_3E4C94_TitleScreenAndIntro
    /* 80111A54 */ .space 0x30

nonmatching D_80111A84_3E4CC4_TitleScreenAndIntro, 0x18

dlabel D_80111A84_3E4CC4_TitleScreenAndIntro
    /* 80111A84 */ .space 0x18

nonmatching D_80111A9C_3E4CDC_TitleScreenAndIntro, 0x30

dlabel D_80111A9C_3E4CDC_TitleScreenAndIntro
    /* 80111A9C */ .space 0x30

nonmatching D_80111ACC_3E4D0C_TitleScreenAndIntro, 0x8

dlabel D_80111ACC_3E4D0C_TitleScreenAndIntro
    /* 80111ACC */ .space 0x08

nonmatching D_80111AD4_3E4D14_TitleScreenAndIntro, 0x4

dlabel D_80111AD4_3E4D14_TitleScreenAndIntro
    /* 80111AD4 */ .space 0x04

nonmatching D_80111AD8_3E4D18_TitleScreenAndIntro, 0x8

dlabel D_80111AD8_3E4D18_TitleScreenAndIntro
    /* 80111AD8 */ .space 0x08

nonmatching D_80111AE0_3E4D20_TitleScreenAndIntro, 0x4

dlabel D_80111AE0_3E4D20_TitleScreenAndIntro
    /* 80111AE0 */ .space 0x04

nonmatching D_80111AE4_3E4D24_TitleScreenAndIntro, 0xC

dlabel D_80111AE4_3E4D24_TitleScreenAndIntro
    /* 80111AE4 */ .space 0x0C

nonmatching D_80111AF0_3E4D30_TitleScreenAndIntro, 0x4

dlabel D_80111AF0_3E4D30_TitleScreenAndIntro
    /* 80111AF0 */ .space 0x04

nonmatching D_80111AF4_3E4D34_TitleScreenAndIntro, 0x4C

dlabel D_80111AF4_3E4D34_TitleScreenAndIntro
    /* 80111AF4 */ .space 0x4C

nonmatching jtbl_80111B40_3E4D80_TitleScreenAndIntro, 0x30

dlabel jtbl_80111B40_3E4D80_TitleScreenAndIntro
    /* 80111B40 */ .space 0x30

nonmatching jtbl_80111B70_3E4DB0_TitleScreenAndIntro, 0x30

dlabel jtbl_80111B70_3E4DB0_TitleScreenAndIntro
    /* 80111B70 */ .space 0x30

nonmatching D_80111BA0_3E4DE0_TitleScreenAndIntro, 0x8

dlabel D_80111BA0_3E4DE0_TitleScreenAndIntro
    /* 80111BA0 */ .space 0x08

nonmatching D_80111BA8_3E4DE8_TitleScreenAndIntro, 0x8

dlabel D_80111BA8_3E4DE8_TitleScreenAndIntro
    /* 80111BA8 */ .space 0x08

nonmatching D_80111BB0_3E4DF0_TitleScreenAndIntro, 0x8

dlabel D_80111BB0_3E4DF0_TitleScreenAndIntro
    /* 80111BB0 */ .space 0x08

nonmatching D_80111BB8_3E4DF8_TitleScreenAndIntro, 0x8

dlabel D_80111BB8_3E4DF8_TitleScreenAndIntro
    /* 80111BB8 */ .space 0x08

nonmatching D_80111BC0_3E4E00_TitleScreenAndIntro, 0x8

dlabel D_80111BC0_3E4E00_TitleScreenAndIntro
    /* 80111BC0 */ .space 0x08

nonmatching D_80111BC8_3E4E08_TitleScreenAndIntro, 0x74

dlabel D_80111BC8_3E4E08_TitleScreenAndIntro
    /* 80111BC8 */ .space 0x74

nonmatching D_80111C3C_3E4E7C_TitleScreenAndIntro, 0x4

dlabel D_80111C3C_3E4E7C_TitleScreenAndIntro
    /* 80111C3C */ .space 0x04

nonmatching D_80111C40_3E4E80_TitleScreenAndIntro, 0x8

dlabel D_80111C40_3E4E80_TitleScreenAndIntro
    /* 80111C40 */ .space 0x08

nonmatching D_80111C48_3E4E88_TitleScreenAndIntro, 0x8

dlabel D_80111C48_3E4E88_TitleScreenAndIntro
    /* 80111C48 */ .space 0x08

nonmatching D_80111C50_3E4E90_TitleScreenAndIntro, 0x8

dlabel D_80111C50_3E4E90_TitleScreenAndIntro
    /* 80111C50 */ .space 0x08

nonmatching D_80111C58_3E4E98_TitleScreenAndIntro, 0x14

dlabel D_80111C58_3E4E98_TitleScreenAndIntro
    /* 80111C58 */ .space 0x14

nonmatching D_80111C6C_3E4EAC_TitleScreenAndIntro, 0x14

dlabel D_80111C6C_3E4EAC_TitleScreenAndIntro
    /* 80111C6C */ .space 0x14

nonmatching D_80111C80_3E4EC0_TitleScreenAndIntro, 0x14

dlabel D_80111C80_3E4EC0_TitleScreenAndIntro
    /* 80111C80 */ .space 0x14

nonmatching D_80111C94_3E4ED4_TitleScreenAndIntro, 0x14

dlabel D_80111C94_3E4ED4_TitleScreenAndIntro
    /* 80111C94 */ .space 0x14

nonmatching D_80111CA8_3E4EE8_TitleScreenAndIntro, 0x14

dlabel D_80111CA8_3E4EE8_TitleScreenAndIntro
    /* 80111CA8 */ .space 0x14

nonmatching D_80111CBC_3E4EFC_TitleScreenAndIntro, 0x14

dlabel D_80111CBC_3E4EFC_TitleScreenAndIntro
    /* 80111CBC */ .space 0x14

nonmatching D_80111CD0_3E4F10_TitleScreenAndIntro, 0x10

dlabel D_80111CD0_3E4F10_TitleScreenAndIntro
    /* 80111CD0 */ .space 0x10

nonmatching D_80111CE0_3E4F20_TitleScreenAndIntro, 0x18

dlabel D_80111CE0_3E4F20_TitleScreenAndIntro
    /* 80111CE0 */ .space 0x18

nonmatching D_80111CF8_3E4F38_TitleScreenAndIntro, 0x8

dlabel D_80111CF8_3E4F38_TitleScreenAndIntro
    /* 80111CF8 */ .space 0x08

nonmatching D_80111D00_3E4F40_TitleScreenAndIntro, 0x8

dlabel D_80111D00_3E4F40_TitleScreenAndIntro
    /* 80111D00 */ .space 0x08

nonmatching D_80111D08_3E4F48_TitleScreenAndIntro, 0x8

dlabel D_80111D08_3E4F48_TitleScreenAndIntro
    /* 80111D08 */ .space 0x08

nonmatching D_80111D10_3E4F50_TitleScreenAndIntro, 0x8

dlabel D_80111D10_3E4F50_TitleScreenAndIntro
    /* 80111D10 */ .space 0x08

nonmatching D_80111D18_3E4F58_TitleScreenAndIntro, 0xC

dlabel D_80111D18_3E4F58_TitleScreenAndIntro
    /* 80111D18 */ .space 0x0C

nonmatching D_80111D24_3E4F64_TitleScreenAndIntro, 0xC

dlabel D_80111D24_3E4F64_TitleScreenAndIntro
    /* 80111D24 */ .space 0x0C

nonmatching D_80111D30_3E4F70_TitleScreenAndIntro, 0x10

dlabel D_80111D30_3E4F70_TitleScreenAndIntro
    /* 80111D30 */ .space 0x10

nonmatching D_80111D40_3E4F80_TitleScreenAndIntro, 0x4

dlabel D_80111D40_3E4F80_TitleScreenAndIntro
    /* 80111D40 */ .space 0x04

nonmatching D_80111D44_3E4F84_TitleScreenAndIntro, 0x4

dlabel D_80111D44_3E4F84_TitleScreenAndIntro
    /* 80111D44 */ .space 0x04

nonmatching D_80111D48_3E4F88_TitleScreenAndIntro, 0x2

dlabel D_80111D48_3E4F88_TitleScreenAndIntro
    /* 80111D48 */ .space 0x02

nonmatching D_80111D4A_3E4F8A_TitleScreenAndIntro, 0x6

dlabel D_80111D4A_3E4F8A_TitleScreenAndIntro
    /* 80111D4A */ .space 0x06

nonmatching D_80111D50_3E4F90_TitleScreenAndIntro, 0x2

dlabel D_80111D50_3E4F90_TitleScreenAndIntro
    /* 80111D50 */ .space 0x02

nonmatching D_80111D52_3E4F92_TitleScreenAndIntro, 0x2

dlabel D_80111D52_3E4F92_TitleScreenAndIntro
    /* 80111D52 */ .space 0x02

nonmatching D_80111D54_3E4F94_TitleScreenAndIntro, 0x4

dlabel D_80111D54_3E4F94_TitleScreenAndIntro
    /* 80111D54 */ .space 0x04

nonmatching D_80111D58_3E4F98_TitleScreenAndIntro, 0x4

dlabel D_80111D58_3E4F98_TitleScreenAndIntro
    /* 80111D58 */ .space 0x04

nonmatching D_80111D5C_3E4F9C_TitleScreenAndIntro, 0x4

dlabel D_80111D5C_3E4F9C_TitleScreenAndIntro
    /* 80111D5C */ .space 0x04

nonmatching D_80111D60_3E4FA0_TitleScreenAndIntro, 0x2

dlabel D_80111D60_3E4FA0_TitleScreenAndIntro
    /* 80111D60 */ .space 0x02

nonmatching D_80111D62_3E4FA2_TitleScreenAndIntro, 0x2

dlabel D_80111D62_3E4FA2_TitleScreenAndIntro
    /* 80111D62 */ .space 0x02

nonmatching D_80111D64_3E4FA4_TitleScreenAndIntro, 0x4

dlabel D_80111D64_3E4FA4_TitleScreenAndIntro
    /* 80111D64 */ .space 0x04

nonmatching D_80111D68_3E4FA8_TitleScreenAndIntro, 0x4

dlabel D_80111D68_3E4FA8_TitleScreenAndIntro
    /* 80111D68 */ .space 0x04

nonmatching D_80111D6C_3E4FAC_TitleScreenAndIntro, 0x4

dlabel D_80111D6C_3E4FAC_TitleScreenAndIntro
    /* 80111D6C */ .space 0x04

nonmatching D_80111D70_3E4FB0_TitleScreenAndIntro, 0x8

dlabel D_80111D70_3E4FB0_TitleScreenAndIntro
    /* 80111D70 */ .space 0x08

nonmatching D_80111D78_3E4FB8_TitleScreenAndIntro, 0x4

dlabel D_80111D78_3E4FB8_TitleScreenAndIntro
    /* 80111D78 */ .space 0x04

nonmatching D_80111D7C_3E4FBC_TitleScreenAndIntro, 0x4

dlabel D_80111D7C_3E4FBC_TitleScreenAndIntro
    /* 80111D7C */ .space 0x04

nonmatching D_80111D80_3E4FC0_TitleScreenAndIntro, 0x4

dlabel D_80111D80_3E4FC0_TitleScreenAndIntro
    /* 80111D80 */ .space 0x04

nonmatching D_80111D84_3E4FC4_TitleScreenAndIntro, 0x4

dlabel D_80111D84_3E4FC4_TitleScreenAndIntro
    /* 80111D84 */ .space 0x04

nonmatching D_80111D88_3E4FC8_TitleScreenAndIntro, 0x4

dlabel D_80111D88_3E4FC8_TitleScreenAndIntro
    /* 80111D88 */ .space 0x04

nonmatching D_80111D8C_3E4FCC_TitleScreenAndIntro, 0x4

dlabel D_80111D8C_3E4FCC_TitleScreenAndIntro
    /* 80111D8C */ .space 0x04

nonmatching D_80111D90_3E4FD0_TitleScreenAndIntro, 0x4

dlabel D_80111D90_3E4FD0_TitleScreenAndIntro
    /* 80111D90 */ .space 0x04

nonmatching D_80111D94_3E4FD4_TitleScreenAndIntro, 0x4

dlabel D_80111D94_3E4FD4_TitleScreenAndIntro
    /* 80111D94 */ .space 0x04

nonmatching D_80111D98_3E4FD8_TitleScreenAndIntro, 0x60

dlabel D_80111D98_3E4FD8_TitleScreenAndIntro
    /* 80111D98 */ .space 0x60

nonmatching D_80111DF8_3E5038_TitleScreenAndIntro, 0x2

dlabel D_80111DF8_3E5038_TitleScreenAndIntro
    /* 80111DF8 */ .space 0x02

nonmatching D_80111DFA_3E503A_TitleScreenAndIntro, 0x2

dlabel D_80111DFA_3E503A_TitleScreenAndIntro
    /* 80111DFA */ .space 0x02

nonmatching D_80111DFC_3E503C_TitleScreenAndIntro, 0x6

dlabel D_80111DFC_3E503C_TitleScreenAndIntro
    /* 80111DFC */ .space 0x06

nonmatching D_80111E02_3E5042_TitleScreenAndIntro, 0x4

dlabel D_80111E02_3E5042_TitleScreenAndIntro
    /* 80111E02 */ .space 0x04

nonmatching D_80111E06_3E5046_TitleScreenAndIntro, 0x2

dlabel D_80111E06_3E5046_TitleScreenAndIntro
    /* 80111E06 */ .space 0x02

nonmatching D_80111E08_3E5048_TitleScreenAndIntro, 0x2

dlabel D_80111E08_3E5048_TitleScreenAndIntro
    /* 80111E08 */ .space 0x02

nonmatching D_80111E0A_3E504A_TitleScreenAndIntro, 0x2

dlabel D_80111E0A_3E504A_TitleScreenAndIntro
    /* 80111E0A */ .space 0x02

nonmatching D_80111E0C_3E504C_TitleScreenAndIntro, 0x2

dlabel D_80111E0C_3E504C_TitleScreenAndIntro
    /* 80111E0C */ .space 0x02

nonmatching D_80111E0E_3E504E_TitleScreenAndIntro, 0x4

dlabel D_80111E0E_3E504E_TitleScreenAndIntro
    /* 80111E0E */ .space 0x04

nonmatching D_80111E12_3E5052_TitleScreenAndIntro, 0x4

dlabel D_80111E12_3E5052_TitleScreenAndIntro
    /* 80111E12 */ .space 0x04

nonmatching D_80111E16_3E5056_TitleScreenAndIntro, 0x22

dlabel D_80111E16_3E5056_TitleScreenAndIntro
    /* 80111E16 */ .space 0x22

nonmatching D_80111E38_3E5078_TitleScreenAndIntro, 0x38

dlabel D_80111E38_3E5078_TitleScreenAndIntro
    /* 80111E38 */ .space 0x38

nonmatching D_80111E70_3E50B0_TitleScreenAndIntro, 0xA

dlabel D_80111E70_3E50B0_TitleScreenAndIntro
    /* 80111E70 */ .space 0x0A

nonmatching D_80111E7A_3E50BA_TitleScreenAndIntro, 0x17E

dlabel D_80111E7A_3E50BA_TitleScreenAndIntro
    /* 80111E7A */ .space 0x17E

nonmatching D_80111FF8_3E5238_TitleScreenAndIntro, 0x8

dlabel D_80111FF8_3E5238_TitleScreenAndIntro
    /* 80111FF8 */ .space 0x08

nonmatching D_80112000_3E5240_TitleScreenAndIntro, 0x10

dlabel D_80112000_3E5240_TitleScreenAndIntro
    /* 80112000 */ .space 0x10

nonmatching D_80112010_3E5250_TitleScreenAndIntro, 0x10

dlabel D_80112010_3E5250_TitleScreenAndIntro
    /* 80112010 */ .space 0x10

nonmatching D_80112020_3E5260_TitleScreenAndIntro, 0x10

dlabel D_80112020_3E5260_TitleScreenAndIntro
    /* 80112020 */ .space 0x10

nonmatching D_80112030_3E5270_TitleScreenAndIntro, 0x30

dlabel D_80112030_3E5270_TitleScreenAndIntro
    /* 80112030 */ .space 0x30

nonmatching D_80112060_3E52A0_TitleScreenAndIntro, 0x4

dlabel D_80112060_3E52A0_TitleScreenAndIntro
    /* 80112060 */ .space 0x04

nonmatching D_80112064_3E52A4_TitleScreenAndIntro, 0x4

dlabel D_80112064_3E52A4_TitleScreenAndIntro
    /* 80112064 */ .space 0x04

nonmatching D_80112068_3E52A8_TitleScreenAndIntro, 0x4

dlabel D_80112068_3E52A8_TitleScreenAndIntro
    /* 80112068 */ .space 0x04

nonmatching D_8011206C_3E52AC_TitleScreenAndIntro, 0x4

dlabel D_8011206C_3E52AC_TitleScreenAndIntro
    /* 8011206C */ .space 0x04

nonmatching D_80112070_3E52B0_TitleScreenAndIntro, 0x4

dlabel D_80112070_3E52B0_TitleScreenAndIntro
    /* 80112070 */ .space 0x04

nonmatching D_80112074_3E52B4_TitleScreenAndIntro, 0xD0

dlabel D_80112074_3E52B4_TitleScreenAndIntro
    /* 80112074 */ .space 0xD0

nonmatching D_80112144_3E5384_TitleScreenAndIntro, 0x4

dlabel D_80112144_3E5384_TitleScreenAndIntro
    /* 80112144 */ .space 0x04

nonmatching D_80112148_3E5388_TitleScreenAndIntro, 0x514

dlabel D_80112148_3E5388_TitleScreenAndIntro
    /* 80112148 */ .space 0x514

nonmatching D_8011265C_3E589C_TitleScreenAndIntro, 0x4

dlabel D_8011265C_3E589C_TitleScreenAndIntro
    /* 8011265C */ .space 0x04

nonmatching D_80112660_3E58A0_TitleScreenAndIntro, 0x8

dlabel D_80112660_3E58A0_TitleScreenAndIntro
    /* 80112660 */ .space 0x08

nonmatching D_80112668_3E58A8_TitleScreenAndIntro, 0x10

dlabel D_80112668_3E58A8_TitleScreenAndIntro
    /* 80112668 */ .space 0x10

nonmatching D_80112678_3E58B8_TitleScreenAndIntro, 0x14

dlabel D_80112678_3E58B8_TitleScreenAndIntro
    /* 80112678 */ .space 0x14

nonmatching D_8011268C_3E58CC_TitleScreenAndIntro, 0x8

dlabel D_8011268C_3E58CC_TitleScreenAndIntro
    /* 8011268C */ .space 0x08

nonmatching D_80112694_3E58D4_TitleScreenAndIntro, 0x120C

dlabel D_80112694_3E58D4_TitleScreenAndIntro
    /* 80112694 */ .space 0x120C

nonmatching D_801138A0_3E6AE0_TitleScreenAndIntro, 0xCCA0

dlabel D_801138A0_3E6AE0_TitleScreenAndIntro
    /* 801138A0 */ .space 0xCCA0
