.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_801065E0_1B8DF0_SpeedHikers, 0x4

glabel D_801065E0_1B8DF0_SpeedHikers
    /* 801065E0 */ .space 0x04

nonmatching D_801065E4_1B8DF4_SpeedHikers, 0x4

glabel D_801065E4_1B8DF4_SpeedHikers
    /* 801065E4 */ .space 0x04

nonmatching D_801065E8_1B8DF8_SpeedHikers, 0x4

glabel D_801065E8_1B8DF8_SpeedHikers
    /* 801065E8 */ .space 0x04

nonmatching D_801065EC_1B8DFC_SpeedHikers, 0x4

dlabel D_801065EC_1B8DFC_SpeedHikers
    /* 801065EC */ .space 0x04

nonmatching D_801065F0_1B8E00_SpeedHikers, 0x4

dlabel D_801065F0_1B8E00_SpeedHikers
    /* 801065F0 */ .space 0x04

nonmatching D_801065F4_1B8E04_SpeedHikers, 0x4C

dlabel D_801065F4_1B8E04_SpeedHikers
    /* 801065F4 */ .space 0x4C

nonmatching D_80106640_1B8E50_SpeedHikers, 0x4

dlabel D_80106640_1B8E50_SpeedHikers
    /* 80106640 */ .space 0x04

nonmatching D_80106644_1B8E54_SpeedHikers, 0x4

dlabel D_80106644_1B8E54_SpeedHikers
    /* 80106644 */ .space 0x04

nonmatching D_80106648_1B8E58_SpeedHikers, 0x40

dlabel D_80106648_1B8E58_SpeedHikers
    /* 80106648 */ .space 0x40

nonmatching D_80106688_1B8E98_SpeedHikers, 0x2

dlabel D_80106688_1B8E98_SpeedHikers
    /* 80106688 */ .space 0x02

nonmatching D_8010668A_1B8E9A_SpeedHikers, 0x2

dlabel D_8010668A_1B8E9A_SpeedHikers
    /* 8010668A */ .space 0x02

nonmatching D_8010668C_1B8E9C_SpeedHikers, 0x4

dlabel D_8010668C_1B8E9C_SpeedHikers
    /* 8010668C */ .space 0x04

nonmatching D_80106690_1B8EA0_SpeedHikers, 0x64

dlabel D_80106690_1B8EA0_SpeedHikers
    /* 80106690 */ .space 0x64

nonmatching D_801066F4_1B8F04_SpeedHikers, 0xC

dlabel D_801066F4_1B8F04_SpeedHikers
    /* 801066F4 */ .space 0x0C

nonmatching D_80106700_1B8F10_SpeedHikers, 0x10

dlabel D_80106700_1B8F10_SpeedHikers
    /* 80106700 */ .space 0x10

nonmatching D_80106710_1B8F20_SpeedHikers, 0xC

dlabel D_80106710_1B8F20_SpeedHikers
    /* 80106710 */ .space 0x0C

nonmatching D_8010671C_1B8F2C_SpeedHikers, 0x10

dlabel D_8010671C_1B8F2C_SpeedHikers
    /* 8010671C */ .space 0x10

nonmatching D_8010672C_1B8F3C_SpeedHikers, 0xC

dlabel D_8010672C_1B8F3C_SpeedHikers
    /* 8010672C */ .space 0x0C

nonmatching D_80106738_1B8F48_SpeedHikers, 0x10

dlabel D_80106738_1B8F48_SpeedHikers
    /* 80106738 */ .space 0x10

nonmatching D_80106748_1B8F58_SpeedHikers, 0xC

dlabel D_80106748_1B8F58_SpeedHikers
    /* 80106748 */ .space 0x0C

nonmatching D_80106754_1B8F64_SpeedHikers, 0x10

dlabel D_80106754_1B8F64_SpeedHikers
    /* 80106754 */ .space 0x10

nonmatching D_80106764_1B8F74_SpeedHikers, 0x10

dlabel D_80106764_1B8F74_SpeedHikers
    /* 80106764 */ .space 0x10

nonmatching D_80106774_1B8F84_SpeedHikers, 0xC

dlabel D_80106774_1B8F84_SpeedHikers
    /* 80106774 */ .space 0x0C

nonmatching D_80106780_1B8F90_SpeedHikers, 0xC

dlabel D_80106780_1B8F90_SpeedHikers
    /* 80106780 */ .space 0x0C

nonmatching D_8010678C_1B8F9C_SpeedHikers, 0x2C0

dlabel D_8010678C_1B8F9C_SpeedHikers
    /* 8010678C */ .space 0x2C0

nonmatching D_80106A4C_1B925C_SpeedHikers, 0x10

dlabel D_80106A4C_1B925C_SpeedHikers
    /* 80106A4C */ .space 0x10

nonmatching D_80106A5C_1B926C_SpeedHikers, 0x10

dlabel D_80106A5C_1B926C_SpeedHikers
    /* 80106A5C */ .space 0x10

nonmatching D_80106A6C_1B927C_SpeedHikers, 0x10

dlabel D_80106A6C_1B927C_SpeedHikers
    /* 80106A6C */ .space 0x10

nonmatching D_80106A7C_1B928C_SpeedHikers, 0x4

dlabel D_80106A7C_1B928C_SpeedHikers
    /* 80106A7C */ .space 0x04

nonmatching D_80106A80_1B9290_SpeedHikers, 0x4

dlabel D_80106A80_1B9290_SpeedHikers
    /* 80106A80 */ .space 0x04

nonmatching D_80106A84_1B9294_SpeedHikers, 0x10

dlabel D_80106A84_1B9294_SpeedHikers
    /* 80106A84 */ .space 0x10

nonmatching D_80106A94_1B92A4_SpeedHikers, 0x14

dlabel D_80106A94_1B92A4_SpeedHikers
    /* 80106A94 */ .space 0x14

nonmatching D_80106AA8_1B92B8_SpeedHikers, 0x18

dlabel D_80106AA8_1B92B8_SpeedHikers
    /* 80106AA8 */ .space 0x18

nonmatching D_80106AC0_1B92D0_SpeedHikers, 0x10

dlabel D_80106AC0_1B92D0_SpeedHikers
    /* 80106AC0 */ .space 0x10

nonmatching D_80106AD0_1B92E0_SpeedHikers, 0x10

dlabel D_80106AD0_1B92E0_SpeedHikers
    /* 80106AD0 */ .space 0x10

nonmatching D_80106AE0_1B92F0_SpeedHikers, 0x1

dlabel D_80106AE0_1B92F0_SpeedHikers
    /* 80106AE0 */ .space 0x01

nonmatching D_80106AE1_1B92F1_SpeedHikers, 0x1

dlabel D_80106AE1_1B92F1_SpeedHikers
    /* 80106AE1 */ .space 0x01

nonmatching D_80106AE2_1B92F2_SpeedHikers, 0x1

dlabel D_80106AE2_1B92F2_SpeedHikers
    /* 80106AE2 */ .space 0x01

nonmatching D_80106AE3_1B92F3_SpeedHikers, 0xD

dlabel D_80106AE3_1B92F3_SpeedHikers
    /* 80106AE3 */ .space 0x0D

nonmatching D_80106AF0_1B9300_SpeedHikers, 0x18

dlabel D_80106AF0_1B9300_SpeedHikers
    /* 80106AF0 */ .space 0x18

nonmatching D_80106B08_1B9318_SpeedHikers, 0x4

dlabel D_80106B08_1B9318_SpeedHikers
    /* 80106B08 */ .space 0x04

nonmatching D_80106B0C_1B931C_SpeedHikers, 0x8C

dlabel D_80106B0C_1B931C_SpeedHikers
    /* 80106B0C */ .space 0x8C

nonmatching D_80106B98_1B93A8_SpeedHikers, 0xC

dlabel D_80106B98_1B93A8_SpeedHikers
    /* 80106B98 */ .space 0x0C

nonmatching D_80106BA4_1B93B4_SpeedHikers, 0x14

dlabel D_80106BA4_1B93B4_SpeedHikers
    /* 80106BA4 */ .space 0x14

nonmatching D_80106BB8_1B93C8_SpeedHikers, 0x34

dlabel D_80106BB8_1B93C8_SpeedHikers
    /* 80106BB8 */ .space 0x34

nonmatching D_80106BEC_1B93FC_SpeedHikers, 0x2

dlabel D_80106BEC_1B93FC_SpeedHikers
    /* 80106BEC */ .space 0x02

nonmatching D_80106BEE_1B93FE_SpeedHikers, 0x2

dlabel D_80106BEE_1B93FE_SpeedHikers
    /* 80106BEE */ .space 0x02

nonmatching D_80106BF0_1B9400_SpeedHikers, 0x2

dlabel D_80106BF0_1B9400_SpeedHikers
    /* 80106BF0 */ .space 0x02

nonmatching D_80106BF2_1B9402_SpeedHikers, 0x2

dlabel D_80106BF2_1B9402_SpeedHikers
    /* 80106BF2 */ .space 0x02

nonmatching D_80106BF4_1B9404_SpeedHikers, 0x2

dlabel D_80106BF4_1B9404_SpeedHikers
    /* 80106BF4 */ .space 0x02

nonmatching D_80106BF6_1B9406_SpeedHikers, 0x2

dlabel D_80106BF6_1B9406_SpeedHikers
    /* 80106BF6 */ .space 0x02

nonmatching D_80106BF8_1B9408_SpeedHikers, 0x2

dlabel D_80106BF8_1B9408_SpeedHikers
    /* 80106BF8 */ .space 0x02

nonmatching D_80106BFA_1B940A_SpeedHikers, 0x2

dlabel D_80106BFA_1B940A_SpeedHikers
    /* 80106BFA */ .space 0x02

nonmatching D_80106BFC_1B940C_SpeedHikers, 0x4

dlabel D_80106BFC_1B940C_SpeedHikers
    /* 80106BFC */ .space 0x04

nonmatching D_80106C00_1B9410_SpeedHikers, 0x4

dlabel D_80106C00_1B9410_SpeedHikers
    /* 80106C00 */ .space 0x04

nonmatching D_80106C04_1B9414_SpeedHikers, 0x1

dlabel D_80106C04_1B9414_SpeedHikers
    /* 80106C04 */ .space 0x01

nonmatching D_80106C05_1B9415_SpeedHikers, 0x1

dlabel D_80106C05_1B9415_SpeedHikers
    /* 80106C05 */ .space 0x01

nonmatching D_80106C06_1B9416_SpeedHikers, 0x2

dlabel D_80106C06_1B9416_SpeedHikers
    /* 80106C06 */ .space 0x02

nonmatching D_80106C08_1B9418_SpeedHikers, 0x4

dlabel D_80106C08_1B9418_SpeedHikers
    /* 80106C08 */ .space 0x04

nonmatching D_80106C0C_1B941C_SpeedHikers, 0x4

dlabel D_80106C0C_1B941C_SpeedHikers
    /* 80106C0C */ .space 0x04

nonmatching D_80106C10_1B9420_SpeedHikers, 0x14

dlabel D_80106C10_1B9420_SpeedHikers
    /* 80106C10 */ .space 0x14

nonmatching D_80106C24_1B9434_SpeedHikers, 0x1C

dlabel D_80106C24_1B9434_SpeedHikers
    /* 80106C24 */ .space 0x1C

nonmatching jtbl_80106C40_1B9450_SpeedHikers, 0x28

dlabel jtbl_80106C40_1B9450_SpeedHikers
    /* 80106C40 */ .space 0x28

nonmatching jtbl_80106C68_1B9478_SpeedHikers, 0x18

dlabel jtbl_80106C68_1B9478_SpeedHikers
    /* 80106C68 */ .space 0x18

nonmatching jtbl_80106C80_1B9490_SpeedHikers, 0x20

dlabel jtbl_80106C80_1B9490_SpeedHikers
    /* 80106C80 */ .space 0x20

nonmatching D_80106CA0_1B94B0_SpeedHikers, 0x4

dlabel D_80106CA0_1B94B0_SpeedHikers
    /* 80106CA0 */ .space 0x04

nonmatching D_80106CA4_1B94B4_SpeedHikers, 0x14

dlabel D_80106CA4_1B94B4_SpeedHikers
    /* 80106CA4 */ .space 0x14

nonmatching D_80106CB8_1B94C8_SpeedHikers, 0x4

dlabel D_80106CB8_1B94C8_SpeedHikers
    /* 80106CB8 */ .space 0x04

nonmatching D_80106CBC_1B94CC_SpeedHikers, 0x4

dlabel D_80106CBC_1B94CC_SpeedHikers
    /* 80106CBC */ .space 0x04

nonmatching D_80106CC0_1B94D0_SpeedHikers, 0x4

dlabel D_80106CC0_1B94D0_SpeedHikers
    /* 80106CC0 */ .space 0x04

nonmatching D_80106CC4_1B94D4_SpeedHikers, 0x34

dlabel D_80106CC4_1B94D4_SpeedHikers
    /* 80106CC4 */ .space 0x34

nonmatching D_80106CF8_1B9508_SpeedHikers, 0x8

dlabel D_80106CF8_1B9508_SpeedHikers
    /* 80106CF8 */ .space 0x08

nonmatching D_80106D00_1B9510_SpeedHikers, 0x130

dlabel D_80106D00_1B9510_SpeedHikers
    /* 80106D00 */ .space 0x130

nonmatching D_80106E30_1B9640_SpeedHikers, 0x70

dlabel D_80106E30_1B9640_SpeedHikers
    /* 80106E30 */ .space 0x70

nonmatching D_80106EA0_1B96B0_SpeedHikers, 0x10

dlabel D_80106EA0_1B96B0_SpeedHikers
    /* 80106EA0 */ .space 0x10

nonmatching D_80106EB0_1B96C0_SpeedHikers, 0x2

dlabel D_80106EB0_1B96C0_SpeedHikers
    /* 80106EB0 */ .space 0x02

nonmatching D_80106EB2_1B96C2_SpeedHikers, 0x2

dlabel D_80106EB2_1B96C2_SpeedHikers
    /* 80106EB2 */ .space 0x02

nonmatching D_80106EB4_1B96C4_SpeedHikers, 0x4

dlabel D_80106EB4_1B96C4_SpeedHikers
    /* 80106EB4 */ .space 0x04

nonmatching D_80106EB8_1B96C8_SpeedHikers, 0x4

dlabel D_80106EB8_1B96C8_SpeedHikers
    /* 80106EB8 */ .space 0x04

nonmatching D_80106EBC_1B96CC_SpeedHikers, 0x4

dlabel D_80106EBC_1B96CC_SpeedHikers
    /* 80106EBC */ .space 0x04

nonmatching D_80106EC0_1B96D0_SpeedHikers, 0x2

dlabel D_80106EC0_1B96D0_SpeedHikers
    /* 80106EC0 */ .space 0x02

nonmatching D_80106EC2_1B96D2_SpeedHikers, 0x4

dlabel D_80106EC2_1B96D2_SpeedHikers
    /* 80106EC2 */ .space 0x04

nonmatching D_80106EC6_1B96D6_SpeedHikers, 0x2

dlabel D_80106EC6_1B96D6_SpeedHikers
    /* 80106EC6 */ .space 0x02

nonmatching D_80106EC8_1B96D8_SpeedHikers, 0x2

dlabel D_80106EC8_1B96D8_SpeedHikers
    /* 80106EC8 */ .space 0x02

nonmatching D_80106ECA_1B96DA_SpeedHikers, 0x1

dlabel D_80106ECA_1B96DA_SpeedHikers
    /* 80106ECA */ .space 0x01

nonmatching D_80106ECB_1B96DB_SpeedHikers, 0x3BB5

dlabel D_80106ECB_1B96DB_SpeedHikers
    /* 80106ECB */ .space 0x3BB5
