.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80108D40_1675A0_BobOmbBarrage, 0x18

dlabel D_80108D40_1675A0_BobOmbBarrage
    /* 80108D40 */ .space 0x18

nonmatching D_80108D58_1675B8_BobOmbBarrage, 0x194

dlabel D_80108D58_1675B8_BobOmbBarrage
    /* 80108D58 */ .space 0x194

nonmatching D_80108EEC_16774C_BobOmbBarrage, 0x1C

dlabel D_80108EEC_16774C_BobOmbBarrage
    /* 80108EEC */ .space 0x1C

nonmatching D_80108F08_167768_BobOmbBarrage, 0x18

dlabel D_80108F08_167768_BobOmbBarrage
    /* 80108F08 */ .space 0x18

nonmatching D_80108F20_167780_BobOmbBarrage, 0x40

dlabel D_80108F20_167780_BobOmbBarrage
    /* 80108F20 */ .space 0x40

nonmatching D_80108F60_1677C0_BobOmbBarrage, 0x10

dlabel D_80108F60_1677C0_BobOmbBarrage
    /* 80108F60 */ .space 0x10

nonmatching D_80108F70_1677D0_BobOmbBarrage, 0x10

dlabel D_80108F70_1677D0_BobOmbBarrage
    /* 80108F70 */ .space 0x10

nonmatching D_80108F80_1677E0_BobOmbBarrage, 0x10

dlabel D_80108F80_1677E0_BobOmbBarrage
    /* 80108F80 */ .space 0x10

nonmatching D_80108F90_1677F0_BobOmbBarrage, 0x10

dlabel D_80108F90_1677F0_BobOmbBarrage
    /* 80108F90 */ .space 0x10

nonmatching D_80108FA0_167800_BobOmbBarrage, 0xC

dlabel D_80108FA0_167800_BobOmbBarrage
    /* 80108FA0 */ .space 0x0C

nonmatching D_80108FAC_16780C_BobOmbBarrage, 0x4

dlabel D_80108FAC_16780C_BobOmbBarrage
    /* 80108FAC */ .space 0x04

nonmatching D_80108FB0_167810_BobOmbBarrage, 0x40

dlabel D_80108FB0_167810_BobOmbBarrage
    /* 80108FB0 */ .space 0x40

nonmatching D_80108FF0_167850_BobOmbBarrage, 0x4

dlabel D_80108FF0_167850_BobOmbBarrage
    /* 80108FF0 */ .space 0x04

nonmatching D_80108FF4_167854_BobOmbBarrage, 0x4

dlabel D_80108FF4_167854_BobOmbBarrage
    /* 80108FF4 */ .space 0x04

nonmatching D_80108FF8_167858_BobOmbBarrage, 0x38

dlabel D_80108FF8_167858_BobOmbBarrage
    /* 80108FF8 */ .space 0x38

nonmatching D_80109030_167890_BobOmbBarrage, 0x10

dlabel D_80109030_167890_BobOmbBarrage
    /* 80109030 */ .space 0x10

nonmatching D_80109040_1678A0_BobOmbBarrage, 0x10

dlabel D_80109040_1678A0_BobOmbBarrage
    /* 80109040 */ .space 0x10

nonmatching D_80109050_1678B0_BobOmbBarrage, 0x10

dlabel D_80109050_1678B0_BobOmbBarrage
    /* 80109050 */ .space 0x10

nonmatching D_80109060_1678C0_BobOmbBarrage, 0x10

dlabel D_80109060_1678C0_BobOmbBarrage
    /* 80109060 */ .space 0x10

nonmatching D_80109070_1678D0_BobOmbBarrage, 0x10

dlabel D_80109070_1678D0_BobOmbBarrage
    /* 80109070 */ .space 0x10

nonmatching D_80109080_1678E0_BobOmbBarrage, 0x10

dlabel D_80109080_1678E0_BobOmbBarrage
    /* 80109080 */ .space 0x10

nonmatching jtbl_80109090_1678F0_BobOmbBarrage, 0x48

dlabel jtbl_80109090_1678F0_BobOmbBarrage
    /* 80109090 */ .space 0x48

nonmatching jtbl_801090D8_167938_BobOmbBarrage, 0x18

dlabel jtbl_801090D8_167938_BobOmbBarrage
    /* 801090D8 */ .space 0x18

nonmatching D_801090F0_167950_BobOmbBarrage, 0xC

dlabel D_801090F0_167950_BobOmbBarrage
    /* 801090F0 */ .space 0x0C

nonmatching D_801090FC_16795C_BobOmbBarrage, 0xC

dlabel D_801090FC_16795C_BobOmbBarrage
    /* 801090FC */ .space 0x0C

nonmatching D_80109108_167968_BobOmbBarrage, 0x10

dlabel D_80109108_167968_BobOmbBarrage
    /* 80109108 */ .space 0x10

nonmatching jtbl_80109118_167978_BobOmbBarrage, 0x30

dlabel jtbl_80109118_167978_BobOmbBarrage
    /* 80109118 */ .space 0x30

nonmatching D_80109148_1679A8_BobOmbBarrage, 0x8

dlabel D_80109148_1679A8_BobOmbBarrage
    /* 80109148 */ .space 0x08

nonmatching D_80109150_1679B0_BobOmbBarrage, 0x8

dlabel D_80109150_1679B0_BobOmbBarrage
    /* 80109150 */ .space 0x08

nonmatching D_80109158_1679B8_BobOmbBarrage, 0x8

dlabel D_80109158_1679B8_BobOmbBarrage
    /* 80109158 */ .space 0x08

nonmatching jtbl_80109160_1679C0_BobOmbBarrage, 0x44

dlabel jtbl_80109160_1679C0_BobOmbBarrage
    /* 80109160 */ .space 0x44

nonmatching D_801091A4_167A04_BobOmbBarrage, 0xC

dlabel D_801091A4_167A04_BobOmbBarrage
    /* 801091A4 */ .space 0x0C

nonmatching jtbl_801091B0_167A10_BobOmbBarrage, 0x68

dlabel jtbl_801091B0_167A10_BobOmbBarrage
    /* 801091B0 */ .space 0x68

nonmatching jtbl_80109218_167A78_BobOmbBarrage, 0x28

dlabel jtbl_80109218_167A78_BobOmbBarrage
    /* 80109218 */ .space 0x28

nonmatching jtbl_80109240_167AA0_BobOmbBarrage, 0x20

dlabel jtbl_80109240_167AA0_BobOmbBarrage
    /* 80109240 */ .space 0x20

nonmatching D_80109260_167AC0_BobOmbBarrage, 0x8

dlabel D_80109260_167AC0_BobOmbBarrage
    /* 80109260 */ .space 0x08

nonmatching D_80109268_167AC8_BobOmbBarrage, 0x8

dlabel D_80109268_167AC8_BobOmbBarrage
    /* 80109268 */ .space 0x08

nonmatching D_80109270_167AD0_BobOmbBarrage, 0x10

dlabel D_80109270_167AD0_BobOmbBarrage
    /* 80109270 */ .space 0x10

nonmatching D_80109280_167AE0_BobOmbBarrage, 0x4

dlabel D_80109280_167AE0_BobOmbBarrage
    /* 80109280 */ .space 0x04

nonmatching D_80109284_167AE4_BobOmbBarrage, 0x4

dlabel D_80109284_167AE4_BobOmbBarrage
    /* 80109284 */ .space 0x04

nonmatching D_80109288_167AE8_BobOmbBarrage, 0x4

dlabel D_80109288_167AE8_BobOmbBarrage
    /* 80109288 */ .space 0x04

nonmatching D_8010928C_167AEC_BobOmbBarrage, 0x8

dlabel D_8010928C_167AEC_BobOmbBarrage
    /* 8010928C */ .space 0x08

nonmatching D_80109294_167AF4_BobOmbBarrage, 0x4

dlabel D_80109294_167AF4_BobOmbBarrage
    /* 80109294 */ .space 0x04

nonmatching D_80109298_167AF8_BobOmbBarrage, 0x8

dlabel D_80109298_167AF8_BobOmbBarrage
    /* 80109298 */ .space 0x08

nonmatching D_801092A0_167B00_BobOmbBarrage, 0x4

dlabel D_801092A0_167B00_BobOmbBarrage
    /* 801092A0 */ .space 0x04

nonmatching D_801092A4_167B04_BobOmbBarrage, 0xC

dlabel D_801092A4_167B04_BobOmbBarrage
    /* 801092A4 */ .space 0x0C

nonmatching D_801092B0_167B10_BobOmbBarrage, 0x4

dlabel D_801092B0_167B10_BobOmbBarrage
    /* 801092B0 */ .space 0x04

nonmatching D_801092B4_167B14_BobOmbBarrage, 0xC

dlabel D_801092B4_167B14_BobOmbBarrage
    /* 801092B4 */ .space 0x0C

nonmatching D_801092C0_167B20_BobOmbBarrage, 0x10

dlabel D_801092C0_167B20_BobOmbBarrage
    /* 801092C0 */ .space 0x10

nonmatching D_801092D0_167B30_BobOmbBarrage, 0x30

dlabel D_801092D0_167B30_BobOmbBarrage
    /* 801092D0 */ .space 0x30

nonmatching D_80109300_167B60_BobOmbBarrage, 0x4

dlabel D_80109300_167B60_BobOmbBarrage
    /* 80109300 */ .space 0x04

nonmatching D_80109304_167B64_BobOmbBarrage, 0x4

dlabel D_80109304_167B64_BobOmbBarrage
    /* 80109304 */ .space 0x04

nonmatching D_80109308_167B68_BobOmbBarrage, 0x4

dlabel D_80109308_167B68_BobOmbBarrage
    /* 80109308 */ .space 0x04

nonmatching D_8010930C_167B6C_BobOmbBarrage, 0x4

dlabel D_8010930C_167B6C_BobOmbBarrage
    /* 8010930C */ .space 0x04

nonmatching D_80109310_167B70_BobOmbBarrage, 0x4

dlabel D_80109310_167B70_BobOmbBarrage
    /* 80109310 */ .space 0x04

nonmatching D_80109314_167B74_BobOmbBarrage, 0x4

dlabel D_80109314_167B74_BobOmbBarrage
    /* 80109314 */ .space 0x04

nonmatching D_80109318_167B78_BobOmbBarrage, 0x4

dlabel D_80109318_167B78_BobOmbBarrage
    /* 80109318 */ .space 0x04

nonmatching D_8010931C_167B7C_BobOmbBarrage, 0x4

dlabel D_8010931C_167B7C_BobOmbBarrage
    /* 8010931C */ .space 0x04

nonmatching D_80109320_167B80_BobOmbBarrage, 0x4

dlabel D_80109320_167B80_BobOmbBarrage
    /* 80109320 */ .space 0x04

nonmatching D_80109324_167B84_BobOmbBarrage, 0x1C

dlabel D_80109324_167B84_BobOmbBarrage
    /* 80109324 */ .space 0x1C

nonmatching D_80109340_167BA0_BobOmbBarrage, 0x4

dlabel D_80109340_167BA0_BobOmbBarrage
    /* 80109340 */ .space 0x04

nonmatching D_80109344_167BA4_BobOmbBarrage, 0x4

dlabel D_80109344_167BA4_BobOmbBarrage
    /* 80109344 */ .space 0x04

nonmatching D_80109348_167BA8_BobOmbBarrage, 0x4

dlabel D_80109348_167BA8_BobOmbBarrage
    /* 80109348 */ .space 0x04

nonmatching D_8010934C_167BAC_BobOmbBarrage, 0x4

dlabel D_8010934C_167BAC_BobOmbBarrage
    /* 8010934C */ .space 0x04

nonmatching D_80109350_167BB0_BobOmbBarrage, 0x8

dlabel D_80109350_167BB0_BobOmbBarrage
    /* 80109350 */ .space 0x08

nonmatching D_80109358_167BB8_BobOmbBarrage, 0x4

dlabel D_80109358_167BB8_BobOmbBarrage
    /* 80109358 */ .space 0x04

nonmatching D_8010935C_167BBC_BobOmbBarrage, 0x4

dlabel D_8010935C_167BBC_BobOmbBarrage
    /* 8010935C */ .space 0x04

nonmatching D_80109360_167BC0_BobOmbBarrage, 0x4

dlabel D_80109360_167BC0_BobOmbBarrage
    /* 80109360 */ .space 0x04

nonmatching D_80109364_167BC4_BobOmbBarrage, 0xC

dlabel D_80109364_167BC4_BobOmbBarrage
    /* 80109364 */ .space 0x0C

nonmatching D_80109370_167BD0_BobOmbBarrage, 0x8

dlabel D_80109370_167BD0_BobOmbBarrage
    /* 80109370 */ .space 0x08

nonmatching D_80109378_167BD8_BobOmbBarrage, 0x8

dlabel D_80109378_167BD8_BobOmbBarrage
    /* 80109378 */ .space 0x08

nonmatching D_80109380_167BE0_BobOmbBarrage, 0x4

dlabel D_80109380_167BE0_BobOmbBarrage
    /* 80109380 */ .space 0x04

nonmatching D_80109384_167BE4_BobOmbBarrage, 0x4

dlabel D_80109384_167BE4_BobOmbBarrage
    /* 80109384 */ .space 0x04

nonmatching D_80109388_167BE8_BobOmbBarrage, 0x4

dlabel D_80109388_167BE8_BobOmbBarrage
    /* 80109388 */ .space 0x04

nonmatching D_8010938C_167BEC_BobOmbBarrage, 0x4

dlabel D_8010938C_167BEC_BobOmbBarrage
    /* 8010938C */ .space 0x04

nonmatching D_80109390_167BF0_BobOmbBarrage, 0x4

dlabel D_80109390_167BF0_BobOmbBarrage
    /* 80109390 */ .space 0x04

nonmatching D_80109394_167BF4_BobOmbBarrage, 0xC

dlabel D_80109394_167BF4_BobOmbBarrage
    /* 80109394 */ .space 0x0C

nonmatching D_801093A0_167C00_BobOmbBarrage, 0x14

dlabel D_801093A0_167C00_BobOmbBarrage
    /* 801093A0 */ .space 0x14

nonmatching D_801093B4_167C14_BobOmbBarrage, 0xC

dlabel D_801093B4_167C14_BobOmbBarrage
    /* 801093B4 */ .space 0x0C

nonmatching D_801093C0_167C20_BobOmbBarrage, 0x4

dlabel D_801093C0_167C20_BobOmbBarrage
    /* 801093C0 */ .space 0x04

nonmatching D_801093C4_167C24_BobOmbBarrage, 0x4

dlabel D_801093C4_167C24_BobOmbBarrage
    /* 801093C4 */ .space 0x04

nonmatching D_801093C8_167C28_BobOmbBarrage, 0x4

dlabel D_801093C8_167C28_BobOmbBarrage
    /* 801093C8 */ .space 0x04

nonmatching D_801093CC_167C2C_BobOmbBarrage, 0x4

dlabel D_801093CC_167C2C_BobOmbBarrage
    /* 801093CC */ .space 0x04

nonmatching D_801093D0_167C30_BobOmbBarrage, 0x2C8

dlabel D_801093D0_167C30_BobOmbBarrage
    /* 801093D0 */ .space 0x2C8

nonmatching D_80109698_167EF8_BobOmbBarrage, 0x8

dlabel D_80109698_167EF8_BobOmbBarrage
    /* 80109698 */ .space 0x08

nonmatching D_801096A0_167F00_BobOmbBarrage, 0x1C

dlabel D_801096A0_167F00_BobOmbBarrage
    /* 801096A0 */ .space 0x1C

nonmatching D_801096BC_167F1C_BobOmbBarrage, 0x14

dlabel D_801096BC_167F1C_BobOmbBarrage
    /* 801096BC */ .space 0x14

nonmatching D_801096D0_167F30_BobOmbBarrage, 0x2

dlabel D_801096D0_167F30_BobOmbBarrage
    /* 801096D0 */ .space 0x02

nonmatching D_801096D2_167F32_BobOmbBarrage, 0x6

dlabel D_801096D2_167F32_BobOmbBarrage
    /* 801096D2 */ .space 0x06

nonmatching D_801096D8_167F38_BobOmbBarrage, 0x2

dlabel D_801096D8_167F38_BobOmbBarrage
    /* 801096D8 */ .space 0x02

nonmatching D_801096DA_167F3A_BobOmbBarrage, 0x4

dlabel D_801096DA_167F3A_BobOmbBarrage
    /* 801096DA */ .space 0x04

nonmatching D_801096DE_167F3E_BobOmbBarrage, 0x2

dlabel D_801096DE_167F3E_BobOmbBarrage
    /* 801096DE */ .space 0x02

nonmatching D_801096E0_167F40_BobOmbBarrage, 0x2

dlabel D_801096E0_167F40_BobOmbBarrage
    /* 801096E0 */ .space 0x02

nonmatching D_801096E2_167F42_BobOmbBarrage, 0x2

dlabel D_801096E2_167F42_BobOmbBarrage
    /* 801096E2 */ .space 0x02

nonmatching D_801096E4_167F44_BobOmbBarrage, 0x2

dlabel D_801096E4_167F44_BobOmbBarrage
    /* 801096E4 */ .space 0x02

nonmatching D_801096E6_167F46_BobOmbBarrage, 0x26

dlabel D_801096E6_167F46_BobOmbBarrage
    /* 801096E6 */ .space 0x26

nonmatching D_8010970C_167F6C_BobOmbBarrage, 0x4

dlabel D_8010970C_167F6C_BobOmbBarrage
    /* 8010970C */ .space 0x04

nonmatching D_80109710_167F70_BobOmbBarrage, 0x4

dlabel D_80109710_167F70_BobOmbBarrage
    /* 80109710 */ .space 0x04

nonmatching D_80109714_167F74_BobOmbBarrage, 0x4

dlabel D_80109714_167F74_BobOmbBarrage
    /* 80109714 */ .space 0x04

nonmatching D_80109718_167F78_BobOmbBarrage, 0x4

dlabel D_80109718_167F78_BobOmbBarrage
    /* 80109718 */ .space 0x04

nonmatching D_8010971C_167F7C_BobOmbBarrage, 0x3C

dlabel D_8010971C_167F7C_BobOmbBarrage
    /* 8010971C */ .space 0x3C

nonmatching D_80109758_167FB8_BobOmbBarrage, 0x24

dlabel D_80109758_167FB8_BobOmbBarrage
    /* 80109758 */ .space 0x24

nonmatching D_8010977C_167FDC_BobOmbBarrage, 0x4

dlabel D_8010977C_167FDC_BobOmbBarrage
    /* 8010977C */ .space 0x04

nonmatching D_80109780_167FE0_BobOmbBarrage, 0x2

dlabel D_80109780_167FE0_BobOmbBarrage
    /* 80109780 */ .space 0x02

nonmatching D_80109782_167FE2_BobOmbBarrage, 0x2

dlabel D_80109782_167FE2_BobOmbBarrage
    /* 80109782 */ .space 0x02

nonmatching D_80109784_167FE4_BobOmbBarrage, 0xA3C

dlabel D_80109784_167FE4_BobOmbBarrage
    /* 80109784 */ .space 0xA3C

nonmatching D_8010A1C0_168A20_BobOmbBarrage, 0x2

dlabel D_8010A1C0_168A20_BobOmbBarrage
    /* 8010A1C0 */ .space 0x02

nonmatching D_8010A1C2_168A22_BobOmbBarrage, 0x2

dlabel D_8010A1C2_168A22_BobOmbBarrage
    /* 8010A1C2 */ .space 0x02

nonmatching D_8010A1C4_168A24_BobOmbBarrage, 0x4

dlabel D_8010A1C4_168A24_BobOmbBarrage
    /* 8010A1C4 */ .space 0x04

nonmatching D_8010A1C8_168A28_BobOmbBarrage, 0x8

dlabel D_8010A1C8_168A28_BobOmbBarrage
    /* 8010A1C8 */ .space 0x08

nonmatching D_8010A1D0_168A30_BobOmbBarrage, 0x55F0

dlabel D_8010A1D0_168A30_BobOmbBarrage
    /* 8010A1D0 */ .space 0x55F0
