.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80103670_415790_MsgTest, 0x2

dlabel D_80103670_415790_MsgTest
    /* 80103670 */ .space 0x02

nonmatching D_80103672_415792_MsgTest, 0x2

dlabel D_80103672_415792_MsgTest
    /* 80103672 */ .space 0x02

nonmatching D_80103674_415794_MsgTest, 0x4

dlabel D_80103674_415794_MsgTest
    /* 80103674 */ .space 0x04

nonmatching D_80103678_415798_MsgTest, 0x4

dlabel D_80103678_415798_MsgTest
    /* 80103678 */ .space 0x04

nonmatching D_8010367C_41579C_MsgTest, 0x4

dlabel D_8010367C_41579C_MsgTest
    /* 8010367C */ .space 0x04

nonmatching D_80103680_4157A0_MsgTest, 0x4

dlabel D_80103680_4157A0_MsgTest
    /* 80103680 */ .space 0x04

nonmatching D_80103684_4157A4_MsgTest, 0x2

dlabel D_80103684_4157A4_MsgTest
    /* 80103684 */ .space 0x02

nonmatching D_80103686_4157A6_MsgTest, 0x2

dlabel D_80103686_4157A6_MsgTest
    /* 80103686 */ .space 0x02

nonmatching func_80103688_4157A8_MsgTest, 0x4

dlabel func_80103688_4157A8_MsgTest
    /* 80103688 */ .space 0x04

nonmatching D_8010368C_4157AC_MsgTest, 0x504

dlabel D_8010368C_4157AC_MsgTest
    /* 8010368C */ .space 0x504

nonmatching D_80103B90_415CB0_MsgTest, 0x178

dlabel D_80103B90_415CB0_MsgTest
    /* 80103B90 */ .space 0x178

nonmatching D_80103D08_415E28_MsgTest, 0x8

dlabel D_80103D08_415E28_MsgTest
    /* 80103D08 */ .space 0x08

nonmatching D_80103D10_415E30_MsgTest, 0x6F0

dlabel D_80103D10_415E30_MsgTest
    /* 80103D10 */ .space 0x6F0

nonmatching D_80104400_416520_MsgTest, 0xD70

dlabel D_80104400_416520_MsgTest
    /* 80104400 */ .space 0xD70
