.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_8010B760_155C90_CraneGame, 0x4

glabel D_8010B760_155C90_CraneGame
    /* 8010B760 */ .space 0x04

nonmatching D_8010B764_155C94_CraneGame, 0x4

dlabel D_8010B764_155C94_CraneGame
    /* 8010B764 */ .space 0x04

nonmatching D_8010B768_155C98_CraneGame, 0x4

dlabel D_8010B768_155C98_CraneGame
    /* 8010B768 */ .space 0x04

nonmatching D_8010B76C_155C9C_CraneGame, 0x4C

dlabel D_8010B76C_155C9C_CraneGame
    /* 8010B76C */ .space 0x4C

nonmatching D_8010B7B8_155CE8_CraneGame, 0x130

dlabel D_8010B7B8_155CE8_CraneGame
    /* 8010B7B8 */ .space 0x130

nonmatching D_8010B8E8_155E18_CraneGame, 0x40

dlabel D_8010B8E8_155E18_CraneGame
    /* 8010B8E8 */ .space 0x40

nonmatching D_8010B928_155E58_CraneGame, 0x50

dlabel D_8010B928_155E58_CraneGame
    /* 8010B928 */ .space 0x50

nonmatching D_8010B978_155EA8_CraneGame, 0x8

dlabel D_8010B978_155EA8_CraneGame
    /* 8010B978 */ .space 0x08

nonmatching D_8010B980_155EB0_CraneGame, 0x18

dlabel D_8010B980_155EB0_CraneGame
    /* 8010B980 */ .space 0x18

nonmatching D_8010B998_155EC8_CraneGame, 0x4

dlabel D_8010B998_155EC8_CraneGame
    /* 8010B998 */ .space 0x04

nonmatching D_8010B99C_155ECC_CraneGame, 0x14

dlabel D_8010B99C_155ECC_CraneGame
    /* 8010B99C */ .space 0x14

nonmatching D_8010B9B0_155EE0_CraneGame, 0x4

dlabel D_8010B9B0_155EE0_CraneGame
    /* 8010B9B0 */ .space 0x04

nonmatching D_8010B9B4_155EE4_CraneGame, 0x32C

dlabel D_8010B9B4_155EE4_CraneGame
    /* 8010B9B4 */ .space 0x32C

nonmatching D_8010BCE0_156210_CraneGame, 0x40

dlabel D_8010BCE0_156210_CraneGame
    /* 8010BCE0 */ .space 0x40

nonmatching D_8010BD20_156250_CraneGame, 0x30

dlabel D_8010BD20_156250_CraneGame
    /* 8010BD20 */ .space 0x30

nonmatching jtbl_8010BD50_156280_CraneGame, 0x18

dlabel jtbl_8010BD50_156280_CraneGame
    /* 8010BD50 */ .space 0x18

nonmatching D_8010BD68_156298_CraneGame, 0x8

dlabel D_8010BD68_156298_CraneGame
    /* 8010BD68 */ .space 0x08

nonmatching D_8010BD70_1562A0_CraneGame, 0x8

dlabel D_8010BD70_1562A0_CraneGame
    /* 8010BD70 */ .space 0x08

nonmatching D_8010BD78_1562A8_CraneGame, 0x8

dlabel D_8010BD78_1562A8_CraneGame
    /* 8010BD78 */ .space 0x08

nonmatching D_8010BD80_1562B0_CraneGame, 0x8

dlabel D_8010BD80_1562B0_CraneGame
    /* 8010BD80 */ .space 0x08

nonmatching D_8010BD88_1562B8_CraneGame, 0x8

dlabel D_8010BD88_1562B8_CraneGame
    /* 8010BD88 */ .space 0x08

nonmatching D_8010BD90_1562C0_CraneGame, 0x8

dlabel D_8010BD90_1562C0_CraneGame
    /* 8010BD90 */ .space 0x08

nonmatching D_8010BD98_1562C8_CraneGame, 0x8

dlabel D_8010BD98_1562C8_CraneGame
    /* 8010BD98 */ .space 0x08

nonmatching D_8010BDA0_1562D0_CraneGame, 0x8

dlabel D_8010BDA0_1562D0_CraneGame
    /* 8010BDA0 */ .space 0x08

nonmatching D_8010BDA8_1562D8_CraneGame, 0x8

dlabel D_8010BDA8_1562D8_CraneGame
    /* 8010BDA8 */ .space 0x08

nonmatching D_8010BDB0_1562E0_CraneGame, 0x8

dlabel D_8010BDB0_1562E0_CraneGame
    /* 8010BDB0 */ .space 0x08

nonmatching D_8010BDB8_1562E8_CraneGame, 0x8

dlabel D_8010BDB8_1562E8_CraneGame
    /* 8010BDB8 */ .space 0x08

nonmatching D_8010BDC0_1562F0_CraneGame, 0x8

dlabel D_8010BDC0_1562F0_CraneGame
    /* 8010BDC0 */ .space 0x08

nonmatching D_8010BDC8_1562F8_CraneGame, 0x8

dlabel D_8010BDC8_1562F8_CraneGame
    /* 8010BDC8 */ .space 0x08

nonmatching D_8010BDD0_156300_CraneGame, 0x8

dlabel D_8010BDD0_156300_CraneGame
    /* 8010BDD0 */ .space 0x08

nonmatching D_8010BDD8_156308_CraneGame, 0x8

dlabel D_8010BDD8_156308_CraneGame
    /* 8010BDD8 */ .space 0x08

nonmatching D_8010BDE0_156310_CraneGame, 0x8

dlabel D_8010BDE0_156310_CraneGame
    /* 8010BDE0 */ .space 0x08

nonmatching D_8010BDE8_156318_CraneGame, 0x8

dlabel D_8010BDE8_156318_CraneGame
    /* 8010BDE8 */ .space 0x08

nonmatching D_8010BDF0_156320_CraneGame, 0x8

dlabel D_8010BDF0_156320_CraneGame
    /* 8010BDF0 */ .space 0x08

nonmatching D_8010BDF8_156328_CraneGame, 0x8

dlabel D_8010BDF8_156328_CraneGame
    /* 8010BDF8 */ .space 0x08

nonmatching D_8010BE00_156330_CraneGame, 0x8

dlabel D_8010BE00_156330_CraneGame
    /* 8010BE00 */ .space 0x08

nonmatching D_8010BE08_156338_CraneGame, 0x8

dlabel D_8010BE08_156338_CraneGame
    /* 8010BE08 */ .space 0x08

nonmatching D_8010BE10_156340_CraneGame, 0x8

dlabel D_8010BE10_156340_CraneGame
    /* 8010BE10 */ .space 0x08

nonmatching D_8010BE18_156348_CraneGame, 0x8

dlabel D_8010BE18_156348_CraneGame
    /* 8010BE18 */ .space 0x08

nonmatching D_8010BE20_156350_CraneGame, 0x8

dlabel D_8010BE20_156350_CraneGame
    /* 8010BE20 */ .space 0x08

nonmatching jtbl_8010BE28_156358_CraneGame, 0x28

dlabel jtbl_8010BE28_156358_CraneGame
    /* 8010BE28 */ .space 0x28

nonmatching D_8010BE50_156380_CraneGame, 0x8

dlabel D_8010BE50_156380_CraneGame
    /* 8010BE50 */ .space 0x08

nonmatching D_8010BE58_156388_CraneGame, 0x8

dlabel D_8010BE58_156388_CraneGame
    /* 8010BE58 */ .space 0x08

nonmatching D_8010BE60_156390_CraneGame, 0x8

dlabel D_8010BE60_156390_CraneGame
    /* 8010BE60 */ .space 0x08

nonmatching D_8010BE68_156398_CraneGame, 0x8

dlabel D_8010BE68_156398_CraneGame
    /* 8010BE68 */ .space 0x08

nonmatching D_8010BE70_1563A0_CraneGame, 0x8

dlabel D_8010BE70_1563A0_CraneGame
    /* 8010BE70 */ .space 0x08

nonmatching D_8010BE78_1563A8_CraneGame, 0x8

dlabel D_8010BE78_1563A8_CraneGame
    /* 8010BE78 */ .space 0x08

nonmatching D_8010BE80_1563B0_CraneGame, 0x8

dlabel D_8010BE80_1563B0_CraneGame
    /* 8010BE80 */ .space 0x08

nonmatching D_8010BE88_1563B8_CraneGame, 0x8

dlabel D_8010BE88_1563B8_CraneGame
    /* 8010BE88 */ .space 0x08

nonmatching D_8010BE90_1563C0_CraneGame, 0x8

dlabel D_8010BE90_1563C0_CraneGame
    /* 8010BE90 */ .space 0x08

nonmatching D_8010BE98_1563C8_CraneGame, 0x8

dlabel D_8010BE98_1563C8_CraneGame
    /* 8010BE98 */ .space 0x08

nonmatching D_8010BEA0_1563D0_CraneGame, 0x8

dlabel D_8010BEA0_1563D0_CraneGame
    /* 8010BEA0 */ .space 0x08

nonmatching D_8010BEA8_1563D8_CraneGame, 0x8

dlabel D_8010BEA8_1563D8_CraneGame
    /* 8010BEA8 */ .space 0x08

nonmatching D_8010BEB0_1563E0_CraneGame, 0x8

dlabel D_8010BEB0_1563E0_CraneGame
    /* 8010BEB0 */ .space 0x08

nonmatching D_8010BEB8_1563E8_CraneGame, 0x8

dlabel D_8010BEB8_1563E8_CraneGame
    /* 8010BEB8 */ .space 0x08

nonmatching D_8010BEC0_1563F0_CraneGame, 0x8

dlabel D_8010BEC0_1563F0_CraneGame
    /* 8010BEC0 */ .space 0x08

nonmatching D_8010BEC8_1563F8_CraneGame, 0x8

dlabel D_8010BEC8_1563F8_CraneGame
    /* 8010BEC8 */ .space 0x08

nonmatching D_8010BED0_156400_CraneGame, 0x8

dlabel D_8010BED0_156400_CraneGame
    /* 8010BED0 */ .space 0x08

nonmatching D_8010BED8_156408_CraneGame, 0x8

dlabel D_8010BED8_156408_CraneGame
    /* 8010BED8 */ .space 0x08

nonmatching D_8010BEE0_156410_CraneGame, 0x8

dlabel D_8010BEE0_156410_CraneGame
    /* 8010BEE0 */ .space 0x08

nonmatching D_8010BEE8_156418_CraneGame, 0x8

dlabel D_8010BEE8_156418_CraneGame
    /* 8010BEE8 */ .space 0x08

nonmatching D_8010BEF0_156420_CraneGame, 0x8

dlabel D_8010BEF0_156420_CraneGame
    /* 8010BEF0 */ .space 0x08

nonmatching D_8010BEF8_156428_CraneGame, 0x8

dlabel D_8010BEF8_156428_CraneGame
    /* 8010BEF8 */ .space 0x08

nonmatching D_8010BF00_156430_CraneGame, 0x8

dlabel D_8010BF00_156430_CraneGame
    /* 8010BF00 */ .space 0x08

nonmatching D_8010BF08_156438_CraneGame, 0x8

dlabel D_8010BF08_156438_CraneGame
    /* 8010BF08 */ .space 0x08

nonmatching D_8010BF10_156440_CraneGame, 0x8

dlabel D_8010BF10_156440_CraneGame
    /* 8010BF10 */ .space 0x08

nonmatching D_8010BF18_156448_CraneGame, 0x8

dlabel D_8010BF18_156448_CraneGame
    /* 8010BF18 */ .space 0x08

nonmatching D_8010BF20_156450_CraneGame, 0x8

dlabel D_8010BF20_156450_CraneGame
    /* 8010BF20 */ .space 0x08

nonmatching D_8010BF28_156458_CraneGame, 0x8

dlabel D_8010BF28_156458_CraneGame
    /* 8010BF28 */ .space 0x08

nonmatching D_8010BF30_156460_CraneGame, 0x8

dlabel D_8010BF30_156460_CraneGame
    /* 8010BF30 */ .space 0x08

nonmatching D_8010BF38_156468_CraneGame, 0x8

dlabel D_8010BF38_156468_CraneGame
    /* 8010BF38 */ .space 0x08

nonmatching D_8010BF40_156470_CraneGame, 0x8

dlabel D_8010BF40_156470_CraneGame
    /* 8010BF40 */ .space 0x08

nonmatching D_8010BF48_156478_CraneGame, 0x8

dlabel D_8010BF48_156478_CraneGame
    /* 8010BF48 */ .space 0x08

nonmatching D_8010BF50_156480_CraneGame, 0x8

dlabel D_8010BF50_156480_CraneGame
    /* 8010BF50 */ .space 0x08

nonmatching D_8010BF58_156488_CraneGame, 0x8

dlabel D_8010BF58_156488_CraneGame
    /* 8010BF58 */ .space 0x08

nonmatching D_8010BF60_156490_CraneGame, 0x8

dlabel D_8010BF60_156490_CraneGame
    /* 8010BF60 */ .space 0x08

nonmatching D_8010BF68_156498_CraneGame, 0x8

dlabel D_8010BF68_156498_CraneGame
    /* 8010BF68 */ .space 0x08

nonmatching D_8010BF70_1564A0_CraneGame, 0x8

dlabel D_8010BF70_1564A0_CraneGame
    /* 8010BF70 */ .space 0x08

nonmatching D_8010BF78_1564A8_CraneGame, 0x8

dlabel D_8010BF78_1564A8_CraneGame
    /* 8010BF78 */ .space 0x08

nonmatching D_8010BF80_1564B0_CraneGame, 0x8

dlabel D_8010BF80_1564B0_CraneGame
    /* 8010BF80 */ .space 0x08

nonmatching D_8010BF88_1564B8_CraneGame, 0x8

dlabel D_8010BF88_1564B8_CraneGame
    /* 8010BF88 */ .space 0x08

nonmatching D_8010BF90_1564C0_CraneGame, 0x8

dlabel D_8010BF90_1564C0_CraneGame
    /* 8010BF90 */ .space 0x08

nonmatching D_8010BF98_1564C8_CraneGame, 0x8

dlabel D_8010BF98_1564C8_CraneGame
    /* 8010BF98 */ .space 0x08

nonmatching D_8010BFA0_1564D0_CraneGame, 0x8

dlabel D_8010BFA0_1564D0_CraneGame
    /* 8010BFA0 */ .space 0x08

nonmatching D_8010BFA8_1564D8_CraneGame, 0x8

dlabel D_8010BFA8_1564D8_CraneGame
    /* 8010BFA8 */ .space 0x08

nonmatching D_8010BFB0_1564E0_CraneGame, 0x8

dlabel D_8010BFB0_1564E0_CraneGame
    /* 8010BFB0 */ .space 0x08

nonmatching D_8010BFB8_1564E8_CraneGame, 0x8

dlabel D_8010BFB8_1564E8_CraneGame
    /* 8010BFB8 */ .space 0x08

nonmatching D_8010BFC0_1564F0_CraneGame, 0x8

dlabel D_8010BFC0_1564F0_CraneGame
    /* 8010BFC0 */ .space 0x08

nonmatching D_8010BFC8_1564F8_CraneGame, 0x8

dlabel D_8010BFC8_1564F8_CraneGame
    /* 8010BFC8 */ .space 0x08

nonmatching D_8010BFD0_156500_CraneGame, 0x8

dlabel D_8010BFD0_156500_CraneGame
    /* 8010BFD0 */ .space 0x08

nonmatching D_8010BFD8_156508_CraneGame, 0x8

dlabel D_8010BFD8_156508_CraneGame
    /* 8010BFD8 */ .space 0x08

nonmatching D_8010BFE0_156510_CraneGame, 0x8

dlabel D_8010BFE0_156510_CraneGame
    /* 8010BFE0 */ .space 0x08

nonmatching D_8010BFE8_156518_CraneGame, 0x8

dlabel D_8010BFE8_156518_CraneGame
    /* 8010BFE8 */ .space 0x08

nonmatching D_8010BFF0_156520_CraneGame, 0x8

dlabel D_8010BFF0_156520_CraneGame
    /* 8010BFF0 */ .space 0x08

nonmatching D_8010BFF8_156528_CraneGame, 0x8

dlabel D_8010BFF8_156528_CraneGame
    /* 8010BFF8 */ .space 0x08

nonmatching D_8010C000_156530_CraneGame, 0x48

dlabel D_8010C000_156530_CraneGame
    /* 8010C000 */ .space 0x48

nonmatching D_8010C048_156578_CraneGame, 0x8

dlabel D_8010C048_156578_CraneGame
    /* 8010C048 */ .space 0x08

nonmatching D_8010C050_156580_CraneGame, 0x8

dlabel D_8010C050_156580_CraneGame
    /* 8010C050 */ .space 0x08

nonmatching D_8010C058_156588_CraneGame, 0x8

dlabel D_8010C058_156588_CraneGame
    /* 8010C058 */ .space 0x08

nonmatching D_8010C060_156590_CraneGame, 0x8

dlabel D_8010C060_156590_CraneGame
    /* 8010C060 */ .space 0x08

nonmatching D_8010C068_156598_CraneGame, 0x8

dlabel D_8010C068_156598_CraneGame
    /* 8010C068 */ .space 0x08

nonmatching D_8010C070_1565A0_CraneGame, 0x8

dlabel D_8010C070_1565A0_CraneGame
    /* 8010C070 */ .space 0x08

nonmatching D_8010C078_1565A8_CraneGame, 0x8

dlabel D_8010C078_1565A8_CraneGame
    /* 8010C078 */ .space 0x08

nonmatching D_8010C080_1565B0_CraneGame, 0x8

dlabel D_8010C080_1565B0_CraneGame
    /* 8010C080 */ .space 0x08

nonmatching D_8010C088_1565B8_CraneGame, 0x8

dlabel D_8010C088_1565B8_CraneGame
    /* 8010C088 */ .space 0x08

nonmatching D_8010C090_1565C0_CraneGame, 0x8

dlabel D_8010C090_1565C0_CraneGame
    /* 8010C090 */ .space 0x08

nonmatching D_8010C098_1565C8_CraneGame, 0x8

dlabel D_8010C098_1565C8_CraneGame
    /* 8010C098 */ .space 0x08

nonmatching D_8010C0A0_1565D0_CraneGame, 0x8

dlabel D_8010C0A0_1565D0_CraneGame
    /* 8010C0A0 */ .space 0x08

nonmatching D_8010C0A8_1565D8_CraneGame, 0x8

dlabel D_8010C0A8_1565D8_CraneGame
    /* 8010C0A8 */ .space 0x08

nonmatching D_8010C0B0_1565E0_CraneGame, 0x8

dlabel D_8010C0B0_1565E0_CraneGame
    /* 8010C0B0 */ .space 0x08

nonmatching D_8010C0B8_1565E8_CraneGame, 0x8

dlabel D_8010C0B8_1565E8_CraneGame
    /* 8010C0B8 */ .space 0x08

nonmatching D_8010C0C0_1565F0_CraneGame, 0x10

dlabel D_8010C0C0_1565F0_CraneGame
    /* 8010C0C0 */ .space 0x10

nonmatching D_8010C0D0_156600_CraneGame, 0x8

dlabel D_8010C0D0_156600_CraneGame
    /* 8010C0D0 */ .space 0x08

nonmatching D_8010C0D8_156608_CraneGame, 0x8

dlabel D_8010C0D8_156608_CraneGame
    /* 8010C0D8 */ .space 0x08

nonmatching D_8010C0E0_156610_CraneGame, 0x8

dlabel D_8010C0E0_156610_CraneGame
    /* 8010C0E0 */ .space 0x08

nonmatching D_8010C0E8_156618_CraneGame, 0x8

dlabel D_8010C0E8_156618_CraneGame
    /* 8010C0E8 */ .space 0x08

nonmatching D_8010C0F0_156620_CraneGame, 0x8

dlabel D_8010C0F0_156620_CraneGame
    /* 8010C0F0 */ .space 0x08

nonmatching D_8010C0F8_156628_CraneGame, 0x8

dlabel D_8010C0F8_156628_CraneGame
    /* 8010C0F8 */ .space 0x08

nonmatching D_8010C100_156630_CraneGame, 0x8

dlabel D_8010C100_156630_CraneGame
    /* 8010C100 */ .space 0x08

nonmatching D_8010C108_156638_CraneGame, 0x8

dlabel D_8010C108_156638_CraneGame
    /* 8010C108 */ .space 0x08

nonmatching D_8010C110_156640_CraneGame, 0x8

dlabel D_8010C110_156640_CraneGame
    /* 8010C110 */ .space 0x08

nonmatching D_8010C118_156648_CraneGame, 0x8

dlabel D_8010C118_156648_CraneGame
    /* 8010C118 */ .space 0x08

nonmatching D_8010C120_156650_CraneGame, 0x8

dlabel D_8010C120_156650_CraneGame
    /* 8010C120 */ .space 0x08

nonmatching D_8010C128_156658_CraneGame, 0x8

dlabel D_8010C128_156658_CraneGame
    /* 8010C128 */ .space 0x08

nonmatching D_8010C130_156660_CraneGame, 0x8

dlabel D_8010C130_156660_CraneGame
    /* 8010C130 */ .space 0x08

nonmatching D_8010C138_156668_CraneGame, 0x8

dlabel D_8010C138_156668_CraneGame
    /* 8010C138 */ .space 0x08

nonmatching D_8010C140_156670_CraneGame, 0x8

dlabel D_8010C140_156670_CraneGame
    /* 8010C140 */ .space 0x08

nonmatching D_8010C148_156678_CraneGame, 0x8

dlabel D_8010C148_156678_CraneGame
    /* 8010C148 */ .space 0x08

nonmatching D_8010C150_156680_CraneGame, 0x8

dlabel D_8010C150_156680_CraneGame
    /* 8010C150 */ .space 0x08

nonmatching D_8010C158_156688_CraneGame, 0x18

dlabel D_8010C158_156688_CraneGame
    /* 8010C158 */ .space 0x18

nonmatching D_8010C170_1566A0_CraneGame, 0x4

dlabel D_8010C170_1566A0_CraneGame
    /* 8010C170 */ .space 0x04

nonmatching D_8010C174_1566A4_CraneGame, 0x2

dlabel D_8010C174_1566A4_CraneGame
    /* 8010C174 */ .space 0x02

nonmatching D_8010C176_1566A6_CraneGame, 0x2

dlabel D_8010C176_1566A6_CraneGame
    /* 8010C176 */ .space 0x02

nonmatching D_8010C178_1566A8_CraneGame, 0x2

dlabel D_8010C178_1566A8_CraneGame
    /* 8010C178 */ .space 0x02

nonmatching D_8010C17A_1566AA_CraneGame, 0x2

dlabel D_8010C17A_1566AA_CraneGame
    /* 8010C17A */ .space 0x02

nonmatching D_8010C17C_1566AC_CraneGame, 0x2

dlabel D_8010C17C_1566AC_CraneGame
    /* 8010C17C */ .space 0x02

nonmatching D_8010C17E_1566AE_CraneGame, 0x2

dlabel D_8010C17E_1566AE_CraneGame
    /* 8010C17E */ .space 0x02

nonmatching D_8010C180_1566B0_CraneGame, 0x2

dlabel D_8010C180_1566B0_CraneGame
    /* 8010C180 */ .space 0x02

nonmatching D_8010C182_1566B2_CraneGame, 0x2

dlabel D_8010C182_1566B2_CraneGame
    /* 8010C182 */ .space 0x02

nonmatching D_8010C184_1566B4_CraneGame, 0x2

dlabel D_8010C184_1566B4_CraneGame
    /* 8010C184 */ .space 0x02

nonmatching D_8010C186_1566B6_CraneGame, 0x2

dlabel D_8010C186_1566B6_CraneGame
    /* 8010C186 */ .space 0x02

nonmatching D_8010C188_1566B8_CraneGame, 0xC

dlabel D_8010C188_1566B8_CraneGame
    /* 8010C188 */ .space 0x0C

nonmatching D_8010C194_1566C4_CraneGame, 0x1

dlabel D_8010C194_1566C4_CraneGame
    /* 8010C194 */ .space 0x01

nonmatching D_8010C195_1566C5_CraneGame, 0x1

dlabel D_8010C195_1566C5_CraneGame
    /* 8010C195 */ .space 0x01

nonmatching D_8010C196_1566C6_CraneGame, 0x6

dlabel D_8010C196_1566C6_CraneGame
    /* 8010C196 */ .space 0x06

nonmatching D_8010C19C_1566CC_CraneGame, 0x2

dlabel D_8010C19C_1566CC_CraneGame
    /* 8010C19C */ .space 0x02

nonmatching D_8010C19E_1566CE_CraneGame, 0x2

dlabel D_8010C19E_1566CE_CraneGame
    /* 8010C19E */ .space 0x02

nonmatching D_8010C1A0_1566D0_CraneGame, 0x4

dlabel D_8010C1A0_1566D0_CraneGame
    /* 8010C1A0 */ .space 0x04

nonmatching D_8010C1A4_1566D4_CraneGame, 0x4

dlabel D_8010C1A4_1566D4_CraneGame
    /* 8010C1A4 */ .space 0x04

nonmatching D_8010C1A8_1566D8_CraneGame, 0x4

dlabel D_8010C1A8_1566D8_CraneGame
    /* 8010C1A8 */ .space 0x04

nonmatching D_8010C1AC_1566DC_CraneGame, 0x34

dlabel D_8010C1AC_1566DC_CraneGame
    /* 8010C1AC */ .space 0x34

nonmatching D_8010C1E0_156710_CraneGame, 0x20

dlabel D_8010C1E0_156710_CraneGame
    /* 8010C1E0 */ .space 0x20

nonmatching D_8010C200_156730_CraneGame, 0x4

dlabel D_8010C200_156730_CraneGame
    /* 8010C200 */ .space 0x04

nonmatching D_8010C204_156734_CraneGame, 0x34

dlabel D_8010C204_156734_CraneGame
    /* 8010C204 */ .space 0x34

nonmatching D_8010C238_156768_CraneGame, 0x1C

dlabel D_8010C238_156768_CraneGame
    /* 8010C238 */ .space 0x1C

nonmatching D_8010C254_156784_CraneGame, 0x4

dlabel D_8010C254_156784_CraneGame
    /* 8010C254 */ .space 0x04

nonmatching D_8010C258_156788_CraneGame, 0x8

dlabel D_8010C258_156788_CraneGame
    /* 8010C258 */ .space 0x08

nonmatching D_8010C260_156790_CraneGame, 0x2

dlabel D_8010C260_156790_CraneGame
    /* 8010C260 */ .space 0x02

nonmatching D_8010C262_156792_CraneGame, 0x2

dlabel D_8010C262_156792_CraneGame
    /* 8010C262 */ .space 0x02

nonmatching D_8010C264_156794_CraneGame, 0x4

dlabel D_8010C264_156794_CraneGame
    /* 8010C264 */ .space 0x04

nonmatching D_8010C268_156798_CraneGame, 0x80

dlabel D_8010C268_156798_CraneGame
    /* 8010C268 */ .space 0x80

nonmatching D_8010C2E8_156818_CraneGame, 0x4

dlabel D_8010C2E8_156818_CraneGame
    /* 8010C2E8 */ .space 0x04

nonmatching D_8010C2EC_15681C_CraneGame, 0x1FC

dlabel D_8010C2EC_15681C_CraneGame
    /* 8010C2EC */ .space 0x1FC

nonmatching D_8010C4E8_156A18_CraneGame, 0x4

dlabel D_8010C4E8_156A18_CraneGame
    /* 8010C4E8 */ .space 0x04

nonmatching D_8010C4EC_156A1C_CraneGame, 0x4

dlabel D_8010C4EC_156A1C_CraneGame
    /* 8010C4EC */ .space 0x04

nonmatching D_8010C4F0_156A20_CraneGame, 0x2F8

dlabel D_8010C4F0_156A20_CraneGame
    /* 8010C4F0 */ .space 0x2F8

nonmatching D_8010C7E8_156D18_CraneGame, 0x100

dlabel D_8010C7E8_156D18_CraneGame
    /* 8010C7E8 */ .space 0x100

nonmatching D_8010C8E8_156E18_CraneGame, 0x4

dlabel D_8010C8E8_156E18_CraneGame
    /* 8010C8E8 */ .space 0x04

nonmatching D_8010C8EC_156E1C_CraneGame, 0x4

dlabel D_8010C8EC_156E1C_CraneGame
    /* 8010C8EC */ .space 0x04

nonmatching D_8010C8F0_156E20_CraneGame, 0x4

dlabel D_8010C8F0_156E20_CraneGame
    /* 8010C8F0 */ .space 0x04

nonmatching D_8010C8F4_156E24_CraneGame, 0x4

dlabel D_8010C8F4_156E24_CraneGame
    /* 8010C8F4 */ .space 0x04

nonmatching D_8010C8F8_156E28_CraneGame, 0xC

dlabel D_8010C8F8_156E28_CraneGame
    /* 8010C8F8 */ .space 0x0C

nonmatching D_8010C904_156E34_CraneGame, 0x4

dlabel D_8010C904_156E34_CraneGame
    /* 8010C904 */ .space 0x04

nonmatching D_8010C908_156E38_CraneGame, 0x4

dlabel D_8010C908_156E38_CraneGame
    /* 8010C908 */ .space 0x04

nonmatching D_8010C90C_156E3C_CraneGame, 0x4

dlabel D_8010C90C_156E3C_CraneGame
    /* 8010C90C */ .space 0x04

nonmatching D_8010C910_156E40_CraneGame, 0xC0

dlabel D_8010C910_156E40_CraneGame
    /* 8010C910 */ .space 0xC0

nonmatching D_8010C9D0_156F00_CraneGame, 0xC0

dlabel D_8010C9D0_156F00_CraneGame
    /* 8010C9D0 */ .space 0xC0

nonmatching D_8010CA90_156FC0_CraneGame, 0x4

dlabel D_8010CA90_156FC0_CraneGame
    /* 8010CA90 */ .space 0x04

nonmatching D_8010CA94_156FC4_CraneGame, 0x4

dlabel D_8010CA94_156FC4_CraneGame
    /* 8010CA94 */ .space 0x04

nonmatching D_8010CA98_156FC8_CraneGame, 0x4

dlabel D_8010CA98_156FC8_CraneGame
    /* 8010CA98 */ .space 0x04

nonmatching D_8010CA9C_156FCC_CraneGame, 0x4

dlabel D_8010CA9C_156FCC_CraneGame
    /* 8010CA9C */ .space 0x04

nonmatching D_8010CAA0_156FD0_CraneGame, 0x2

dlabel D_8010CAA0_156FD0_CraneGame
    /* 8010CAA0 */ .space 0x02

nonmatching D_8010CAA2_156FD2_CraneGame, 0x2

dlabel D_8010CAA2_156FD2_CraneGame
    /* 8010CAA2 */ .space 0x02

nonmatching D_8010CAA4_156FD4_CraneGame, 0x4

dlabel D_8010CAA4_156FD4_CraneGame
    /* 8010CAA4 */ .space 0x04

nonmatching D_8010CAA8_156FD8_CraneGame, 0x42

dlabel D_8010CAA8_156FD8_CraneGame
    /* 8010CAA8 */ .space 0x42

nonmatching D_8010CAEA_15701A_CraneGame, 0x2

dlabel D_8010CAEA_15701A_CraneGame
    /* 8010CAEA */ .space 0x02

nonmatching D_8010CAEC_15701C_CraneGame, 0x4

dlabel D_8010CAEC_15701C_CraneGame
    /* 8010CAEC */ .space 0x04

nonmatching D_8010CAF0_157020_CraneGame, 0x10

dlabel D_8010CAF0_157020_CraneGame
    /* 8010CAF0 */ .space 0x10

nonmatching D_8010CB00_157030_CraneGame, 0x8

dlabel D_8010CB00_157030_CraneGame
    /* 8010CB00 */ .space 0x08

nonmatching D_8010CB08_157038_CraneGame, 0x2

dlabel D_8010CB08_157038_CraneGame
    /* 8010CB08 */ .space 0x02

nonmatching D_8010CB0A_15703A_CraneGame, 0x1

dlabel D_8010CB0A_15703A_CraneGame
    /* 8010CB0A */ .space 0x01

nonmatching D_8010CB0B_15703B_CraneGame, 0x1

dlabel D_8010CB0B_15703B_CraneGame
    /* 8010CB0B */ .space 0x01

nonmatching D_8010CB0C_15703C_CraneGame, 0x4

dlabel D_8010CB0C_15703C_CraneGame
    /* 8010CB0C */ .space 0x04

nonmatching D_8010CB10_157040_CraneGame, 0x2F8

dlabel D_8010CB10_157040_CraneGame
    /* 8010CB10 */ .space 0x2F8

nonmatching D_8010CE08_157338_CraneGame, 0x4

dlabel D_8010CE08_157338_CraneGame
    /* 8010CE08 */ .space 0x04

nonmatching D_8010CE0C_15733C_CraneGame, 0x4

dlabel D_8010CE0C_15733C_CraneGame
    /* 8010CE0C */ .space 0x04

nonmatching D_8010CE10_157340_CraneGame, 0x20

dlabel D_8010CE10_157340_CraneGame
    /* 8010CE10 */ .space 0x20

nonmatching D_8010CE30_157360_CraneGame, 0x400

dlabel D_8010CE30_157360_CraneGame
    /* 8010CE30 */ .space 0x400

nonmatching D_8010D230_157760_CraneGame, 0x4

dlabel D_8010D230_157760_CraneGame
    /* 8010D230 */ .space 0x04

nonmatching D_8010D234_157764_CraneGame, 0x7E9C

dlabel D_8010D234_157764_CraneGame
    /* 8010D234 */ .space 0x7E9C
