.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80108AF0_2386E0_BombsAway, 0x4

glabel D_80108AF0_2386E0_BombsAway
    /* 80108AF0 */ .space 0x04

nonmatching D_80108AF4_2386E4_BombsAway, 0x4

dlabel D_80108AF4_2386E4_BombsAway
    /* 80108AF4 */ .space 0x04

nonmatching D_80108AF8_2386E8_BombsAway, 0x4

dlabel D_80108AF8_2386E8_BombsAway
    /* 80108AF8 */ .space 0x04

nonmatching D_80108AFC_2386EC_BombsAway, 0x1

dlabel D_80108AFC_2386EC_BombsAway
    /* 80108AFC */ .space 0x01

nonmatching D_80108AFD_2386ED_BombsAway, 0x1

dlabel D_80108AFD_2386ED_BombsAway
    /* 80108AFD */ .space 0x01

nonmatching D_80108AFE_2386EE_BombsAway, 0x1

dlabel D_80108AFE_2386EE_BombsAway
    /* 80108AFE */ .space 0x01

nonmatching D_80108AFF_2386EF_BombsAway, 0x5

dlabel D_80108AFF_2386EF_BombsAway
    /* 80108AFF */ .space 0x05

nonmatching D_80108B04_2386F4_BombsAway, 0x10

dlabel D_80108B04_2386F4_BombsAway
    /* 80108B04 */ .space 0x10

nonmatching D_80108B14_238704_BombsAway, 0x4

dlabel D_80108B14_238704_BombsAway
    /* 80108B14 */ .space 0x04

nonmatching D_80108B18_238708_BombsAway, 0x4

dlabel D_80108B18_238708_BombsAway
    /* 80108B18 */ .space 0x04

nonmatching D_80108B1C_23870C_BombsAway, 0x8

dlabel D_80108B1C_23870C_BombsAway
    /* 80108B1C */ .space 0x08

nonmatching D_80108B24_238714_BombsAway, 0x20

dlabel D_80108B24_238714_BombsAway
    /* 80108B24 */ .space 0x20

nonmatching D_80108B44_238734_BombsAway, 0x8

dlabel D_80108B44_238734_BombsAway
    /* 80108B44 */ .space 0x08

nonmatching D_80108B4C_23873C_BombsAway, 0x4

dlabel D_80108B4C_23873C_BombsAway
    /* 80108B4C */ .space 0x04

nonmatching D_80108B50_238740_BombsAway, 0x4

dlabel D_80108B50_238740_BombsAway
    /* 80108B50 */ .space 0x04

nonmatching D_80108B54_238744_BombsAway, 0x4

dlabel D_80108B54_238744_BombsAway
    /* 80108B54 */ .space 0x04

nonmatching D_80108B58_238748_BombsAway, 0x4

dlabel D_80108B58_238748_BombsAway
    /* 80108B58 */ .space 0x04

nonmatching D_80108B5C_23874C_BombsAway, 0x4

dlabel D_80108B5C_23874C_BombsAway
    /* 80108B5C */ .space 0x04

nonmatching D_80108B60_238750_BombsAway, 0x4

dlabel D_80108B60_238750_BombsAway
    /* 80108B60 */ .space 0x04

nonmatching D_80108B64_238754_BombsAway, 0x4

dlabel D_80108B64_238754_BombsAway
    /* 80108B64 */ .space 0x04

nonmatching D_80108B68_238758_BombsAway, 0x3

dlabel D_80108B68_238758_BombsAway
    /* 80108B68 */ .space 0x03

nonmatching D_80108B6B_23875B_BombsAway, 0x1

dlabel D_80108B6B_23875B_BombsAway
    /* 80108B6B */ .space 0x01

nonmatching D_80108B6C_23875C_BombsAway, 0x3

dlabel D_80108B6C_23875C_BombsAway
    /* 80108B6C */ .space 0x03

nonmatching D_80108B6F_23875F_BombsAway, 0x1

dlabel D_80108B6F_23875F_BombsAway
    /* 80108B6F */ .space 0x01

nonmatching D_80108B70_238760_BombsAway, 0x3

dlabel D_80108B70_238760_BombsAway
    /* 80108B70 */ .space 0x03

nonmatching D_80108B73_238763_BombsAway, 0x1

dlabel D_80108B73_238763_BombsAway
    /* 80108B73 */ .space 0x01

nonmatching D_80108B74_238764_BombsAway, 0x4

dlabel D_80108B74_238764_BombsAway
    /* 80108B74 */ .space 0x04

nonmatching D_80108B78_238768_BombsAway, 0x4

dlabel D_80108B78_238768_BombsAway
    /* 80108B78 */ .space 0x04

nonmatching D_80108B7C_23876C_BombsAway, 0x4

dlabel D_80108B7C_23876C_BombsAway
    /* 80108B7C */ .space 0x04

nonmatching D_80108B80_238770_BombsAway, 0x4

dlabel D_80108B80_238770_BombsAway
    /* 80108B80 */ .space 0x04

nonmatching D_80108B84_238774_BombsAway, 0x4

dlabel D_80108B84_238774_BombsAway
    /* 80108B84 */ .space 0x04

nonmatching D_80108B88_238778_BombsAway, 0x4

dlabel D_80108B88_238778_BombsAway
    /* 80108B88 */ .space 0x04

nonmatching D_80108B8C_23877C_BombsAway, 0x4

dlabel D_80108B8C_23877C_BombsAway
    /* 80108B8C */ .space 0x04

nonmatching D_80108B90_238780_BombsAway, 0x4

dlabel D_80108B90_238780_BombsAway
    /* 80108B90 */ .space 0x04

nonmatching D_80108B94_238784_BombsAway, 0x4

dlabel D_80108B94_238784_BombsAway
    /* 80108B94 */ .space 0x04

nonmatching D_80108B98_238788_BombsAway, 0x4

dlabel D_80108B98_238788_BombsAway
    /* 80108B98 */ .space 0x04

nonmatching D_80108B9C_23878C_BombsAway, 0x4

dlabel D_80108B9C_23878C_BombsAway
    /* 80108B9C */ .space 0x04

nonmatching D_80108BA0_238790_BombsAway, 0x4

dlabel D_80108BA0_238790_BombsAway
    /* 80108BA0 */ .space 0x04

nonmatching D_80108BA4_238794_BombsAway, 0x4

dlabel D_80108BA4_238794_BombsAway
    /* 80108BA4 */ .space 0x04

nonmatching D_80108BA8_238798_BombsAway, 0x4

dlabel D_80108BA8_238798_BombsAway
    /* 80108BA8 */ .space 0x04

nonmatching D_80108BAC_23879C_BombsAway, 0x4

dlabel D_80108BAC_23879C_BombsAway
    /* 80108BAC */ .space 0x04

nonmatching D_80108BB0_2387A0_BombsAway, 0x4

dlabel D_80108BB0_2387A0_BombsAway
    /* 80108BB0 */ .space 0x04

nonmatching D_80108BB4_2387A4_BombsAway, 0x4

dlabel D_80108BB4_2387A4_BombsAway
    /* 80108BB4 */ .space 0x04

nonmatching D_80108BB8_2387A8_BombsAway, 0x10

dlabel D_80108BB8_2387A8_BombsAway
    /* 80108BB8 */ .space 0x10

nonmatching D_80108BC8_2387B8_BombsAway, 0x4

dlabel D_80108BC8_2387B8_BombsAway
    /* 80108BC8 */ .space 0x04

nonmatching D_80108BCC_2387BC_BombsAway, 0x4

dlabel D_80108BCC_2387BC_BombsAway
    /* 80108BCC */ .space 0x04

nonmatching D_80108BD0_2387C0_BombsAway, 0x4

dlabel D_80108BD0_2387C0_BombsAway
    /* 80108BD0 */ .space 0x04

nonmatching D_80108BD4_2387C4_BombsAway, 0x4

dlabel D_80108BD4_2387C4_BombsAway
    /* 80108BD4 */ .space 0x04

nonmatching D_80108BD8_2387C8_BombsAway, 0x4

dlabel D_80108BD8_2387C8_BombsAway
    /* 80108BD8 */ .space 0x04

nonmatching D_80108BDC_2387CC_BombsAway, 0x4

dlabel D_80108BDC_2387CC_BombsAway
    /* 80108BDC */ .space 0x04

nonmatching D_80108BE0_2387D0_BombsAway, 0x4

dlabel D_80108BE0_2387D0_BombsAway
    /* 80108BE0 */ .space 0x04

nonmatching D_80108BE4_2387D4_BombsAway, 0x4

dlabel D_80108BE4_2387D4_BombsAway
    /* 80108BE4 */ .space 0x04

nonmatching D_80108BE8_2387D8_BombsAway, 0x4

dlabel D_80108BE8_2387D8_BombsAway
    /* 80108BE8 */ .space 0x04

nonmatching D_80108BEC_2387DC_BombsAway, 0x4

dlabel D_80108BEC_2387DC_BombsAway
    /* 80108BEC */ .space 0x04

nonmatching D_80108BF0_2387E0_BombsAway, 0x4

dlabel D_80108BF0_2387E0_BombsAway
    /* 80108BF0 */ .space 0x04

nonmatching D_80108BF4_2387E4_BombsAway, 0x4

dlabel D_80108BF4_2387E4_BombsAway
    /* 80108BF4 */ .space 0x04

nonmatching D_80108BF8_2387E8_BombsAway, 0x4

dlabel D_80108BF8_2387E8_BombsAway
    /* 80108BF8 */ .space 0x04

nonmatching D_80108BFC_2387EC_BombsAway, 0x4

dlabel D_80108BFC_2387EC_BombsAway
    /* 80108BFC */ .space 0x04

nonmatching D_80108C00_2387F0_BombsAway, 0x4

dlabel D_80108C00_2387F0_BombsAway
    /* 80108C00 */ .space 0x04

nonmatching D_80108C04_2387F4_BombsAway, 0x4

dlabel D_80108C04_2387F4_BombsAway
    /* 80108C04 */ .space 0x04

nonmatching D_80108C08_2387F8_BombsAway, 0x1C

dlabel D_80108C08_2387F8_BombsAway
    /* 80108C08 */ .space 0x1C

nonmatching D_80108C24_238814_BombsAway, 0x10

dlabel D_80108C24_238814_BombsAway
    /* 80108C24 */ .space 0x10

nonmatching D_80108C34_238824_BombsAway, 0x2C

dlabel D_80108C34_238824_BombsAway
    /* 80108C34 */ .space 0x2C

nonmatching D_80108C60_238850_BombsAway, 0x2

dlabel D_80108C60_238850_BombsAway
    /* 80108C60 */ .space 0x02

nonmatching D_80108C62_238852_BombsAway, 0x2

dlabel D_80108C62_238852_BombsAway
    /* 80108C62 */ .space 0x02

nonmatching D_80108C64_238854_BombsAway, 0x2

dlabel D_80108C64_238854_BombsAway
    /* 80108C64 */ .space 0x02

nonmatching D_80108C66_238856_BombsAway, 0x2

dlabel D_80108C66_238856_BombsAway
    /* 80108C66 */ .space 0x02

nonmatching D_80108C68_238858_BombsAway, 0x10

dlabel D_80108C68_238858_BombsAway
    /* 80108C68 */ .space 0x10

nonmatching D_80108C78_238868_BombsAway, 0x18

dlabel D_80108C78_238868_BombsAway
    /* 80108C78 */ .space 0x18

nonmatching D_80108C90_238880_BombsAway, 0x14

dlabel D_80108C90_238880_BombsAway
    /* 80108C90 */ .space 0x14

nonmatching D_80108CA4_238894_BombsAway, 0x2

dlabel D_80108CA4_238894_BombsAway
    /* 80108CA4 */ .space 0x02

nonmatching D_80108CA6_238896_BombsAway, 0xA

dlabel D_80108CA6_238896_BombsAway
    /* 80108CA6 */ .space 0x0A

nonmatching D_80108CB0_2388A0_BombsAway, 0x18

dlabel D_80108CB0_2388A0_BombsAway
    /* 80108CB0 */ .space 0x18

nonmatching D_80108CC8_2388B8_BombsAway, 0x8

dlabel D_80108CC8_2388B8_BombsAway
    /* 80108CC8 */ .space 0x08

nonmatching D_80108CD0_2388C0_BombsAway, 0x8

dlabel D_80108CD0_2388C0_BombsAway
    /* 80108CD0 */ .space 0x08

nonmatching D_80108CD8_2388C8_BombsAway, 0x8

dlabel D_80108CD8_2388C8_BombsAway
    /* 80108CD8 */ .space 0x08

nonmatching D_80108CE0_2388D0_BombsAway, 0x8

dlabel D_80108CE0_2388D0_BombsAway
    /* 80108CE0 */ .space 0x08

nonmatching D_80108CE8_2388D8_BombsAway, 0x8

dlabel D_80108CE8_2388D8_BombsAway
    /* 80108CE8 */ .space 0x08

nonmatching D_80108CF0_2388E0_BombsAway, 0x8

dlabel D_80108CF0_2388E0_BombsAway
    /* 80108CF0 */ .space 0x08

nonmatching D_80108CF8_2388E8_BombsAway, 0x8

dlabel D_80108CF8_2388E8_BombsAway
    /* 80108CF8 */ .space 0x08

nonmatching D_80108D00_2388F0_BombsAway, 0x8

dlabel D_80108D00_2388F0_BombsAway
    /* 80108D00 */ .space 0x08

nonmatching D_80108D08_2388F8_BombsAway, 0x8

dlabel D_80108D08_2388F8_BombsAway
    /* 80108D08 */ .space 0x08

nonmatching D_80108D10_238900_BombsAway, 0x8

dlabel D_80108D10_238900_BombsAway
    /* 80108D10 */ .space 0x08

nonmatching D_80108D18_238908_BombsAway, 0x8

dlabel D_80108D18_238908_BombsAway
    /* 80108D18 */ .space 0x08

nonmatching D_80108D20_238910_BombsAway, 0x8

dlabel D_80108D20_238910_BombsAway
    /* 80108D20 */ .space 0x08

nonmatching D_80108D28_238918_BombsAway, 0x50

dlabel D_80108D28_238918_BombsAway
    /* 80108D28 */ .space 0x50

nonmatching jtbl_80108D78_238968_BombsAway, 0x18

dlabel jtbl_80108D78_238968_BombsAway
    /* 80108D78 */ .space 0x18

nonmatching D_80108D90_238980_BombsAway, 0x12

dlabel D_80108D90_238980_BombsAway
    /* 80108D90 */ .space 0x12

nonmatching D_80108DA2_238992_BombsAway, 0x62DE

dlabel D_80108DA2_238992_BombsAway
    /* 80108DA2 */ .space 0x62DE
