.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80108840_3252C0_LightsOut2P, 0x2

dlabel D_80108840_3252C0_LightsOut2P
    /* 80108840 */ .space 0x02

nonmatching D_80108842_3252C2_LightsOut2P, 0x2

dlabel D_80108842_3252C2_LightsOut2P
    /* 80108842 */ .space 0x02

nonmatching D_80108844_3252C4_LightsOut2P, 0x2

dlabel D_80108844_3252C4_LightsOut2P
    /* 80108844 */ .space 0x02

nonmatching D_80108846_3252C6_LightsOut2P, 0x1C

dlabel D_80108846_3252C6_LightsOut2P
    /* 80108846 */ .space 0x1C

nonmatching D_80108862_3252E2_LightsOut2P, 0x1BE

dlabel D_80108862_3252E2_LightsOut2P
    /* 80108862 */ .space 0x1BE

nonmatching D_80108A20_3254A0_LightsOut2P, 0x18

dlabel D_80108A20_3254A0_LightsOut2P
    /* 80108A20 */ .space 0x18

nonmatching D_80108A38_3254B8_LightsOut2P, 0x4

dlabel D_80108A38_3254B8_LightsOut2P
    /* 80108A38 */ .space 0x04

nonmatching D_80108A3C_3254BC_LightsOut2P, 0xC

dlabel D_80108A3C_3254BC_LightsOut2P
    /* 80108A3C */ .space 0x0C

nonmatching D_80108A48_3254C8_LightsOut2P, 0xC

dlabel D_80108A48_3254C8_LightsOut2P
    /* 80108A48 */ .space 0x0C

nonmatching D_80108A54_3254D4_LightsOut2P, 0x24

dlabel D_80108A54_3254D4_LightsOut2P
    /* 80108A54 */ .space 0x24

nonmatching D_80108A78_3254F8_LightsOut2P, 0xC

dlabel D_80108A78_3254F8_LightsOut2P
    /* 80108A78 */ .space 0x0C

nonmatching D_80108A84_325504_LightsOut2P, 0xC

dlabel D_80108A84_325504_LightsOut2P
    /* 80108A84 */ .space 0x0C

nonmatching D_80108A90_325510_LightsOut2P, 0x30

dlabel D_80108A90_325510_LightsOut2P
    /* 80108A90 */ .space 0x30

nonmatching D_80108AC0_325540_LightsOut2P, 0x8

dlabel D_80108AC0_325540_LightsOut2P
    /* 80108AC0 */ .space 0x08

nonmatching D_80108AC8_325548_LightsOut2P, 0x10

dlabel D_80108AC8_325548_LightsOut2P
    /* 80108AC8 */ .space 0x10

nonmatching D_80108AD8_325558_LightsOut2P, 0x2

dlabel D_80108AD8_325558_LightsOut2P
    /* 80108AD8 */ .space 0x02

nonmatching D_80108ADA_32555A_LightsOut2P, 0x2

dlabel D_80108ADA_32555A_LightsOut2P
    /* 80108ADA */ .space 0x02

nonmatching D_80108ADC_32555C_LightsOut2P, 0x2

dlabel D_80108ADC_32555C_LightsOut2P
    /* 80108ADC */ .space 0x02

nonmatching D_80108ADE_32555E_LightsOut2P, 0x12

dlabel D_80108ADE_32555E_LightsOut2P
    /* 80108ADE */ .space 0x12

nonmatching D_80108AF0_325570_LightsOut2P, 0x8

dlabel D_80108AF0_325570_LightsOut2P
    /* 80108AF0 */ .space 0x08

nonmatching D_80108AF8_325578_LightsOut2P, 0x14

dlabel D_80108AF8_325578_LightsOut2P
    /* 80108AF8 */ .space 0x14

nonmatching D_80108B0C_32558C_LightsOut2P, 0x14

dlabel D_80108B0C_32558C_LightsOut2P
    /* 80108B0C */ .space 0x14

nonmatching D_80108B20_3255A0_LightsOut2P, 0x14

dlabel D_80108B20_3255A0_LightsOut2P
    /* 80108B20 */ .space 0x14

nonmatching D_80108B34_3255B4_LightsOut2P, 0xC

dlabel D_80108B34_3255B4_LightsOut2P
    /* 80108B34 */ .space 0x0C

nonmatching D_80108B40_3255C0_LightsOut2P, 0xC

dlabel D_80108B40_3255C0_LightsOut2P
    /* 80108B40 */ .space 0x0C

nonmatching D_80108B4C_3255CC_LightsOut2P, 0x8

dlabel D_80108B4C_3255CC_LightsOut2P
    /* 80108B4C */ .space 0x08

nonmatching func_80108B54_3255D4_LightsOut2P, 0x4

dlabel func_80108B54_3255D4_LightsOut2P
    /* 80108B54 */ .space 0x04

nonmatching jtbl_80108B58_3255D8_LightsOut2P, 0x18

dlabel jtbl_80108B58_3255D8_LightsOut2P
    /* 80108B58 */ .space 0x18

nonmatching D_80108B70_3255F0_LightsOut2P, 0x8

dlabel D_80108B70_3255F0_LightsOut2P
    /* 80108B70 */ .space 0x08

nonmatching D_80108B78_3255F8_LightsOut2P, 0x4

dlabel D_80108B78_3255F8_LightsOut2P
    /* 80108B78 */ .space 0x04

nonmatching D_80108B7C_3255FC_LightsOut2P, 0xC

dlabel D_80108B7C_3255FC_LightsOut2P
    /* 80108B7C */ .space 0x0C

nonmatching D_80108B88_325608_LightsOut2P, 0x18

dlabel D_80108B88_325608_LightsOut2P
    /* 80108B88 */ .space 0x18

nonmatching D_80108BA0_325620_LightsOut2P, 0x10

dlabel D_80108BA0_325620_LightsOut2P
    /* 80108BA0 */ .space 0x10

nonmatching D_80108BB0_325630_LightsOut2P, 0x4

dlabel D_80108BB0_325630_LightsOut2P
    /* 80108BB0 */ .space 0x04

nonmatching D_80108BB4_325634_LightsOut2P, 0xC

dlabel D_80108BB4_325634_LightsOut2P
    /* 80108BB4 */ .space 0x0C

nonmatching D_80108BC0_325640_LightsOut2P, 0x10

dlabel D_80108BC0_325640_LightsOut2P
    /* 80108BC0 */ .space 0x10

nonmatching D_80108BD0_325650_LightsOut2P, 0x8

dlabel D_80108BD0_325650_LightsOut2P
    /* 80108BD0 */ .space 0x08

nonmatching D_80108BD8_325658_LightsOut2P, 0x8

dlabel D_80108BD8_325658_LightsOut2P
    /* 80108BD8 */ .space 0x08

nonmatching D_80108BE0_325660_LightsOut2P, 0x80

dlabel D_80108BE0_325660_LightsOut2P
    /* 80108BE0 */ .space 0x80

nonmatching D_80108C60_3256E0_LightsOut2P, 0x10

dlabel D_80108C60_3256E0_LightsOut2P
    /* 80108C60 */ .space 0x10

nonmatching D_80108C70_3256F0_LightsOut2P, 0x10

dlabel D_80108C70_3256F0_LightsOut2P
    /* 80108C70 */ .space 0x10

nonmatching D_80108C80_325700_LightsOut2P, 0x4

dlabel D_80108C80_325700_LightsOut2P
    /* 80108C80 */ .space 0x04

nonmatching D_80108C84_325704_LightsOut2P, 0x4

dlabel D_80108C84_325704_LightsOut2P
    /* 80108C84 */ .space 0x04

nonmatching D_80108C88_325708_LightsOut2P, 0x2

dlabel D_80108C88_325708_LightsOut2P
    /* 80108C88 */ .space 0x02

nonmatching D_80108C8A_32570A_LightsOut2P, 0x2

dlabel D_80108C8A_32570A_LightsOut2P
    /* 80108C8A */ .space 0x02

nonmatching D_80108C8C_32570C_LightsOut2P, 0x2

dlabel D_80108C8C_32570C_LightsOut2P
    /* 80108C8C */ .space 0x02

nonmatching D_80108C8E_32570E_LightsOut2P, 0x2

dlabel D_80108C8E_32570E_LightsOut2P
    /* 80108C8E */ .space 0x02

nonmatching D_80108C90_325710_LightsOut2P, 0x4

dlabel D_80108C90_325710_LightsOut2P
    /* 80108C90 */ .space 0x04

nonmatching D_80108C94_325714_LightsOut2P, 0x4

dlabel D_80108C94_325714_LightsOut2P
    /* 80108C94 */ .space 0x04

nonmatching D_80108C98_325718_LightsOut2P, 0x4

dlabel D_80108C98_325718_LightsOut2P
    /* 80108C98 */ .space 0x04

nonmatching D_80108C9C_32571C_LightsOut2P, 0x4

dlabel D_80108C9C_32571C_LightsOut2P
    /* 80108C9C */ .space 0x04

nonmatching D_80108CA0_325720_LightsOut2P, 0x4

dlabel D_80108CA0_325720_LightsOut2P
    /* 80108CA0 */ .space 0x04

nonmatching D_80108CA4_325724_LightsOut2P, 0x4

dlabel D_80108CA4_325724_LightsOut2P
    /* 80108CA4 */ .space 0x04

nonmatching D_80108CA8_325728_LightsOut2P, 0x10

dlabel D_80108CA8_325728_LightsOut2P
    /* 80108CA8 */ .space 0x10

nonmatching D_80108CB8_325738_LightsOut2P, 0x8

dlabel D_80108CB8_325738_LightsOut2P
    /* 80108CB8 */ .space 0x08

nonmatching D_80108CC0_325740_LightsOut2P, 0x10

dlabel D_80108CC0_325740_LightsOut2P
    /* 80108CC0 */ .space 0x10

nonmatching D_80108CD0_325750_LightsOut2P, 0x4

dlabel D_80108CD0_325750_LightsOut2P
    /* 80108CD0 */ .space 0x04

nonmatching D_80108CD4_325754_LightsOut2P, 0x4

dlabel D_80108CD4_325754_LightsOut2P
    /* 80108CD4 */ .space 0x04

nonmatching D_80108CD8_325758_LightsOut2P, 0x4

dlabel D_80108CD8_325758_LightsOut2P
    /* 80108CD8 */ .space 0x04

nonmatching D_80108CDC_32575C_LightsOut2P, 0x4

dlabel D_80108CDC_32575C_LightsOut2P
    /* 80108CDC */ .space 0x04

nonmatching D_80108CE0_325760_LightsOut2P, 0x4

dlabel D_80108CE0_325760_LightsOut2P
    /* 80108CE0 */ .space 0x04

nonmatching D_80108CE4_325764_LightsOut2P, 0x4

dlabel D_80108CE4_325764_LightsOut2P
    /* 80108CE4 */ .space 0x04

nonmatching D_80108CE8_325768_LightsOut2P, 0x8

dlabel D_80108CE8_325768_LightsOut2P
    /* 80108CE8 */ .space 0x08

nonmatching D_80108CF0_325770_LightsOut2P, 0x8

dlabel D_80108CF0_325770_LightsOut2P
    /* 80108CF0 */ .space 0x08

nonmatching D_80108CF8_325778_LightsOut2P, 0x258

dlabel D_80108CF8_325778_LightsOut2P
    /* 80108CF8 */ .space 0x258

nonmatching D_80108F50_3259D0_LightsOut2P, 0x4

dlabel D_80108F50_3259D0_LightsOut2P
    /* 80108F50 */ .space 0x04

nonmatching D_80108F54_3259D4_LightsOut2P, 0x4

dlabel D_80108F54_3259D4_LightsOut2P
    /* 80108F54 */ .space 0x04

nonmatching D_80108F58_3259D8_LightsOut2P, 0x4

dlabel D_80108F58_3259D8_LightsOut2P
    /* 80108F58 */ .space 0x04

nonmatching D_80108F5C_3259DC_LightsOut2P, 0x4

dlabel D_80108F5C_3259DC_LightsOut2P
    /* 80108F5C */ .space 0x04

nonmatching D_80108F60_3259E0_LightsOut2P, 0x8

dlabel D_80108F60_3259E0_LightsOut2P
    /* 80108F60 */ .space 0x08

nonmatching D_80108F68_3259E8_LightsOut2P, 0x4

dlabel D_80108F68_3259E8_LightsOut2P
    /* 80108F68 */ .space 0x04

nonmatching D_80108F6C_3259EC_LightsOut2P, 0x14

dlabel D_80108F6C_3259EC_LightsOut2P
    /* 80108F6C */ .space 0x14

nonmatching D_80108F80_325A00_LightsOut2P, 0x4

dlabel D_80108F80_325A00_LightsOut2P
    /* 80108F80 */ .space 0x04

nonmatching D_80108F84_325A04_LightsOut2P, 0xC

dlabel D_80108F84_325A04_LightsOut2P
    /* 80108F84 */ .space 0x0C

nonmatching D_80108F90_325A10_LightsOut2P, 0x2

dlabel D_80108F90_325A10_LightsOut2P
    /* 80108F90 */ .space 0x02

nonmatching D_80108F92_325A12_LightsOut2P, 0x2

dlabel D_80108F92_325A12_LightsOut2P
    /* 80108F92 */ .space 0x02

nonmatching D_80108F94_325A14_LightsOut2P, 0x2

dlabel D_80108F94_325A14_LightsOut2P
    /* 80108F94 */ .space 0x02

nonmatching D_80108F96_325A16_LightsOut2P, 0x2

dlabel D_80108F96_325A16_LightsOut2P
    /* 80108F96 */ .space 0x02

nonmatching D_80108F98_325A18_LightsOut2P, 0x2

dlabel D_80108F98_325A18_LightsOut2P
    /* 80108F98 */ .space 0x02

nonmatching D_80108F9A_325A1A_LightsOut2P, 0x2

dlabel D_80108F9A_325A1A_LightsOut2P
    /* 80108F9A */ .space 0x02

nonmatching D_80108F9C_325A1C_LightsOut2P, 0x2

dlabel D_80108F9C_325A1C_LightsOut2P
    /* 80108F9C */ .space 0x02

nonmatching D_80108F9E_325A1E_LightsOut2P, 0x2

dlabel D_80108F9E_325A1E_LightsOut2P
    /* 80108F9E */ .space 0x02

nonmatching D_80108FA0_325A20_LightsOut2P, 0x8

dlabel D_80108FA0_325A20_LightsOut2P
    /* 80108FA0 */ .space 0x08

nonmatching D_80108FA8_325A28_LightsOut2P, 0x8

dlabel D_80108FA8_325A28_LightsOut2P
    /* 80108FA8 */ .space 0x08

nonmatching D_80108FB0_325A30_LightsOut2P, 0x8

dlabel D_80108FB0_325A30_LightsOut2P
    /* 80108FB0 */ .space 0x08

nonmatching D_80108FB8_325A38_LightsOut2P, 0x2

dlabel D_80108FB8_325A38_LightsOut2P
    /* 80108FB8 */ .space 0x02

nonmatching D_80108FBA_325A3A_LightsOut2P, 0x2

dlabel D_80108FBA_325A3A_LightsOut2P
    /* 80108FBA */ .space 0x02

nonmatching D_80108FBC_325A3C_LightsOut2P, 0x2

dlabel D_80108FBC_325A3C_LightsOut2P
    /* 80108FBC */ .space 0x02

nonmatching D_80108FBE_325A3E_LightsOut2P, 0x2

dlabel D_80108FBE_325A3E_LightsOut2P
    /* 80108FBE */ .space 0x02

nonmatching D_80108FC0_325A40_LightsOut2P, 0x4

dlabel D_80108FC0_325A40_LightsOut2P
    /* 80108FC0 */ .space 0x04

nonmatching D_80108FC4_325A44_LightsOut2P, 0xBCC

dlabel D_80108FC4_325A44_LightsOut2P
    /* 80108FC4 */ .space 0xBCC

nonmatching func_80109B90_326610_LightsOut2P, 0x5130

dlabel func_80109B90_326610_LightsOut2P
    /* 80109B90 */ .space 0x5130
