#ifndef ENUMS_H
#define ENUMS_H

enum CHARACTER_IMAGES {
    CHAR_NONE = -1,
    CHAR_KOOPA_RED = 1,
    CHAR_KOOPA_GREEN = 2,
    CHAR_TOAD = 3,
    CHAR_BOWSER = 4,
    CHAR_BABY_BOWSER = 5,
    CHAR_GOOMBA = 6,
    CHAR_BOO = 7,
};

enum ITEM_IDS {
    ITEM_NONE = 0,
    ITEM_MUSHROOM = 1,
    ITEM_GOLDEN_MUSHROOM = 2,
    ITEM_SKELETON_KEY = 3,
    ITEM_PLUNDER_CHEST = 4,
    ITEM_BOWSER_BOMB = 5,
    ITEM_DUELING_GLOVE = 6,
    ITEM_WARP_BLOCK = 7,
    ITEM_BOO_BELL = 8,
    ITEM_BOWSER_SUIT = 9,
    ITEM_MAGIC_LAMP = 10,
};

enum BOARD_IDS {
    BOARD_WESTERN_LAND = 0,
    BOARD_SPACE_LAND = 1,
    BOARD_PIRATE_LAND = 2,
    BOARD_HORROR_LAND = 3,
    BOARD_MYSTERY_LAND = 4,
    BOARD_BOWSER_LAND = 5,
};

#endif
