.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_8010CA40_1913A0_ToadtressScramble, 0x2

dlabel D_8010CA40_1913A0_ToadtressScramble
    /* 8010CA40 */ .space 0x02

nonmatching D_8010CA42_1913A2_ToadtressScramble, 0xE

dlabel D_8010CA42_1913A2_ToadtressScramble
    /* 8010CA42 */ .space 0x0E

nonmatching D_8010CA50_1913B0_ToadtressScramble, 0x120

dlabel D_8010CA50_1913B0_ToadtressScramble
    /* 8010CA50 */ .space 0x120

nonmatching D_8010CB70_1914D0_ToadtressScramble, 0x4

dlabel D_8010CB70_1914D0_ToadtressScramble
    /* 8010CB70 */ .space 0x04

nonmatching D_8010CB74_1914D4_ToadtressScramble, 0x8

dlabel D_8010CB74_1914D4_ToadtressScramble
    /* 8010CB74 */ .space 0x08

nonmatching D_8010CB7C_1914DC_ToadtressScramble, 0x88

dlabel D_8010CB7C_1914DC_ToadtressScramble
    /* 8010CB7C */ .space 0x88

nonmatching D_8010CC04_191564_ToadtressScramble, 0x4

dlabel D_8010CC04_191564_ToadtressScramble
    /* 8010CC04 */ .space 0x04

nonmatching D_8010CC08_191568_ToadtressScramble, 0x20

dlabel D_8010CC08_191568_ToadtressScramble
    /* 8010CC08 */ .space 0x20

nonmatching D_8010CC28_191588_ToadtressScramble, 0x18

dlabel D_8010CC28_191588_ToadtressScramble
    /* 8010CC28 */ .space 0x18

nonmatching D_8010CC40_1915A0_ToadtressScramble, 0x3C

dlabel D_8010CC40_1915A0_ToadtressScramble
    /* 8010CC40 */ .space 0x3C

nonmatching D_8010CC7C_1915DC_ToadtressScramble, 0x18

dlabel D_8010CC7C_1915DC_ToadtressScramble
    /* 8010CC7C */ .space 0x18

nonmatching D_8010CC94_1915F4_ToadtressScramble, 0x18

dlabel D_8010CC94_1915F4_ToadtressScramble
    /* 8010CC94 */ .space 0x18

nonmatching D_8010CCAC_19160C_ToadtressScramble, 0x18

dlabel D_8010CCAC_19160C_ToadtressScramble
    /* 8010CCAC */ .space 0x18

nonmatching D_8010CCC4_191624_ToadtressScramble, 0x1C

dlabel D_8010CCC4_191624_ToadtressScramble
    /* 8010CCC4 */ .space 0x1C

nonmatching D_8010CCE0_191640_ToadtressScramble, 0x50

dlabel D_8010CCE0_191640_ToadtressScramble
    /* 8010CCE0 */ .space 0x50

nonmatching D_8010CD30_191690_ToadtressScramble, 0x50

dlabel D_8010CD30_191690_ToadtressScramble
    /* 8010CD30 */ .space 0x50

nonmatching D_8010CD80_1916E0_ToadtressScramble, 0xC

dlabel D_8010CD80_1916E0_ToadtressScramble
    /* 8010CD80 */ .space 0x0C

nonmatching D_8010CD8C_1916EC_ToadtressScramble, 0x4

dlabel D_8010CD8C_1916EC_ToadtressScramble
    /* 8010CD8C */ .space 0x04

nonmatching D_8010CD90_1916F0_ToadtressScramble, 0x4

dlabel D_8010CD90_1916F0_ToadtressScramble
    /* 8010CD90 */ .space 0x04

nonmatching D_8010CD94_1916F4_ToadtressScramble, 0x48

dlabel D_8010CD94_1916F4_ToadtressScramble
    /* 8010CD94 */ .space 0x48

nonmatching D_8010CDDC_19173C_ToadtressScramble, 0x48

dlabel D_8010CDDC_19173C_ToadtressScramble
    /* 8010CDDC */ .space 0x48

nonmatching D_8010CE24_191784_ToadtressScramble, 0x6C

dlabel D_8010CE24_191784_ToadtressScramble
    /* 8010CE24 */ .space 0x6C

nonmatching D_8010CE90_1917F0_ToadtressScramble, 0x18

dlabel D_8010CE90_1917F0_ToadtressScramble
    /* 8010CE90 */ .space 0x18

nonmatching D_8010CEA8_191808_ToadtressScramble, 0x48

dlabel D_8010CEA8_191808_ToadtressScramble
    /* 8010CEA8 */ .space 0x48

nonmatching D_8010CEF0_191850_ToadtressScramble, 0x48

dlabel D_8010CEF0_191850_ToadtressScramble
    /* 8010CEF0 */ .space 0x48

nonmatching D_8010CF38_191898_ToadtressScramble, 0x6C

dlabel D_8010CF38_191898_ToadtressScramble
    /* 8010CF38 */ .space 0x6C

nonmatching D_8010CFA4_191904_ToadtressScramble, 0x18

dlabel D_8010CFA4_191904_ToadtressScramble
    /* 8010CFA4 */ .space 0x18

nonmatching D_8010CFBC_19191C_ToadtressScramble, 0x8

dlabel D_8010CFBC_19191C_ToadtressScramble
    /* 8010CFBC */ .space 0x08

nonmatching D_8010CFC4_191924_ToadtressScramble, 0x10

dlabel D_8010CFC4_191924_ToadtressScramble
    /* 8010CFC4 */ .space 0x10

nonmatching D_8010CFD4_191934_ToadtressScramble, 0x1C

dlabel D_8010CFD4_191934_ToadtressScramble
    /* 8010CFD4 */ .space 0x1C

nonmatching jtbl_8010CFF0_191950_ToadtressScramble, 0x40

dlabel jtbl_8010CFF0_191950_ToadtressScramble
    /* 8010CFF0 */ .space 0x40

nonmatching D_8010D030_191990_ToadtressScramble, 0x8

dlabel D_8010D030_191990_ToadtressScramble
    /* 8010D030 */ .space 0x08

nonmatching D_8010D038_191998_ToadtressScramble, 0x8

dlabel D_8010D038_191998_ToadtressScramble
    /* 8010D038 */ .space 0x08

nonmatching D_8010D040_1919A0_ToadtressScramble, 0x8

dlabel D_8010D040_1919A0_ToadtressScramble
    /* 8010D040 */ .space 0x08

nonmatching D_8010D048_1919A8_ToadtressScramble, 0x8

dlabel D_8010D048_1919A8_ToadtressScramble
    /* 8010D048 */ .space 0x08

nonmatching D_8010D050_1919B0_ToadtressScramble, 0x8

dlabel D_8010D050_1919B0_ToadtressScramble
    /* 8010D050 */ .space 0x08

nonmatching D_8010D058_1919B8_ToadtressScramble, 0x8

dlabel D_8010D058_1919B8_ToadtressScramble
    /* 8010D058 */ .space 0x08

nonmatching D_8010D060_1919C0_ToadtressScramble, 0x8

dlabel D_8010D060_1919C0_ToadtressScramble
    /* 8010D060 */ .space 0x08

nonmatching D_8010D068_1919C8_ToadtressScramble, 0x8

dlabel D_8010D068_1919C8_ToadtressScramble
    /* 8010D068 */ .space 0x08

nonmatching D_8010D070_1919D0_ToadtressScramble, 0x8

dlabel D_8010D070_1919D0_ToadtressScramble
    /* 8010D070 */ .space 0x08

nonmatching D_8010D078_1919D8_ToadtressScramble, 0x8

dlabel D_8010D078_1919D8_ToadtressScramble
    /* 8010D078 */ .space 0x08

nonmatching D_8010D080_1919E0_ToadtressScramble, 0x8

dlabel D_8010D080_1919E0_ToadtressScramble
    /* 8010D080 */ .space 0x08

nonmatching D_8010D088_1919E8_ToadtressScramble, 0x8

dlabel D_8010D088_1919E8_ToadtressScramble
    /* 8010D088 */ .space 0x08

nonmatching D_8010D090_1919F0_ToadtressScramble, 0x8

dlabel D_8010D090_1919F0_ToadtressScramble
    /* 8010D090 */ .space 0x08

nonmatching D_8010D098_1919F8_ToadtressScramble, 0x8

dlabel D_8010D098_1919F8_ToadtressScramble
    /* 8010D098 */ .space 0x08

nonmatching D_8010D0A0_191A00_ToadtressScramble, 0x8

dlabel D_8010D0A0_191A00_ToadtressScramble
    /* 8010D0A0 */ .space 0x08

nonmatching D_8010D0A8_191A08_ToadtressScramble, 0x8

dlabel D_8010D0A8_191A08_ToadtressScramble
    /* 8010D0A8 */ .space 0x08

nonmatching D_8010D0B0_191A10_ToadtressScramble, 0x8

dlabel D_8010D0B0_191A10_ToadtressScramble
    /* 8010D0B0 */ .space 0x08

nonmatching D_8010D0B8_191A18_ToadtressScramble, 0x8

dlabel D_8010D0B8_191A18_ToadtressScramble
    /* 8010D0B8 */ .space 0x08

nonmatching D_8010D0C0_191A20_ToadtressScramble, 0x8

dlabel D_8010D0C0_191A20_ToadtressScramble
    /* 8010D0C0 */ .space 0x08

nonmatching D_8010D0C8_191A28_ToadtressScramble, 0x8

dlabel D_8010D0C8_191A28_ToadtressScramble
    /* 8010D0C8 */ .space 0x08

nonmatching D_8010D0D0_191A30_ToadtressScramble, 0x8

dlabel D_8010D0D0_191A30_ToadtressScramble
    /* 8010D0D0 */ .space 0x08

nonmatching D_8010D0D8_191A38_ToadtressScramble, 0x8

dlabel D_8010D0D8_191A38_ToadtressScramble
    /* 8010D0D8 */ .space 0x08

nonmatching D_8010D0E0_191A40_ToadtressScramble, 0x8

dlabel D_8010D0E0_191A40_ToadtressScramble
    /* 8010D0E0 */ .space 0x08

nonmatching D_8010D0E8_191A48_ToadtressScramble, 0x8

dlabel D_8010D0E8_191A48_ToadtressScramble
    /* 8010D0E8 */ .space 0x08

nonmatching D_8010D0F0_191A50_ToadtressScramble, 0x8

dlabel D_8010D0F0_191A50_ToadtressScramble
    /* 8010D0F0 */ .space 0x08

nonmatching D_8010D0F8_191A58_ToadtressScramble, 0x8

dlabel D_8010D0F8_191A58_ToadtressScramble
    /* 8010D0F8 */ .space 0x08

nonmatching D_8010D100_191A60_ToadtressScramble, 0x8

dlabel D_8010D100_191A60_ToadtressScramble
    /* 8010D100 */ .space 0x08

nonmatching D_8010D108_191A68_ToadtressScramble, 0x8

dlabel D_8010D108_191A68_ToadtressScramble
    /* 8010D108 */ .space 0x08

nonmatching D_8010D110_191A70_ToadtressScramble, 0x8

dlabel D_8010D110_191A70_ToadtressScramble
    /* 8010D110 */ .space 0x08

nonmatching D_8010D118_191A78_ToadtressScramble, 0x8

dlabel D_8010D118_191A78_ToadtressScramble
    /* 8010D118 */ .space 0x08

nonmatching D_8010D120_191A80_ToadtressScramble, 0x8

dlabel D_8010D120_191A80_ToadtressScramble
    /* 8010D120 */ .space 0x08

nonmatching D_8010D128_191A88_ToadtressScramble, 0x8

dlabel D_8010D128_191A88_ToadtressScramble
    /* 8010D128 */ .space 0x08

nonmatching D_8010D130_191A90_ToadtressScramble, 0x8

dlabel D_8010D130_191A90_ToadtressScramble
    /* 8010D130 */ .space 0x08

nonmatching D_8010D138_191A98_ToadtressScramble, 0x8

dlabel D_8010D138_191A98_ToadtressScramble
    /* 8010D138 */ .space 0x08

nonmatching D_8010D140_191AA0_ToadtressScramble, 0x3C

dlabel D_8010D140_191AA0_ToadtressScramble
    /* 8010D140 */ .space 0x3C

nonmatching D_8010D17C_191ADC_ToadtressScramble, 0xC

dlabel D_8010D17C_191ADC_ToadtressScramble
    /* 8010D17C */ .space 0x0C

nonmatching jtbl_8010D188_191AE8_ToadtressScramble, 0x30

dlabel jtbl_8010D188_191AE8_ToadtressScramble
    /* 8010D188 */ .space 0x30

nonmatching D_8010D1B8_191B18_ToadtressScramble, 0x8

dlabel D_8010D1B8_191B18_ToadtressScramble
    /* 8010D1B8 */ .space 0x08

nonmatching D_8010D1C0_191B20_ToadtressScramble, 0x8

dlabel D_8010D1C0_191B20_ToadtressScramble
    /* 8010D1C0 */ .space 0x08

nonmatching D_8010D1C8_191B28_ToadtressScramble, 0x8

dlabel D_8010D1C8_191B28_ToadtressScramble
    /* 8010D1C8 */ .space 0x08

nonmatching D_8010D1D0_191B30_ToadtressScramble, 0x8

dlabel D_8010D1D0_191B30_ToadtressScramble
    /* 8010D1D0 */ .space 0x08

nonmatching D_8010D1D8_191B38_ToadtressScramble, 0x8

dlabel D_8010D1D8_191B38_ToadtressScramble
    /* 8010D1D8 */ .space 0x08

nonmatching D_8010D1E0_191B40_ToadtressScramble, 0x8

dlabel D_8010D1E0_191B40_ToadtressScramble
    /* 8010D1E0 */ .space 0x08

nonmatching D_8010D1E8_191B48_ToadtressScramble, 0x8

dlabel D_8010D1E8_191B48_ToadtressScramble
    /* 8010D1E8 */ .space 0x08

nonmatching D_8010D1F0_191B50_ToadtressScramble, 0x8

dlabel D_8010D1F0_191B50_ToadtressScramble
    /* 8010D1F0 */ .space 0x08

nonmatching D_8010D1F8_191B58_ToadtressScramble, 0x8

dlabel D_8010D1F8_191B58_ToadtressScramble
    /* 8010D1F8 */ .space 0x08

nonmatching D_8010D200_191B60_ToadtressScramble, 0x8

dlabel D_8010D200_191B60_ToadtressScramble
    /* 8010D200 */ .space 0x08

nonmatching D_8010D208_191B68_ToadtressScramble, 0x8

dlabel D_8010D208_191B68_ToadtressScramble
    /* 8010D208 */ .space 0x08

nonmatching D_8010D210_191B70_ToadtressScramble, 0x8

dlabel D_8010D210_191B70_ToadtressScramble
    /* 8010D210 */ .space 0x08

nonmatching D_8010D218_191B78_ToadtressScramble, 0x8

dlabel D_8010D218_191B78_ToadtressScramble
    /* 8010D218 */ .space 0x08

nonmatching D_8010D220_191B80_ToadtressScramble, 0x8

dlabel D_8010D220_191B80_ToadtressScramble
    /* 8010D220 */ .space 0x08

nonmatching D_8010D228_191B88_ToadtressScramble, 0x8

dlabel D_8010D228_191B88_ToadtressScramble
    /* 8010D228 */ .space 0x08

nonmatching D_8010D230_191B90_ToadtressScramble, 0x8

dlabel D_8010D230_191B90_ToadtressScramble
    /* 8010D230 */ .space 0x08

nonmatching D_8010D238_191B98_ToadtressScramble, 0x8

dlabel D_8010D238_191B98_ToadtressScramble
    /* 8010D238 */ .space 0x08

nonmatching D_8010D240_191BA0_ToadtressScramble, 0x8

dlabel D_8010D240_191BA0_ToadtressScramble
    /* 8010D240 */ .space 0x08

nonmatching D_8010D248_191BA8_ToadtressScramble, 0x8

dlabel D_8010D248_191BA8_ToadtressScramble
    /* 8010D248 */ .space 0x08

nonmatching D_8010D250_191BB0_ToadtressScramble, 0x8

dlabel D_8010D250_191BB0_ToadtressScramble
    /* 8010D250 */ .space 0x08

nonmatching D_8010D258_191BB8_ToadtressScramble, 0x8

dlabel D_8010D258_191BB8_ToadtressScramble
    /* 8010D258 */ .space 0x08

nonmatching D_8010D260_191BC0_ToadtressScramble, 0x8

dlabel D_8010D260_191BC0_ToadtressScramble
    /* 8010D260 */ .space 0x08

nonmatching D_8010D268_191BC8_ToadtressScramble, 0x8

dlabel D_8010D268_191BC8_ToadtressScramble
    /* 8010D268 */ .space 0x08

nonmatching D_8010D270_191BD0_ToadtressScramble, 0x8

dlabel D_8010D270_191BD0_ToadtressScramble
    /* 8010D270 */ .space 0x08

nonmatching D_8010D278_191BD8_ToadtressScramble, 0x8

dlabel D_8010D278_191BD8_ToadtressScramble
    /* 8010D278 */ .space 0x08

nonmatching D_8010D280_191BE0_ToadtressScramble, 0x8

dlabel D_8010D280_191BE0_ToadtressScramble
    /* 8010D280 */ .space 0x08

nonmatching D_8010D288_191BE8_ToadtressScramble, 0x8

dlabel D_8010D288_191BE8_ToadtressScramble
    /* 8010D288 */ .space 0x08

nonmatching D_8010D290_191BF0_ToadtressScramble, 0x4

dlabel D_8010D290_191BF0_ToadtressScramble
    /* 8010D290 */ .space 0x04

nonmatching D_8010D294_191BF4_ToadtressScramble, 0x4

dlabel D_8010D294_191BF4_ToadtressScramble
    /* 8010D294 */ .space 0x04

nonmatching D_8010D298_191BF8_ToadtressScramble, 0x4

dlabel D_8010D298_191BF8_ToadtressScramble
    /* 8010D298 */ .space 0x04

nonmatching D_8010D29C_191BFC_ToadtressScramble, 0x4

dlabel D_8010D29C_191BFC_ToadtressScramble
    /* 8010D29C */ .space 0x04

nonmatching D_8010D2A0_191C00_ToadtressScramble, 0x8

dlabel D_8010D2A0_191C00_ToadtressScramble
    /* 8010D2A0 */ .space 0x08

nonmatching D_8010D2A8_191C08_ToadtressScramble, 0x8

dlabel D_8010D2A8_191C08_ToadtressScramble
    /* 8010D2A8 */ .space 0x08

nonmatching D_8010D2B0_191C10_ToadtressScramble, 0x8

dlabel D_8010D2B0_191C10_ToadtressScramble
    /* 8010D2B0 */ .space 0x08

nonmatching D_8010D2B8_191C18_ToadtressScramble, 0x8

dlabel D_8010D2B8_191C18_ToadtressScramble
    /* 8010D2B8 */ .space 0x08

nonmatching D_8010D2C0_191C20_ToadtressScramble, 0x8

dlabel D_8010D2C0_191C20_ToadtressScramble
    /* 8010D2C0 */ .space 0x08

nonmatching D_8010D2C8_191C28_ToadtressScramble, 0x8

dlabel D_8010D2C8_191C28_ToadtressScramble
    /* 8010D2C8 */ .space 0x08

nonmatching D_8010D2D0_191C30_ToadtressScramble, 0x8

dlabel D_8010D2D0_191C30_ToadtressScramble
    /* 8010D2D0 */ .space 0x08

nonmatching D_8010D2D8_191C38_ToadtressScramble, 0x8

dlabel D_8010D2D8_191C38_ToadtressScramble
    /* 8010D2D8 */ .space 0x08

nonmatching D_8010D2E0_191C40_ToadtressScramble, 0x8

dlabel D_8010D2E0_191C40_ToadtressScramble
    /* 8010D2E0 */ .space 0x08

nonmatching D_8010D2E8_191C48_ToadtressScramble, 0x8

dlabel D_8010D2E8_191C48_ToadtressScramble
    /* 8010D2E8 */ .space 0x08

nonmatching D_8010D2F0_191C50_ToadtressScramble, 0x8

dlabel D_8010D2F0_191C50_ToadtressScramble
    /* 8010D2F0 */ .space 0x08

nonmatching D_8010D2F8_191C58_ToadtressScramble, 0x8

dlabel D_8010D2F8_191C58_ToadtressScramble
    /* 8010D2F8 */ .space 0x08

nonmatching D_8010D300_191C60_ToadtressScramble, 0x8

dlabel D_8010D300_191C60_ToadtressScramble
    /* 8010D300 */ .space 0x08

nonmatching D_8010D308_191C68_ToadtressScramble, 0x8

dlabel D_8010D308_191C68_ToadtressScramble
    /* 8010D308 */ .space 0x08

nonmatching D_8010D310_191C70_ToadtressScramble, 0x8

dlabel D_8010D310_191C70_ToadtressScramble
    /* 8010D310 */ .space 0x08

nonmatching D_8010D318_191C78_ToadtressScramble, 0x8

dlabel D_8010D318_191C78_ToadtressScramble
    /* 8010D318 */ .space 0x08

nonmatching D_8010D320_191C80_ToadtressScramble, 0x8

dlabel D_8010D320_191C80_ToadtressScramble
    /* 8010D320 */ .space 0x08

nonmatching D_8010D328_191C88_ToadtressScramble, 0x8

dlabel D_8010D328_191C88_ToadtressScramble
    /* 8010D328 */ .space 0x08

nonmatching D_8010D330_191C90_ToadtressScramble, 0x8

dlabel D_8010D330_191C90_ToadtressScramble
    /* 8010D330 */ .space 0x08

nonmatching D_8010D338_191C98_ToadtressScramble, 0x8

dlabel D_8010D338_191C98_ToadtressScramble
    /* 8010D338 */ .space 0x08

nonmatching D_8010D340_191CA0_ToadtressScramble, 0x8

dlabel D_8010D340_191CA0_ToadtressScramble
    /* 8010D340 */ .space 0x08

nonmatching D_8010D348_191CA8_ToadtressScramble, 0x8

dlabel D_8010D348_191CA8_ToadtressScramble
    /* 8010D348 */ .space 0x08

nonmatching D_8010D350_191CB0_ToadtressScramble, 0x8

dlabel D_8010D350_191CB0_ToadtressScramble
    /* 8010D350 */ .space 0x08

nonmatching D_8010D358_191CB8_ToadtressScramble, 0x8

dlabel D_8010D358_191CB8_ToadtressScramble
    /* 8010D358 */ .space 0x08

nonmatching D_8010D360_191CC0_ToadtressScramble, 0x8

dlabel D_8010D360_191CC0_ToadtressScramble
    /* 8010D360 */ .space 0x08

nonmatching D_8010D368_191CC8_ToadtressScramble, 0x8

dlabel D_8010D368_191CC8_ToadtressScramble
    /* 8010D368 */ .space 0x08

nonmatching D_8010D370_191CD0_ToadtressScramble, 0x8

dlabel D_8010D370_191CD0_ToadtressScramble
    /* 8010D370 */ .space 0x08

nonmatching D_8010D378_191CD8_ToadtressScramble, 0x8

dlabel D_8010D378_191CD8_ToadtressScramble
    /* 8010D378 */ .space 0x08

nonmatching D_8010D380_191CE0_ToadtressScramble, 0x8

dlabel D_8010D380_191CE0_ToadtressScramble
    /* 8010D380 */ .space 0x08

nonmatching D_8010D388_191CE8_ToadtressScramble, 0x8

dlabel D_8010D388_191CE8_ToadtressScramble
    /* 8010D388 */ .space 0x08

nonmatching D_8010D390_191CF0_ToadtressScramble, 0x18

dlabel D_8010D390_191CF0_ToadtressScramble
    /* 8010D390 */ .space 0x18

nonmatching D_8010D3A8_191D08_ToadtressScramble, 0x8

dlabel D_8010D3A8_191D08_ToadtressScramble
    /* 8010D3A8 */ .space 0x08

nonmatching D_8010D3B0_191D10_ToadtressScramble, 0x8

dlabel D_8010D3B0_191D10_ToadtressScramble
    /* 8010D3B0 */ .space 0x08

nonmatching D_8010D3B8_191D18_ToadtressScramble, 0x8

dlabel D_8010D3B8_191D18_ToadtressScramble
    /* 8010D3B8 */ .space 0x08

nonmatching D_8010D3C0_191D20_ToadtressScramble, 0x8

dlabel D_8010D3C0_191D20_ToadtressScramble
    /* 8010D3C0 */ .space 0x08

nonmatching D_8010D3C8_191D28_ToadtressScramble, 0x8

dlabel D_8010D3C8_191D28_ToadtressScramble
    /* 8010D3C8 */ .space 0x08

nonmatching D_8010D3D0_191D30_ToadtressScramble, 0x8

dlabel D_8010D3D0_191D30_ToadtressScramble
    /* 8010D3D0 */ .space 0x08

nonmatching D_8010D3D8_191D38_ToadtressScramble, 0x8

dlabel D_8010D3D8_191D38_ToadtressScramble
    /* 8010D3D8 */ .space 0x08

nonmatching D_8010D3E0_191D40_ToadtressScramble, 0x8

dlabel D_8010D3E0_191D40_ToadtressScramble
    /* 8010D3E0 */ .space 0x08

nonmatching D_8010D3E8_191D48_ToadtressScramble, 0x8

dlabel D_8010D3E8_191D48_ToadtressScramble
    /* 8010D3E8 */ .space 0x08

nonmatching D_8010D3F0_191D50_ToadtressScramble, 0x8

dlabel D_8010D3F0_191D50_ToadtressScramble
    /* 8010D3F0 */ .space 0x08

nonmatching D_8010D3F8_191D58_ToadtressScramble, 0x8

dlabel D_8010D3F8_191D58_ToadtressScramble
    /* 8010D3F8 */ .space 0x08

nonmatching D_8010D400_191D60_ToadtressScramble, 0x8

dlabel D_8010D400_191D60_ToadtressScramble
    /* 8010D400 */ .space 0x08

nonmatching D_8010D408_191D68_ToadtressScramble, 0x8

dlabel D_8010D408_191D68_ToadtressScramble
    /* 8010D408 */ .space 0x08

nonmatching D_8010D410_191D70_ToadtressScramble, 0x8

dlabel D_8010D410_191D70_ToadtressScramble
    /* 8010D410 */ .space 0x08

nonmatching D_8010D418_191D78_ToadtressScramble, 0x8

dlabel D_8010D418_191D78_ToadtressScramble
    /* 8010D418 */ .space 0x08

nonmatching D_8010D420_191D80_ToadtressScramble, 0x8

dlabel D_8010D420_191D80_ToadtressScramble
    /* 8010D420 */ .space 0x08

nonmatching D_8010D428_191D88_ToadtressScramble, 0x8

dlabel D_8010D428_191D88_ToadtressScramble
    /* 8010D428 */ .space 0x08

nonmatching D_8010D430_191D90_ToadtressScramble, 0x8

dlabel D_8010D430_191D90_ToadtressScramble
    /* 8010D430 */ .space 0x08

nonmatching D_8010D438_191D98_ToadtressScramble, 0x8

dlabel D_8010D438_191D98_ToadtressScramble
    /* 8010D438 */ .space 0x08

nonmatching D_8010D440_191DA0_ToadtressScramble, 0x8

dlabel D_8010D440_191DA0_ToadtressScramble
    /* 8010D440 */ .space 0x08

nonmatching D_8010D448_191DA8_ToadtressScramble, 0x8

dlabel D_8010D448_191DA8_ToadtressScramble
    /* 8010D448 */ .space 0x08

nonmatching D_8010D450_191DB0_ToadtressScramble, 0x8

dlabel D_8010D450_191DB0_ToadtressScramble
    /* 8010D450 */ .space 0x08

nonmatching D_8010D458_191DB8_ToadtressScramble, 0x8

dlabel D_8010D458_191DB8_ToadtressScramble
    /* 8010D458 */ .space 0x08

nonmatching D_8010D460_191DC0_ToadtressScramble, 0x8

dlabel D_8010D460_191DC0_ToadtressScramble
    /* 8010D460 */ .space 0x08

nonmatching D_8010D468_191DC8_ToadtressScramble, 0x8

dlabel D_8010D468_191DC8_ToadtressScramble
    /* 8010D468 */ .space 0x08

nonmatching D_8010D470_191DD0_ToadtressScramble, 0x8

dlabel D_8010D470_191DD0_ToadtressScramble
    /* 8010D470 */ .space 0x08

nonmatching D_8010D478_191DD8_ToadtressScramble, 0x8

dlabel D_8010D478_191DD8_ToadtressScramble
    /* 8010D478 */ .space 0x08

nonmatching D_8010D480_191DE0_ToadtressScramble, 0x8

dlabel D_8010D480_191DE0_ToadtressScramble
    /* 8010D480 */ .space 0x08

nonmatching D_8010D488_191DE8_ToadtressScramble, 0x8

dlabel D_8010D488_191DE8_ToadtressScramble
    /* 8010D488 */ .space 0x08

nonmatching D_8010D490_191DF0_ToadtressScramble, 0x8

dlabel D_8010D490_191DF0_ToadtressScramble
    /* 8010D490 */ .space 0x08

nonmatching D_8010D498_191DF8_ToadtressScramble, 0x8

dlabel D_8010D498_191DF8_ToadtressScramble
    /* 8010D498 */ .space 0x08

nonmatching D_8010D4A0_191E00_ToadtressScramble, 0x8

dlabel D_8010D4A0_191E00_ToadtressScramble
    /* 8010D4A0 */ .space 0x08

nonmatching D_8010D4A8_191E08_ToadtressScramble, 0x8

dlabel D_8010D4A8_191E08_ToadtressScramble
    /* 8010D4A8 */ .space 0x08

nonmatching D_8010D4B0_191E10_ToadtressScramble, 0x8

dlabel D_8010D4B0_191E10_ToadtressScramble
    /* 8010D4B0 */ .space 0x08

nonmatching D_8010D4B8_191E18_ToadtressScramble, 0x8

dlabel D_8010D4B8_191E18_ToadtressScramble
    /* 8010D4B8 */ .space 0x08

nonmatching D_8010D4C0_191E20_ToadtressScramble, 0x8

dlabel D_8010D4C0_191E20_ToadtressScramble
    /* 8010D4C0 */ .space 0x08

nonmatching D_8010D4C8_191E28_ToadtressScramble, 0x8

dlabel D_8010D4C8_191E28_ToadtressScramble
    /* 8010D4C8 */ .space 0x08

nonmatching D_8010D4D0_191E30_ToadtressScramble, 0x8

dlabel D_8010D4D0_191E30_ToadtressScramble
    /* 8010D4D0 */ .space 0x08

nonmatching D_8010D4D8_191E38_ToadtressScramble, 0x8

dlabel D_8010D4D8_191E38_ToadtressScramble
    /* 8010D4D8 */ .space 0x08

nonmatching D_8010D4E0_191E40_ToadtressScramble, 0x8

dlabel D_8010D4E0_191E40_ToadtressScramble
    /* 8010D4E0 */ .space 0x08

nonmatching D_8010D4E8_191E48_ToadtressScramble, 0x8

dlabel D_8010D4E8_191E48_ToadtressScramble
    /* 8010D4E8 */ .space 0x08

nonmatching D_8010D4F0_191E50_ToadtressScramble, 0x8

dlabel D_8010D4F0_191E50_ToadtressScramble
    /* 8010D4F0 */ .space 0x08

nonmatching D_8010D4F8_191E58_ToadtressScramble, 0x8

dlabel D_8010D4F8_191E58_ToadtressScramble
    /* 8010D4F8 */ .space 0x08

nonmatching D_8010D500_191E60_ToadtressScramble, 0x8

dlabel D_8010D500_191E60_ToadtressScramble
    /* 8010D500 */ .space 0x08

nonmatching D_8010D508_191E68_ToadtressScramble, 0x8

dlabel D_8010D508_191E68_ToadtressScramble
    /* 8010D508 */ .space 0x08

nonmatching D_8010D510_191E70_ToadtressScramble, 0x8

dlabel D_8010D510_191E70_ToadtressScramble
    /* 8010D510 */ .space 0x08

nonmatching D_8010D518_191E78_ToadtressScramble, 0x8

dlabel D_8010D518_191E78_ToadtressScramble
    /* 8010D518 */ .space 0x08

nonmatching D_8010D520_191E80_ToadtressScramble, 0x8

dlabel D_8010D520_191E80_ToadtressScramble
    /* 8010D520 */ .space 0x08

nonmatching D_8010D528_191E88_ToadtressScramble, 0x8

dlabel D_8010D528_191E88_ToadtressScramble
    /* 8010D528 */ .space 0x08

nonmatching D_8010D530_191E90_ToadtressScramble, 0x8

dlabel D_8010D530_191E90_ToadtressScramble
    /* 8010D530 */ .space 0x08

nonmatching D_8010D538_191E98_ToadtressScramble, 0x8

dlabel D_8010D538_191E98_ToadtressScramble
    /* 8010D538 */ .space 0x08

nonmatching D_8010D540_191EA0_ToadtressScramble, 0x8

dlabel D_8010D540_191EA0_ToadtressScramble
    /* 8010D540 */ .space 0x08

nonmatching D_8010D548_191EA8_ToadtressScramble, 0x8

dlabel D_8010D548_191EA8_ToadtressScramble
    /* 8010D548 */ .space 0x08

nonmatching D_8010D550_191EB0_ToadtressScramble, 0x8

dlabel D_8010D550_191EB0_ToadtressScramble
    /* 8010D550 */ .space 0x08

nonmatching D_8010D558_191EB8_ToadtressScramble, 0x8

dlabel D_8010D558_191EB8_ToadtressScramble
    /* 8010D558 */ .space 0x08

nonmatching D_8010D560_191EC0_ToadtressScramble, 0x4

dlabel D_8010D560_191EC0_ToadtressScramble
    /* 8010D560 */ .space 0x04

nonmatching D_8010D564_191EC4_ToadtressScramble, 0x4

dlabel D_8010D564_191EC4_ToadtressScramble
    /* 8010D564 */ .space 0x04

nonmatching D_8010D568_191EC8_ToadtressScramble, 0x8

dlabel D_8010D568_191EC8_ToadtressScramble
    /* 8010D568 */ .space 0x08

nonmatching D_8010D570_191ED0_ToadtressScramble, 0x8

dlabel D_8010D570_191ED0_ToadtressScramble
    /* 8010D570 */ .space 0x08

nonmatching D_8010D578_191ED8_ToadtressScramble, 0x8

dlabel D_8010D578_191ED8_ToadtressScramble
    /* 8010D578 */ .space 0x08

nonmatching D_8010D580_191EE0_ToadtressScramble, 0x8

dlabel D_8010D580_191EE0_ToadtressScramble
    /* 8010D580 */ .space 0x08

nonmatching D_8010D588_191EE8_ToadtressScramble, 0x8

dlabel D_8010D588_191EE8_ToadtressScramble
    /* 8010D588 */ .space 0x08

nonmatching D_8010D590_191EF0_ToadtressScramble, 0x8

dlabel D_8010D590_191EF0_ToadtressScramble
    /* 8010D590 */ .space 0x08

nonmatching D_8010D598_191EF8_ToadtressScramble, 0x8

dlabel D_8010D598_191EF8_ToadtressScramble
    /* 8010D598 */ .space 0x08

nonmatching D_8010D5A0_191F00_ToadtressScramble, 0x8

dlabel D_8010D5A0_191F00_ToadtressScramble
    /* 8010D5A0 */ .space 0x08

nonmatching D_8010D5A8_191F08_ToadtressScramble, 0x8

dlabel D_8010D5A8_191F08_ToadtressScramble
    /* 8010D5A8 */ .space 0x08

nonmatching D_8010D5B0_191F10_ToadtressScramble, 0x8

dlabel D_8010D5B0_191F10_ToadtressScramble
    /* 8010D5B0 */ .space 0x08

nonmatching D_8010D5B8_191F18_ToadtressScramble, 0x8

dlabel D_8010D5B8_191F18_ToadtressScramble
    /* 8010D5B8 */ .space 0x08

nonmatching D_8010D5C0_191F20_ToadtressScramble, 0x8

dlabel D_8010D5C0_191F20_ToadtressScramble
    /* 8010D5C0 */ .space 0x08

nonmatching D_8010D5C8_191F28_ToadtressScramble, 0x8

dlabel D_8010D5C8_191F28_ToadtressScramble
    /* 8010D5C8 */ .space 0x08

nonmatching D_8010D5D0_191F30_ToadtressScramble, 0x8

dlabel D_8010D5D0_191F30_ToadtressScramble
    /* 8010D5D0 */ .space 0x08

nonmatching D_8010D5D8_191F38_ToadtressScramble, 0x8

dlabel D_8010D5D8_191F38_ToadtressScramble
    /* 8010D5D8 */ .space 0x08

nonmatching D_8010D5E0_191F40_ToadtressScramble, 0x8

dlabel D_8010D5E0_191F40_ToadtressScramble
    /* 8010D5E0 */ .space 0x08

nonmatching D_8010D5E8_191F48_ToadtressScramble, 0x8

dlabel D_8010D5E8_191F48_ToadtressScramble
    /* 8010D5E8 */ .space 0x08

nonmatching D_8010D5F0_191F50_ToadtressScramble, 0x8

dlabel D_8010D5F0_191F50_ToadtressScramble
    /* 8010D5F0 */ .space 0x08

nonmatching D_8010D5F8_191F58_ToadtressScramble, 0x8

dlabel D_8010D5F8_191F58_ToadtressScramble
    /* 8010D5F8 */ .space 0x08

nonmatching D_8010D600_191F60_ToadtressScramble, 0x8

dlabel D_8010D600_191F60_ToadtressScramble
    /* 8010D600 */ .space 0x08

nonmatching D_8010D608_191F68_ToadtressScramble, 0x8

dlabel D_8010D608_191F68_ToadtressScramble
    /* 8010D608 */ .space 0x08

nonmatching D_8010D610_191F70_ToadtressScramble, 0x8

dlabel D_8010D610_191F70_ToadtressScramble
    /* 8010D610 */ .space 0x08

nonmatching D_8010D618_191F78_ToadtressScramble, 0x8

dlabel D_8010D618_191F78_ToadtressScramble
    /* 8010D618 */ .space 0x08

nonmatching D_8010D620_191F80_ToadtressScramble, 0x8

dlabel D_8010D620_191F80_ToadtressScramble
    /* 8010D620 */ .space 0x08

nonmatching D_8010D628_191F88_ToadtressScramble, 0x8

dlabel D_8010D628_191F88_ToadtressScramble
    /* 8010D628 */ .space 0x08

nonmatching D_8010D630_191F90_ToadtressScramble, 0x8

dlabel D_8010D630_191F90_ToadtressScramble
    /* 8010D630 */ .space 0x08

nonmatching D_8010D638_191F98_ToadtressScramble, 0x8

dlabel D_8010D638_191F98_ToadtressScramble
    /* 8010D638 */ .space 0x08

nonmatching D_8010D640_191FA0_ToadtressScramble, 0x8

dlabel D_8010D640_191FA0_ToadtressScramble
    /* 8010D640 */ .space 0x08

nonmatching D_8010D648_191FA8_ToadtressScramble, 0x8

dlabel D_8010D648_191FA8_ToadtressScramble
    /* 8010D648 */ .space 0x08

nonmatching D_8010D650_191FB0_ToadtressScramble, 0x8

dlabel D_8010D650_191FB0_ToadtressScramble
    /* 8010D650 */ .space 0x08

nonmatching D_8010D658_191FB8_ToadtressScramble, 0x8

dlabel D_8010D658_191FB8_ToadtressScramble
    /* 8010D658 */ .space 0x08

nonmatching D_8010D660_191FC0_ToadtressScramble, 0x8

dlabel D_8010D660_191FC0_ToadtressScramble
    /* 8010D660 */ .space 0x08

nonmatching D_8010D668_191FC8_ToadtressScramble, 0x8

dlabel D_8010D668_191FC8_ToadtressScramble
    /* 8010D668 */ .space 0x08

nonmatching D_8010D670_191FD0_ToadtressScramble, 0x8

dlabel D_8010D670_191FD0_ToadtressScramble
    /* 8010D670 */ .space 0x08

nonmatching D_8010D678_191FD8_ToadtressScramble, 0x8

dlabel D_8010D678_191FD8_ToadtressScramble
    /* 8010D678 */ .space 0x08

nonmatching D_8010D680_191FE0_ToadtressScramble, 0x8

dlabel D_8010D680_191FE0_ToadtressScramble
    /* 8010D680 */ .space 0x08

nonmatching D_8010D688_191FE8_ToadtressScramble, 0x8

dlabel D_8010D688_191FE8_ToadtressScramble
    /* 8010D688 */ .space 0x08

nonmatching D_8010D690_191FF0_ToadtressScramble, 0x8

dlabel D_8010D690_191FF0_ToadtressScramble
    /* 8010D690 */ .space 0x08

nonmatching D_8010D698_191FF8_ToadtressScramble, 0x8

dlabel D_8010D698_191FF8_ToadtressScramble
    /* 8010D698 */ .space 0x08

nonmatching D_8010D6A0_192000_ToadtressScramble, 0x8

dlabel D_8010D6A0_192000_ToadtressScramble
    /* 8010D6A0 */ .space 0x08

nonmatching D_8010D6A8_192008_ToadtressScramble, 0x8

dlabel D_8010D6A8_192008_ToadtressScramble
    /* 8010D6A8 */ .space 0x08

nonmatching D_8010D6B0_192010_ToadtressScramble, 0x8

dlabel D_8010D6B0_192010_ToadtressScramble
    /* 8010D6B0 */ .space 0x08

nonmatching D_8010D6B8_192018_ToadtressScramble, 0x8

dlabel D_8010D6B8_192018_ToadtressScramble
    /* 8010D6B8 */ .space 0x08

nonmatching D_8010D6C0_192020_ToadtressScramble, 0x8

dlabel D_8010D6C0_192020_ToadtressScramble
    /* 8010D6C0 */ .space 0x08

nonmatching D_8010D6C8_192028_ToadtressScramble, 0x8

dlabel D_8010D6C8_192028_ToadtressScramble
    /* 8010D6C8 */ .space 0x08

nonmatching D_8010D6D0_192030_ToadtressScramble, 0x8

dlabel D_8010D6D0_192030_ToadtressScramble
    /* 8010D6D0 */ .space 0x08

nonmatching D_8010D6D8_192038_ToadtressScramble, 0x8

dlabel D_8010D6D8_192038_ToadtressScramble
    /* 8010D6D8 */ .space 0x08

nonmatching D_8010D6E0_192040_ToadtressScramble, 0x8

dlabel D_8010D6E0_192040_ToadtressScramble
    /* 8010D6E0 */ .space 0x08

nonmatching D_8010D6E8_192048_ToadtressScramble, 0x8

dlabel D_8010D6E8_192048_ToadtressScramble
    /* 8010D6E8 */ .space 0x08

nonmatching D_8010D6F0_192050_ToadtressScramble, 0x8

dlabel D_8010D6F0_192050_ToadtressScramble
    /* 8010D6F0 */ .space 0x08

nonmatching D_8010D6F8_192058_ToadtressScramble, 0x8

dlabel D_8010D6F8_192058_ToadtressScramble
    /* 8010D6F8 */ .space 0x08

nonmatching D_8010D700_192060_ToadtressScramble, 0x8

dlabel D_8010D700_192060_ToadtressScramble
    /* 8010D700 */ .space 0x08

nonmatching D_8010D708_192068_ToadtressScramble, 0x8

dlabel D_8010D708_192068_ToadtressScramble
    /* 8010D708 */ .space 0x08

nonmatching D_8010D710_192070_ToadtressScramble, 0x138

dlabel D_8010D710_192070_ToadtressScramble
    /* 8010D710 */ .space 0x138

nonmatching D_8010D848_1921A8_ToadtressScramble, 0x18

dlabel D_8010D848_1921A8_ToadtressScramble
    /* 8010D848 */ .space 0x18

nonmatching D_8010D860_1921C0_ToadtressScramble, 0x8

dlabel D_8010D860_1921C0_ToadtressScramble
    /* 8010D860 */ .space 0x08

nonmatching D_8010D868_1921C8_ToadtressScramble, 0x10

dlabel D_8010D868_1921C8_ToadtressScramble
    /* 8010D868 */ .space 0x10

nonmatching D_8010D878_1921D8_ToadtressScramble, 0x10

dlabel D_8010D878_1921D8_ToadtressScramble
    /* 8010D878 */ .space 0x10

nonmatching D_8010D888_1921E8_ToadtressScramble, 0x8

dlabel D_8010D888_1921E8_ToadtressScramble
    /* 8010D888 */ .space 0x08

nonmatching D_8010D890_1921F0_ToadtressScramble, 0x6C

dlabel D_8010D890_1921F0_ToadtressScramble
    /* 8010D890 */ .space 0x6C

nonmatching D_8010D8FC_19225C_ToadtressScramble, 0x4

dlabel D_8010D8FC_19225C_ToadtressScramble
    /* 8010D8FC */ .space 0x04

nonmatching D_8010D900_192260_ToadtressScramble, 0x4

dlabel D_8010D900_192260_ToadtressScramble
    /* 8010D900 */ .space 0x04

nonmatching D_8010D904_192264_ToadtressScramble, 0x4

dlabel D_8010D904_192264_ToadtressScramble
    /* 8010D904 */ .space 0x04

nonmatching D_8010D908_192268_ToadtressScramble, 0x10

dlabel D_8010D908_192268_ToadtressScramble
    /* 8010D908 */ .space 0x10

nonmatching D_8010D918_192278_ToadtressScramble, 0x8

dlabel D_8010D918_192278_ToadtressScramble
    /* 8010D918 */ .space 0x08

nonmatching D_8010D920_192280_ToadtressScramble, 0x4

dlabel D_8010D920_192280_ToadtressScramble
    /* 8010D920 */ .space 0x04

nonmatching D_8010D924_192284_ToadtressScramble, 0x14

dlabel D_8010D924_192284_ToadtressScramble
    /* 8010D924 */ .space 0x14

nonmatching D_8010D938_192298_ToadtressScramble, 0x8

dlabel D_8010D938_192298_ToadtressScramble
    /* 8010D938 */ .space 0x08

nonmatching D_8010D940_1922A0_ToadtressScramble, 0x20

dlabel D_8010D940_1922A0_ToadtressScramble
    /* 8010D940 */ .space 0x20

nonmatching D_8010D960_1922C0_ToadtressScramble, 0x20

dlabel D_8010D960_1922C0_ToadtressScramble
    /* 8010D960 */ .space 0x20

nonmatching D_8010D980_1922E0_ToadtressScramble, 0x4

dlabel D_8010D980_1922E0_ToadtressScramble
    /* 8010D980 */ .space 0x04

nonmatching D_8010D984_1922E4_ToadtressScramble, 0x4

dlabel D_8010D984_1922E4_ToadtressScramble
    /* 8010D984 */ .space 0x04

nonmatching D_8010D988_1922E8_ToadtressScramble, 0x3

dlabel D_8010D988_1922E8_ToadtressScramble
    /* 8010D988 */ .space 0x03

nonmatching D_8010D98B_1922EB_ToadtressScramble, 0x5

dlabel D_8010D98B_1922EB_ToadtressScramble
    /* 8010D98B */ .space 0x05

nonmatching D_8010D990_1922F0_ToadtressScramble, 0x2

dlabel D_8010D990_1922F0_ToadtressScramble
    /* 8010D990 */ .space 0x02

nonmatching D_8010D992_1922F2_ToadtressScramble, 0x10

dlabel D_8010D992_1922F2_ToadtressScramble
    /* 8010D992 */ .space 0x10

nonmatching D_8010D9A2_192302_ToadtressScramble, 0xE

dlabel D_8010D9A2_192302_ToadtressScramble
    /* 8010D9A2 */ .space 0x0E

nonmatching D_8010D9B0_192310_ToadtressScramble, 0x4

dlabel D_8010D9B0_192310_ToadtressScramble
    /* 8010D9B0 */ .space 0x04

nonmatching D_8010D9B4_192314_ToadtressScramble, 0x8

dlabel D_8010D9B4_192314_ToadtressScramble
    /* 8010D9B4 */ .space 0x08

nonmatching D_8010D9BC_19231C_ToadtressScramble, 0x4

dlabel D_8010D9BC_19231C_ToadtressScramble
    /* 8010D9BC */ .space 0x04

nonmatching D_8010D9C0_192320_ToadtressScramble, 0x48

dlabel D_8010D9C0_192320_ToadtressScramble
    /* 8010D9C0 */ .space 0x48

nonmatching D_8010DA08_192368_ToadtressScramble, 0x20

dlabel D_8010DA08_192368_ToadtressScramble
    /* 8010DA08 */ .space 0x20

nonmatching D_8010DA28_192388_ToadtressScramble, 0x2

dlabel D_8010DA28_192388_ToadtressScramble
    /* 8010DA28 */ .space 0x02

nonmatching D_8010DA2A_19238A_ToadtressScramble, 0x2

dlabel D_8010DA2A_19238A_ToadtressScramble
    /* 8010DA2A */ .space 0x02

nonmatching D_8010DA2C_19238C_ToadtressScramble, 0x2

dlabel D_8010DA2C_19238C_ToadtressScramble
    /* 8010DA2C */ .space 0x02

nonmatching D_8010DA2E_19238E_ToadtressScramble, 0x2

dlabel D_8010DA2E_19238E_ToadtressScramble
    /* 8010DA2E */ .space 0x02

nonmatching D_8010DA30_192390_ToadtressScramble, 0x2

dlabel D_8010DA30_192390_ToadtressScramble
    /* 8010DA30 */ .space 0x02

nonmatching D_8010DA32_192392_ToadtressScramble, 0xE

dlabel D_8010DA32_192392_ToadtressScramble
    /* 8010DA32 */ .space 0x0E

nonmatching D_8010DA40_1923A0_ToadtressScramble, 0x2

dlabel D_8010DA40_1923A0_ToadtressScramble
    /* 8010DA40 */ .space 0x02

nonmatching D_8010DA42_1923A2_ToadtressScramble, 0x26

dlabel D_8010DA42_1923A2_ToadtressScramble
    /* 8010DA42 */ .space 0x26

nonmatching D_8010DA68_1923C8_ToadtressScramble, 0x4

dlabel D_8010DA68_1923C8_ToadtressScramble
    /* 8010DA68 */ .space 0x04

nonmatching D_8010DA6C_1923CC_ToadtressScramble, 0x4

dlabel D_8010DA6C_1923CC_ToadtressScramble
    /* 8010DA6C */ .space 0x04

nonmatching D_8010DA70_1923D0_ToadtressScramble, 0x8

dlabel D_8010DA70_1923D0_ToadtressScramble
    /* 8010DA70 */ .space 0x08

nonmatching D_8010DA78_1923D8_ToadtressScramble, 0x10

dlabel D_8010DA78_1923D8_ToadtressScramble
    /* 8010DA78 */ .space 0x10

nonmatching D_8010DA88_1923E8_ToadtressScramble, 0x10

dlabel D_8010DA88_1923E8_ToadtressScramble
    /* 8010DA88 */ .space 0x10

nonmatching D_8010DA98_1923F8_ToadtressScramble, 0x8

dlabel D_8010DA98_1923F8_ToadtressScramble
    /* 8010DA98 */ .space 0x08

nonmatching D_8010DAA0_192400_ToadtressScramble, 0x2

dlabel D_8010DAA0_192400_ToadtressScramble
    /* 8010DAA0 */ .space 0x02

nonmatching D_8010DAA2_192402_ToadtressScramble, 0x1

dlabel D_8010DAA2_192402_ToadtressScramble
    /* 8010DAA2 */ .space 0x01

nonmatching D_8010DAA3_192403_ToadtressScramble, 0x1

dlabel D_8010DAA3_192403_ToadtressScramble
    /* 8010DAA3 */ .space 0x01

nonmatching D_8010DAA4_192404_ToadtressScramble, 0x1

dlabel D_8010DAA4_192404_ToadtressScramble
    /* 8010DAA4 */ .space 0x01

nonmatching D_8010DAA5_192405_ToadtressScramble, 0x1

dlabel D_8010DAA5_192405_ToadtressScramble
    /* 8010DAA5 */ .space 0x01

nonmatching D_8010DAA6_192406_ToadtressScramble, 0x2

dlabel D_8010DAA6_192406_ToadtressScramble
    /* 8010DAA6 */ .space 0x02

nonmatching D_8010DAA8_192408_ToadtressScramble, 0x4

dlabel D_8010DAA8_192408_ToadtressScramble
    /* 8010DAA8 */ .space 0x04

nonmatching D_8010DAAC_19240C_ToadtressScramble, 0x1

dlabel D_8010DAAC_19240C_ToadtressScramble
    /* 8010DAAC */ .space 0x01

nonmatching D_8010DAAD_19240D_ToadtressScramble, 0xB

dlabel D_8010DAAD_19240D_ToadtressScramble
    /* 8010DAAD */ .space 0x0B

nonmatching D_8010DAB8_192418_ToadtressScramble, 0x9E98

dlabel D_8010DAB8_192418_ToadtressScramble
    /* 8010DAB8 */ .space 0x9E98
