.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80105700_40EC60_BattleResults, 0x10

dlabel D_80105700_40EC60_BattleResults
    /* 80105700 */ .space 0x10

nonmatching D_80105710_40EC70_BattleResults, 0x4

dlabel D_80105710_40EC70_BattleResults
    /* 80105710 */ .space 0x04

nonmatching D_80105714_40EC74_BattleResults, 0x4

dlabel D_80105714_40EC74_BattleResults
    /* 80105714 */ .space 0x04

nonmatching D_80105718_40EC78_BattleResults, 0x4

dlabel D_80105718_40EC78_BattleResults
    /* 80105718 */ .space 0x04

nonmatching D_8010571C_40EC7C_BattleResults, 0xC

dlabel D_8010571C_40EC7C_BattleResults
    /* 8010571C */ .space 0x0C

nonmatching D_80105728_40EC88_BattleResults, 0xC

dlabel D_80105728_40EC88_BattleResults
    /* 80105728 */ .space 0x0C

nonmatching D_80105734_40EC94_BattleResults, 0xC

dlabel D_80105734_40EC94_BattleResults
    /* 80105734 */ .space 0x0C

nonmatching D_80105740_40ECA0_BattleResults, 0x10

dlabel D_80105740_40ECA0_BattleResults
    /* 80105740 */ .space 0x10

nonmatching D_80105750_40ECB0_BattleResults, 0x80

dlabel D_80105750_40ECB0_BattleResults
    /* 80105750 */ .space 0x80

nonmatching D_801057D0_40ED30_BattleResults, 0x30

dlabel D_801057D0_40ED30_BattleResults
    /* 801057D0 */ .space 0x30

nonmatching D_80105800_40ED60_BattleResults, 0x50

dlabel D_80105800_40ED60_BattleResults
    /* 80105800 */ .space 0x50

nonmatching D_80105850_40EDB0_BattleResults, 0x18

dlabel D_80105850_40EDB0_BattleResults
    /* 80105850 */ .space 0x18

nonmatching D_80105868_40EDC8_BattleResults, 0x18

dlabel D_80105868_40EDC8_BattleResults
    /* 80105868 */ .space 0x18

nonmatching D_80105880_40EDE0_BattleResults, 0x2

dlabel D_80105880_40EDE0_BattleResults
    /* 80105880 */ .space 0x02

nonmatching D_80105882_40EDE2_BattleResults, 0x2

dlabel D_80105882_40EDE2_BattleResults
    /* 80105882 */ .space 0x02

nonmatching D_80105884_40EDE4_BattleResults, 0x6

dlabel D_80105884_40EDE4_BattleResults
    /* 80105884 */ .space 0x06

nonmatching D_8010588A_40EDEA_BattleResults, 0x10

dlabel D_8010588A_40EDEA_BattleResults
    /* 8010588A */ .space 0x10

nonmatching D_8010589A_40EDFA_BattleResults, 0x16

dlabel D_8010589A_40EDFA_BattleResults
    /* 8010589A */ .space 0x16

nonmatching D_801058B0_40EE10_BattleResults, 0x1C

dlabel D_801058B0_40EE10_BattleResults
    /* 801058B0 */ .space 0x1C

nonmatching D_801058CC_40EE2C_BattleResults, 0x1C

dlabel D_801058CC_40EE2C_BattleResults
    /* 801058CC */ .space 0x1C

nonmatching D_801058E8_40EE48_BattleResults, 0x18

dlabel D_801058E8_40EE48_BattleResults
    /* 801058E8 */ .space 0x18

nonmatching D_80105900_40EE60_BattleResults, 0x1C

dlabel D_80105900_40EE60_BattleResults
    /* 80105900 */ .space 0x1C

nonmatching D_8010591C_40EE7C_BattleResults, 0xC

dlabel D_8010591C_40EE7C_BattleResults
    /* 8010591C */ .space 0x0C

nonmatching jtbl_80105928_40EE88_BattleResults, 0x18

dlabel jtbl_80105928_40EE88_BattleResults
    /* 80105928 */ .space 0x18

nonmatching jtbl_80105940_40EEA0_BattleResults, 0x20

dlabel jtbl_80105940_40EEA0_BattleResults
    /* 80105940 */ .space 0x20

nonmatching D_80105960_40EEC0_BattleResults, 0x2

dlabel D_80105960_40EEC0_BattleResults
    /* 80105960 */ .space 0x02

nonmatching D_80105962_40EEC2_BattleResults, 0xE

dlabel D_80105962_40EEC2_BattleResults
    /* 80105962 */ .space 0x0E

nonmatching D_80105970_40EED0_BattleResults, 0x2

dlabel D_80105970_40EED0_BattleResults
    /* 80105970 */ .space 0x02

nonmatching D_80105972_40EED2_BattleResults, 0xE

dlabel D_80105972_40EED2_BattleResults
    /* 80105972 */ .space 0x0E

nonmatching D_80105980_40EEE0_BattleResults, 0x10

dlabel D_80105980_40EEE0_BattleResults
    /* 80105980 */ .space 0x10

nonmatching D_80105990_40EEF0_BattleResults, 0x2

dlabel D_80105990_40EEF0_BattleResults
    /* 80105990 */ .space 0x02

nonmatching D_80105992_40EEF2_BattleResults, 0xE

dlabel D_80105992_40EEF2_BattleResults
    /* 80105992 */ .space 0x0E

nonmatching D_801059A0_40EF00_BattleResults, 0x10

dlabel D_801059A0_40EF00_BattleResults
    /* 801059A0 */ .space 0x10

nonmatching D_801059B0_40EF10_BattleResults, 0x2

dlabel D_801059B0_40EF10_BattleResults
    /* 801059B0 */ .space 0x02

nonmatching D_801059B2_40EF12_BattleResults, 0x2

dlabel D_801059B2_40EF12_BattleResults
    /* 801059B2 */ .space 0x02

nonmatching D_801059B4_40EF14_BattleResults, 0x2

dlabel D_801059B4_40EF14_BattleResults
    /* 801059B4 */ .space 0x02

nonmatching D_801059B6_40EF16_BattleResults, 0x2

dlabel D_801059B6_40EF16_BattleResults
    /* 801059B6 */ .space 0x02

nonmatching D_801059B8_40EF18_BattleResults, 0x2

dlabel D_801059B8_40EF18_BattleResults
    /* 801059B8 */ .space 0x02

nonmatching D_801059BA_40EF1A_BattleResults, 0x2

dlabel D_801059BA_40EF1A_BattleResults
    /* 801059BA */ .space 0x02

nonmatching D_801059BC_40EF1C_BattleResults, 0x2

dlabel D_801059BC_40EF1C_BattleResults
    /* 801059BC */ .space 0x02

nonmatching D_801059BE_40EF1E_BattleResults, 0x2

dlabel D_801059BE_40EF1E_BattleResults
    /* 801059BE */ .space 0x02

nonmatching D_801059C0_40EF20_BattleResults, 0x2

dlabel D_801059C0_40EF20_BattleResults
    /* 801059C0 */ .space 0x02

nonmatching D_801059C2_40EF22_BattleResults, 0x6

dlabel D_801059C2_40EF22_BattleResults
    /* 801059C2 */ .space 0x06

nonmatching D_801059C8_40EF28_BattleResults, 0x4

dlabel D_801059C8_40EF28_BattleResults
    /* 801059C8 */ .space 0x04

nonmatching D_801059CC_40EF2C_BattleResults, 0x4

dlabel D_801059CC_40EF2C_BattleResults
    /* 801059CC */ .space 0x04

nonmatching D_801059D0_40EF30_BattleResults, 0x28

dlabel D_801059D0_40EF30_BattleResults
    /* 801059D0 */ .space 0x28

nonmatching D_801059F8_40EF58_BattleResults, 0x10

dlabel D_801059F8_40EF58_BattleResults
    /* 801059F8 */ .space 0x10

nonmatching D_80105A08_40EF68_BattleResults, 0x10

dlabel D_80105A08_40EF68_BattleResults
    /* 80105A08 */ .space 0x10

nonmatching D_80105A18_40EF78_BattleResults, 0x2

dlabel D_80105A18_40EF78_BattleResults
    /* 80105A18 */ .space 0x02

nonmatching D_80105A1A_40EF7A_BattleResults, 0x2

dlabel D_80105A1A_40EF7A_BattleResults
    /* 80105A1A */ .space 0x02

nonmatching D_80105A1C_40EF7C_BattleResults, 0x2

dlabel D_80105A1C_40EF7C_BattleResults
    /* 80105A1C */ .space 0x02

nonmatching D_80105A1E_40EF7E_BattleResults, 0x2

dlabel D_80105A1E_40EF7E_BattleResults
    /* 80105A1E */ .space 0x02

nonmatching D_80105A20_40EF80_BattleResults, 0x2

dlabel D_80105A20_40EF80_BattleResults
    /* 80105A20 */ .space 0x02

nonmatching D_80105A22_40EF82_BattleResults, 0x6

dlabel D_80105A22_40EF82_BattleResults
    /* 80105A22 */ .space 0x06

nonmatching D_80105A28_40EF88_BattleResults, 0x2

dlabel D_80105A28_40EF88_BattleResults
    /* 80105A28 */ .space 0x02

nonmatching D_80105A2A_40EF8A_BattleResults, 0xE

dlabel D_80105A2A_40EF8A_BattleResults
    /* 80105A2A */ .space 0x0E

nonmatching D_80105A38_40EF98_BattleResults, 0x10

dlabel D_80105A38_40EF98_BattleResults
    /* 80105A38 */ .space 0x10

nonmatching D_80105A48_40EFA8_BattleResults, 0x10

dlabel D_80105A48_40EFA8_BattleResults
    /* 80105A48 */ .space 0x10

nonmatching D_80105A58_40EFB8_BattleResults, 0x10

dlabel D_80105A58_40EFB8_BattleResults
    /* 80105A58 */ .space 0x10

nonmatching D_80105A68_40EFC8_BattleResults, 0x4

dlabel D_80105A68_40EFC8_BattleResults
    /* 80105A68 */ .space 0x04

nonmatching D_80105A6C_40EFCC_BattleResults, 0x4

dlabel D_80105A6C_40EFCC_BattleResults
    /* 80105A6C */ .space 0x04

nonmatching D_80105A70_40EFD0_BattleResults, 0x2DF0

dlabel D_80105A70_40EFD0_BattleResults
    /* 80105A70 */ .space 0x2DF0
