#!/usr/bin/env python3
"""Generate libaudio and MP2 audio API call-site inventory from symbol_addrs.txt and asm."""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SUBSYSTEMS: dict[str, list[str]] = {
    "AI (Audio Interface)": [
        "osAiSetNextBuffer",
        "osAiSetFrequency",
        "osAiGetLength",
        "osAiDeviceBusy",
    ],
    "libaudio — Sequence Player": [
        "alSeqpNew",
        "alSeqpPlay",
        "alSeqpStop",
        "alSeqpSetSeq",
        "alSeqpSetBank",
        "alSeqpSetVol",
        "alSeqpSetTempo",
        "alSeqpGetState",
        "alSeqpDelete",
        "alSeqpGetChlVol",
        "alSeqpGetChlPan",
        "alSeqpGetChlProgram",
        "alSeqpGetChlFXMix",
    ],
    "libaudio — Sound Player": [
        "alSndpAllocate",
        "alSndpDeallocate",
        "alSndpSetSound",
        "alSndpPlay",
        "alSndpStop",
        "alSndpGetState",
        "alSndpSetVol",
        "alSndpSetPan",
        "alSndpSetPitch",
        "alSndpSetFXMix",
        "alSndpSetPriority",
    ],
    "libaudio — Synthesizer": [
        "alSynNew",
        "alSynDelete",
        "alSynAddPlayer",
        "alSynRemovePlayer",
        "alSynAllocVoice",
        "alSynFreeVoice",
        "alSynStartVoice",
        "alSynStopVoice",
        "alSynSetVol",
        "alSynSetPan",
        "alSynSetPitch",
        "alSynSetFXMix",
        "alSynStartVoiceParams",
    ],
    "libaudio — Frame and Files": [
        "alAudioFrame",
        "alBnkfNew",
        "alSeqFileNew",
        "alCSeqNew",
        "alHeapInit",
        "alHeapDBAlloc",
    ],
    "libaudio — Sample Pull": [
        "alAdpcmPull",
        "alRaw16Pull",
        "alEnvmixerPull",
        "alResamplePull",
        "alMainBusPull",
        "alSavePull",
    ],
    "MP2 Engine Audio": [
        "PlaySound",
        "PlayCharacterSound",
    ],
}

SYM_LINE = re.compile(r"^(\w+)\s*=\s*(0x[0-9A-Fa-f]+)")
JAL = re.compile(r"\bjal\s+(\w+)")


def load_symbols(path: Path) -> dict[str, int]:
    symbols: dict[str, int] = {}
    for line in path.read_text().splitlines():
        match = SYM_LINE.match(line.strip())
        if match:
            symbols[match.group(1)] = int(match.group(2), 16)
    return symbols


def canonical(name: str) -> str:
    return re.sub(r"_\d+$", "", name)


def count_calls(asm_path: Path) -> dict[str, int]:
    counts: dict[str, int] = defaultdict(int)
    for line in asm_path.read_text().splitlines():
        match = JAL.search(line)
        if match:
            counts[canonical(match.group(1))] += 1
    return counts


def render_markdown(symbols: dict[str, int], counts: dict[str, int]) -> str:
    lines = [
        "<!-- Auto-generated by tools/audio_xref.py -->",
        "",
        "## MP2 Main-Segment Audio Call Inventory",
        "",
        "Call counts are `jal` sites in [`asm/1060.s`](../asm/1060.s) only.",
        "",
    ]
    for subsystem, names in SUBSYSTEMS.items():
        lines.append(f"### {subsystem}")
        lines.append("")
        lines.append("| Function | VRAM | Calls in main |")
        lines.append("|----------|------|---------------|")
        for name in names:
            vram = symbols.get(name)
            if vram is None:
                for key, addr in symbols.items():
                    if canonical(key) == name:
                        vram = addr
                        break
            vram_str = f"`0x{vram:08X}`" if vram else "—"
            call_count = counts.get(name, 0)
            if vram or call_count:
                lines.append(f"| `{name}` | {vram_str} | {call_count} |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--symbols", type=Path, default=ROOT / "symbol_addrs.txt")
    parser.add_argument("--asm", type=Path, default=ROOT / "asm" / "1060.s")
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "docs" / "hardware" / "audio-call-inventory.md",
    )
    args = parser.parse_args()

    symbols = load_symbols(args.symbols)
    counts = count_calls(args.asm)
    body = render_markdown(symbols, counts)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body)
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
