#!/usr/bin/env python3
"""Parse MP2 OSViMode table from asm/1060.s and emit markdown."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TABLE_LABEL = "D_800CDF10_CEB10"
WORD_RE = re.compile(r"\.word\s+(0x[0-9A-Fa-f]+)")
LABEL_RE = re.compile(r"dlabel\s+" + re.escape(TABLE_LABEL))

# Stride from func_8007E2A0: index * 5 * 16 = index * 80
ENTRY_STRIDE = 0x50
BASE_VRAM = 0x800CDF10

# Known libultra type bytes (second byte of first word in some layouts)
TYPE_NAMES = {
    0x00: "reserved",
    0x01: "NTSC LAN1 (640x480i hi-res)",
    0x02: "NTSC LF1 (320x240p)",
    0x03: "NTSC MF1",
    0x04: "NTSC HF1",
    0x05: "NTSC LP1",
    0x06: "NTSC HP1",
    0x07: "NTSC MP1",
}

# fldRegs width at word offset 10 in each 0x50 block (heuristic from com/fld layout)
FLD_WIDTH_WORD = 10


def extract_table_words(asm_path: Path) -> list[int]:
    text = asm_path.read_text()
    match = LABEL_RE.search(text)
    if not match:
        raise SystemExit(f"Label {TABLE_LABEL} not found in {asm_path}")
    chunk = text[match.start() : match.start() + 12000]
    words = [int(m.group(1), 16) for m in WORD_RE.finditer(chunk)]
    return words


def decode_entry(index: int, words: list[int]) -> dict:
    off = index * (ENTRY_STRIDE // 4)
    if off + 16 > len(words):
        return {}
    block = words[off : off + (ENTRY_STRIDE // 4)]
    type_word = block[0]
    type_byte = (type_word >> 24) & 0xFF
    if type_byte == 0 and block[1]:
        type_byte = (block[1] >> 8) & 0xFF
    ctrl = block[1] & 0xFFFF if len(block) > 1 else 0
    width = block[FLD_WIDTH_WORD] & 0xFFFF if len(block) > FLD_WIDTH_WORD else 0
    height_scale = block[11] & 0xFFFF if len(block) > 11 else 0
    return {
        "index": index,
        "vram": BASE_VRAM + index * ENTRY_STRIDE,
        "type_byte": type_byte,
        "type_name": TYPE_NAMES.get(type_byte, f"unknown 0x{type_byte:02X}"),
        "ctrl": ctrl,
        "fld_width": width,
        "height_hint": height_scale,
        "words_hex": [f"0x{w:08X}" for w in block[:8]],
    }


def render_markdown(entries: list[dict]) -> str:
    lines = [
        "<!-- Auto-generated by tools/dump_vi_modes.py -->",
        "",
        "## MP2 Embedded VI Mode Table (`D_800CDF10`)",
        "",
        f"- **VRAM base:** `0x{BASE_VRAM:08X}`",
        f"- **Stride:** `0x{ENTRY_STRIDE:02X}` (80 bytes) per mode index",
        "- **Indexed by:** `func_8007E2A0` → `osViSetMode`",
        "",
        "| Index | VRAM | Type | Ctrl | Fld width | First words |",
        "|-------|------|------|------|-----------|-------------|",
    ]
    for e in entries:
        if not e:
            continue
        words_preview = ", ".join(e["words_hex"][:4])
        lines.append(
            f"| {e['index']} | `0x{e['vram']:08X}` | {e['type_name']} | "
            f"`0x{e['ctrl']:04X}` | {e['fld_width']} | {words_preview} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--asm", type=Path, default=ROOT / "asm" / "1060.s")
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "docs" / "hardware" / "mp2-vi-mode-table.md",
    )
    parser.add_argument("--count", type=int, default=12, help="Number of entries to dump")
    args = parser.parse_args()

    words = extract_table_words(args.asm)
    entries = [decode_entry(i, words) for i in range(args.count)]
    entries = [e for e in entries if e]

    body = render_markdown(entries)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body)
    print(f"Wrote {args.output} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
