#!/usr/bin/env python3
"""Generate libultra SI/EEPROM and MP2 input/save call-site inventory."""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SUBSYSTEMS: dict[str, list[str]] = {
    "SI — Controller Poll": [
        "osContStartReadData",
        "osContGetReadData",
    ],
    "SI — Controller Pak / PFS": [
        "osContRamRead",
        "osContRamWrite",
        "osPfsIsPlug",
        "osPfsGetStatus",
        "osPfsSelectBank",
        "osContDataCrc",
        "osContAddressCrc",
    ],
    "SI — Rumble Motor": [
        "osMotorInit",
        "osMotorAccess",
    ],
    "EEPROM — libultra": [
        "osEepromProbe",
        "osEepromRead",
        "osEepromWrite",
        "osEepromLongRead",
        "osEepromLongWrite",
    ],
    "MP2 — Input Engine": [
        "PlayerIsCPU",
    ],
}

# Engine helpers not yet in symbol_addrs.txt — counted by glabel name in asm
ENGINE_LABELS: dict[str, list[str]] = {
    "MP2 — Input Manager (labels)": [
        "func_80016840",
        "func_80017244",
        "func_80016A44",
        "func_80016BD0",
        "func_80016BBC",
    ],
    "MP2 — EEPROM Module (labels)": [
        "func_8001ACD0",
        "func_8001AEDC",
        "func_8001AFD8",
        "func_8001B078",
        "func_8001B114",
        "func_8001B0B4",
    ],
}

SYM_LINE = re.compile(r"^(\w+)\s*=\s*(0x[0-9A-Fa-f]+)")
JAL = re.compile(r"\bjal\s+(\w+)")


def load_symbols(path: Path) -> dict[str, int]:
    symbols: dict[str, int] = {}
    for line in path.read_text().splitlines():
        match = SYM_LINE.match(line.strip())
        if match:
            symbols[match.group(1)] = int(match.group(2), 16)
    return symbols


def canonical(name: str) -> str:
    return re.sub(r"_\d+$", "", name)


def count_calls(asm_path: Path) -> dict[str, int]:
    counts: dict[str, int] = defaultdict(int)
    for line in asm_path.read_text().splitlines():
        match = JAL.search(line)
        if match:
            counts[canonical(match.group(1))] += 1
    return counts


def render_markdown(symbols: dict[str, int], counts: dict[str, int]) -> str:
    lines = [
        "<!-- Auto-generated by tools/input_save_xref.py -->",
        "",
        "## MP2 Main-Segment Input and Save Call Inventory",
        "",
        "Call counts are `jal` sites in [`asm/1060.s`](../asm/1060.s) only.",
        "",
    ]
    for subsystem, names in SUBSYSTEMS.items():
        lines.append(f"### {subsystem}")
        lines.append("")
        lines.append("| Function | VRAM | Calls in main |")
        lines.append("|----------|------|---------------|")
        for name in names:
            vram = symbols.get(name)
            if vram is None:
                for key, addr in symbols.items():
                    if canonical(key) == name:
                        vram = addr
                        break
            vram_str = f"`0x{vram:08X}`" if vram else "—"
            call_count = counts.get(name, 0)
            if vram or call_count:
                lines.append(f"| `{name}` | {vram_str} | {call_count} |")
        lines.append("")

    lines.append("### Note on engine helpers")
    lines.append("")
    lines.append(
        "Input manager and EEPROM packer entry points are not yet named in "
        "`symbol_addrs.txt`. Counts below use `glabel` names from `1060.s`."
    )
    lines.append("")
    for subsystem, names in ENGINE_LABELS.items():
        lines.append(f"### {subsystem}")
        lines.append("")
        lines.append("| Label | Calls in main |")
        lines.append("|-------|---------------|")
        for name in names:
            call_count = counts.get(name, 0)
            if call_count:
                lines.append(f"| `{name}` | {call_count} |")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--symbols", type=Path, default=ROOT / "symbol_addrs.txt")
    parser.add_argument("--asm", type=Path, default=ROOT / "asm" / "1060.s")
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "docs" / "hardware" / "input-save-call-inventory.md",
    )
    args = parser.parse_args()

    symbols = load_symbols(args.symbols)
    counts = count_calls(args.asm)
    body = render_markdown(symbols, counts)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body)
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
