#!/usr/bin/env python3
"""Generate per-overlay jal call inventory for MP2 engine and libultra APIs."""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# APIs tracked across overlay code @ 0x80102800
TRACKED: dict[str, list[str]] = {
    "Assets": [
        "ReadMainFS",
        "FreeMainFS",
        "interpretFORM",
        "interpretMTNX",
        "func_80027884",
    ],
    "CPU / Process": [
        "InitProcess",
        "SleepProcess",
        "SleepVProcess",
        "MallocPerm",
        "MallocTemp",
        "Malloc",
        "FreePerm",
    ],
    "Board / Gameplay": [
        "RunDecisionTree",
        "EventTableHydrate",
        "PlayerHasCoins",
        "IsBoardFeatureDisabled",
        "ShowMessage",
        "CloseMessage",
        "GetRandomByte",
    ],
    "Graphics / Fade": [
        "InitFadeIn",
        "InitFadeOut",
        "osViSwapBuffer",
        "osWritebackDCache",
        "osWritebackDCacheAll",
        "osSpTaskStartGo",
    ],
    "Audio": [
        "PlaySound",
        "PlayCharacterSound",
        "alSeqpPlay",
        "alSndpPlay",
    ],
    "Input / Save": [
        "osContGetReadData",
        "PlayerIsCPU",
        "func_8001ACD0",
    ],
}

SYM_LINE = re.compile(r"^(\w+)\s*=\s*(0x[0-9A-Fa-f]+)")
JAL = re.compile(r"\bjal\s+(\w+)")


def load_symbols(path: Path) -> dict[str, int]:
    symbols: dict[str, int] = {}
    for line in path.read_text().splitlines():
        match = SYM_LINE.match(line.strip())
        if match:
            symbols[match.group(1)] = int(match.group(2), 16)
    return symbols


def canonical(name: str) -> str:
    return re.sub(r"_\d+$", "", name)


def all_tracked_names() -> set[str]:
    names: set[str] = set()
    for group in TRACKED.values():
        names.update(group)
    return names


def count_calls(asm_path: Path) -> dict[str, int]:
    counts: dict[str, int] = defaultdict(int)
    for line in asm_path.read_text().splitlines():
        match = JAL.search(line)
        if match:
            counts[canonical(match.group(1))] += 1
    return counts


def overlay_name(path: Path) -> str:
    # asm/overlays/ovl_5F_BoardMain/3AB9A0.s -> ovl_5F_BoardMain
    return path.parent.name


def scan_overlays(overlay_dir: Path) -> dict[str, dict[str, int]]:
    tracked = all_tracked_names()
    by_overlay: dict[str, dict[str, int]] = {}
    for asm_file in sorted(overlay_dir.glob("**/*.s")):
        name = overlay_name(asm_file)
        counts = count_calls(asm_file)
        filtered = {k: v for k, v in counts.items() if k in tracked and v > 0}
        if filtered:
            by_overlay[name] = filtered
    return by_overlay


def aggregate(by_overlay: dict[str, dict[str, int]]) -> dict[str, int]:
    totals: dict[str, int] = defaultdict(int)
    for counts in by_overlay.values():
        for fn, n in counts.items():
            totals[fn] += n
    return dict(totals)


def render_markdown(
    symbols: dict[str, int],
    by_overlay: dict[str, dict[str, int]],
    totals: dict[str, int],
    main_counts: dict[str, int],
) -> str:
    lines = [
        "<!-- Auto-generated by tools/overlay_xref.py -->",
        "",
        "## MP2 Overlay Call Inventory",
        "",
        "Call counts are `jal` sites in [`asm/overlays/`](../asm/overlays/) "
        "(115 overlays loaded @ `0x80102800`). Main-segment counts from "
        "[`asm/1060.s`](../asm/1060.s) are included for comparison.",
        "",
        f"Overlays with at least one tracked call: **{len(by_overlay)}**.",
        "",
        "### Totals (all overlays)",
        "",
        "| Function | VRAM | Overlays total | Main segment |",
        "|----------|------|----------------|--------------|",
    ]
    for fn in sorted(totals.keys(), key=lambda k: (-totals[k], k)):
        vram = symbols.get(fn)
        if vram is None:
            for key, addr in symbols.items():
                if canonical(key) == fn:
                    vram = addr
                    break
        vram_str = f"`0x{vram:08X}`" if vram else "—"
        lines.append(
            f"| `{fn}` | {vram_str} | {totals[fn]} | {main_counts.get(fn, 0)} |"
        )
    lines.append("")

    for group, names in TRACKED.items():
        group_totals = {n: totals.get(n, 0) for n in names if totals.get(n, 0)}
        if not group_totals:
            continue
        lines.append(f"### Top overlays — {group}")
        lines.append("")
        lines.append("| Overlay | " + " | ".join(f"`{n}`" for n in names) + " |")
        lines.append("|---------|" + "|".join("---" for _ in names) + "|")
        rows: list[tuple[str, int, list[str]]] = []
        for ovl, counts in by_overlay.items():
            row_sum = sum(counts.get(n, 0) for n in names)
            if row_sum:
                cells = [str(counts.get(n, 0)) if counts.get(n, 0) else "·" for n in names]
                rows.append((ovl, row_sum, cells))
        rows.sort(key=lambda r: (-r[1], r[0]))
        for ovl, _, cells in rows[:20]:
            lines.append(f"| `{ovl}` | " + " | ".join(cells) + " |")
        lines.append("")

    lines.append("### Per-overlay summary (any tracked API)")
    lines.append("")
    lines.append("| Overlay | Total tracked calls | Top APIs |")
    lines.append("|---------|---------------------|----------|")
    summary: list[tuple[str, int, str]] = []
    for ovl, counts in by_overlay.items():
        total = sum(counts.values())
        top = sorted(counts.items(), key=lambda x: (-x[1], x[0]))[:3]
        top_str = ", ".join(f"`{k}`×{v}" for k, v in top)
        summary.append((ovl, total, top_str))
    summary.sort(key=lambda r: (-r[1], r[0]))
    for ovl, total, top_str in summary:
        lines.append(f"| `{ovl}` | {total} | {top_str} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--symbols", type=Path, default=ROOT / "symbol_addrs.txt")
    parser.add_argument("--overlays", type=Path, default=ROOT / "asm" / "overlays")
    parser.add_argument("--main-asm", type=Path, default=ROOT / "asm" / "1060.s")
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "docs" / "hardware" / "overlay-call-inventory.md",
    )
    args = parser.parse_args()

    symbols = load_symbols(args.symbols)
    by_overlay = scan_overlays(args.overlays)
    totals = aggregate(by_overlay)
    main_counts = count_calls(args.main_asm)
    body = render_markdown(symbols, by_overlay, totals, main_counts)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body)
    print(f"Wrote {args.output} ({len(by_overlay)} overlays)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
