.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80107770_27F4F0_CoffinCongestion2P, 0x1

dlabel D_80107770_27F4F0_CoffinCongestion2P
    /* 80107770 */ .space 0x01

nonmatching D_80107771_27F4F1_CoffinCongestion2P, 0x1

dlabel D_80107771_27F4F1_CoffinCongestion2P
    /* 80107771 */ .space 0x01

nonmatching D_80107772_27F4F2_CoffinCongestion2P, 0x2

dlabel D_80107772_27F4F2_CoffinCongestion2P
    /* 80107772 */ .space 0x02

nonmatching D_80107774_27F4F4_CoffinCongestion2P, 0x2

dlabel D_80107774_27F4F4_CoffinCongestion2P
    /* 80107774 */ .space 0x02

nonmatching D_80107776_27F4F6_CoffinCongestion2P, 0x1

dlabel D_80107776_27F4F6_CoffinCongestion2P
    /* 80107776 */ .space 0x01

nonmatching D_80107777_27F4F7_CoffinCongestion2P, 0x1

dlabel D_80107777_27F4F7_CoffinCongestion2P
    /* 80107777 */ .space 0x01

nonmatching D_80107778_27F4F8_CoffinCongestion2P, 0x4

dlabel D_80107778_27F4F8_CoffinCongestion2P
    /* 80107778 */ .space 0x04

nonmatching D_8010777C_27F4FC_CoffinCongestion2P, 0x1

dlabel D_8010777C_27F4FC_CoffinCongestion2P
    /* 8010777C */ .space 0x01

nonmatching D_8010777D_27F4FD_CoffinCongestion2P, 0x1

dlabel D_8010777D_27F4FD_CoffinCongestion2P
    /* 8010777D */ .space 0x01

nonmatching D_8010777E_27F4FE_CoffinCongestion2P, 0x1

dlabel D_8010777E_27F4FE_CoffinCongestion2P
    /* 8010777E */ .space 0x01

nonmatching D_8010777F_27F4FF_CoffinCongestion2P, 0x1

dlabel D_8010777F_27F4FF_CoffinCongestion2P
    /* 8010777F */ .space 0x01

nonmatching D_80107780_27F500_CoffinCongestion2P, 0x4

dlabel D_80107780_27F500_CoffinCongestion2P
    /* 80107780 */ .space 0x04

nonmatching D_80107784_27F504_CoffinCongestion2P, 0x4

dlabel D_80107784_27F504_CoffinCongestion2P
    /* 80107784 */ .space 0x04

nonmatching D_80107788_27F508_CoffinCongestion2P, 0x4

dlabel D_80107788_27F508_CoffinCongestion2P
    /* 80107788 */ .space 0x04

nonmatching D_8010778C_27F50C_CoffinCongestion2P, 0x4

dlabel D_8010778C_27F50C_CoffinCongestion2P
    /* 8010778C */ .space 0x04

nonmatching D_80107790_27F510_CoffinCongestion2P, 0x18

dlabel D_80107790_27F510_CoffinCongestion2P
    /* 80107790 */ .space 0x18

nonmatching D_801077A8_27F528_CoffinCongestion2P, 0x4

dlabel D_801077A8_27F528_CoffinCongestion2P
    /* 801077A8 */ .space 0x04

nonmatching D_801077AC_27F52C_CoffinCongestion2P, 0x1

dlabel D_801077AC_27F52C_CoffinCongestion2P
    /* 801077AC */ .space 0x01

nonmatching D_801077AD_27F52D_CoffinCongestion2P, 0x1

dlabel D_801077AD_27F52D_CoffinCongestion2P
    /* 801077AD */ .space 0x01

nonmatching D_801077AE_27F52E_CoffinCongestion2P, 0x2

dlabel D_801077AE_27F52E_CoffinCongestion2P
    /* 801077AE */ .space 0x02

nonmatching D_801077B0_27F530_CoffinCongestion2P, 0x2

dlabel D_801077B0_27F530_CoffinCongestion2P
    /* 801077B0 */ .space 0x02

nonmatching D_801077B2_27F532_CoffinCongestion2P, 0x2

dlabel D_801077B2_27F532_CoffinCongestion2P
    /* 801077B2 */ .space 0x02

nonmatching D_801077B4_27F534_CoffinCongestion2P, 0x4

dlabel D_801077B4_27F534_CoffinCongestion2P
    /* 801077B4 */ .space 0x04

nonmatching D_801077B8_27F538_CoffinCongestion2P, 0x8

dlabel D_801077B8_27F538_CoffinCongestion2P
    /* 801077B8 */ .space 0x08

nonmatching D_801077C0_27F540_CoffinCongestion2P, 0x4

dlabel D_801077C0_27F540_CoffinCongestion2P
    /* 801077C0 */ .space 0x04

nonmatching D_801077C4_27F544_CoffinCongestion2P, 0x4

dlabel D_801077C4_27F544_CoffinCongestion2P
    /* 801077C4 */ .space 0x04

nonmatching D_801077C8_27F548_CoffinCongestion2P, 0x4

dlabel D_801077C8_27F548_CoffinCongestion2P
    /* 801077C8 */ .space 0x04

nonmatching D_801077CC_27F54C_CoffinCongestion2P, 0x8

dlabel D_801077CC_27F54C_CoffinCongestion2P
    /* 801077CC */ .space 0x08

nonmatching D_801077D4_27F554_CoffinCongestion2P, 0x2

dlabel D_801077D4_27F554_CoffinCongestion2P
    /* 801077D4 */ .space 0x02

nonmatching D_801077D6_27F556_CoffinCongestion2P, 0x2

dlabel D_801077D6_27F556_CoffinCongestion2P
    /* 801077D6 */ .space 0x02

nonmatching D_801077D8_27F558_CoffinCongestion2P, 0x4

dlabel D_801077D8_27F558_CoffinCongestion2P
    /* 801077D8 */ .space 0x04

nonmatching D_801077DC_27F55C_CoffinCongestion2P, 0x4

dlabel D_801077DC_27F55C_CoffinCongestion2P
    /* 801077DC */ .space 0x04

nonmatching D_801077E0_27F560_CoffinCongestion2P, 0x10

dlabel D_801077E0_27F560_CoffinCongestion2P
    /* 801077E0 */ .space 0x10

nonmatching D_801077F0_27F570_CoffinCongestion2P, 0x10

dlabel D_801077F0_27F570_CoffinCongestion2P
    /* 801077F0 */ .space 0x10

nonmatching D_80107800_27F580_CoffinCongestion2P, 0x10

dlabel D_80107800_27F580_CoffinCongestion2P
    /* 80107800 */ .space 0x10

nonmatching D_80107810_27F590_CoffinCongestion2P, 0x8

dlabel D_80107810_27F590_CoffinCongestion2P
    /* 80107810 */ .space 0x08

nonmatching D_80107818_27F598_CoffinCongestion2P, 0x30

dlabel D_80107818_27F598_CoffinCongestion2P
    /* 80107818 */ .space 0x30

nonmatching D_80107848_27F5C8_CoffinCongestion2P, 0x98

dlabel D_80107848_27F5C8_CoffinCongestion2P
    /* 80107848 */ .space 0x98

nonmatching jtbl_801078E0_27F660_CoffinCongestion2P, 0x30

dlabel jtbl_801078E0_27F660_CoffinCongestion2P
    /* 801078E0 */ .space 0x30

nonmatching D_80107910_27F690_CoffinCongestion2P, 0xC

dlabel D_80107910_27F690_CoffinCongestion2P
    /* 80107910 */ .space 0x0C

nonmatching D_8010791C_27F69C_CoffinCongestion2P, 0x8

dlabel D_8010791C_27F69C_CoffinCongestion2P
    /* 8010791C */ .space 0x08

nonmatching D_80107924_27F6A4_CoffinCongestion2P, 0x4

dlabel D_80107924_27F6A4_CoffinCongestion2P
    /* 80107924 */ .space 0x04

nonmatching D_80107928_27F6A8_CoffinCongestion2P, 0x10

dlabel D_80107928_27F6A8_CoffinCongestion2P
    /* 80107928 */ .space 0x10

nonmatching D_80107938_27F6B8_CoffinCongestion2P, 0x10

dlabel D_80107938_27F6B8_CoffinCongestion2P
    /* 80107938 */ .space 0x10

nonmatching D_80107948_27F6C8_CoffinCongestion2P, 0x10

dlabel D_80107948_27F6C8_CoffinCongestion2P
    /* 80107948 */ .space 0x10

nonmatching D_80107958_27F6D8_CoffinCongestion2P, 0x8

dlabel D_80107958_27F6D8_CoffinCongestion2P
    /* 80107958 */ .space 0x08

nonmatching D_80107960_27F6E0_CoffinCongestion2P, 0x18

dlabel D_80107960_27F6E0_CoffinCongestion2P
    /* 80107960 */ .space 0x18

nonmatching D_80107978_27F6F8_CoffinCongestion2P, 0x2

dlabel D_80107978_27F6F8_CoffinCongestion2P
    /* 80107978 */ .space 0x02

nonmatching D_8010797A_27F6FA_CoffinCongestion2P, 0xE

dlabel D_8010797A_27F6FA_CoffinCongestion2P
    /* 8010797A */ .space 0x0E

nonmatching D_80107988_27F708_CoffinCongestion2P, 0x2

dlabel D_80107988_27F708_CoffinCongestion2P
    /* 80107988 */ .space 0x02

nonmatching D_8010798A_27F70A_CoffinCongestion2P, 0xE

dlabel D_8010798A_27F70A_CoffinCongestion2P
    /* 8010798A */ .space 0x0E

nonmatching D_80107998_27F718_CoffinCongestion2P, 0x2

dlabel D_80107998_27F718_CoffinCongestion2P
    /* 80107998 */ .space 0x02

nonmatching D_8010799A_27F71A_CoffinCongestion2P, 0xE

dlabel D_8010799A_27F71A_CoffinCongestion2P
    /* 8010799A */ .space 0x0E

nonmatching D_801079A8_27F728_CoffinCongestion2P, 0x2

dlabel D_801079A8_27F728_CoffinCongestion2P
    /* 801079A8 */ .space 0x02

nonmatching D_801079AA_27F72A_CoffinCongestion2P, 0xE

dlabel D_801079AA_27F72A_CoffinCongestion2P
    /* 801079AA */ .space 0x0E

nonmatching D_801079B8_27F738_CoffinCongestion2P, 0x8

dlabel D_801079B8_27F738_CoffinCongestion2P
    /* 801079B8 */ .space 0x08

nonmatching D_801079C0_27F740_CoffinCongestion2P, 0x1

dlabel D_801079C0_27F740_CoffinCongestion2P
    /* 801079C0 */ .space 0x01

nonmatching D_801079C1_27F741_CoffinCongestion2P, 0x3

dlabel D_801079C1_27F741_CoffinCongestion2P
    /* 801079C1 */ .space 0x03

nonmatching D_801079C4_27F744_CoffinCongestion2P, 0x4

dlabel D_801079C4_27F744_CoffinCongestion2P
    /* 801079C4 */ .space 0x04

nonmatching D_801079C8_27F748_CoffinCongestion2P, 0x2

dlabel D_801079C8_27F748_CoffinCongestion2P
    /* 801079C8 */ .space 0x02

nonmatching D_801079CA_27F74A_CoffinCongestion2P, 0x6

dlabel D_801079CA_27F74A_CoffinCongestion2P
    /* 801079CA */ .space 0x06

nonmatching D_801079D0_27F750_CoffinCongestion2P, 0x10

dlabel D_801079D0_27F750_CoffinCongestion2P
    /* 801079D0 */ .space 0x10

nonmatching D_801079E0_27F760_CoffinCongestion2P, 0x4

dlabel D_801079E0_27F760_CoffinCongestion2P
    /* 801079E0 */ .space 0x04

nonmatching D_801079E4_27F764_CoffinCongestion2P, 0x59C

dlabel D_801079E4_27F764_CoffinCongestion2P
    /* 801079E4 */ .space 0x59C

nonmatching D_80107F80_27FD00_CoffinCongestion2P, 0x68

dlabel D_80107F80_27FD00_CoffinCongestion2P
    /* 80107F80 */ .space 0x68

nonmatching D_80107FE8_27FD68_CoffinCongestion2P, 0x38

dlabel D_80107FE8_27FD68_CoffinCongestion2P
    /* 80107FE8 */ .space 0x38

nonmatching D_80108020_27FDA0_CoffinCongestion2P, 0x4

dlabel D_80108020_27FDA0_CoffinCongestion2P
    /* 80108020 */ .space 0x04

nonmatching D_80108024_27FDA4_CoffinCongestion2P, 0x1

dlabel D_80108024_27FDA4_CoffinCongestion2P
    /* 80108024 */ .space 0x01

nonmatching D_80108025_27FDA5_CoffinCongestion2P, 0x1

dlabel D_80108025_27FDA5_CoffinCongestion2P
    /* 80108025 */ .space 0x01

nonmatching D_80108026_27FDA6_CoffinCongestion2P, 0x2

dlabel D_80108026_27FDA6_CoffinCongestion2P
    /* 80108026 */ .space 0x02

nonmatching D_80108028_27FDA8_CoffinCongestion2P, 0xC

dlabel D_80108028_27FDA8_CoffinCongestion2P
    /* 80108028 */ .space 0x0C

nonmatching D_80108034_27FDB4_CoffinCongestion2P, 0x48FC

dlabel D_80108034_27FDB4_CoffinCongestion2P
    /* 80108034 */ .space 0x48FC
