.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80111960_352E10_BalloonBurst1P, 0x4

dlabel D_80111960_352E10_BalloonBurst1P
    /* 80111960 */ .space 0x04

nonmatching D_80111964_352E14_BalloonBurst1P, 0x18

dlabel D_80111964_352E14_BalloonBurst1P
    /* 80111964 */ .space 0x18

nonmatching D_8011197C_352E2C_BalloonBurst1P, 0x1A

dlabel D_8011197C_352E2C_BalloonBurst1P
    /* 8011197C */ .space 0x1A

nonmatching D_80111996_352E46_BalloonBurst1P, 0x4

dlabel D_80111996_352E46_BalloonBurst1P
    /* 80111996 */ .space 0x04

nonmatching D_8011199A_352E4A_BalloonBurst1P, 0x4

dlabel D_8011199A_352E4A_BalloonBurst1P
    /* 8011199A */ .space 0x04

nonmatching D_8011199E_352E4E_BalloonBurst1P, 0x4

dlabel D_8011199E_352E4E_BalloonBurst1P
    /* 8011199E */ .space 0x04

nonmatching D_801119A2_352E52_BalloonBurst1P, 0x4

dlabel D_801119A2_352E52_BalloonBurst1P
    /* 801119A2 */ .space 0x04

nonmatching D_801119A6_352E56_BalloonBurst1P, 0x68

dlabel D_801119A6_352E56_BalloonBurst1P
    /* 801119A6 */ .space 0x68

nonmatching D_80111A0E_352EBE_BalloonBurst1P, 0x4

dlabel D_80111A0E_352EBE_BalloonBurst1P
    /* 80111A0E */ .space 0x04

nonmatching D_80111A12_352EC2_BalloonBurst1P, 0x2C

dlabel D_80111A12_352EC2_BalloonBurst1P
    /* 80111A12 */ .space 0x2C

nonmatching D_80111A3E_352EEE_BalloonBurst1P, 0x4

dlabel D_80111A3E_352EEE_BalloonBurst1P
    /* 80111A3E */ .space 0x04

nonmatching D_80111A42_352EF2_BalloonBurst1P, 0x4

dlabel D_80111A42_352EF2_BalloonBurst1P
    /* 80111A42 */ .space 0x04

nonmatching D_80111A46_352EF6_BalloonBurst1P, 0x3E

dlabel D_80111A46_352EF6_BalloonBurst1P
    /* 80111A46 */ .space 0x3E

nonmatching D_80111A84_352F34_BalloonBurst1P, 0x18

dlabel D_80111A84_352F34_BalloonBurst1P
    /* 80111A84 */ .space 0x18

nonmatching D_80111A9C_352F4C_BalloonBurst1P, 0x18

dlabel D_80111A9C_352F4C_BalloonBurst1P
    /* 80111A9C */ .space 0x18

nonmatching D_80111AB4_352F64_BalloonBurst1P, 0x18

dlabel D_80111AB4_352F64_BalloonBurst1P
    /* 80111AB4 */ .space 0x18

nonmatching D_80111ACC_352F7C_BalloonBurst1P, 0x18

dlabel D_80111ACC_352F7C_BalloonBurst1P
    /* 80111ACC */ .space 0x18

nonmatching D_80111AE4_352F94_BalloonBurst1P, 0xC

dlabel D_80111AE4_352F94_BalloonBurst1P
    /* 80111AE4 */ .space 0x0C

nonmatching D_80111AF0_352FA0_BalloonBurst1P, 0x4

dlabel D_80111AF0_352FA0_BalloonBurst1P
    /* 80111AF0 */ .space 0x04

nonmatching D_80111AF4_352FA4_BalloonBurst1P, 0x4

dlabel D_80111AF4_352FA4_BalloonBurst1P
    /* 80111AF4 */ .space 0x04

nonmatching D_80111AF8_352FA8_BalloonBurst1P, 0x4

dlabel D_80111AF8_352FA8_BalloonBurst1P
    /* 80111AF8 */ .space 0x04

nonmatching D_80111AFC_352FAC_BalloonBurst1P, 0x3C

dlabel D_80111AFC_352FAC_BalloonBurst1P
    /* 80111AFC */ .space 0x3C

nonmatching D_80111B38_352FE8_BalloonBurst1P, 0xC

dlabel D_80111B38_352FE8_BalloonBurst1P
    /* 80111B38 */ .space 0x0C

nonmatching D_80111B44_352FF4_BalloonBurst1P, 0xC

dlabel D_80111B44_352FF4_BalloonBurst1P
    /* 80111B44 */ .space 0x0C

nonmatching D_80111B50_353000_BalloonBurst1P, 0xC

dlabel D_80111B50_353000_BalloonBurst1P
    /* 80111B50 */ .space 0x0C

nonmatching D_80111B5C_35300C_BalloonBurst1P, 0xC

dlabel D_80111B5C_35300C_BalloonBurst1P
    /* 80111B5C */ .space 0x0C

nonmatching D_80111B68_353018_BalloonBurst1P, 0xC

dlabel D_80111B68_353018_BalloonBurst1P
    /* 80111B68 */ .space 0x0C

nonmatching D_80111B74_353024_BalloonBurst1P, 0xC

dlabel D_80111B74_353024_BalloonBurst1P
    /* 80111B74 */ .space 0x0C

nonmatching D_80111B80_353030_BalloonBurst1P, 0xC

dlabel D_80111B80_353030_BalloonBurst1P
    /* 80111B80 */ .space 0x0C

nonmatching D_80111B8C_35303C_BalloonBurst1P, 0xFC

dlabel D_80111B8C_35303C_BalloonBurst1P
    /* 80111B8C */ .space 0xFC

nonmatching D_80111C88_353138_BalloonBurst1P, 0x18

dlabel D_80111C88_353138_BalloonBurst1P
    /* 80111C88 */ .space 0x18

nonmatching D_80111CA0_353150_BalloonBurst1P, 0xC

dlabel D_80111CA0_353150_BalloonBurst1P
    /* 80111CA0 */ .space 0x0C

nonmatching D_80111CAC_35315C_BalloonBurst1P, 0x38

dlabel D_80111CAC_35315C_BalloonBurst1P
    /* 80111CAC */ .space 0x38

nonmatching D_80111CE4_353194_BalloonBurst1P, 0x1C

dlabel D_80111CE4_353194_BalloonBurst1P
    /* 80111CE4 */ .space 0x1C

nonmatching D_80111D00_3531B0_BalloonBurst1P, 0x8

dlabel D_80111D00_3531B0_BalloonBurst1P
    /* 80111D00 */ .space 0x08

nonmatching D_80111D08_3531B8_BalloonBurst1P, 0x4

dlabel D_80111D08_3531B8_BalloonBurst1P
    /* 80111D08 */ .space 0x04

nonmatching D_80111D0C_3531BC_BalloonBurst1P, 0x8

dlabel D_80111D0C_3531BC_BalloonBurst1P
    /* 80111D0C */ .space 0x08

nonmatching D_80111D14_3531C4_BalloonBurst1P, 0xC

dlabel D_80111D14_3531C4_BalloonBurst1P
    /* 80111D14 */ .space 0x0C

nonmatching D_80111D20_3531D0_BalloonBurst1P, 0xC

dlabel D_80111D20_3531D0_BalloonBurst1P
    /* 80111D20 */ .space 0x0C

nonmatching D_80111D2C_3531DC_BalloonBurst1P, 0xC

dlabel D_80111D2C_3531DC_BalloonBurst1P
    /* 80111D2C */ .space 0x0C

nonmatching D_80111D38_3531E8_BalloonBurst1P, 0xC

dlabel D_80111D38_3531E8_BalloonBurst1P
    /* 80111D38 */ .space 0x0C

nonmatching D_80111D44_3531F4_BalloonBurst1P, 0xC

dlabel D_80111D44_3531F4_BalloonBurst1P
    /* 80111D44 */ .space 0x0C

nonmatching D_80111D50_353200_BalloonBurst1P, 0xC

dlabel D_80111D50_353200_BalloonBurst1P
    /* 80111D50 */ .space 0x0C

nonmatching D_80111D5C_35320C_BalloonBurst1P, 0xC

dlabel D_80111D5C_35320C_BalloonBurst1P
    /* 80111D5C */ .space 0x0C

nonmatching D_80111D68_353218_BalloonBurst1P, 0xC

dlabel D_80111D68_353218_BalloonBurst1P
    /* 80111D68 */ .space 0x0C

nonmatching D_80111D74_353224_BalloonBurst1P, 0xC

dlabel D_80111D74_353224_BalloonBurst1P
    /* 80111D74 */ .space 0x0C

nonmatching D_80111D80_353230_BalloonBurst1P, 0xC

dlabel D_80111D80_353230_BalloonBurst1P
    /* 80111D80 */ .space 0x0C

nonmatching D_80111D8C_35323C_BalloonBurst1P, 0x8

dlabel D_80111D8C_35323C_BalloonBurst1P
    /* 80111D8C */ .space 0x08

nonmatching D_80111D94_353244_BalloonBurst1P, 0xC

dlabel D_80111D94_353244_BalloonBurst1P
    /* 80111D94 */ .space 0x0C

nonmatching D_80111DA0_353250_BalloonBurst1P, 0x4

dlabel D_80111DA0_353250_BalloonBurst1P
    /* 80111DA0 */ .space 0x04

nonmatching D_80111DA4_353254_BalloonBurst1P, 0x4

dlabel D_80111DA4_353254_BalloonBurst1P
    /* 80111DA4 */ .space 0x04

nonmatching D_80111DA8_353258_BalloonBurst1P, 0x40

dlabel D_80111DA8_353258_BalloonBurst1P
    /* 80111DA8 */ .space 0x40

nonmatching D_80111DE8_353298_BalloonBurst1P, 0xC

dlabel D_80111DE8_353298_BalloonBurst1P
    /* 80111DE8 */ .space 0x0C

nonmatching D_80111DF4_3532A4_BalloonBurst1P, 0xC

dlabel D_80111DF4_3532A4_BalloonBurst1P
    /* 80111DF4 */ .space 0x0C

nonmatching D_80111E00_3532B0_BalloonBurst1P, 0xC

dlabel D_80111E00_3532B0_BalloonBurst1P
    /* 80111E00 */ .space 0x0C

nonmatching D_80111E0C_3532BC_BalloonBurst1P, 0xC

dlabel D_80111E0C_3532BC_BalloonBurst1P
    /* 80111E0C */ .space 0x0C

nonmatching D_80111E18_3532C8_BalloonBurst1P, 0x4

dlabel D_80111E18_3532C8_BalloonBurst1P
    /* 80111E18 */ .space 0x04

nonmatching D_80111E1C_3532CC_BalloonBurst1P, 0x4

dlabel D_80111E1C_3532CC_BalloonBurst1P
    /* 80111E1C */ .space 0x04

nonmatching D_80111E20_3532D0_BalloonBurst1P, 0x40

dlabel D_80111E20_3532D0_BalloonBurst1P
    /* 80111E20 */ .space 0x40

nonmatching D_80111E60_353310_BalloonBurst1P, 0xC

dlabel D_80111E60_353310_BalloonBurst1P
    /* 80111E60 */ .space 0x0C

nonmatching D_80111E6C_35331C_BalloonBurst1P, 0x4

dlabel D_80111E6C_35331C_BalloonBurst1P
    /* 80111E6C */ .space 0x04

nonmatching D_80111E70_353320_BalloonBurst1P, 0x4

dlabel D_80111E70_353320_BalloonBurst1P
    /* 80111E70 */ .space 0x04

nonmatching D_80111E74_353324_BalloonBurst1P, 0x40

dlabel D_80111E74_353324_BalloonBurst1P
    /* 80111E74 */ .space 0x40

nonmatching D_80111EB4_353364_BalloonBurst1P, 0x4

dlabel D_80111EB4_353364_BalloonBurst1P
    /* 80111EB4 */ .space 0x04

nonmatching D_80111EB8_353368_BalloonBurst1P, 0x4

dlabel D_80111EB8_353368_BalloonBurst1P
    /* 80111EB8 */ .space 0x04

nonmatching D_80111EBC_35336C_BalloonBurst1P, 0x40

dlabel D_80111EBC_35336C_BalloonBurst1P
    /* 80111EBC */ .space 0x40

nonmatching D_80111EFC_3533AC_BalloonBurst1P, 0x10C

dlabel D_80111EFC_3533AC_BalloonBurst1P
    /* 80111EFC */ .space 0x10C

nonmatching D_80112008_3534B8_BalloonBurst1P, 0x18

dlabel D_80112008_3534B8_BalloonBurst1P
    /* 80112008 */ .space 0x18

nonmatching D_80112020_3534D0_BalloonBurst1P, 0x14

dlabel D_80112020_3534D0_BalloonBurst1P
    /* 80112020 */ .space 0x14

nonmatching D_80112034_3534E4_BalloonBurst1P, 0x30

dlabel D_80112034_3534E4_BalloonBurst1P
    /* 80112034 */ .space 0x30

nonmatching D_80112064_353514_BalloonBurst1P, 0x8

dlabel D_80112064_353514_BalloonBurst1P
    /* 80112064 */ .space 0x08

nonmatching D_8011206C_35351C_BalloonBurst1P, 0x4

dlabel D_8011206C_35351C_BalloonBurst1P
    /* 8011206C */ .space 0x04

nonmatching D_80112070_353520_BalloonBurst1P, 0x8

dlabel D_80112070_353520_BalloonBurst1P
    /* 80112070 */ .space 0x08

nonmatching D_80112078_353528_BalloonBurst1P, 0x4

dlabel D_80112078_353528_BalloonBurst1P
    /* 80112078 */ .space 0x04

nonmatching D_8011207C_35352C_BalloonBurst1P, 0x10

dlabel D_8011207C_35352C_BalloonBurst1P
    /* 8011207C */ .space 0x10

nonmatching D_8011208C_35353C_BalloonBurst1P, 0xC

dlabel D_8011208C_35353C_BalloonBurst1P
    /* 8011208C */ .space 0x0C

nonmatching D_80112098_353548_BalloonBurst1P, 0x18

dlabel D_80112098_353548_BalloonBurst1P
    /* 80112098 */ .space 0x18

nonmatching D_801120B0_353560_BalloonBurst1P, 0xC

dlabel D_801120B0_353560_BalloonBurst1P
    /* 801120B0 */ .space 0x0C

nonmatching D_801120BC_35356C_BalloonBurst1P, 0xC

dlabel D_801120BC_35356C_BalloonBurst1P
    /* 801120BC */ .space 0x0C

nonmatching D_801120C8_353578_BalloonBurst1P, 0x18

dlabel D_801120C8_353578_BalloonBurst1P
    /* 801120C8 */ .space 0x18

nonmatching D_801120E0_353590_BalloonBurst1P, 0xC

dlabel D_801120E0_353590_BalloonBurst1P
    /* 801120E0 */ .space 0x0C

nonmatching D_801120EC_35359C_BalloonBurst1P, 0xC

dlabel D_801120EC_35359C_BalloonBurst1P
    /* 801120EC */ .space 0x0C

nonmatching D_801120F8_3535A8_BalloonBurst1P, 0x18

dlabel D_801120F8_3535A8_BalloonBurst1P
    /* 801120F8 */ .space 0x18

nonmatching D_80112110_3535C0_BalloonBurst1P, 0xC

dlabel D_80112110_3535C0_BalloonBurst1P
    /* 80112110 */ .space 0x0C

nonmatching D_8011211C_3535CC_BalloonBurst1P, 0xC

dlabel D_8011211C_3535CC_BalloonBurst1P
    /* 8011211C */ .space 0x0C

nonmatching D_80112128_3535D8_BalloonBurst1P, 0xC

dlabel D_80112128_3535D8_BalloonBurst1P
    /* 80112128 */ .space 0x0C

nonmatching D_80112134_3535E4_BalloonBurst1P, 0xC

dlabel D_80112134_3535E4_BalloonBurst1P
    /* 80112134 */ .space 0x0C

nonmatching D_80112140_3535F0_BalloonBurst1P, 0x18

dlabel D_80112140_3535F0_BalloonBurst1P
    /* 80112140 */ .space 0x18

nonmatching D_80112158_353608_BalloonBurst1P, 0x18

dlabel D_80112158_353608_BalloonBurst1P
    /* 80112158 */ .space 0x18

nonmatching D_80112170_353620_BalloonBurst1P, 0xC

dlabel D_80112170_353620_BalloonBurst1P
    /* 80112170 */ .space 0x0C

nonmatching D_8011217C_35362C_BalloonBurst1P, 0xC

dlabel D_8011217C_35362C_BalloonBurst1P
    /* 8011217C */ .space 0x0C

nonmatching D_80112188_353638_BalloonBurst1P, 0x8

dlabel D_80112188_353638_BalloonBurst1P
    /* 80112188 */ .space 0x08

nonmatching D_80112190_353640_BalloonBurst1P, 0x178

dlabel D_80112190_353640_BalloonBurst1P
    /* 80112190 */ .space 0x178

nonmatching D_80112308_3537B8_BalloonBurst1P, 0x18

dlabel D_80112308_3537B8_BalloonBurst1P
    /* 80112308 */ .space 0x18

nonmatching D_80112320_3537D0_BalloonBurst1P, 0x14

dlabel D_80112320_3537D0_BalloonBurst1P
    /* 80112320 */ .space 0x14

nonmatching D_80112334_3537E4_BalloonBurst1P, 0x38

dlabel D_80112334_3537E4_BalloonBurst1P
    /* 80112334 */ .space 0x38

nonmatching D_8011236C_35381C_BalloonBurst1P, 0x2C

dlabel D_8011236C_35381C_BalloonBurst1P
    /* 8011236C */ .space 0x2C

nonmatching D_80112398_353848_BalloonBurst1P, 0x8

dlabel D_80112398_353848_BalloonBurst1P
    /* 80112398 */ .space 0x08

nonmatching D_801123A0_353850_BalloonBurst1P, 0x4

dlabel D_801123A0_353850_BalloonBurst1P
    /* 801123A0 */ .space 0x04

nonmatching D_801123A4_353854_BalloonBurst1P, 0x8

dlabel D_801123A4_353854_BalloonBurst1P
    /* 801123A4 */ .space 0x08

nonmatching D_801123AC_35385C_BalloonBurst1P, 0x4

dlabel D_801123AC_35385C_BalloonBurst1P
    /* 801123AC */ .space 0x04

nonmatching D_801123B0_353860_BalloonBurst1P, 0x4

dlabel D_801123B0_353860_BalloonBurst1P
    /* 801123B0 */ .space 0x04

nonmatching D_801123B4_353864_BalloonBurst1P, 0x4

dlabel D_801123B4_353864_BalloonBurst1P
    /* 801123B4 */ .space 0x04

nonmatching D_801123B8_353868_BalloonBurst1P, 0xC

dlabel D_801123B8_353868_BalloonBurst1P
    /* 801123B8 */ .space 0x0C

nonmatching D_801123C4_353874_BalloonBurst1P, 0xC

dlabel D_801123C4_353874_BalloonBurst1P
    /* 801123C4 */ .space 0x0C

nonmatching D_801123D0_353880_BalloonBurst1P, 0xC

dlabel D_801123D0_353880_BalloonBurst1P
    /* 801123D0 */ .space 0x0C

nonmatching D_801123DC_35388C_BalloonBurst1P, 0xC

dlabel D_801123DC_35388C_BalloonBurst1P
    /* 801123DC */ .space 0x0C

nonmatching D_801123E8_353898_BalloonBurst1P, 0x18

dlabel D_801123E8_353898_BalloonBurst1P
    /* 801123E8 */ .space 0x18

nonmatching D_80112400_3538B0_BalloonBurst1P, 0xC

dlabel D_80112400_3538B0_BalloonBurst1P
    /* 80112400 */ .space 0x0C

nonmatching D_8011240C_3538BC_BalloonBurst1P, 0xC

dlabel D_8011240C_3538BC_BalloonBurst1P
    /* 8011240C */ .space 0x0C

nonmatching D_80112418_3538C8_BalloonBurst1P, 0xC

dlabel D_80112418_3538C8_BalloonBurst1P
    /* 80112418 */ .space 0x0C

nonmatching D_80112424_3538D4_BalloonBurst1P, 0x30

dlabel D_80112424_3538D4_BalloonBurst1P
    /* 80112424 */ .space 0x30

nonmatching D_80112454_353904_BalloonBurst1P, 0xC

dlabel D_80112454_353904_BalloonBurst1P
    /* 80112454 */ .space 0x0C

nonmatching D_80112460_353910_BalloonBurst1P, 0xC

dlabel D_80112460_353910_BalloonBurst1P
    /* 80112460 */ .space 0x0C

nonmatching D_8011246C_35391C_BalloonBurst1P, 0xC

dlabel D_8011246C_35391C_BalloonBurst1P
    /* 8011246C */ .space 0x0C

nonmatching D_80112478_353928_BalloonBurst1P, 0xC

dlabel D_80112478_353928_BalloonBurst1P
    /* 80112478 */ .space 0x0C

nonmatching D_80112484_353934_BalloonBurst1P, 0x4

dlabel D_80112484_353934_BalloonBurst1P
    /* 80112484 */ .space 0x04

nonmatching D_80112488_353938_BalloonBurst1P, 0x4

dlabel D_80112488_353938_BalloonBurst1P
    /* 80112488 */ .space 0x04

nonmatching D_8011248C_35393C_BalloonBurst1P, 0x1C

dlabel D_8011248C_35393C_BalloonBurst1P
    /* 8011248C */ .space 0x1C

nonmatching D_801124A8_353958_BalloonBurst1P, 0xA

dlabel D_801124A8_353958_BalloonBurst1P
    /* 801124A8 */ .space 0x0A

nonmatching D_801124B2_353962_BalloonBurst1P, 0xA

dlabel D_801124B2_353962_BalloonBurst1P
    /* 801124B2 */ .space 0x0A

nonmatching D_801124BC_35396C_BalloonBurst1P, 0x2

dlabel D_801124BC_35396C_BalloonBurst1P
    /* 801124BC */ .space 0x02

nonmatching D_801124BE_35396E_BalloonBurst1P, 0x2

dlabel D_801124BE_35396E_BalloonBurst1P
    /* 801124BE */ .space 0x02

nonmatching D_801124C0_353970_BalloonBurst1P, 0x2

dlabel D_801124C0_353970_BalloonBurst1P
    /* 801124C0 */ .space 0x02

nonmatching D_801124C2_353972_BalloonBurst1P, 0x2

dlabel D_801124C2_353972_BalloonBurst1P
    /* 801124C2 */ .space 0x02

nonmatching D_801124C4_353974_BalloonBurst1P, 0x2

dlabel D_801124C4_353974_BalloonBurst1P
    /* 801124C4 */ .space 0x02

nonmatching D_801124C6_353976_BalloonBurst1P, 0x2

dlabel D_801124C6_353976_BalloonBurst1P
    /* 801124C6 */ .space 0x02

nonmatching D_801124C8_353978_BalloonBurst1P, 0x2

dlabel D_801124C8_353978_BalloonBurst1P
    /* 801124C8 */ .space 0x02

nonmatching D_801124CA_35397A_BalloonBurst1P, 0x2

dlabel D_801124CA_35397A_BalloonBurst1P
    /* 801124CA */ .space 0x02

nonmatching D_801124CC_35397C_BalloonBurst1P, 0x4

dlabel D_801124CC_35397C_BalloonBurst1P
    /* 801124CC */ .space 0x04

nonmatching D_801124D0_353980_BalloonBurst1P, 0x10

dlabel D_801124D0_353980_BalloonBurst1P
    /* 801124D0 */ .space 0x10

nonmatching D_801124E0_353990_BalloonBurst1P, 0x10

dlabel D_801124E0_353990_BalloonBurst1P
    /* 801124E0 */ .space 0x10

nonmatching D_801124F0_3539A0_BalloonBurst1P, 0x88

dlabel D_801124F0_3539A0_BalloonBurst1P
    /* 801124F0 */ .space 0x88

nonmatching D_80112578_353A28_BalloonBurst1P, 0x8

dlabel D_80112578_353A28_BalloonBurst1P
    /* 80112578 */ .space 0x08

nonmatching D_80112580_353A30_BalloonBurst1P, 0x10

dlabel D_80112580_353A30_BalloonBurst1P
    /* 80112580 */ .space 0x10

nonmatching D_80112590_353A40_BalloonBurst1P, 0x10

dlabel D_80112590_353A40_BalloonBurst1P
    /* 80112590 */ .space 0x10

nonmatching D_801125A0_353A50_BalloonBurst1P, 0x10

dlabel D_801125A0_353A50_BalloonBurst1P
    /* 801125A0 */ .space 0x10

nonmatching D_801125B0_353A60_BalloonBurst1P, 0x4

dlabel D_801125B0_353A60_BalloonBurst1P
    /* 801125B0 */ .space 0x04

nonmatching D_801125B4_353A64_BalloonBurst1P, 0x4

dlabel D_801125B4_353A64_BalloonBurst1P
    /* 801125B4 */ .space 0x04

nonmatching D_801125B8_353A68_BalloonBurst1P, 0x4

dlabel D_801125B8_353A68_BalloonBurst1P
    /* 801125B8 */ .space 0x04

nonmatching D_801125BC_353A6C_BalloonBurst1P, 0x4

dlabel D_801125BC_353A6C_BalloonBurst1P
    /* 801125BC */ .space 0x04

nonmatching D_801125C0_353A70_BalloonBurst1P, 0x10

dlabel D_801125C0_353A70_BalloonBurst1P
    /* 801125C0 */ .space 0x10

nonmatching D_801125D0_353A80_BalloonBurst1P, 0x2

dlabel D_801125D0_353A80_BalloonBurst1P
    /* 801125D0 */ .space 0x02

nonmatching D_801125D2_353A82_BalloonBurst1P, 0x2

dlabel D_801125D2_353A82_BalloonBurst1P
    /* 801125D2 */ .space 0x02

nonmatching D_801125D4_353A84_BalloonBurst1P, 0x4

dlabel D_801125D4_353A84_BalloonBurst1P
    /* 801125D4 */ .space 0x04

nonmatching D_801125D8_353A88_BalloonBurst1P, 0x4

dlabel D_801125D8_353A88_BalloonBurst1P
    /* 801125D8 */ .space 0x04

nonmatching D_801125DC_353A8C_BalloonBurst1P, 0x4

dlabel D_801125DC_353A8C_BalloonBurst1P
    /* 801125DC */ .space 0x04

nonmatching D_801125E0_353A90_BalloonBurst1P, 0x4

dlabel D_801125E0_353A90_BalloonBurst1P
    /* 801125E0 */ .space 0x04

nonmatching D_801125E4_353A94_BalloonBurst1P, 0x4

dlabel D_801125E4_353A94_BalloonBurst1P
    /* 801125E4 */ .space 0x04

nonmatching D_801125E8_353A98_BalloonBurst1P, 0xC

dlabel D_801125E8_353A98_BalloonBurst1P
    /* 801125E8 */ .space 0x0C

nonmatching D_801125F4_353AA4_BalloonBurst1P, 0xC

dlabel D_801125F4_353AA4_BalloonBurst1P
    /* 801125F4 */ .space 0x0C

nonmatching D_80112600_353AB0_BalloonBurst1P, 0x4

dlabel D_80112600_353AB0_BalloonBurst1P
    /* 80112600 */ .space 0x04

nonmatching D_80112604_353AB4_BalloonBurst1P, 0xC

dlabel D_80112604_353AB4_BalloonBurst1P
    /* 80112604 */ .space 0x0C

nonmatching D_80112610_353AC0_BalloonBurst1P, 0x4

dlabel D_80112610_353AC0_BalloonBurst1P
    /* 80112610 */ .space 0x04

nonmatching D_80112614_353AC4_BalloonBurst1P, 0x4

dlabel D_80112614_353AC4_BalloonBurst1P
    /* 80112614 */ .space 0x04

nonmatching D_80112618_353AC8_BalloonBurst1P, 0x4

dlabel D_80112618_353AC8_BalloonBurst1P
    /* 80112618 */ .space 0x04

nonmatching D_8011261C_353ACC_BalloonBurst1P, 0xC

dlabel D_8011261C_353ACC_BalloonBurst1P
    /* 8011261C */ .space 0x0C

nonmatching D_80112628_353AD8_BalloonBurst1P, 0xC

dlabel D_80112628_353AD8_BalloonBurst1P
    /* 80112628 */ .space 0x0C

nonmatching D_80112634_353AE4_BalloonBurst1P, 0x4

dlabel D_80112634_353AE4_BalloonBurst1P
    /* 80112634 */ .space 0x04

nonmatching D_80112638_353AE8_BalloonBurst1P, 0x8

dlabel D_80112638_353AE8_BalloonBurst1P
    /* 80112638 */ .space 0x08

nonmatching D_80112640_353AF0_BalloonBurst1P, 0x80

dlabel D_80112640_353AF0_BalloonBurst1P
    /* 80112640 */ .space 0x80

nonmatching D_801126C0_353B70_BalloonBurst1P, 0x80

dlabel D_801126C0_353B70_BalloonBurst1P
    /* 801126C0 */ .space 0x80

nonmatching D_80112740_353BF0_BalloonBurst1P, 0x4

dlabel D_80112740_353BF0_BalloonBurst1P
    /* 80112740 */ .space 0x04

nonmatching D_80112744_353BF4_BalloonBurst1P, 0x4

dlabel D_80112744_353BF4_BalloonBurst1P
    /* 80112744 */ .space 0x04

nonmatching D_80112748_353BF8_BalloonBurst1P, 0x4

dlabel D_80112748_353BF8_BalloonBurst1P
    /* 80112748 */ .space 0x04

nonmatching D_8011274C_353BFC_BalloonBurst1P, 0x4

dlabel D_8011274C_353BFC_BalloonBurst1P
    /* 8011274C */ .space 0x04

nonmatching D_80112750_353C00_BalloonBurst1P, 0x2

dlabel D_80112750_353C00_BalloonBurst1P
    /* 80112750 */ .space 0x02

nonmatching D_80112752_353C02_BalloonBurst1P, 0x4

dlabel D_80112752_353C02_BalloonBurst1P
    /* 80112752 */ .space 0x04

nonmatching D_80112756_353C06_BalloonBurst1P, 0x2

dlabel D_80112756_353C06_BalloonBurst1P
    /* 80112756 */ .space 0x02

nonmatching D_80112758_353C08_BalloonBurst1P, 0x2

dlabel D_80112758_353C08_BalloonBurst1P
    /* 80112758 */ .space 0x02

nonmatching D_8011275A_353C0A_BalloonBurst1P, 0x2

dlabel D_8011275A_353C0A_BalloonBurst1P
    /* 8011275A */ .space 0x02

nonmatching D_8011275C_353C0C_BalloonBurst1P, 0xEFB4

dlabel D_8011275C_353C0C_BalloonBurst1P
    /* 8011275C */ .space 0xEFB4
