.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_801028B0_3E4320_MainMenu, 0x4

glabel D_801028B0_3E4320_MainMenu
    /* 801028B0 */ .space 0x04

nonmatching func_801028B4_3E4324_MainMenu, 0xCC

dlabel func_801028B4_3E4324_MainMenu
    /* 801028B4 */ .space 0xCC
