.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching D_80105B60_360670_HoneycombTreasureHunt1P, 0x28

dlabel D_80105B60_360670_HoneycombTreasureHunt1P
    /* 80105B60 */ .space 0x28

nonmatching D_80105B88_360698_HoneycombTreasureHunt1P, 0x4

dlabel D_80105B88_360698_HoneycombTreasureHunt1P
    /* 80105B88 */ .space 0x04

nonmatching D_80105B8C_36069C_HoneycombTreasureHunt1P, 0x1

dlabel D_80105B8C_36069C_HoneycombTreasureHunt1P
    /* 80105B8C */ .space 0x01

nonmatching D_80105B8D_36069D_HoneycombTreasureHunt1P, 0x7

dlabel D_80105B8D_36069D_HoneycombTreasureHunt1P
    /* 80105B8D */ .space 0x07

nonmatching D_80105B94_3606A4_HoneycombTreasureHunt1P, 0x18

dlabel D_80105B94_3606A4_HoneycombTreasureHunt1P
    /* 80105B94 */ .space 0x18

nonmatching D_80105BAC_3606BC_HoneycombTreasureHunt1P, 0x18

dlabel D_80105BAC_3606BC_HoneycombTreasureHunt1P
    /* 80105BAC */ .space 0x18

nonmatching D_80105BC4_3606D4_HoneycombTreasureHunt1P, 0x60

dlabel D_80105BC4_3606D4_HoneycombTreasureHunt1P
    /* 80105BC4 */ .space 0x60

nonmatching D_80105C24_360734_HoneycombTreasureHunt1P, 0x8

dlabel D_80105C24_360734_HoneycombTreasureHunt1P
    /* 80105C24 */ .space 0x08

nonmatching D_80105C2C_36073C_HoneycombTreasureHunt1P, 0x2C

dlabel D_80105C2C_36073C_HoneycombTreasureHunt1P
    /* 80105C2C */ .space 0x2C

nonmatching D_80105C58_360768_HoneycombTreasureHunt1P, 0x18

dlabel D_80105C58_360768_HoneycombTreasureHunt1P
    /* 80105C58 */ .space 0x18

nonmatching D_80105C70_360780_HoneycombTreasureHunt1P, 0x4

dlabel D_80105C70_360780_HoneycombTreasureHunt1P
    /* 80105C70 */ .space 0x04

nonmatching D_80105C74_360784_HoneycombTreasureHunt1P, 0x28

dlabel D_80105C74_360784_HoneycombTreasureHunt1P
    /* 80105C74 */ .space 0x28

nonmatching D_80105C9C_3607AC_HoneycombTreasureHunt1P, 0x30

dlabel D_80105C9C_3607AC_HoneycombTreasureHunt1P
    /* 80105C9C */ .space 0x30

nonmatching D_80105CCC_3607DC_HoneycombTreasureHunt1P, 0x24

dlabel D_80105CCC_3607DC_HoneycombTreasureHunt1P
    /* 80105CCC */ .space 0x24

nonmatching jtbl_80105CF0_360800_HoneycombTreasureHunt1P, 0x18

dlabel jtbl_80105CF0_360800_HoneycombTreasureHunt1P
    /* 80105CF0 */ .space 0x18

nonmatching D_80105D08_360818_HoneycombTreasureHunt1P, 0x8

dlabel D_80105D08_360818_HoneycombTreasureHunt1P
    /* 80105D08 */ .space 0x08

nonmatching D_80105D10_360820_HoneycombTreasureHunt1P, 0x8

dlabel D_80105D10_360820_HoneycombTreasureHunt1P
    /* 80105D10 */ .space 0x08

nonmatching D_80105D18_360828_HoneycombTreasureHunt1P, 0x8

dlabel D_80105D18_360828_HoneycombTreasureHunt1P
    /* 80105D18 */ .space 0x08

nonmatching D_80105D20_360830_HoneycombTreasureHunt1P, 0x8

dlabel D_80105D20_360830_HoneycombTreasureHunt1P
    /* 80105D20 */ .space 0x08

nonmatching D_80105D28_360838_HoneycombTreasureHunt1P, 0x8

dlabel D_80105D28_360838_HoneycombTreasureHunt1P
    /* 80105D28 */ .space 0x08

nonmatching D_80105D30_360840_HoneycombTreasureHunt1P, 0x8

dlabel D_80105D30_360840_HoneycombTreasureHunt1P
    /* 80105D30 */ .space 0x08

nonmatching D_80105D38_360848_HoneycombTreasureHunt1P, 0x8

dlabel D_80105D38_360848_HoneycombTreasureHunt1P
    /* 80105D38 */ .space 0x08

nonmatching D_80105D40_360850_HoneycombTreasureHunt1P, 0x8

dlabel D_80105D40_360850_HoneycombTreasureHunt1P
    /* 80105D40 */ .space 0x08

nonmatching D_80105D48_360858_HoneycombTreasureHunt1P, 0x8

dlabel D_80105D48_360858_HoneycombTreasureHunt1P
    /* 80105D48 */ .space 0x08

nonmatching D_80105D50_360860_HoneycombTreasureHunt1P, 0x8

dlabel D_80105D50_360860_HoneycombTreasureHunt1P
    /* 80105D50 */ .space 0x08

nonmatching D_80105D58_360868_HoneycombTreasureHunt1P, 0x8

dlabel D_80105D58_360868_HoneycombTreasureHunt1P
    /* 80105D58 */ .space 0x08

nonmatching D_80105D60_360870_HoneycombTreasureHunt1P, 0xA

dlabel D_80105D60_360870_HoneycombTreasureHunt1P
    /* 80105D60 */ .space 0x0A

nonmatching D_80105D6A_36087A_HoneycombTreasureHunt1P, 0x6

dlabel D_80105D6A_36087A_HoneycombTreasureHunt1P
    /* 80105D6A */ .space 0x06

nonmatching D_80105D70_360880_HoneycombTreasureHunt1P, 0x2

dlabel D_80105D70_360880_HoneycombTreasureHunt1P
    /* 80105D70 */ .space 0x02

nonmatching D_80105D72_360882_HoneycombTreasureHunt1P, 0x30

dlabel D_80105D72_360882_HoneycombTreasureHunt1P
    /* 80105D72 */ .space 0x30

nonmatching D_80105DA2_3608B2_HoneycombTreasureHunt1P, 0x2

dlabel D_80105DA2_3608B2_HoneycombTreasureHunt1P
    /* 80105DA2 */ .space 0x02

nonmatching D_80105DA4_3608B4_HoneycombTreasureHunt1P, 0x1

dlabel D_80105DA4_3608B4_HoneycombTreasureHunt1P
    /* 80105DA4 */ .space 0x01

nonmatching D_80105DA5_3608B5_HoneycombTreasureHunt1P, 0x1

dlabel D_80105DA5_3608B5_HoneycombTreasureHunt1P
    /* 80105DA5 */ .space 0x01

nonmatching D_80105DA6_3608B6_HoneycombTreasureHunt1P, 0x2

dlabel D_80105DA6_3608B6_HoneycombTreasureHunt1P
    /* 80105DA6 */ .space 0x02

nonmatching D_80105DA8_3608B8_HoneycombTreasureHunt1P, 0x4

dlabel D_80105DA8_3608B8_HoneycombTreasureHunt1P
    /* 80105DA8 */ .space 0x04

nonmatching D_80105DAC_3608BC_HoneycombTreasureHunt1P, 0x4

dlabel D_80105DAC_3608BC_HoneycombTreasureHunt1P
    /* 80105DAC */ .space 0x04

nonmatching D_80105DB0_3608C0_HoneycombTreasureHunt1P, 0x2

dlabel D_80105DB0_3608C0_HoneycombTreasureHunt1P
    /* 80105DB0 */ .space 0x02

nonmatching D_80105DB2_3608C2_HoneycombTreasureHunt1P, 0x2

dlabel D_80105DB2_3608C2_HoneycombTreasureHunt1P
    /* 80105DB2 */ .space 0x02

nonmatching D_80105DB4_3608C4_HoneycombTreasureHunt1P, 0x2

dlabel D_80105DB4_3608C4_HoneycombTreasureHunt1P
    /* 80105DB4 */ .space 0x02

nonmatching D_80105DB6_3608C6_HoneycombTreasureHunt1P, 0x2

dlabel D_80105DB6_3608C6_HoneycombTreasureHunt1P
    /* 80105DB6 */ .space 0x02

nonmatching D_80105DB8_3608C8_HoneycombTreasureHunt1P, 0x2

dlabel D_80105DB8_3608C8_HoneycombTreasureHunt1P
    /* 80105DB8 */ .space 0x02

nonmatching D_80105DBA_3608CA_HoneycombTreasureHunt1P, 0x2

dlabel D_80105DBA_3608CA_HoneycombTreasureHunt1P
    /* 80105DBA */ .space 0x02

nonmatching D_80105DBC_3608CC_HoneycombTreasureHunt1P, 0x4

dlabel D_80105DBC_3608CC_HoneycombTreasureHunt1P
    /* 80105DBC */ .space 0x04

nonmatching D_80105DC0_3608D0_HoneycombTreasureHunt1P, 0x4

dlabel D_80105DC0_3608D0_HoneycombTreasureHunt1P
    /* 80105DC0 */ .space 0x04

nonmatching D_80105DC4_3608D4_HoneycombTreasureHunt1P, 0x4

dlabel D_80105DC4_3608D4_HoneycombTreasureHunt1P
    /* 80105DC4 */ .space 0x04

nonmatching D_80105DC8_3608D8_HoneycombTreasureHunt1P, 0x4

dlabel D_80105DC8_3608D8_HoneycombTreasureHunt1P
    /* 80105DC8 */ .space 0x04

nonmatching D_80105DCC_3608DC_HoneycombTreasureHunt1P, 0x4

dlabel D_80105DCC_3608DC_HoneycombTreasureHunt1P
    /* 80105DCC */ .space 0x04

nonmatching D_80105DD0_3608E0_HoneycombTreasureHunt1P, 0x2

dlabel D_80105DD0_3608E0_HoneycombTreasureHunt1P
    /* 80105DD0 */ .space 0x02

nonmatching D_80105DD2_3608E2_HoneycombTreasureHunt1P, 0x2

dlabel D_80105DD2_3608E2_HoneycombTreasureHunt1P
    /* 80105DD2 */ .space 0x02

nonmatching D_80105DD4_3608E4_HoneycombTreasureHunt1P, 0x32EC

dlabel D_80105DD4_3608E4_HoneycombTreasureHunt1P
    /* 80105DD4 */ .space 0x32EC
